paradedb/paradedb

- .github/workflows/lint-and-check-types.yml
- docs/README.md
- docs/introduction.mdx
- docs/quickstart/pipeline.mdx
- Closes #
**What**
Modify Mintlify README and fix broken links in the docs
**Why**
**How**
**Tests**
> fix: Mintlify README and broken links

- README.md
- Closes #
**What**
Add Installation instructions to the README
**Why**
**How**
**Tests**
> feat: Add Installation to README

- README.md
- Closes #
**What**
Add instructions on how to build and run the Python SDK locally
**Why**
**How**
Modified README
**Tests**
> feat: Add development instructions to README

- docs/concepts/sink.mdx
- docs/concepts/target.mdx
- docs/quickstart/pipeline.mdx
- Closes #
**What**
Adds docs for the new Pinecone `Sink`
**Why**
Documentation!
**How**
**Tests**
> feat: Pinecone docs

- README.md
- Closes #
**What**
Add updated Retake website links to the README
**Why**
**How**
**Tests**
> fix: Update website links

- docs/concepts/embedding.mdx
- Closes #
**What**
Add documentation for Cohere and custom embedding models
**Why**
Because we added support for Cohere and custom embedding models
**How**
**Tests**
> feat: Add documentation for Cohere and custom embedding models

- .github/issue_templates/BUG_REPORT.md
- .github/issue_templates/FEATURE_REQUEST.md
- Closes #
**What**
GH issue templates!
**Why**
Make it easier to create well-written GH issues
**How**
**Tests**
> feat: Introduce bug/feature templates

- .github/workflows/publish-to-pypi.yml
- pyproject.toml
- Closes #
**What**
**Why**
**How**
**Tests**
> test: Version number workflow

- .github/workflows/publish-to-pypi.yml
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: Typo in `patch-version.yaml`

- .github/workflows/patch-version.yml
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: Use SSH key when pushing

- docs/company/roadmap.mdx
- docs/concepts/pipeline.mdx
- docs/concepts/sink.mdx
- docs/concepts/target.mdx
- docs/quickstart/batch-update.mdx
- docs/quickstart/pipeline.mdx
- Closes #
**What**
Update documentation after Weaviate PR was merged
**Why**
**How**
**Tests**
> feat: Update docs w/ Weaviate connector and new pipe() function

- .github/workflows/lint-and-check-types.yml
- .github/workflows/publish-to-pypi.yml
- core/load/base.py
- core/load/elasticsearch.py
- core/load/opensearch.py
- core/load/pinecone.py
- core/load/tests/test_pinecone.py
- core/load/weaviate.py
- core/sdk/pipeline.py
- docs/company/roadmap.mdx
- docs/concepts/pipeline.mdx
- docs/concepts/sink.mdx
- docs/concepts/target.mdx
- docs/quickstart/batch-update.mdx
- docs/quickstart/pipeline.mdx
- mypy.ini
- streams/app.py
- Closes #
**What**
- Fix to deploy workflow
- Separate `pipe` and `pipe_all` functions
**Why**
**How**
**Tests**
> Prod Promotion [07/16/2023]

- core/load/weaviate.py
- core/sdk/target.py
- Closes #
**What**
I noticed a small typo on the `WeaviateVectorizer`  target type. This short PR fixes it.
**Why**
**How**
**Tests**
> fix: typo Vecotorizer -> Vectorizer

- core/load/qdrant.py
- core/load/tests/test_qdrant.py
- core/load/weaviate.py
- core/sdk/pipeline.py
- core/sdk/sink.py
- core/sdk/target.py
- pyproject.toml
- streams/app.py
- Closes #
**What**
Introduce support for Qdrant `Sink`. Only works for batch uploads, not real-time yet
**Why**
**How**
**Tests**
Wrote and ran unit tests
> feat: Introduce Qdrant `Sink`

- .flake8
- .github/workflows/lint-and-check-types.yml
- connectors/connect.py
- connectors/consumer.py
- core/extract/base.py
- core/extract/postgres.py
- core/load/elasticsearch.py
- core/load/opensearch.py
- core/load/pinecone.py
- core/load/qdrant.py
- core/load/tests/test_pinecone.py
- core/load/tests/test_qdrant.py
- core/load/weaviate.py
- core/sdk/pipeline.py
- core/sdk/source.py
- core/transform/tests/test_cohere.py
- core/transform/tests/test_custom.py
- core/transform/tests/test_openai.py
- core/transform/tests/test_sentence_transformers.py
- pyproject.toml
- streams/app.py
- Closes #
**What**
Introduces linting with `flake8`. Added to Github actions and fixed linting errors.
**Why**
Fix linting errors like unused imports.
**How**
**Tests**
Ran flake8
> feat: Introduce flake8 linting and fix lint errors

- docs/company/roadmap.mdx
- docs/concepts/sink.mdx
- docs/concepts/target.mdx
- docs/deployment/setup.mdx
- docs/introduction.mdx
- docs/quickstart/real-time-update.mdx
- Closes #
**What**
- Add documentation about Qdrant `Sink` and `Target` classes
- Fix a few small issues with the docs in other places
**Why**
**How**
**Tests**
> feat: Add Qdrant documentation

- CONTRIBUTING.md
- LICENSE
Fixing minor formatting issues
> fix: fixing some formatting issues

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- CODE_OF_CONDUCT.md
- README.md
- deploy.sh
- docs/README.md
- docs/concepts/realtime.mdx
- docs/deployment/cloud.mdx
- docs/introduction.mdx
Fixing some small formatting issues and outdated docs
> fix: Fix a few small issues/format

- README.md
- docs/architecture.mdx
- docs/company/roadmap.mdx
- docs/deployment/kubernetes.mdx
- docs/deployment/local.mdx
- docs/introduction.mdx
- docs/mint.json
- docs/quickstart.mdx
- docs/search/pagination.mdx
- Closes #
**What**
- Introduce some fixes to the README and documentation
- Added Deployment and Roadmap sections
**Why**
**How**
**Tests**
> feat: Add more documentation

- README.md
- docs/introduction.mdx
- Closes #
**What**
**Why**
**How**
**Tests**
> feat: Add section to README about vector cache feature

- README.md
- docs/architecture.mdx
- docs/company/roadmap.mdx
- docs/deployment/kubernetes.mdx
- docs/deployment/local.mdx
- docs/introduction.mdx
- docs/mint.json
- docs/quickstart.mdx
- docs/search/pagination.mdx
- Closes #
**What**
**Why**
**How**
**Tests**
> ci: Prod Promotion [7/26/23]

- README.md
- docs/company/roadmap.mdx
- docs/introduction.mdx
- docs/quickstart.mdx
- docs/search/aggregation.mdx
- docs/search/custom.mdx
- docs/search/filtering.mdx
- docs/search/keyword.mdx
- docs/search/neural.mdx
- docs/search/overview.mdx
- docs/search/pagination.mdx
- docs/search/sorting.mdx
- Closes #
**What**
- Should be merged after #90  is merged
- Change documentation to reflect changes in the Python client
**Why**
**How**
**Tests**
> feat: Change docs to reflect Python client refactor

- README.md
- Closes #
**What**
- Adds links to documentation and website to top of README
- Adds badges to README 
**Why**
**How**
**Tests**
> feat: Add badges and links to top of README

- docs/mint.json
- docs/quickstart.mdx
- docs/setup.mdx
- Closes #103 
**What**
Should be merged after #83 is merged. This PR adds instructions on how to enable logical replication for Debezium in Postgres.
**Why**
**How**
**Tests**
> feat: Add Setup page to docs for enabling logical replication

- .flake8
- .github/workflows/helpers/check-shellcheck.py
- .github/workflows/lint-python.yml
- README.md
- api/app.py
- api/config/base.py
- api/config/kafka.py
- api/config/opensearch.py
- api/routers/index.py
- api/sink_consumer.py
- clients/python/retakesearch/index.py
- core/extract/base.py
- core/extract/postgres.py
- core/extract/realtime.py
- core/search/client.py
- core/search/index.py
- core/search/index_mappings.py
- core/search/model.py
- core/search/model_group.py
- core/search/pipeline.py
- docker-compose.yml
- docs/introduction.mdx
- docs/mint.json
- docs/quickstart.mdx
- docs/setup.mdx
- examples/flask/app.py
- examples/flask/scripts/setup.py
- mypy.ini
- poetry.lock
- pyproject.toml
- Closes #
**What**
**Why**
**How**
**Tests**
> ci: Prod Promotion [7/28/23]

- docs/deployment/local.mdx
- docs/introduction.mdx
- docs/quickstart.mdx
- Closes #
**What**
- Fixed some small typos
**Why**
**How**
**Tests**
> fix: Small typos in docs

- api/routers/index.py
- clients/python/retakesearch/client.py
- Closes #
**What**
- Allows the user to delete an index
- Small fix to Python client to throw error message if API req fails
**Why**
**How**
**Tests**
> feat: Introduce `delete` index to python client

- README.md
- docs/quickstart.mdx
- Closes #
**What**
- Rephrase and clean up the quick start guide
**Why**
**How**
**Tests**
> fix: Clean up quickstart guide

- README.md
- api/routers/index.py
- clients/python/pyproject.toml
- clients/python/retakesearch/index.py
- core/search/index.py
- docs/introduction.mdx
- docs/quickstart.mdx
- docs/search/aggregation.mdx
- docs/search/custom.mdx
- docs/search/filtering.mdx
- docs/search/keyword.mdx
- docs/search/neural.mdx
- docs/search/overview.mdx
- docs/search/pagination.mdx
- docs/search/sorting.mdx
- docs/setup.mdx
- examples/flask/README.md
- examples/flask/app.py
- examples/flask/scripts/setup.py
- examples/nextjs/README.md
- pyproject.toml
- tests/test_pipeline.py
- Closes #130 
**What**
- Introduces `Index.vectorize`, which takes in a list of columns and vectorizes them
- This function only needs to be run once and guarantees that vectors will stay in sync
- Usage:
```python
fields = ["field1", "field2"]
index.vectorize(fields)
```
- Updated documentation 
**Why**
- Previously we were specifying which columns to vectorize in the `Table` object. This was somewhat confusing and also made it so that we couldn't specify which columns to vectorize when upserting documents from memory
- This approach is much more intuitive and clean
**How**
**Tests**
Updated and tested the example Flask app
> feat: Introduce `vectorize` function

- docs/introduction.mdx
- docs/quickstart.mdx
- Closes #
**What**
- Replaces the waitlist with Calendly in documentation
**Why**
**How**
**Tests**
> fix: Add contact sales to docs

- README.md
- docs/introduction.mdx
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: Punctuation typo

- README.md
- api/routers/index.py
- clients/python/pyproject.toml
- clients/python/retakesearch/index.py
- core/search/index.py
- docs/introduction.mdx
- docs/quickstart.mdx
- docs/search/aggregation.mdx
- docs/search/custom.mdx
- docs/search/filtering.mdx
- docs/search/keyword.mdx
- docs/search/neural.mdx
- docs/search/overview.mdx
- docs/search/pagination.mdx
- docs/search/sorting.mdx
- docs/setup.mdx
- examples/flask/README.md
- examples/flask/app.py
- examples/flask/scripts/setup.py
- examples/nextjs/README.md
- pyproject.toml
- tests/test_pipeline.py
- Closes #
**What**
**Why**
**How**
**Tests**
> ci: Prod Promotion (7/31/23)

- README.md
- clients/python/pyproject.toml
- docs/quickstart.mdx
- docs/search/neural.mdx
- examples/flask/app.py
- poetry.lock
- pyproject.toml
- tests/test_pipeline.py
- Closes #
**What**
- Pushed an update to `opensearch-py` to replace `neuralQuery` with `with_semantic` and `with_neural`
- Updates docs and tests to reflect that change
**Why**
**How**
**Tests**
> feat: Introduce docs for new with_neural and with_semantic functions

- README.md
- clients/python/pyproject.toml
- docs/quickstart.mdx
- docs/search/neural.mdx
- examples/flask/app.py
- poetry.lock
- pyproject.toml
- tests/test_pipeline.py
…(#139)
- Closes #
**What**
- Updated documentation for new neural search functions
**Why**
**How**
**Tests**
> ci: Prod Promotion [7/31/23]

- .github/workflows/publish-to-dockerhub.yml
- sync/Dockerfile
This PR also publishes our new PGSync Dockerfile to DockerHub
> ci: Publish other dockerfile

- docs/deployment/local.mdx
- docs/quickstart.mdx
- Closes #
**What**
**Why**
**How**
**Tests**
> docs: Update documentation to link docker compose file

- docker-compose.yml
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: Use dockerhub images in docker compose file

- .github/workflows/publish-to-dockerhub.yml
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: Fix docker deploy (#152)

- README.md
- docs/introduction.mdx
- docs/quickstart.mdx
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: A few small typos in the docs

- docs/mint.json
- Closes #
**What**
- Adds Intercom to docs
**Why**
**How**
**Tests**
> feat: Add intercom to docs

- .flake8
- api/routers/index.py
- docs/mint.json
- Closes #
**What**
- Intercom
- Small quality of life fix
**Why**
**How**
**Tests**
> ci: Prod Promotion [8/1/23]

- core/search/client.py
- Closes #
**What**
- Sets retries and increases timeout for OpenSearch connection
**Why**
**How**
**Tests**
> fix: Increase OpenSearch client timeout

- .gitignore
- README.md
- api/routers/index.py
- clients/python/retakesearch/index.py
- clients/typescript/src/lib/client.ts
- clients/typescript/src/lib/index.ts
- core/search/client.py
- core/search/index.py
- docker-compose.yml
- docs/architecture.mdx
- docs/python/index.mdx
- docs/python/table.mdx
- docs/quickstart.mdx
- docs/typescript/database.mdx
- docs/typescript/index.mdx
- docs/typescript/table.mdx
- examples/flask/scripts/setup.py
- examples/nextjs/app/search.tsx
- examples/nextjs/package-lock.json
- examples/nextjs/scripts/setup.js
- sync/sidecar.py
- tests/docker-compose.yml
- tests/test_pipeline.py
- Closes #
**What**
- Replaced the old `add_source` endpoint with the new endpoint that uses pgsync
- Updated documentation
- Updated tests and examples
- Slight modification to the `Table` object (no longer requires `primary_key`)
**Why**
**How**
**Tests**
> refactor: Use pgysnc for `add_source`

- .github/workflows/publish-retake-to-npm.yml
- .gitignore
- README.md
- api/routers/index.py
- clients/python/retakesearch/index.py
- clients/typescript/package.json
- clients/typescript/src/lib/client.ts
- clients/typescript/src/lib/index.ts
- core/search/client.py
- core/search/index.py
- docker-compose.yml
- docs/architecture.mdx
- docs/python/index.mdx
- docs/python/table.mdx
- docs/quickstart.mdx
- docs/typescript/database.mdx
- docs/typescript/index.mdx
- docs/typescript/table.mdx
- examples/flask/scripts/setup.py
- examples/nextjs/app/search.tsx
- examples/nextjs/package-lock.json
- examples/nextjs/scripts/setup.js
- sync/sidecar.py
- tests/docker-compose.yml
- tests/test_pipeline.py
- Closes #
**What**
- Real time sync working
**Why**
**How**
**Tests**
> ci: Prod Promotion [8/2/23]

- clients/python/retakesearch/index.py
- clients/typescript/src/lib/index.ts
- docs/python/table.mdx
- docs/quickstart.mdx
- docs/typescript/table.mdx
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: Allow users to specify `schema` in `Table` (#172)

- examples/nextjs/README.md
- examples/nextjs/app/page.tsx
- examples/nextjs/app/search.tsx
- examples/nextjs/package-lock.json
- examples/nextjs/package.json
- examples/nextjs/scripts/preinstall.js
- examples/nextjs/scripts/setup.js
- Closes #
**What**
Made a few improvements to the example Nextjs app:
- Added a preinstall hook that builds `retake-search` on `npm install`
- Added a search button to the app
**Why**
**How**
**Tests**
> feat: Brush up the Nextjs example

- docs/deployment/kubernetes.mdx
- docs/deployment/managed.mdx
- docs/mint.json
- Closes #
**What**
- Adds documentation about managed deployments
**Why**
**How**
**Tests**
> feat: Add section about managed version

- README.md
- docs/introduction.mdx
- docs/quickstart.mdx
- docs/search/neural.mdx
- docs/setup.mdx
- Closes #
**What**
- Add more documentation to setup and quickstart
**Why**
**How**
**Tests**
> feat: Add more documentation to setup and quickstart

- docs/mint.json
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: New intercom account

- README.md
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: Update README title

- README.md
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: Update README title (#210)

- docs/quickstart.mdx
- docs/search/overview.mdx
- docs/typescript/client.mdx
… (#212)
- Closes #
**What**
**Why**
**How**
**Tests**
> ci: Prod Promotion [8/11/23]

- clients/typescript/package.json
- clients/typescript/src/index.ts
- examples/nextjs/package-lock.json
- Closes #
**What**
**Why**
**How**
**Tests**
> fix: Don't bundle React into Node library (HOTFIX) (#214)

- README.md
- Closes #
**What**
- The Typescript code block was using the wrong function name and was missing `await`s
**Why**
**How**
**Tests**
> fix: Typo in README typescript code block

- docs/quickstart.mdx
- Closes #
**What**
- There were more typos in the code blocks in the quick start
- Added a sentence clarifying that the upload data code should only be run once
**Why**
**How**
**Tests**
> fix: More typos in Quickstart

- poetry.lock
This should fix the two open security vulnerabilities, which are deps of deps
> chore: Fix security vulnerabilities

- .github/workflows/lint-typescript.yml
- clients/typescript/tsconfig.json
- examples/nextjs/postcss.config.js
- examples/nextjs/scripts/setup.js
This workflow lints TypeScript with Prettier, I'll make another one for ESLint
> ci: Initial ts lint

- .gitignore
- .prettierrc.json
- README.md
- docs/quickstart.mdx
- docs/search/aggregation.mdx
- docs/search/boosting.mdx
- docs/search/filtering.mdx
- docs/search/highlighting.mdx
- docs/search/keyword.mdx
- docs/search/neural.mdx
- docs/search/object.mdx
- docs/search/overview.mdx
- docs/search/pagination.mdx
- docs/search/sorting.mdx
- docs/typescript/client.mdx
- docs/typescript/database.mdx
- docs/typescript/index.mdx
- docs/typescript/search.mdx
- docs/typescript/table.mdx
- examples/nextjs/app/layout.tsx
- examples/nextjs/app/page.tsx
- examples/nextjs/app/search.tsx
- examples/nextjs/next.config.mjs
- examples/nextjs/postcss.config.js
- examples/nextjs/scripts/preinstall.js
- examples/nextjs/scripts/setup.js
- examples/nextjs/tailwind.config.js
- tests/docker-compose.yml
This adds Prettierrc for formatting consistency
> ci: Add .prettierrc for formatting

- clients/typescript/package.json
- clients/typescript/rollup.config.mjs
- clients/typescript/src/index.ts
- deploy.sh
- docker/docker-compose.base.yml
- docker/docker-compose.dev.yml
- docker/docker-compose.prod.yml
- docker/docker-compose.yml
- examples/nextjs/app/page.tsx
- examples/nextjs/app/search.tsx
- examples/nextjs/package-lock.json
- examples/nextjs/scripts/preinstall.js
- examples/nextjs/scripts/setup.js
- tests/docker-compose.yml
- Closes #
**What**
**Why**
**How**
**Tests**
> ci: Prod Promotion

- README.md
- docs/introduction.mdx
- docs/search/boosting.mdx
- docs/search/highlighting.mdx
- docs/setup.mdx
- Closes #
**What**
- Change language of docs to discuss the database aspect of Retake over the search aspect
- Fixed some errors in the Typescript examples for highlighting and boosting
**Why**
**How**
**Tests**
> docs: Change language of docs to emphasize the real-time database aspect

- docs/import.mdx
- docs/mint.json
- Closes #
Wrote instructions on how to migrate from another Postgres database using `pg_dump` and how to import a CSV file using the `\copy` option.
> docs: Add documentation on importing data into ParadeDB

- docs/mint.json
- Closes #N/A
I noticed a few things were missing from our Mintlify, compared to Mintlify's own docs: https://github.com/mintlify/docs
Better docs experience for users, for instance enabling them to edit in GitHub, thumbs up/down to give us feedback, and more easily reach our Slack community
Followed Mintlify's example
N/A
> docs: Improvements to Mintlify config

- docs/quickstart.mdx
> fix: Updated output for hybrid search query

- .github/codecov.yml
- Closes #
This should get it to stop complaining unnecessarily
> fix: Fix codecov.yml

- .github/codecov.yml
- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_search.yml
- README.md
- Closes #
This disables Codecov, we can re-enable once we want it/have tests to get coverage on
> chore: Disable codecov

- docs/blog/introducing_bm25.mdx
- Closes #
Second draft of the BM25 blog post
> docs: Edit BM25 blog post

- docs/blog/introducing_bm25.mdx
> docs: Add thumbnail to blog post

- docs/blog/introducing_bm25.mdx
> fix: Thumbnail on blog

- docs/blog/introducing_bm25.mdx
> fix: Thumbnail on blog (#319)

- docs/deploy/aws.mdx
- docs/deploy/gcp.mdx
- docs/deploy/helm.mdx
- docs/deploy/introductions.mdx
- docs/mint.json
> docs: add docs for deploying AWS, GCP and Helm

- .prettierignore
- docs/quickstart.mdx
- Closes #
- Fix formatting issue
> docs: Fix quickstart formatting

- docs/blog/introducing_bm25.mdx
- Closes #
- Major edits to the pg_bm25 blog post
> docs: Revised BM25 blog post

- docs/blog/introducing_bm25.mdx
- pg_bm25/README.md
- Closes #
- Updated the roadmap, license, and a few small things
> docs: Update `pg_bm25` README

- docker/Dockerfile
- docker/docker-compose.local.yml
- scripts/entrypoint.sh
This promotion adds missing extensions for the Crunchy operator
> feat: Prod Promotion

- .github/workflows/publish-paradedb-to-dockerhub.yml
> fix: add pgnodemx version to release workflow (#353)

- .prettierignore
- README.md
- benchmarks/README.md
- benchmarks/benchmark-elasticsearch.sh
- benchmarks/benchmark-paradedb.sh
- benchmarks/benchmark-tsquery.sh
- benchmarks/helpers/destroy_data.sql
- benchmarks/helpers/get_data.sh
- benchmarks/helpers/load_data.sql
- docs/mint.json
- pg_bm25/README.md
- pg_bm25/test/runtests.sh
- pg_search/test/runtests.sh
- Closes #346
This PR cleans up our benchmarking suite, and also tests on up to 5M rows. I was not able to reproduce the issue w/ crashes post-2M rows, so considering that issue fixed.
Easier to use benchmarks to eventually add other systems and run benchmarks more easily, and stress-test on more data
N/A
Ran all the benchmarks, they all still work
> feat: Cleanup benchmarks + Test on 5M rows 

- README.md
- SECURITY.md
- Closes #
Just making things a bit more up-to-date in the READMEs
> chore: Some small README updates

- .github/CODEOWNERS
- .github/workflows/lint-markdown.yml
- README.md
- docs/blog/introducing_bm25.mdx
- pg_bm25/README.md
- pg_search/README.md
- Closes #
This adds some small README fixes to clarify things, and brings up-to-date the `pg_search` README.
> chore: Improve READMEs

- .github/CODEOWNERS
- .github/workflows/benchmark-paradedb.yml
- .github/workflows/lint-markdown.yml
- .prettierignore
- README.md
- benchmarks/.gitignore
- benchmarks/README.md
- benchmarks/benchmark-elasticsearch.sh
- benchmarks/benchmark-tsquery.sh
- benchmarks/benchmark-typesense.sh
- benchmarks/helpers/get_data.sh
- docs/blog/introducing_bm25.mdx
- pg_bm25/README.md
- pg_search/README.md
- Closes #
This promotion is triggered to compile paradedb/paradedb:latest with our latest Tantivy
> chore: Prod Promotion

- benchmarks/benchmark-typesense.sh
- Closes #
They would balloon up between each iteration of the loop, this fixes this
> fix: Currently typesense collections don't get deleted, this should fix it

- README.md
- Closes #
The managed cloud now works internally. We're starting to onboard customers onto the platform! Reach out if you'd like to be amongst the early users of ParadeDB Cloud.
> chore: Update Private Beta to Public Beta

- .github/workflows/helpers/check-pipefail.sh
- .github/workflows/helpers/check-shebang.sh
- .github/workflows/helpers/check-shellcheck.py
- .github/workflows/helpers/fix_trailing_newline.sh
- .pre-commit-config.yaml
- benchmarks/helpers/elastify-data.py
- dashboard/components/tremor/index.ts
- docker/Dockerfile
- docs/aggregations/bucket.mdx
- docs/indexing/bm25.mdx
- docs/quickstart.mdx
- docs/search/autocomplete.mdx
- docs/search/fuzzy.mdx
- docs/search/hybrid.mdx
- pg_bm25/src/lib.rs
- Closes #
This PR brings our pre-commit hooks back up-to-date (they were broken previously). I added a few more hooks (browsed the whole list, I believe this should be pretty comprehensive). Some of them are commented out because they don't pass -- will fix them in subsequent PR(s)
> chore: Update pre-commit hooks

- README.md
- Closes #
Fix the broken benchmarks link in `README.md`
> docs: fix broken benchmarks link

- README.md
- docs/indexing/overview.mdx
- pg_bm25/README.md
- Closes #
Some feedback we received on the README from early users -- this should help clarify things
> chore: Clarify README

- .github/workflows/helpers/check-shellcheck.py
- .pre-commit-config.yaml
- benchmarks/helpers/elastify-data.py
- dashboard/app/globals.css
- Closes #
I was bored, so I quickly added some other pre-commit hooks that are commented. I'll finish them next time I'm bored, it's quite quick
> chore: Add some missing pre-commit hooks

- .github/workflows/publish-paradedb-to-dockerhub.yml
> fix: Add missing $ to tag in DockerHub deploy

- .github/workflows/publish-paradedb-to-dockerhub.yml
> fix: Add missing $ to tag in DockerHub deploy (#433)

- .github/workflows/publish-pg_bm25.yml
- .github/workflows/publish-pg_search.yml
- docker/Dockerfile
> fix: Properly sed to avoid shared/ folder

- .github/workflows/publish-pg_bm25.yml
- .github/workflows/publish-pg_search.yml
- docker/Dockerfile
> fix: Properly sed to avoid shared/ folder (#435)

- docker/Dockerfile
> fix: Also import the shared folder in the extension builder stages

- docs/quickstart.mdx
> fix: Docs typo

- .github/workflows/benchmark-paradedb.yml
- .github/workflows/lint-bash.yml
- .github/workflows/lint-dockerfiles.yml
- .github/workflows/lint-file-endings.yml
- .github/workflows/lint-markdown.yml
- .github/workflows/lint-pr-title.yml
- .github/workflows/lint-python.yml
- .github/workflows/lint-rust.yml
- .github/workflows/lint-yaml.yml
- .github/workflows/publish-github-release.yml
- .github/workflows/publish-paradedb.yml
- .github/workflows/publish-pg_bm25.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/publish-third-party-pg_extensions.yml
- .github/workflows/test-paradedb.yml
- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_search.yml
- Closes #
Right now, they are this:
So impossible to know which workflow to trigger when I want to trigger a manual deploy. This will fix it.
> chore: Make GHA workflow names more expressive

- README.md
- Closes #
We can re-add those once we have more interesting badges to display.
> chore: Remove badges

- .github/workflows/publish-pg_bm25.yml
- .github/workflows/publish-pg_search.yml
> fix: Properly specify github_token for releases (#457)

- .github/workflows/publish-pg_bm25.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/publish-third-party-pg_extensions.yml
- Closes #
These aren't used anymore, so removing
> chore: rm unused codeblocks in CI

- .github/workflows/publish-pg_bm25.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/publish-third-party-pg_extensions.yml
> chore: Bigger CI runner for arm64

- dashboard/app/page.tsx
- dashboard/app/template.tsx
- dashboard/components/skeleton/index.ts
- dashboard/components/skeleton/spinner.tsx
- Closes #
- Adds a loading animation to the dashboard that shows while the user is being authenticated
- Hides the dashboard from non-authenticated users
> fix: Add loading state to dashboard

- pg_sparse/Cargo.toml
> chore: Update hnswlib commit hash

- .github/workflows/publish-pg_sparse.yml
- Cargo.lock
- docs/mint.json
- pg_sparse/src/api/mod.rs
- Closes #
This PR adds the missing workflow to publish `pg_sparse`, now that it's getting closer to production-ready. It also runs the pre-commit hooks.
> chore: Add workflow to publish `pg_sparse`

- scripts/entrypoint.sh
- Closes #
fix: Set `search_path` to across sessions and users (#487)
> fix: Prod Promotion (fix search_path)

- .github/CODEOWNERS
- .github/codecov.yml
- .github/dependabot.yml
- .github/workflows/lint-docker.yml
- .github/workflows/publish-paradedb.yml
- .gitignore
- .prettierignore
- Cargo.toml
- docker/Dockerfile
- docker/docker-compose.dev.yml
- pg_bm25/Cargo.toml
- pg_search/Cargo.toml
- pg_sparse/.gitignore
- pg_sparse/Cargo.toml
- pg_sparse/test/fixtures.sql
- scripts/entrypoint.sh
- Closes #
This PR finishes integration `pg_sparse` in our repo, alongside a few minor cleanup steps.
> chore: Finish integrating `pg_sparse` into our repo

- .github/dependabot.yml
- Closes #
Doesn't provide much value for now, turning off
> chore: Turn off Dependabot

- dashboard/app/template.tsx
- dashboard/tailwind.config.ts
- Closes #
- Subtle change to the black of our dashboard background to match the black of our docs
> fix(ui): Change background color and border styling

- README.md
- docs/search/bm25.mdx
- docs/search/hnsw.mdx
This PR simply fixes some formatting issues in #494 so that it can be merged. 
Thanks for the fixes @PzaThief!
> fix: tiny typos causing wrong redirection

- README.md
- docs/introduction.mdx
- docs/quickstart.mdx
- Closes #
- Replaces all mentions of a waitlist and coming soon with the link to ParadeDB cloud
> docs: Add ParadeDB cloud to README and docs

- pg_bm25/README.md
- pg_search/README.md
- pg_sparse/README.md
- Closes #
The cURL command was complicated and brittle. This simplifies it all.
> chore: Fix installation steps for self-hosted

- .github/dependabot.yml
- Closes #
Just so it's commented out but doesn't cause a fail due to syntax issue with the GitHub parser
> chore: Don't make dependabot fail in CI

- README.md
> chore: Update Roadmap on our top-level README

- pg_bm25/src/index_access/build.rs
- pg_bm25/src/parade_index/index.rs
We have a problem with our index creation timing out, and our theory is that it's because we create a new writer for every insert on index creation.
While this is still likely necessary for regular inserts, we have the opportunity to use the same writer through the build process to speed this up.
> fix: Use same writer instance for entire pg_bm25 index build

- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_search.yml
- .github/workflows/test-pg_sparse.yml
> fix: Fix brackets in CI

- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_search.yml
- .github/workflows/test-pg_sparse.yml
- README.md
- Closes #
I tried setting badges in the per-flag basis, and it broke everything with Codecov. Given that this is really not a big deal, I decided to just drop it for now. This fixes back Codecov to when it was working, and adds its badge on the top-level of the project.
> fix: Fix codecov, set badges in top-level

- .github/workflows/publish-paradedb.yml
- Closes #
The telemetry wasn't properly sent because the environment variables in the deploy had a small syntax issue. This fixes it!
> fix: Fix PostHog

- pg_bm25/sql/pg_bm25--0.3.6--0.3.7.sql
- pg_search/sql/pg_search--0.3.6--0.3.7.sql
- pg_sparse/sql/pg_sparse--0.3.6--0.3.7.sql
> chore: Add extension update scripts from v0.3.6 to v0.3.7

- .github/workflows/publish-paradedb.yml
- Closes #
I had merged a change here which broke CloudPGNative. I added a comment to it.
> fix: Fix operator for kubernetes

- pg_bm25/test/runtests.sh
- pg_search/test/runtests.sh
- pg_sparse/test/runtests.sh
- Closes #
There would be telemetry sent from our extension upgrade test. This makes it so it doesn't happen
> chore: Don't send telemetry in CI

- .github/workflows/publish-paradedb.yml
- Closes #
This enables us to deploy via AWS Marketplace, which just approved our listing!
> feat: Push to ECR

- .github/workflows/publish-paradedb.yml
- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_search.yml
- .github/workflows/test-pg_sparse.yml
- pg_bm25/sql/pg_bm25--0.3.8--0.3.9.sql
- pg_search/sql/pg_search--0.3.8--0.3.9.sql
- pg_sparse/sql/pg_sparse--0.3.8--0.3.9.sql
- Closes #
The tagging was somehow incorrect, I think hardcoding it like this should make things work.
> fix: Fix ECR deployment issue

- .github/workflows/publish-paradedb.yml
- pg_bm25/sql/pg_bm25--0.3.9--0.3.10.sql
- pg_search/sql/pg_search--0.3.9--0.3.10.sql
- pg_sparse/sql/pg_sparse--0.3.9--0.3.10.sql
- Closes #
The default login action could not log into the "hidden" AWS Marketplace repositories
> fix: Actually fix ECR deploy

- THANKYOU.md
- Closes #
We swapped operator a while back, this reflects it.
> chore: Update `THANKYOU.md`

- .github/workflows/publish-paradedb.yml
- docker/Dockerfile
- Closes #
Previously, I was hardcoding it. This will make it reflect properly in ArtifactHub
> feat: Dynamic build date tag

- .github/workflows/publish-paradedb.yml
- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_search.yml
- .github/workflows/test-pg_sparse.yml
> fix: Trigger CI for `pg_sparse` on `dev` as well

- .github/workflows/test-pg_sparse.yml
> chore: Don't need to run CI on `dev` for pg_sparse

- pg_bm25/sql/pg_bm25--0.3.11--0.3.12.sql
- pg_search/sql/pg_search--0.3.11--0.3.12.sql
- pg_sparse/sql/svector--0.3.11--0.3.12.sql
> chore: Add upgrade scripts for 0.3.12

- benchmarks/benchmark-paradedb.sh
- Closes #
We updated the syntax for ParadeQL, so need to update our benchmarks
https://github.com/paradedb/paradedb/actions/runs/7052649974
> fix: Fix syntax issue in benchmarks

- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_search.yml
> fix: Fix deploys

- .github/workflows/publish-pg_bm25.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/publish-pg_sparse.yml
- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_search.yml
- scripts/build_and_deploy_third_party_pg_extensions.sh
> chore: Prod Promotion (v0.3.12)

- pg_bm25/sql/pg_bm25--0.3.12--0.3.13.sql
- pg_search/pg_search.control
- pg_search/sql/pg_search--0.3.12--0.3.13.sql
- pg_sparse/sql/svector--0.3.12--0.3.13.sql
- Closes #594 
it is now deployed! and ready! yay!
> feat: Add pg_sparse to pg_search

- pg_search/configure.sh
- pg_sparse/README.md
- pg_sparse/sql/svector--0.0.0--0.1.1.sql
- pg_sparse/sql/svector--0.2.2--0.3.0.sql
- pg_sparse/sql/svector.sql
- pg_sparse/src/svector.c
- pg_sparse/test/expected/functions.out
- pg_sparse/test/expected/shnsw_cosine.out
- pg_sparse/test/expected/shnsw_ip.out
- pg_sparse/test/expected/shnsw_l2.out
- pg_sparse/test/expected/shnsw_options.out
- pg_sparse/test/expected/shnsw_unlogged.out
- pg_sparse/test/sql/functions.sql
- pg_sparse/test/sql/shnsw_cosine.sql
- pg_sparse/test/sql/shnsw_ip.sql
- pg_sparse/test/sql/shnsw_l2.sql
- pg_sparse/test/sql/shnsw_options.sql
- pg_sparse/test/sql/shnsw_unlogged.sql
> fix: `pg_sparse` L2 scan

- pg_search/test/runtests.sh
> fix: Fix naming in extension upgrade test

- .prettierignore
> chore: Remove dashboard/ from prettierignore

- pg_bm25/README.md
- Closes #
We forgot to update the README in #551
> docs: pg_bm25 README

- pg_bm25/README.md
Make it clear in the README that Windows is not supported due to pgrx not being supported on Windows.
> docs: pg_bm25 does not support Windows

- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_sparse.yml
- pg_bm25/README.md
- pg_bm25/test/fixtures.sql
- pg_bm25/test/runtests.sh
- pg_sparse/test/runtests.sh
- scripts/configure.sh
- Closes #
I had done this as part of trying to fix the `pg_search` tests. We're no longe doing `pg_search`, but this code is still nice to merge.
> chore: Cleanup testing framework

- .github/workflows/test-paradedb.yml
- pg_bm25/sql/pg_bm25--0.4.1--0.4.2.sql
- pg_sparse/sql/svector--0.4.1--0.4.2.sql
- scripts/entrypoint.sh
- Closes #
This caused an issue due to some cached state w/ pg_sparse
> fix: Make sure there's no previous extension

- .github/workflows/publish-paradedb.yml
- .github/workflows/publish-pg_bm25.yml
- .github/workflows/publish-pg_sparse.yml
- benchmarks/benchmark-paradedb.sh
- scripts/entrypoint.sh
- Closes #
This PR makes it so don't preinstall all the extensions we support, and makes some fixes so we can manually deploy the Dockerfile later.
> chore: Don't preinstall all extensions

- docker/Dockerfile
> feat: Disable archnative for pg_sparse in Dockerfile

- pg_bm25/README.md
> chore: Specify Rust v1.73.0

- README.md
> chore: Add status to README

- README.md
- pg_bm25/README.md
> chore: Clarify roadmap

- docs/changelog/0.4.3.mdx
- docs/mint.json
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.4.2--0.4.3.sql
- pg_sparse/sql/svector--0.4.2--0.4.3.sql
- pg_sparse/svector.control
- Closes #
Upgrade scripts and docs for 0.4.3
> chore: Upgrade to 0.4.3

- docs/introduction.mdx
- Closes #
Some users were mentioning that our documentation is confusing regarding what Postgres-based mean, so I clarified it:
> docs: Clarify "postgres-based"

- docs/blog/introducing_sparse.mdx
- docs/latest/indexing/bm25.mdx
> docs: Updates

- docs/introduction.mdx
- docs/latest/quickstart.mdx
> docs: Fix broken quickstart link

- Cargo.lock
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.4.4--0.4.5.sql
- pg_sparse/sql/svector--0.4.3--0.4.4.sql
- pg_sparse/sql/svector--0.4.4--0.4.5.sql
> chore: Add scripts for 0.4.5

- .github/workflows/publish-pg_bm25.yml
- Closes #
Properly do v0.4.5 promotion via quotes in the --features of pgrx
> feat: Prod Promotion -- v0.4.5

- docs/introduction.mdx
- docs/mint.json
- Closes #
Update `mint.json` to remove deprecated pages and update the changelog.
> docs: Update `mint.json`

- .github/workflows/test-pg_analytics.yml
- Closes #
This will ensure we don't release without forgetting to increment the version.
> ci: Version check for `pg_analytics`

- pg_analytics/README.md
- Closes #
Adds a clarifying line to pg_analytics readme.
> docs: Add line to readme

- README.md
- Closes #
They mean the same thing colloquially, but Postgres is more concise and readable.
> docs: Replace PostgreSQL with Postgres in tagline

- Cargo.lock
- docs/changelog/0.5.1.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.0.0--0.4.5.sql
- pg_analytics/sql/pg_analytics--0.0.0--0.5.1.sql
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.4.5--0.5.1.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.4.5--0.5.1.sql
- pg_sparse/svector.control
> chore: Prepare v0.5.1

- pg_analytics/README.md
> docs: Update `pg_analytics` README

- pg_analytics/README.md
> docs: Update README.md

- .github/workflows/publish-pg_analytics.yml
- Closes #
The comment was outdated. This makes it match the Cargo.toml
^
^
^
> chore: Proper comment in pg_analytics package

- .github/workflows/test-pg_analytics.yml
- .github/workflows/test-pg_bm25.yml
- Closes #
Typo was preventing workflows from triggering properly
> chore: Fix if conditions

- .github/workflows/benchmark-pg_analytics.yml
- .github/workflows/benchmark-pg_bm25.yml
- Cargo.lock
- pg_analytics/Cargo.toml
- pg_bm25/Cargo.toml
- Closes #
We hadn't updated them in a while. Plus, now when there are updates to our Cargo.toml, it will run all our benchmarks which should do pretty comprehensive testing.
> chore: Upgrade deps, make them trigger benchmarks

- Cargo.lock
- docs/changelog/0.4.5.mdx
- docs/changelog/0.5.2.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.5.1--0.5.2.sql
- pg_analytics/test/runtests.sh
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.5.1--0.5.2.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.1--0.5.2.sql
- pg_sparse/svector.control
- Closes #N/A
This upgrades the version for the upcoming release of `v0.5.2`!
^
^
^
> chore: Prep 0.5.2

- pg_bm25/README.md
- Closes #751
This clarifies a question that a user had.
N/A
N/A
N/A
> chore: Clarify ICU tokenizer

- pg_analytics/test/runtests.sh
- pg_bm25/test/runtests.sh
> fix: Fix extension upgrade test

- Cargo.lock
- docs/changelog/0.5.3.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.5.2--0.5.3.sql
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.5.2--0.5.3.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.2--0.5.3.sql
- pg_sparse/svector.control
- Closes #
This prepares for the upcoming release of `v0.5.3`
> chore: Upgrade versions to 0.5.3

- docs/blog/introducing_analytics.mdx
- Closes #
Address Hamish's comment
> chore: Clarify language in blog post

- pg_bm25/README.md
- Closes #751
There is a specific version required, which this clarifies.
> chore: Clarify libicu requirement

- docs/search/indexing/overview.mdx
- Closes #
Ming had a clearer suggestion, so using it here.
> docs: Improve docs for consistency

- docs/mint.json
- Closes #
Configure redirects so that the old blog links aren't broken
> docs: Redirect blog to new site

- README.md
- docs/changelog/0.5.4.mdx
- docs/introduction.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.5.3--0.5.4.sql
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.5.3--0.5.4.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.3-0.5.4.sql
- pg_sparse/svector.control
- Closes #
Upgrade scripts for 0.5.4 release.
Also minor README rephrasing
> docs: Add upgrade scripts

- .github/workflows/publish-pg_analytics.yml
- .github/workflows/publish-pg_bm25.yml
- .github/workflows/publish-pg_sparse.yml
- Closes #788
Some of our users are still using PG15, so let's publish both.
> feat: Also publish pg15 debs

- .github/workflows/test-pg_analytics.yml
- .github/workflows/test-pg_bm25.yml
- Cargo.lock
- Closes #
This happened: https://github.com/paradedb/paradedb/actions/runs/7894031937/job/21543855648
We would've caught it if we tested packaging when doing Prod promotions, so now we do!
^
^
See CI
> ci: Test packaging the extensions on promotion PRs

- pg_analytics/README.md
- Closes #
Forgot to rename deltalake to parquet in one part of the readme
> docs: Fix README

- docs/changelog/0.5.6.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.5.5--0.5.6.sql
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.5.5--0.5.6.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.5--0.5.6.sql
- pg_sparse/svector.control
> chore: Upgrade to 0.5.6

- docs/changelog/0.5.6.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/README.md
- pg_analytics/sql/pg_analytics--0.5.5--0.5.6.sql
- pg_analytics/src/hooks/executor.rs
- pg_analytics/tests/basic.rs
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.5.5--0.5.6.sql
- pg_bm25/src/api/search.rs
- pg_bm25/src/postgres/build.rs
- pg_bm25/tests/bm25_search.rs
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.5--0.5.6.sql
- pg_sparse/svector.control
> chore: Prod Promotion -- v0.5.6

- Cargo.lock
- docs/changelog/0.5.7.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.5.6--0.5.7.sql
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.5.6--0.5.7.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.6--0.5.7.sql
- pg_sparse/svector.control
> chore: Upgrade to 0.5.7

- docs/search/quickstart.mdx
> docs: fix spelling in search/quickstart.mdx

- docs/deploy/aws.mdx
> docs: fix spelling in aws.mdx

- .github/workflows/test-pg_analytics.yml
- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_sparse.yml
> ci: Run one test on arm for compatibility

- .github/workflows/test-pg_analytics.yml
- .github/workflows/test-pg_bm25.yml
- pg_analytics/runtests.sh
- pg_bm25/runtests.sh
- Closes #
Now that we also run tests on arm, we also test upgrading on arm. That's probably a good thing, but we need to no longer hardcode the arch!
> fix: Take arch into factor for extension upgrade

- .github/workflows/test-pg_analytics.yml
- .github/workflows/test-pg_bm25.yml
- .github/workflows/test-pg_sparse.yml
- docs/deploy/aws.mdx
- docs/deploy/gcp.mdx
- docs/search/quickstart.mdx
- pg_analytics/runtests.sh
- pg_analytics/src/datafusion/context.rs
- pg_bm25/runtests.sh
- Closes #
This fixes an issue with a datatype between arm and intel, and adds a test to CI to catch it earlier in the future
> feat: Prod Promotion - v0.5.7

- pg_analytics/src/hooks/executor.rs
- pg_analytics/src/hooks/process.rs
- pg_analytics/tests/basic.rs
- Closes #
Fixes a bug where statements like `ALTER TABLE <table> ENABLE ROW LEVEL SECURITY` were failing on heap tables because the process utility hook would try to parse them with `sqlparser`, which doesn't handle 100% of Postgres statements.
If `sqlparser` fails, we just pass the query to Postgres.
Added a test where we enable RLS on a heap table.
> fix: Statements not parseable by `sqlparser` are handed to Postgres

- benchmarks/README.md
- Closes #N/A
Needed to go back one subfolder level
N/A
N/A
N/A
> fix: Fix links in /benchmarks top-level folder

- Cargo.lock
- docs/changelog/0.5.8.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.5.7--0.5.8.sql
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.5.5--0.5.6.sql
- pg_bm25/sql/pg_bm25--0.5.6--0.5.7.sql
- pg_bm25/sql/pg_bm25--0.5.7--0.5.8.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.7--0.5.8.sql
- pg_sparse/svector.control
> feat: Prepare promotion for v0.5.8

- docs/changelog/0.5.8.mdx
> chore: Fix typos in Changelog

- CHANGELOG.md
- Closes #N/A
I've noticed some users looking for it. This is the standard practice, and what DataFusion does as well: https://github.com/apache/arrow-datafusion/blob/main/CHANGELOG.md
Easier to find changelog
^
N/A
> chore: Add top-level ParadeDB changelog

- .github/workflows/publish-paradedb.yml
- Closes #
We don't actually list on AWS marketplace yet, so this is not needed and it's been causing troubles.
> fix: Remove ECR

- .github/workflows/publish-paradedb.yml
- Closes #
This fixes an issue with the Docker deployment due to ECR
> feat: Prod Promotion - v0.5.8

- docs/changelog/0.5.8.mdx
> fix:  Language in 0.5.8 changelog

- docker/01_bootstrap.sh
- docker/docker-compose.dev.yml
- shared/src/telemetry/posthog.rs
- Closes #954 
Fix an issue where passing telemetry would crash the Docker container bootstrap.
> fix: Fix Docker telemetry

- Cargo.lock
- docs/changelog/0.5.9.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.5.8--0.5.9.sql
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.5.8--0.5.9.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.8--0.5.9.sql
- pg_sparse/svector.control
> chore: Prepare 0.5.9 release

- docs/analytics/quickstart.mdx
- docs/analytics/replication.mdx
- docs/analytics/types.mdx
- docs/mint.json
- pg_analytics/README.md
- pg_analytics/tests/primitives.rs
- Closes #968 
- Closes #874 
Adds documentation for supported types and backup solutions.
Wrote tests for supported array types.
> docs: Document and test supported types + backup solutions

- docs/changelog/0.5.10.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.5.9--0.5.10.sql
- pg_bm25/Cargo.toml
- pg_bm25/sql/pg_bm25--0.5.9--0.5.10.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.9--0.5.10.sql
- pg_sparse/svector.control
> chore: Upgrade 0.5.10

- pg_bm25/README.md
> fix: pg_bm25 README typo

- README.md
- Closes #N/A
We list the number of Docker pulls we have, but I thought it'd be nice to list the number of extension self-hosted.
Showcase how great ParadeDB is!
Used shields.io
See the README
> chore: Add extension deployment counts

- Cargo.lock
- docs/changelog/0.6.0.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.5.11--0.6.0.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.5.11--0.6.0.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.5.11--0.6.0.sql
- pg_sparse/svector.control
- shared/Cargo.toml
- Closes #N/A
Changelog and version numbers
^
^
^
> chore: Prepare v0.6.0

- .github/workflows/test-pg_analytics.yml
- .github/workflows/test-pg_search.yml
- pg_search/runtests.sh
> ci: Fix extension upgrade test following renaming + restructuring of version

- .github/workflows/lint-markdown.yml
- docs/analytics/htap.mdx
- docs/analytics/quickstart.mdx
- docs/analytics/udf.mdx
- docs/mint.json
- docs/search/quickstart.mdx
- docs/upgrading.mdx
Adds documentation for HTAP joins and UDF limitations
> docs: federated joins and udfs

- docs/search/quickstart.mdx
- pg_search/README.md
- pg_search/benchmarks/benchmark-pg_search.sh
- pg_search/tests/quickstart.rs
> docs: Update quickstart examples to use efficient filtering/limit

- README.md
- Closes #
Clarify language for using ParadeDB.
> chore: Add commercial information to README

- docker/docker-compose.dev.yml
- docker/docker-compose.yml
- Closes #
It is apparently deprecated, so removing to silence the warning.
> chore: Rm compose version

- README.md
- docker/docker-compose.dev.yml
- docker/docker-compose.yml
- pg_analytics/src/lib.rs
- pg_search/src/lib.rs
- Closes #
Fix a small issue causing the Dockerfile not to start properly in `v0.6.0`.
> fix: Prod Promotion v0.6.0

- README.md
> chore: Update Typeform link

- docs/mint.json
- Closes #N/A
This enables better analytics on our docs, and correlating with our blog.
^
^
^
> chore: Add Google Tag Manager

- docs/changelog/0.6.1.mdx
- docs/mint.json
- pg_analytics/Cargo.toml
- pg_analytics/sql/pg_analytics--0.6.0--0.6.1.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.6.0--0.6.1.sql
- pg_sparse/Makefile
- pg_sparse/sql/svector--0.6.0--0.6.1.sql
- pg_sparse/svector.control
- shared/Cargo.toml
> chore: Upgrade to 0.6.1

- .github/workflows/test-paradedb.yml
- Closes #N/A
We keep having issues where it builds in our CI tests, but not in the Dockerfile. We should just test that every PR.
^
^
^
> ci: Also test Docker on `src/` code change to our extensions

- .github/workflows/publish-paradedb.yml
- Closes #N/A
I noticed we only print the short one in our telemetry. This will help debug down the line.
^
^
^
> chore: Print full commit SHA

- Cargo.lock
- pg_analytics/Cargo.toml
- pg_analytics/src/datafusion/catalog.rs
- pg_analytics/src/datafusion/context.rs
- pg_analytics/src/datafusion/query.rs
- pg_analytics/src/datafusion/schema.rs
- pg_analytics/src/datafusion/table.rs
- pg_analytics/src/datafusion/writer.rs
- pg_analytics/src/federation/executor.rs
- pg_analytics/src/types/timestamp.rs
N/A
Upgrade delta-rs to the latest version, which allows us to also upgrade datafusion-federation and datafusion to the latest versions.
^^
^^
No new tests needed
> chore: upgrade delta-rs, datafusion, and datafusion-federation

- docs/deploy_pg_analytics.mdx
- docs/deploy_pg_search.mdx
- docs/mint.json
- Closes #N/A
It's been asked several times by our users. This should clarify things.
Make sure people can get started easily.
Just wrote some docs!
N/A
> docs: Add documentation for installing extensions

- pg_lakehouse/Cargo.toml
- pg_search/Cargo.toml
> fix: Fix pg_lakehouse packaging

- .github/CODEOWNERS
> chore: Fix CODEOWNERS

- pg_lakehouse/src/lib.rs
- Closes #
Disable telemetry until we correctly configure it for `pg_lakehouse`
> chore: Disable telemetry

- .github/CODEOWNERS
- pg_lakehouse/src/lib.rs
- Closes #
A fix to the v0.7.0 to avoid a telemetry issue in `pg_lakehouse`
> feat: Prod Promotion v0.7.0

- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- Closes #N/A
We ran out of Ubicloud credits, and Depot still gives us ~9.9k$ credits. We'll convert to this to avoid unnecessary spending for now.
^
^
Tested the connection manually. Will run at the next deploy.
> chore: Convert from Ubicloud to Depot

- docs/analytics/quickstart.mdx
- pg_lakehouse/README.md
- Closes #
Add docs about partitioned directories in the quickstart
> docs: Make it more clear how to create a foreign table over a directory

- pg_search/README.md
- Closes #
- Clean up roadmap
- Clean up overview section
> docs: Update `pg_search` README

- THANKYOU.md
- Closes #N/A
I think they deserve a thank you too! cc @Xuanwo 
^
N/A
N/A
> chore: Add OpenDAL to THANKYOU.md

- Cargo.lock
- README.md
- docs/analytics/object_stores/gcs.mdx
- docs/analytics/object_stores/s3.mdx
- docs/analytics/quickstart.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/README.md
- pg_lakehouse/src/api/mod.rs
- pg_lakehouse/src/datafusion/catalog.rs
- pg_lakehouse/src/datafusion/provider.rs
- pg_lakehouse/src/datafusion/schema.rs
- pg_lakehouse/src/fdw/base.rs
- pg_lakehouse/src/fdw/gcs.rs
- pg_lakehouse/src/fdw/handler.rs
- pg_lakehouse/src/fdw/local.rs
- pg_lakehouse/src/fdw/options.rs
- pg_lakehouse/src/fdw/s3.rs
- pg_lakehouse/src/schema/attribute.rs
- pg_lakehouse/src/schema/cell.rs
- pg_lakehouse/tests/scan.rs
- shared/src/fixtures/tables/nyc_trips.rs
- Closes #1134 
- Adds support for Google Cloud Storage
- Fixes a bug where Delta tables in S3/GCS weren't working
- Fixes a bug where `Decimal128` and numerics weren't being handled correctly
- Removes `bucket` and `root` from server options - they can be inferred from the table path
> feat: GCS support + bug fixes

- .github/workflows/lint-rust.yml
- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/test-pg_lakehouse.yml
- .github/workflows/test-pg_search.yml
- Closes #N/A
It's not needed, apparently. This is part of a side effort I am doing to cleanup a few things in our repo which have grown unwieldy over time.
> chore: Remove Rust install in CI

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.7.1.mdx
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.7.0--0.7.1.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.7.0--0.7.1.sql
- shared/Cargo.toml
> chore: Prepare v0.7.1

- pg_search/sql/pg_search--0.5.10--0.5.11.sql
- pg_search/sql/pg_search--0.5.11--0.6.0.sql
- pg_search/sql/pg_search--0.5.5--0.5.6.sql
- pg_search/sql/pg_search--0.5.6--0.5.7.sql
- pg_search/sql/pg_search--0.5.7--0.5.8.sql
- pg_search/sql/pg_search--0.5.8--0.5.9.sql
- pg_search/sql/pg_search--0.5.9--0.5.10.sql
- Closes #
We only tested upgrading from 0.6 onwards, so we should only keep those as we have no guarantee the old ones work. Either way, there's no point to the old ones.
> chore: Remove more outdated SQL scripts

- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- docs/deploy/pg_analytics.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- pg_search/README.md
- Closes #N/A
Customer request. Also fixed some typos.
^
^
^
> chore: Also deploy extensions to PG14

- pg_lakehouse/src/datafusion/context.rs
- pg_lakehouse/src/fdw/local.rs
- Closes #
Reading local delta tables was accidentally broken by a previous PR.
> fix: Local delta tables

- .github/workflows/test-pg_lakehouse.yml
- .github/workflows/test-pg_search.yml
- Closes #
These were missing, breaking the `dev` CI
> fix: Add skips in the right places

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.5.8.mdx
- docs/changelog/0.7.2.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.7.1--0.7.2.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.7.1--0.7.2.sql
- shared/Cargo.toml
> chore: Prepare `v0.7.2`

- .github/workflows/benchmark-pg_lakehouse.yml
- .github/workflows/benchmark-pg_search.yml
- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/test-pg_lakehouse.yml
- .github/workflows/test-pg_search.yml
- Closes #
We have a blocker in CI when trying to run `cargo pgrx install`
> fix: Set permissions to the whole folder

- .github/workflows/benchmark-pg_lakehouse.yml
- .github/workflows/benchmark-pg_search.yml
- .github/workflows/test-pg_lakehouse.yml
- .github/workflows/test-pg_search.yml
- Closes #
As per: https://github.com/pgcentralfoundation/pgrx/blob/develop/cargo-pgrx/README.md#installing-your-extension-locally
> fix: Add --sudo to `cargo pgrx install` in CI

- pg_analytics/README.md
> docs: Update pg_analytics README

- docs/changelog/0.7.2.mdx
- Closes #
We merged Ming's PR, so we need to update the changelog. I didn't expect it to go in this release.
> chore: Add Azure to changelog

- Cargo.lock
- pg_lakehouse/Cargo.toml
- Closes #
I realized that Avro is feature flagged in DataFusion and needs to be enabled.
> feat: Enable avro

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.7.3.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.7.2--0.7.3.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.7.2--0.7.3.sql
- shared/Cargo.toml
- Closes #N/A
Adds the changelog and updates the version numbers
> chore: Prepare `v0.7.3` release

- .github/workflows/benchmark-pg_lakehouse.yml
- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/test-pg_lakehouse.yml
- Cargo.lock
- cargo-paradedb/Cargo.toml
- docker/Dockerfile
- docs/analytics/object_stores/azblob.mdx
- docs/analytics/object_stores/azdls.mdx
- docs/analytics/object_stores/gcs.mdx
- docs/analytics/object_stores/s3.mdx
- docs/changelog/0.7.3.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.7.2--0.7.3.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.7.2--0.7.3.sql
- shared/Cargo.toml
> chore: Prod Promotion - `v0.7.3`

- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- Closes #
This is required in the case of Debian deployments
> fix: Also install Rust on `publish-pg_search`

- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- Closes #
Hotfix to the new CI deployment
> feat: Prod Promotion v0.7.3

- .cargo/config.toml
- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- Closes #
fix: Fix illegal instructions issue on `arm64` extensions (#1210)
> feat: Prod Promotion - v0.7.3

- README.md
- docs/deploy/pg_analytics.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- pg_lakehouse/README.md
- Closes #
We've added more pre-built binaries!
> chore: Fix documentation on prebuilt binaries

- pg_search/src/postgres/utils.rs
- pg_search/tests/index_config.rs
- Closes #1231
Fixed incorrect indexing on datums caused by drop column
^^
^^
1 test for drop column and re-create index
> fix: fix indexing on datums

- docs/mint.json
- Closes #
Puts the latest version in the doc header.
> docs: Add current version to header

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.7.4.mdx
- docs/deploy/pg_analytics.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.7.3--0.7.4.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.7.3--0.7.4.sql
- shared/Cargo.toml
> chore: Prepare promotion v0.7.4

- .github/workflows/test-pg_search.yml
- docker/Dockerfile
- Closes #
There was a new release to speed up HNSW builds.
> chore: Upgrade to pgvector 0.7.1

- docs/search/sparse/index.mdx
- Closes #1249 
Typo in our sparse vector search docs
> fix: sparsevec docs

- cargo-paradedb/Cargo.toml
- docs/changelog/0.7.5.mdx
- docs/deploy/pg_analytics.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.7.4--0.7.5.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.7.4--0.7.5.sql
- shared/Cargo.toml
> chore: Prod Promotion 0.7.5

- Cargo.lock
> chore: Add missing Cargo.lock version upgrade

- README.md
- docker/01_bootstrap.sh
- docker/Dockerfile
- Closes #1258
This new extension was released to improve pgvector's performance, so we're bundling it in.
^
^
Needs testing
> feat: Add `pgvectorscale` to ParadeDB 

- .github/workflows/test-pg_search.yml
- docker/Dockerfile
- Closes #
They pushed a hotfix to a broken feature in v0.7.1.
> chore: Upgrade pgvector to v0.7.2

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.7.6.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.7.5--0.7.6.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.7.5--0.7.6.sql
- shared/Cargo.toml
- Closes #N/a
Add the changelog and version bump for v0.7.6.
N/A
N/A
N/A
> chore: Prepare v0.7.6

- .github/workflows/publish-pg_lakehouse.yml
> chore: Add missing if for Ubuntu packaging

- .github/workflows/publish-pg_lakehouse.yml
> chore: Add missing if for pg_lakehouse publishing

- .github/workflows/publish-pg_lakehouse.yml
- Closes #
Fix a missing if for deployment of `pg_lakehouse`
> feat: Prod Promotion -- v0.7.6

- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
> fix: Fix shell expansion in Debian-based packaging

- pg_lakehouse/README.md
- pg_search/src/globals.rs
- pg_search/src/index/search.rs
- pg_search/src/lib.rs
N/A
Just a few minor spelling errors scattered throughout.
It's no fun reading documents with typos.
I used my brain.
I used my brain again with a dictionary this time.
> docs: Fix typos

- CONTRIBUTING.md
- README.md
- benchmarks/README.md
- docs/support.mdx
> chore: Update Slack invite link

- cargo-paradedb/Cargo.toml
- docs/changelog/0.8.0.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.7.6--0.8.0.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.7.6--0.8.0.sql
- shared/Cargo.toml
> chore: Prepare `v0.8.0`

- docs/changelog/0.8.0.mdx
- docs/mint.json
- docs/search/full-text/aggregations.mdx
- pg_search/README.md
- Closes #
Adds docs for faceting/aggregations.
> docs: Add aggregations docs

- .github/workflows/benchmark-pg_lakehouse.yml
- .github/workflows/benchmark-pg_search.yml
- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/test-pg_lakehouse.yml
- .github/workflows/test-pg_search.yml
- Closes #
We had removed it altogether, which broke some deploys
> fix: Install stable rust in CI

- .github/workflows/benchmark-pg_lakehouse.yml
- .github/workflows/benchmark-pg_search.yml
- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/test-pg_lakehouse.yml
- .github/workflows/test-pg_search.yml
> feat: Prod Promotion -- v0.8.0

- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
> chore: Reorder Rust install

- pg_lakehouse/src/api/csv.rs
- pg_lakehouse/src/api/mod.rs
- pg_lakehouse/src/api/parquet.rs
- pg_search/src/postgres/types.rs
- pg_search/tests/key.rs
- tokenizers/src/icu.rs
- tokenizers/src/lib.rs
- tokenizers/src/manager.rs
> chore: Add missing license headers

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.8.1.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.8.0--0.8.1.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.8.0--0.8.1.sql
- shared/Cargo.toml
> chore: Upgrade to 0.8.1

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.8.1.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.8.0--0.8.1.sql
- pg_lakehouse/src/api/csv.rs
- pg_lakehouse/src/api/mod.rs
- pg_lakehouse/src/api/parquet.rs
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.8.0--0.8.1.sql
- pg_search/src/index/search.rs
- pg_search/src/postgres/build.rs
- pg_search/src/postgres/insert.rs
- pg_search/src/postgres/types.rs
- pg_search/src/postgres/utils.rs
- pg_search/src/writer/mod.rs
- pg_search/tests/index_config.rs
- pg_search/tests/key.rs
- shared/Cargo.toml
- tokenizers/src/icu.rs
- tokenizers/src/lib.rs
- tokenizers/src/manager.rs
> feat: Release 0.8.1

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.8.2.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.8.1--0.8.2.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.8.1--0.8.2.sql
- shared/Cargo.toml
> chore: Upgrade to 0.8.2

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.8.2.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- docs/search/full-text/complex.mdx
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.8.1--0.8.2.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.8.1--0.8.2.sql
- pg_search/src/api/index.rs
- pg_search/src/bootstrap/create_bm25.rs
- pg_search/src/query/mod.rs
- pg_search/tests/bm25_search.rs
- pg_search/tests/index_config.rs
- pg_search/tests/query.rs
- shared/Cargo.toml
> feat: Prod Promotion - v0.8.2

- docs/search/hybrid/basic.mdx
- Closes #1329 
- Fixes a typo in hybrid search
- Adds missing documentation for hybrid search with advanced search queries
> docs: Hybrid search

- .github/ISSUE_TEMPLATE/bug_report.md
- Closes #N/A
A new issue template!
We keep getting bug reports which are difficult to answer due to missing information. This will help solve this issue.
Thank you to the @duckdb team for the inspiration on this issue template!
N/A
> chore: Update Issue Template

- .github/ISSUE_TEMPLATE/bug_report.md
> chore: Fix bug report template

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.8.3.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.8.2--0.8.3.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.8.2--0.8.3.sql
- shared/Cargo.toml
> chore: Upgrade 0.8.3

- .github/ISSUE_TEMPLATE/bug_report.md
> chore: Fix the issue template

- .github/workflows/benchmark-pg_lakehouse.yml
- .github/workflows/benchmark-pg_search.yml
- .github/workflows/test-paradedb.yml
- .github/workflows/test-pg_lakehouse.yml
- .github/workflows/test-pg_search.yml
> fix: Fix ignore paths in CI

- .github/workflows/publish-paradedb.yml
- Closes #
Fixes this: https://github.com/paradedb/paradedb/actions/runs/9863063565/job/27234999940
> fix: Only create `paradedb-enterprise` if there is no open PR

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .prettierignore
> fix: Fix GitHub Issue template

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.8.3.mdx
- docs/changelog/0.8.4.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.8.3--0.8.4.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.8.3--0.8.4.sql
- shared/Cargo.toml
> chore: Prepare v0.8.4

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> chore: Fix issue

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> fix: Clean up GitHub Issue

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> chore: Nitpick to standardize issues

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- Closes #N/a
Add labels so we can easily see what people are pushing as GitHub Issues.
^
N/A
N/A
> chore: Add labels

- .github/workflows/benchmark-pg_lakehouse.yml
- .github/workflows/benchmark-pg_search.yml
- Cargo.lock
> fix: Fix broken benchmarks CI

- .github/workflows/publish-paradedb.yml
- Closes #
We'll just do it manually
> chore: Remove `paradedb-enterprise` sync

- .github/ISSUE_TEMPLATE/bug_report.yml
- Closes #N/A
I modified it a bit more to provide more information about whether the user is using extensions or our Docker/Helm files.
Easier debug
N/A
N/A
> chore: Polish issue template

- .github/workflows/benchmark-pg_lakehouse.yml
- .github/workflows/benchmark-pg_search.yml
> chore: Fix typo in our benchmark CI

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.8.5.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.8.4--0.8.5.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.8.4--0.8.5.sql
- shared/Cargo.toml
- tokenizers/Cargo.toml
> chore: Upgrade to 0.8.5

- .github/workflows/test-pg_search.yml
- docker/Dockerfile
- Closes #N/A
New release dropped!
N/A
N/A
N/A
> chore: Upgrade pgvector

- README.md
- Closes #N/A
Some anthills inspired by popular open-source repos.
N/A
N/A
N/A
> chore: Add badges

- README.md
> chore: Fix redirects in badges

- Cargo.lock
- pg_lakehouse/Cargo.toml
- pg_lakehouse/src/schema/cell.rs
> chore: Upgrade `wrappers` to latest version

- .prettierignore
- CONTRIBUTING.md
- docs/mint.json
- docs/search/full-text/joins.mdx
- pg_search/tests/documentation.rs
- Closes #
Added documentation on how to create a BM25 index over materialized views. Added tests for all examples in this documentation.
> chore: Docs and tests for materialized views

- docs/upgrading.mdx
> docs: Fix documentation for extension upgrade

- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- Closes #1116 
This PR adds support for pre-packaging EL8 binaries. This was requested by @Vonng.
Most popular OS in China
Had to fiddle with the dependencies for a bit, but made it work.
See https://github.com/paradedb/paradedb/releases/tag/v0.0.0 for the successfully uploaded version
> feat: Ship binaries for RHEL 8

- docs/search/quickstart.mdx
- Closes #
Missing comma in quickstart code example
> fix: readme typo

- docs/search/full-text/overview.mdx
- Closes #
Found a typo in the docs
I fixed the spelling
> docs: fix misspelling of algorithm

- .github/workflows/test-pg_search.yml
- docker/Dockerfile
- Closes #N/A
They fixed a nasty bug with parallel indexing
N/A
N/A
N/A
> chore: Upgrade pgvector to 0.7.4

- CONTRIBUTING.md
- Cargo.lock
- README.md
- Closes #1452
A user pointed out that our CONTRIBUTING.md file was outdated. This PR fixes that.
Make it easier for people to contribute!
N/A
N/A
> chore: Update CONTRIBUTING.md

- docs/mint.json
- docs/replication/pg_lakehouse.mdx
- docs/replication/pg_search.mdx
- docs/search/replication/setup.mdx
> chore: Add docs for pg_search replication

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.9.0.mdx
- docs/deploy/pg_lakehouse.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- docs/upgrading.mdx
- pg_lakehouse/Cargo.toml
- pg_lakehouse/sql/pg_lakehouse--0.8.6--0.9.0.sql
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.8.6--0.9.0.sql
- shared/Cargo.toml
- tokenizers/Cargo.toml
- Closes #N/A
This PR prepares the `v0.9.0` release.
N/A
N/A
N/A
> chore: Prepare v0.9.0

- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- Cargo.lock
- pg_lakehouse/Cargo.toml
- tokenizers/Cargo.toml
- Closes #N/A
These two were blocking deployments. I've created an issue to re-add `--features icu` to the RHEL deployments once we've got time to test it properly: #1479
Fix deploys
N/A
See CI
> fix: Remove `--features icu` from RHEL deploys, and fix Dockerfile build

- .github/workflows/publish-pg_lakehouse.yml
- .github/workflows/publish-pg_search.yml
- Cargo.lock
- pg_lakehouse/Cargo.toml
- Closes #N/A
This fixes two small issues in our latest deployment.
^
^
^
> feat: Prod Promotion - v0.9.0

- .github/workflows/publish-pg_analytics.yml
- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.9.1.mdx
- docs/deploy/pg_analytics.mdx
- docs/deploy/pg_search.mdx
- docs/mint.json
- docs/upgrading.mdx
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.9.0--0.9.1.sql
- shared/Cargo.toml
- tokenizers/Cargo.toml
> chore: Prepare v0.9.1

- .github/workflows/test-pg_analytics.yml
> chore: Comment out upgrade test for `pg_analytics`

- README.md
- docker/bootstrap.sh
- docker/docker-compose.yml
- docs/deploy/aws.mdx
- docs/deploy/gcp.mdx
- docs/introduction.mdx
- pg_search/README.md
- Closes #1525
This fixes a lapse in our documentation, where we mounted to the wrong volume.
Correct docs!
Update docs!
> docs: Fix the documentation for setting a Docker volume

- .github/workflows/test-paradedb.yml
- README.md
- docker/Dockerfile
- docker/bootstrap.sh
- docker/docker-compose.yml
- docs/deploy/aws.mdx
- docs/deploy/gcp.mdx
- docs/introduction.mdx
- docs/search/full-text/index.mdx
- pg_search/README.md
- pg_search/src/bootstrap/create_bm25.rs
- pg_search/src/postgres/build.rs
- pg_search/tests/index_config.rs
- Closes #
Hotfix to `v0.9.1` to account for a small issue in `pg_cron` and in our documentation.
> feat: Prod Promotion - v0.9.1

- docs/search/performance.mdx
> feat: Adding memory tuning to performance docs

- pg_search/tests/replication.rs
Installing `pg_search` only on replicas is a common workflow, so we should have a test for it.
> chore: add replication test for replica-only installation of pg_search

- CONTRIBUTING.md
- Closes #
This was pointed out in #1537.
> docs: Clarify CONTRIBUTING.md

- pg_search/src/api/config.rs
> chore: Missing license in `api/config.rs`

- .github/workflows/test-paradedb.yml
- docs/mint.json
- Closes #N/A
We keep facing issues with architecture causing crashes for illegal instructions on ARM64 machines when running the Dockerfile. This adds a test to make sure we catch this moving forward.
I also added a missing changelog entry.
N/A
N/A
See CI
> ci: Add Docker ARM Test

- docs/search/performance.mdx
> fix: Index memory tuning

- docs/mint.json
Similar to: https://github.com/paradedb/paradedb/pull/1294/files
> chore: Update slack invite in docs

- pg_search/src/api/operator.rs
- pg_search/src/api/search.rs
- pg_search/src/index/state.rs
- pg_search/src/postgres/scan.rs
Does some cleanup that should follow after #1571 is merged.
Clean code is good code
> chore: Cleanup issue 1571

- docs/ingest/configuration/schema.mdx
- Closes #
Add documentation for https://github.com/paradedb/pg_analytics/pull/103 which makes it possible to modify the columns created in a DuckDB view.
> docs: Document foreign table column configuration

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docker/Dockerfile
- docs/changelog/0.9.3.mdx
- docs/deploy/pg_analytics.mdx
- docs/deploy/pg_search.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.9.2--0.9.3.sql
- shared/Cargo.toml
- tokenizers/Cargo.toml
> chore: Upgrade 0.9.3

- .github/workflows/test-paradedb.yml
> ci: On dev, don't use Depot

- .github/workflows/test-pg_search.yml
- Closes #N/A
I don't think we need this and it slows down CI
^
^
^
> ci: RM `cargo clean`

- README.md
- Closes #N/A
It was linking to the homepage.
^
^
^
> docs: Update blog URL

- docs/api-reference/full-text/bm25.mdx
- Closes https://github.com/paradedb/paradedb/issues/1609
See issue
See issue
> docs: document datetime and set terms filtering options

- pg_search/src/postgres/utils.rs
- Closes # n/a
While working on Custom Scan stuff, I releazed that there's a slightly more efficient way of doing the visibility checks we need to perform. This uses `ReleaseAndReadBuffer`, which Postgres says one should prefer as it eliminates the separate Release and Read steps.
We also reduce the time the last Buffer's lock is held to be as short as possible.
This logic was reduced out of Postgres' `nodeindexscan.c` functions.
General cleanup and correctness
Existing tests pass locally.
> chore: Cleanup the Visibility Checker

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docker/Dockerfile
- docs/changelog/0.9.3.mdx
- docs/changelog/0.9.4.mdx
- docs/deploy/pg_analytics.mdx
- docs/deploy/pg_search.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.9.3--0.9.4.sql
- shared/Cargo.toml
- tokenizers/Cargo.toml
> chore: Prepare v0.9.4

- Cargo.lock
- pg_search/Cargo.toml
- pg_search/src/index/search.rs
- pg_search/src/index/state.rs
- pg_search/src/query/mod.rs
- pg_search/src/schema/document.rs
- pg_search/tests/bm25_search.rs
- tokenizers/Cargo.toml
- Part #1547
Since Aggregations are an enterprise feature of ParadeDB, I cannot access the source code to integrate Cardinality.
> chore: Rebase tantivy to support more aggregation functions

- .github/workflows/publish-paradedb.yml
- Closes #
This will publish new versions of ParadeDB to the new Helm chart
> chore: Update to new Helm Chart repo

- docs/deploy/replication.mdx
> docs: Update replication.mdx (replciated -> replicated)

- .github/workflows/benchmark-pg_search.yml
- .github/workflows/lint-rust.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/test-pg_search.yml
- docker/Dockerfile
> feat: Dynamically determine pgrx version in CI / Docker

- pg_search/src/api/search.rs
> fix: compilation problem in dev

- .github/DISCUSSION_TEMPLATE/general.yml
- .github/DISCUSSION_TEMPLATE/ideas.yml
- .github/DISCUSSION_TEMPLATE/q-a.yml
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- README.md
- docs/deploy/helm.mdx
- Closes #N/A
We're now using our own repo forked from `cloudnative-pg/charts`, so the URL was changed. This updates it accordingly.
^
^
^
> chore: Update documentation for new Helm Charts

- pg_search/src/postgres/scan.rs
> fix: merge conflict mistake

- README.md
- pg_search/README.md
- Closes #N/A
It was requested by several users. This will also help us get more feedback.
^
^
^
> chore: Add detailed public-facing roadmap

- .github/workflows/test-pg_search.yml
- Closes #
We need to comment it out and rebase it off of 0.10.0 once the release is live because we're making a non-backwards-compatible release.
> chore: Comment out upgrade test

- docs/api-reference/full-text/sorting.mdx
- Closes #
Fixes mistake in docs.
> docs: stable_sort defaults to `true`

- pg_search/src/index/state.rs
- Closes # n/a
This improves performance of returning large resultsets.
Locally, this improved a simple query that returns 2.1M rows by a little over 3x:
```sql
[v16.2][1826627] foo=# select count(*) from foo where id @@@ 'body:the';
count   
----------
21599227
(1 row)
Time: 18440.915 ms (00:18.441)
```
```sql
[v16.2][1831083] foo=# select count(*) from foo where id @@@ 'body:the';
count   
----------
21599227
(1 row)
Time: 5837.171 ms (00:05.837)
```
Faster is always better.
In the "search with channel" case, rather than sending each match over the channel individually, we collect them into a Vec (per segment).
Once the segment has found all matching docs, its set of matches are then sorted by ctid and the whole vec is sent over the channel.
Sorting by ctid helps Postgres in that, at …
> feat: improve perf of selecting large resultsets

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.10.1.mdx
- docs/deploy/pg_search.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.10.0--0.10.1.sql
- shared/Cargo.toml
- tokenizers/Cargo.toml
> chore: Upgrade to 0.10.1

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.10.2.mdx
- docs/deploy/pg_search.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.10.1--0.10.2.sql
- shared/Cargo.toml
- tokenizers/Cargo.toml
> chore: Prepare 0.10.2

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.10.2.mdx
- docs/deploy/pg_search.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.10.1--0.10.2.sql
- pg_search/src/api/operator/searchconfig.rs
- shared/Cargo.toml
- shared/src/gucs.rs
- tokenizers/Cargo.toml
> feat: Prod Promotion -- v0.10.2

- docs/ingest/import/json.mdx
- docs/mint.json
No ticket associated
Docs for https://github.com/paradedb/pg_analytics/pull/133
Inspired by docs for CSV ingest
N/A
> docs: json ingest docs

- .codespellignore
- .github/workflows/check-typo.yml
- shared/src/telemetry/bgworker.rs
> feat: Add GitHub Actions Workflow to check for typos

- Cargo.lock
- cargo-paradedb/Cargo.toml
- docs/changelog/0.10.3.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.10.2--0.10.3.sql
- shared/Cargo.toml
- tokenizers/Cargo.toml
> chore: Prepare `0.10.3`

- .github/workflows/publish-paradedb.yml
- Closes #N/A
The version wasn't passed properly. This fixes that, to enable us to hotfix Docker and Helm deploys manually.
^
^
^
> fix: Fix manual deploy of Helm chart

- .github/workflows/lint-rust.yml
- Closes #N/A
I randomly realized this was missing in the flight.
Speed up CI
^
^
> chore: Add rust cache to lint rust for faster runtime

- .github/workflows/publish-paradedb.yml
- .github/workflows/test-paradedb.yml
- docker/Dockerfile
- docs/deploy/self-hosted/docker.mdx
- docs/welcome/introduction.mdx
- Closes #1736
Add Docker images for Postgres 13 to 17.
See #1736
See #1736
See CI.
> chore: Add Docker images for Postgres 13 to 17

- Cargo.lock
- docker/Dockerfile
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- pg_search/Cargo.toml
- pg_search/README.md
- shared/Cargo.toml
- Closes #
Upgrades to pgrx `0.12.6`
> chore: pgrx `0.12.6` upgrade

- pg_search/sql/pg_search--0.10.3--0.10.4.sql
- pg_search/src/api/operator/searchconfig.rs
- pg_search/src/api/operator/searchqueryinput.rs
- pg_search/src/api/operator/text.rs
- pg_search/tests/query.rs
> fix:  prepared statements will replan to avoid sequential scans

- pg_search/sql/pg_search--0.10.3--0.10.4.sql
- Closes #
This fixes some issues with the `sql/pg_search--0.10.3--0.10.4.sql` upgrade script.
> fix: ALTER EXTENSION upgrade script

- docs/documentation/advanced/term/range_term.mdx
- docs/documentation/full-text/sorting.mdx
- docs/documentation/getting-started/quickstart.mdx
- docs/documentation/indexing/create_index.mdx
- docs/mint.json
- pg_search/src/bootstrap/test_table.rs
- pg_search/tests/documentation.rs
- Closes #
Documents the usage of `range_fields` and `range_term`.
Should be merged after #1783 goes in, as it contains documentation for APIs introduced in that PR.
Need to add tests for new documented code blocks.
> docs: `range_term`

- .github/workflows/assign-github-issue.yml
- .github/workflows/benchmark-pg_search.yml
- .github/workflows/check-pg_search-schema-upgrade.yml
- .github/workflows/check-typo.yml
- .github/workflows/lint-bash.yml
- .github/workflows/lint-docker.yml
- .github/workflows/lint-format.yml
- .github/workflows/lint-markdown.yml
- .github/workflows/lint-pr-title.yml
- .github/workflows/lint-rust.yml
- .github/workflows/lint-yaml.yml
- .github/workflows/publish-github-release.yml
- .github/workflows/publish-paradedb.yml
- .github/workflows/publish-pg_search.yml
- .github/workflows/test-docs.yml
- .github/workflows/test-paradedb.yml
- .github/workflows/test-pg_search.yml
- Closes #N/A
PR 2/2 to move off of Depot after the fat bills they're about to send us (without informing us before!). Ubicloud is 10x cheaper, and we just need to change the runner tag :)
Money is better in our bank account than in someone else's.
Change runner names, we already had an Ubicloud account.
Well, CI!
> chore: Move from Depot to Ubicloud

- .github/workflows/benchmark-pg_search.yml
> ci: make the benchmark job faster and have a memory

- .github/workflows/benchmark-pg_search.yml
> ci: Run benchmark on dev to fill CI

- docs/deploy/self-hosted/k8s.mdx
- Closes #N/A
It was out of date following recent updates to our Helm Chart.
This PR is dependent on: https://github.com/paradedb/charts/pull/46: EDIT, PR #47, the rebase, is merged.
Up-to-date documentation is good.
Wrote more words that reflect the present state.
These were all tested manually and in CI in the development of the Helm Chart
> docs: Update Kubernetes documentation

- .prettierignore
- docs/documentation/full-text/scoring.mdx
- docs/documentation/full-text/sorting.mdx
- docs/documentation/indexing/fast_fields.mdx
- Closes #
Edits to docs for PR #1820
> docs: Suggestions on top N sort

- docs/documentation/advanced/term/regex.mdx
- tests/tests/documentation.rs
- Closes #
Introduces an example wildcard query so that the term "wildcard" is indexed in our docs
> docs: Example wildcard query

- .github/workflows/benchmark-pg_search.yml
> ci: Test comparing benchmark performances

- pg_search/sql/pg_search--0.11.0--0.11.1.sql
> fix:  the v0.11.0--v0.11.1 upgrade script

- .github/workflows/test-pg_search-upgrade.yml
- .github/workflows/test-pg_search.yml
- Closes #1813
This adds the extension upgrade test again. It was previously removed due to reworking of our CI.
Ensure our extensions upgrade properly.
Add a new workflow.
See CI!
> ci: Re-add extension upgrade test

- tests/tests/documentation.rs
> chore: fix quickstart test

- .github/workflows/test-paradedb.yml
- docker/Dockerfile
> chore: Remove last reference to Depot

- .github/workflows/test-pg_search-upgrade.yml
> chore: fix test working dir

- .github/workflows/publish-paradedb.yml
- docker/Dockerfile
> feat: Prod Promotion -- v0.11.1

- .github/workflows/publish-paradedb.yml
> fix: Swap to Depot for Docker

- docs/documentation/full-text/boosting.mdx
- Closes #1861
Brought up by a user.
Correct docs.
Swap words.
None
> docs: Fix typo in "Boosting" section

- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- Closes #N/A
Improve our docs on how to upgrade the extension, to avoid issues
N/A
N/A
N/A
> docs: Improve extension upgrade docs

- docs/deploy/self-hosted/docker.mdx
- docs/documentation/getting-started/install.mdx
- docs/documentation/getting-started/load.mdx
- docs/documentation/getting-started/quickstart.mdx
- docs/welcome/introduction.mdx
- Closes #N/A
A few users faced issues getting started, especially in a VPC environment. This PR clarifies the docs.
Ease of onboarding for users.
Write words after doing research.
N/A
> docs: Improve `pg_dump` documentation

- .github/workflows/test-pg_search.yml
- Closes #N/A
We moved it to the top-level workspace.
> ci: Fix version check

- .github/workflows/test-pg_search-upgrade.yml
- .github/workflows/test-pg_search.yml
- docker/Dockerfile
- Closes #
We have reworked the versions around a bit, which this fixes.
> ci: Fix upgrade issues with promotion

- docs/documentation/aggregates/overview.mdx
- docs/documentation/configuration/parallel.mdx
- pg_search/src/index/merge_policy.rs
- pg_search/src/index/search.rs
- pg_search/src/postgres/build.rs
- pg_search/src/postgres/insert.rs
- tests/tests/cleanup.rs
- tests/tests/replication.rs
> feat: Prod Promotion -- 0.12.0

- docs/documentation/aggregates/limitations.mdx
- docs/documentation/aggregates/overview.mdx
- docs/mint.json
- Closes #
Updates instructions for configuring fast aggregates based on latest testing
> docs: update fast field instructions

- docs/documentation/indexing/create_index.mdx
> docs: recommend integer key field

- docs/documentation/aggregates/common.mdx
- docs/documentation/aggregates/limitations.mdx
- docs/documentation/aggregates/overview.mdx
- Closes #
Update aggregates with latest query plans and info.
> docs: Update aggregates

- .github/workflows/check-typo.yml
- .github/workflows/publish-pg_search.yml
- Closes #
Fixed a small issue with Docker authentication.
> feat: Prod Promotion -- v0.12.1

- pg_search/src/index/reader.rs
- Closes #
This specializes doing searches when there's no scores being calculated to try and minimize the amount of memory that has to be allocated for each matching tantivy doc.
On a query like `SELECT count(*) FROM t WHERE ...@@@...` this shaves off another ~25%, give or take.
Existing tests pass
> feat: improve performance of `SearchIndexReader::search_via_channel()/search_segment()`

- Cargo.lock
- Cargo.toml
- docs/changelog/0.12.2.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
> chore: Prepare 0.12.2

- pg_search/sql/pg_search--0.12.1--0.12.2.sql
> chore: Add missing upgrade script for 0.12.2

- Cargo.lock
- Cargo.toml
- docs/changelog/0.12.2.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
- pg_search/sql/pg_search--0.12.1--0.12.2.sql
- pg_search/src/api/operator/text.rs
- pg_search/src/index/reader.rs
- pg_search/src/postgres/customscan/pdbscan/exec_methods/normal.rs
- pg_search/src/postgres/customscan/pdbscan/mod.rs
- pg_search/src/postgres/customscan/pdbscan/scan_state.rs
- pg_search/src/postgres/visibility_checker.rs
- tests/tests/cleanup.rs
- tests/tests/parallel_index_scan.rs
> feat: Prod Promotion -- v0.12.2

- tests/tests/documentation.rs
- Closes #
Comments out failing test temporarily, opened #1946 to track the underlying issue.
> chore: comment out failing quickstart test

- docs/documentation/indexing/create_index.mdx
- pg_search/src/postgres/build.rs
- pg_search/src/schema/mod.rs
> feat: Expose fieldnorms for JSON fields

- Cargo.lock
- Cargo.toml
- docs/changelog/0.12.1.mdx
- docs/changelog/0.12.2.mdx
- docs/changelog/0.13.0.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
> chore: Upgrade to `0.13.0`

- docs/documentation/aggregates/tantivy.mdx
- Closes #
Document enterprise Tantivy aggregates in a non-indexed page.
> docs: Tantivy aggregate functions

- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- Closes #N/a
Other OSes were not getting rate limited, and this one was. 🤷
> ci: Fix macOS deploy authorization

- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- Closes #
Small fix to macOS deploy.
> feat: Prod Promotion -- v0.13.0

- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- Closes #
We had an issue with rate limits and incorrect authentication.
> ci: Fix macOS deployment

- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- Cargo.lock
- pg_search/Cargo.toml
> fix: Fix pgrx version

- Cargo.lock
- docs/documentation/advanced/phrase/phrase_prefix.mdx
- docs/documentation/advanced/phrase/regex_phrase.mdx
- pg_search/Cargo.toml
- pg_search/sql/pg_search--0.13.0--0.13.1.sql
- pg_search/src/api/index.rs
- pg_search/src/query/mod.rs
- tests/tests/documentation.rs
- tests/tests/query.rs
> feat: add regex_phrase function for advanced regex queries

- pg_search/src/index/reader.rs
- pg_search/src/index/writer.rs
- pg_search/src/postgres/customscan/hook.rs
- pg_search/src/query/mod.rs
- pg_search/src/trace.rs
- tokenizers/src/cjk.rs
- tokenizers/src/code.rs
- tokenizers/src/lindera.rs
We want to add some specific `allow` directives to address new clippy errors in Rust 1.83.
> chore: fix clippy for rust 1.83

- tokenizers/src/icu.rs
- Closes #1856 
Fixes the icu tokenizer to handle texts containing emojis and multi-byte characters without causing index out-of-bounds errors or deadlocks.
Previously, the icu tokenizer encountered errors when processing texts with emojis or certain special characters... resulting in “index out of bounds” errors or deadlocks.
**Adjusted UTF-16 to UTF-8 Mapping**: Updated the mapping from UTF-16 code unit indices (used by `UBreakIterator`) to UTF-8 byte offsets (used in Rust strings). The new mapping accurately correlates each UTF-16 index with the correct UTF-8 byte offset.
**Modified ICUBreakingWord Implementation:** Revised the `From<&'a str> for ICUBreakingWord<'a>` implementation to build an accurate mapping of UTF-16 indices to byte offsets, accounting for multi-byte characters like …
> fix: correct index mapping in ICUTokenizer for emojis and multi-byte characters

- .gitignore
- docker/Dockerfile
> fix: Downgraded Barman Cloud version because of issues upstream

- Cargo.lock
- Cargo.toml
- README.md
- docs/changelog/0.13.1.mdx
- docs/changelog/0.13.2.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/integrations/object_stores/huggingface.mdx
- docs/mint.json
- pg_search/sql/pg_search--0.13.1--0.13.2.sql
> chore: Upgrade to `0.13.2`

- .github/workflows/publish-pg_search-macos.yml
- Cargo.lock
- Cargo.toml
- README.md
- docs/changelog/0.13.1.mdx
- docs/changelog/0.13.2.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/integrations/object_stores/huggingface.mdx
- docs/mint.json
- pg_search/sql/pg_search--0.13.1--0.13.2.sql
- pg_search/src/postgres/scan.rs
> feat: Prod Promotion -- v0.13.2

- docker/Dockerfile
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- Closes #N/A
New release, fixing some bugs with Azure credential access.
^
^
^
> chore: Update pg_analytics to 0.2.4

- pg_search/src/postgres/delete.rs
- pg_search/src/postgres/vacuum.rs
> chore: new cleanup lock idea for `ambulkdelete`

- .github/workflows/check-pg_search-schema-upgrade.yml
- Closes #
Fixes CI job that was failing to pull the pgrx version.
> fix: schema upgrade CI job

- .github/workflows/publish-paradedb-docker.yml
- Closes (partial) #1587 
Adds missing attestations to our Docker publishing.
Fix issues in Docker Scout.
Followed the Docker docs.
^
> feat: Add support for SBOM and provenance to Docker

- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- .github/workflows/test-paradedb.yml
- docker/Dockerfile
- Closes #N/A
Add vulnerability checking in the PR process.
Will help with pushing high quality images, recommended by Docker.
This: https://docs.docker.com/scout/integrations/ci/gha/
CI
> ci: Add Docker Scout to our CI

- tests/Cargo.toml
- tests/tests/replication.rs
> feat: physical replication tests

- .github/workflows/publish-paradedb-docker.yml
- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- Closes #N/A
This was pushed to our closed-source repository.
> ci: Upgrade attestation action

- pg_search/src/index/directory/utils.rs
- pg_search/src/postgres/storage/block.rs
We (nor tantivy) actually use the `opstamp` value, so there's no need to store it.  We now fabricate a fake opstamp based on our stored segment's `xmin` and `xmax` values.
This saves 8 bytes for every segment entry and for entries that contain a deletes file, it saves another 8 bytes -- 16 total.
- Closes #
> chore: remove `opstamp` from `SegmentMetaEntry`

- .github/workflows/test-stressgres.yml
Adds our `stressgres` tool to CI.
> chore: add test-stressgres workflow to ci

- .github/workflows/test-pg_search-stressgres.yml
- Closes #N/a
Convert Stressgres to run nightly instead of on every PR.
Eric wanted this.
Cron
Manual
> ci: Run Stressgres nightly in CI

- docker/Dockerfile
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
> chore: Upgrade pg_analytics to 0.3.0

- .github/workflows/publish-paradedb-docker.yml
- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- .github/workflows/test-paradedb.yml
> chore: Clean up Docker build process

- pg_search/src/postgres/storage/linked_bytes.rs
- Closes #
PR #2065 introduced a `BlockList` which is attached to a `LinkedBytesList`.  The `BlockList`'s physical Postgres blocks need to be marked deleted when the LinkedBytesList is.
We chase that linked list of blocks and `.mark_deleted()` them.
An index would grow unbounded.  Rather quickly under load.
> fix: mark the blocklist deleted when deleting a LinkedBytesList

- Cargo.lock
- Cargo.toml
- pg_search/sql/pg_search--0.13.2--0.13.3.sql
- pg_search/src/api/index.rs
- pg_search/src/query/mod.rs
- tests/tests/documentation.rs
- tests/tests/query.rs
> chore: restore regex_phrase and regex anchors fix

- .github/workflows/publish-paradedb-docker.yml
- Closes #
Hotfix to deployment CI
> feat: Prod Promotion -- v0.14.0

- tests/tests/documentation.rs
- Closes #1946 
Eric said it's fine for it to be arbitrary, so here we assert for either.
Reactivate the test
Assert
CI
> chore: Reactivate missing row in quickstart test

- pg_search/src/index/merge_policy.rs
- Closes #2112 
If the last merge had the same XID, it is visible and we can merge again.
> fix: allow multiple merges in same transaction

- Cargo.lock
- Cargo.toml
- docs/changelog/0.14.1.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
- pg_search/sql/pg-search--0.14.0--0.14.1.sql
> chore: upgrade to `0.14.1`

- Cargo.lock
- Cargo.toml
- Closes #
Updates our tantivy dependency git revision to be that of the our current changes.
> chore: update tantivy dependency rev

- docs/documentation/advanced/json/overview.mdx
- pg_search/src/query/mod.rs
- tests/tests/bm25_search.rs
- Closes #
Enables `term_set` queries over JSON.
> fix: allow json for `term_set`

- pg_search/src/index/directory/utils.rs
- pg_search/src/index/reader/segment_component.rs
- pg_search/src/index/writer/segment_component.rs
- pg_search/src/postgres/storage/block.rs
> chore: fix potential typo staring_block -> starting_block

- pg_search/src/index/reader/index.rs
- Closes #
When querying all segments we can elide converting our `SearchInputQuery` into a tantivy `Box<dyn Query>` once for each segment, and instead just do it once.
This also moves the `Box<dyn Weight>` construction into the deferred part of `DeferredScorer`, eliminating the need to construct weights at all for segments we don't end up processing.
Eliminating some search overhead
Existing tests pass
> perf: avoid parsing a query once per segment being queried

- .github/workflows/test-pg_search-upgrade.yml
- docker/Dockerfile
> fix: Fix issues with `pg_search` removed from `shared_preload_libs` where it needs to be

- .github/workflows/benchmark-pg_search.yml
- .github/workflows/test-pg_search-stressgres.yml
- .github/workflows/test-pg_search-upgrade.yml
- .github/workflows/test-pg_search.yml
- Cargo.lock
- Cargo.toml
- docker/Dockerfile
- docs/changelog/0.15.1.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/self-hosted/logical-replication/getting-started.mdx
- docs/deploy/upgrading.mdx
- docs/mint.json
- pg_search/Cargo.toml
- pg_search/README.md
- pg_search/sql/pg_search--0.15.0--0.15.1.sql
- pg_search/src/gucs.rs
- pg_search/src/index/directory/channel.rs
- pg_search/src/index/directory/mvcc.rs
- pg_search/src/index/reader/index.rs
- pg_search/src/index/writer/index.rs
- pg_search/src/lib.rs
- pg_search/src/postgres/customscan/pdbscan/scan_state.rs
- tests/tests/aborted_xact.rs
- tests/tests/bm25_search.rs
- tests/tests/replication.rs
> feat: Prod Promotion -- v0.15.1

- .github/workflows/check-typo.yml
- .github/workflows/publish-paradedb-docker.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/test-paradedb.yml
- Closes #N/A
This was suggested by @itay-grudev and will avoid the value being blurred everywhere in our CI, which makes debugging a lot easier.
^
^
^
> chore: Swap from Secrets to Variables for DOCKERHUB_USERNAME

- .github/workflows/test-pg_search-upgrade.yml
- Closes #N/A
We were missing this, as pointed out by @eeeebbbbrrrr, to make sure the indexes are compatible.
Make sure our extensions upgrade.
Write letters.
Next release's CI!
> ci: Add BM25 index creation and querying to ALTER EXTENSION CI Test

- docs/integrations/formats/parquet.mdx
> docs: New `parquet_describe` and `parquet_schema` function arguments

- docker/Dockerfile
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
> chore: Upgrade pg_analytics to 0.3.3

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.2.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: Prepare v0.15.2

- docker/Dockerfile
- Closes #N/A
Builds on top of #2214 to productionize the Dockerfile a bit more and make it work on arm64 too.
^
^
^
> fix: Upgrade libicu to 76.1

- Cargo.lock
- Cargo.toml
- docker/Dockerfile
- docs/changelog/0.15.3.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.2--0.15.3.sql
> chore: Prepare 0.15.3

- docker/Dockerfile
- Closes #N/A
Fast-follow release for a Docker fix with the ICU tokenizer.
^
^
^
> feat: Prod Promotion -- v0.15.3

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.4.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- pg_search/sql/pg_search--0.15.3--0.15.4.sql
> chore: upgrade 0.15.4

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.4.mdx
- docs/changelog/0.15.5.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.4--0.15.5.sql
> chore: Prepare 0.15.5

- .github/stressgres/single-server.toml
- .github/workflows/test-paradedb.yml
- .github/workflows/test-pg_search-stressgres.yml
- Cargo.lock
- Cargo.toml
- docker/docker-compose.dev.yml
- docs/changelog/0.15.4.mdx
- docs/changelog/0.15.5.mdx
- docs/deploy/ci/github-actions.mdx
- docs/deploy/ci/gitlab-ci.mdx
- docs/deploy/ci/overview.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- docs/welcome/support.mdx
- pg_search/sql/pg_search--0.15.4--0.15.5.sql
> feat: Prod Promotion -- v0.15.5

- .github/workflows/test-pg_search-upgrade.yml
- pg_search/README.md
- Closes #2242 
Updates `pgrx` version to `0.13.0` in docs
> docs: Update `pgrx` version

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.6.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: Prepare 0.15.6

- docker/Dockerfile
- docker/bootstrap.sh
> chore: swap Dockerfile to use `pg_parquet`

- .github/workflows/publish-paradedb-docker.yml
> feat: Prod Promotion -- v0.15.6

- .github/workflows/benchmark-pg_search.yml
- .github/workflows/check-pg_search-schema-upgrade.yml
- .github/workflows/lint-rust.yml
- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- .github/workflows/test-pg_search-stressgres.yml
- .github/workflows/test-pg_search-upgrade.yml
- .github/workflows/test-pg_search.yml
- Closes #N/A
New postgresql scripts require this change.
> ci: Fix PG CI

- docker/Dockerfile
- Closes #N/A
Resets the path to the standard WORKDIR
^
^
^
> chore: Fix docker path

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.7.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.6--0.15.7.sql
> chore: Upgrade to 0.15.7

- .github/workflows/benchmark-pg_search.yml
- .github/workflows/check-pg_search-schema-upgrade.yml
- .github/workflows/lint-rust.yml
- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- .github/workflows/test-pg_search-stressgres.yml
- .github/workflows/test-pg_search-upgrade.yml
- .github/workflows/test-pg_search.yml
> ci: Fix Ubuntu publishing and PostgreSQL CI Download

- .github/workflows/benchmark-pg_search.yml
- .github/workflows/check-pg_search-schema-upgrade.yml
- .github/workflows/lint-rust.yml
- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- .github/workflows/test-pg_search-stressgres.yml
- .github/workflows/test-pg_search-upgrade.yml
- .github/workflows/test-pg_search.yml
> feat: Prod Promotion -- v0.15.7

- docs/documentation/indexing/inspect_index.mdx
> docs: fix typo in `paradedb.is_merging`

- tests/README.md
- Closes #2261 
Update test suite README to include instructions on how to run tests on self hosted postgres. 
Clear instruction on how to run tests.
not required.
> docs: Update test suite `README`

- .github/workflows/benchmark-pg_search.yml
> chore: send benchmarks to dedicated channel

- Cargo.lock
- Cargo.toml
- Closes #
Eric's PR got merged
> chore: Use upstream lindera

- .github/workflows/benchmark-pg_search.yml
- .github/workflows/test-pg_search-stressgres.yml
> chore: Add new webhooks for benchmarks channel

- .github/workflows/benchmark-pg_search.yml
- .github/workflows/test-pg_search-stressgres.yml
- Closes #N/A
The benchmarks channel ID secret was wrong. I fixed it and cleaned a few things.
I also made it use the latest API and separated the uploads, but that is optional.
^
^
^
> chore: Properly upload benchmark results to Slack

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.8.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- docs/documentation/configuration/write.mdx
- pg_search/sql/pg_search--0.15.7--0.15.8.sql
> chore: Prepare 0.15.8

- .github/workflows/check-pg_search-schema-upgrade.yml
> chore: move schemabot's environment to pg14

- .github/stressgres/bulk-updates.toml
- .github/workflows/test-pg_search-stressgres.yml
- Closes #
Not yet ready, just letting CI run!
> chore: new stressgres for bulk updates

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.10.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.9--0.15.10.sql
> chore: Prepare 0.15.10

- .github/workflows/publish-pg_search-macos.yml
- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.10.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- docs/documentation/indexing/fast_fields.mdx
- pg_search/sql/pg_search--0.15.9--0.15.10.sql
- pg_search/src/index/directory/mvcc.rs
- pg_search/src/index/merge_policy.rs
- pg_search/src/postgres/insert.rs
> feat: Prod Promotion -- v0.15.10

- .github/workflows/assign-github-issue.yml
- .github/workflows/check-typo.yml
- .github/workflows/lint-bash.yml
- .github/workflows/lint-docker.yml
- .github/workflows/lint-format.yml
- .github/workflows/lint-markdown.yml
- .github/workflows/lint-pr-title.yml
- .github/workflows/lint-rust.yml
- .github/workflows/lint-yaml.yml
- .github/workflows/publish-github-release.yml
- .github/workflows/test-docs.yml
- .github/workflows/test-paradedb.yml
- Closes #N/A
It's been on Ubicloud. We get it for free on GitHub and I don't want to rely too much on Ubicloud.
^
^
^
> ci: Move small CI back to GitHub

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.11.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: upgrade to `0.15.11`

- docs/style.css
> docs: hide searchbar

- pg_search/src/postgres/storage/block.rs
> fix: the logic from 3b25bf201a49a2db1bbcc9d9fb4116dc2992711b

- .github/stressgres/bulk-updates.toml
- .github/stressgres/single-server.toml
- Closes #
Syntax was changed upstream in stressgres
> chore: Update stressgres `.toml` files

- pg_search/src/postgres/storage/linked_items.rs
- Closes #
We can't allow concurrent backends to try and garbage collect the segment meta entries list concurrently.
This becomes problematic when the list grows over one page and then, after garbage collection, shrinks down by a page.  Concurrently changing the structure of the list like this isn't correct.
Doing so leads to trying to mark that now-leftover page in the list as deleted concurrently, which is not kosher.  Could see errors such as `ERROR: page 79364 is already marked deleted with xid=24844, trying to change to 24819`
> fix: `LinkedItemList::garbage_collect()` should be sync'd

- pg_search/src/postgres/insert.rs
- Closes #
Segment merging could be cancelled due to a user cancel query request, such as `^C` in psql.  In that case we'd prefer to report that rather than raising a generic ERROR saying the merge was cancelled.
Largely this is so the proper SQL error code gets sent to the interrupted client.
Kinda difficult to unit test, but our automated CI stressgres jobs should exercise this because stressgres issues cancel query requests and looks for that specific error code.
> fix: `check_for_interrupts!()` after merging

- .github/workflows/test-paradedb.yml
- Closes #N/A
It was always testing as of `dev`, which meant we never testing with `--tmpfs`. This fixes that.
^
^
CI
> ci: Fix Docker test on PRs to `main`

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.13.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: upgrade to 0.15.13

- pg_search/sql/pg_search--0.15.12--0.15.13.sql
> chore: fix upgrade script again

- .github/ISSUE_TEMPLATE/bug_report.yml
> chore: Ask for explain analyze

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.14.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.13--0.15.14.sql
> chore: Upgrade to `0.15.14`

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/benchmark-pg_search.yml
- .github/workflows/test-pg_search-stressgres.yml
- .github/workflows/test-pg_search.yml
- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.14.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.13--0.15.14.sql
- pg_search/src/index/directory/utils.rs
- pg_search/src/index/reader/index.rs
- pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs
- pg_search/src/postgres/insert.rs
- pg_search/src/postgres/storage/block.rs
- pg_search/src/postgres/storage/linked_items.rs
- pg_search/src/postgres/storage/merge.rs
- tests/tests/custom_scan.rs
> feat: Prod Promotion -- v0.15.14

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.15.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.14--0.15.15.sql
> chore: Upgrade to `0.15.15`

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.16.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.15--0.15.16.sql
> chore: upgrade to `0.15.16`

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.16.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- docs/documentation/guides/hybrid.mdx
- pg_search/sql/pg_search--0.15.15--0.15.16.sql
- pg_search/src/bootstrap/create_bm25.rs
- pg_search/src/index/directory/utils.rs
- pg_search/src/index/merge_policy.rs
- pg_search/src/postgres/delete.rs
- pg_search/src/postgres/insert.rs
- pg_search/src/postgres/storage/buffer.rs
- pg_search/src/postgres/storage/linked_bytes.rs
- pg_search/src/postgres/storage/linked_items.rs
- pg_search/src/postgres/storage/merge.rs
- pg_search/src/postgres/storage/utils.rs
- tests/tests/documentation.rs
> feat: Prod Promotion -- v0.15.16

- pg_search/src/postgres/customscan/pdbscan/pushdown.rs
- pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs
- tests/tests/pushdown.rs
- Closes #2439
This teaches the pushdown code about `pg_sys::RelabelType` nodes (as best as I understand them) so that predicates that use the `text` equality opertoers but the lhs Var is a `varchar` can be pushed down too.
As far as users are concerned, there's not actually any difference between `text` and `varchar` and they expect query predicates that use a `varchar` column to be pushed down too.
Teaching a bit of our pushdown/qual extract code about the `pg_sys::RelabelType`.
The existing `pushdown` test has been updated to include a `varchar` field and now passes.
> fix: issue #2439 -- support pushing down `varchar` predicates

- pg_search/src/postgres/customscan/pdbscan/parallel.rs
- pg_search/src/postgres/mod.rs
- pg_search/src/postgres/parallel.rs
> fix: Add function to cancel query in physical replica if vacuum in progress

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.17.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.16--0.15.17.sql
> chore: upgrade `0.15.17`

- docs/documentation/getting-started/load.mdx
- Closes #N/A
Reported by a user.
^
^
^
> docs: Update `pg_dump` docs to add missing `\`

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.18.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.17--0.15.18.sql
> chore: upgrade `0.15.18`

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.18.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- docs/documentation/full-text/sorting.mdx
- docs/documentation/getting-started/load.mdx
- pg_search/sql/pg_search--0.15.17--0.15.18.sql
- pg_search/src/postgres/customscan/pdbscan/mod.rs
- pg_search/src/postgres/customscan/pdbscan/privdat.rs
- pg_search/src/postgres/customscan/pdbscan/scan_state.rs
- pg_search/src/schema/mod.rs
- tests/tests/search_config.rs
- tests/tests/sorting.rs
- tests/tests/term.rs
> feat: Prod Promotion v0.15.18

- pg_search/src/postgres/customscan/pdbscan/mod.rs
The custom scan planning code has some nesting that can be removed.
It's unnecessary, and forces formatting to do extra acrobatics.
Early return if we don't have quals: no other changes.
n/a
> chore: Reduce nesting in custom scan planning.

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.19.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.18--0.15.19.sql
- Closes #N/A
This will be used to test our first `beta` release.
^
^
^
> chore: Prep 0.15.19

- .github/workflows/check-pg_search-schema-upgrade.yml
- .github/workflows/publish-github-release.yml
- .github/workflows/publish-paradedb-docker.yml
- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-pgxn.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- .github/workflows/test-docs.yml
- .github/workflows/test-pg_search-benchmark.yml
- .github/workflows/test-pg_search-docker.yml
- .github/workflows/test-pg_search-stressgres.yml
- .github/workflows/test-pg_search-upgrade.yml
- .github/workflows/test-pg_search.yml
- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.19.mdx
- docs/deploy/ci/github-actions.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.18--0.15.19.sql
- pg_search/src/postgres/customscan/pdbscan/mod.rs
- tests/tests/sorting.rs
> chore: Staging Promotion -- v0.15.19-rc.1

- .github/workflows/publish-pg_search-rhel.yml
- Closes #1479
Add the `--features icu` to the RHEL packages. It was the only platform for which it was missing.
User requests / tech debt
Compile ICU 76.1 from source and properly link it.
See CI: https://github.com/paradedb/paradedb/actions/runs/14697643171/job/41241608324?pr=2482
> feat: Add Rhel ICU

- .github/workflows/test-pg_search-benchmark.yml
- .github/workflows/test-pg_search-stressgres.yml
> ci: Fix Stressgres CI

- .github/workflows/test-pg_search-benchmark.yml
- .github/workflows/test-pg_search-stressgres.yml
- .github/workflows/test-pg_search.yml
- Closes #N/A
Something I had forgotten from introducing the `staging` branch.
^
^
^
> ci: Also group PRs to staging

- .github/workflows/test-pg_search-docker.yml
> ci: Add missing check for staging

- .github/workflows/publish-github-release.yml
- Closes #N/A
Eric flagged this out, thank you Eric!
^
^
^
> ci: Mark `staging` deployments as prereleases

- .github/workflows/test-pg_search.yml
- Cargo.lock
- tests/Cargo.toml
- tests/tests/fixtures/mod.rs
- tests/tests/fixtures/querygen/joingen.rs
- tests/tests/fixtures/querygen/mod.rs
- tests/tests/fixtures/querygen/wheregen.rs
- tests/tests/qgen.rs
- Closes #
Adds two new `#[rstests]` that generate random SQL queries and compares their results between "postgres" and "pg_search".
The new `generated_single_relation_queries` test generates 10k queries with various where clauses and compares the number of results between "postgres" (using the `=` operator) and "pg_search" (using pg_search's pushdown abilities).  
This test did surface one bug, but it was fixed by #2524, so it runs successfully now.  
The fact it did surface at least one bug makes me think it's still a good test to run.  The new `WhereGenerator` will actually generate where clauses forever, and I locally let it generate/execute a million queries without failures, once #2524 was fixed.
The other new test `generated_join_queries` generates "JOIN" queries (using INNER, …
> feat: tests that generate random queries

- docs/changelog/0.15.19.mdx
> docs: Add to `0.15.19` changelog

- .github/workflows/test-pg_search-upgrade.yml
> fix: bump `cargo-pgrx` in upgrade CI

- .github/workflows/test-pg_search.yml
- Closes #
If `cargo pgrx regress` fails, make CI fail
> chore: make regression tests fail CI

- pg_search/src/postgres/options.rs
- pg_search/tests/pg_regress/expected/index_config_errors.out
- pg_search/tests/pg_regress/sql/index_config_errors.sql
- Closes #
Got a buggy error while trying to create an index
> fix: minor formatting change on index creation 

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.20.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: Upgrade to `0.15.20`

- tests/tests/parallel_index_scan.rs
- Closes #
This test is flakey in CI, disable until fixed.
> fix: disable flakey test

- pg_search/sql/pg_search--0.15.19--0.15.20.sql
- Closes #
Upgrade script from `0.15.19` to `0.15.20`
> chore: upgrade script for `0.15.20`

- docs/documentation/indexing/tokenizers.mdx
- Closes #2506
Documentation for jieba tokeniser per https://github.com/paradedb/paradedb/issues/2490
We need to document the feature before it can be put in the release.
Just a little documentation nada más.
n/a
> docs: Add documentation for tantivy tokenizer

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- pg_search/README.md
- Closes #N/A
New rule, I guess.
^
^
^
> chore: Fix Markdownlint

- docs/deploy/enterprise.mdx
> docs: update enterprise comparison page

- docs/documentation/indexing/create_index.mdx
- Closes #N/A
I had two different users confused about how to configure the CREATE INDEX. This small change should make it easier.
^
^
^
> docs: Point users to the Field Configuration section

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.21.mdx
- docs/deploy/self-hosted/extensions.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: Upgrade to `0.15.21`

- Cargo.lock
- pg_search/Cargo.toml
- pg_search/src/api/aggregate.rs
- pg_search/src/parallel_worker/mod.rs
- tests/tests/aggregate.rs
> feat: Prod Promotion -- v0.15.21

- docs/deploy/enterprise.mdx
> docs: Fix incorrect footer in /enterprise

- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.24.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.23--0.15.24.sql
> feat: Release 0.15.24

- .github/workflows/publish-github-release.yml
- Cargo.lock
- Cargo.toml
- docs/changelog/0.15.25.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.15.24--0.15.25.sql
> feat: Release v0.15.25

- docs/docs.json
- docs/style.css
- Closes #
Mintlify now has different themes...and I like the willow one.
Had to add some custom CSS to fix a small issue w it.
> docs: use willow theme

- pg_search/src/api/aggregate.rs
If the leader is participating we should request 1 less parallel worker.
Also adds some debug statements about the number of workers requested and timings for each worker.
This could have led to having 1 more worker than there are segments, which would create an unbalanced amount of work in each worker, causing performance to be much worse.
Existing tests pass.  It's a little difficult to somehow assert, via a test, that only a specific number of workers were started.
> fix: `paradedb.aggregate()` should account for `parallel_leader_participation`

- pg_search/src/postgres/storage/utils.rs
- Closes #
#2708 got automerged before I addressed everything
> chore: address comments on `BufferMutVec`

- Cargo.lock
- Cargo.toml
- pg_search/src/query/score.rs
updates to the tip of our tantivy fork as of today.
> chore: update to latest tantivy rev

- Cargo.lock
- Cargo.toml
- docs/changelog/0.16.1.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
> chore: Upgrade to `0.16.1`

- pg_search/src/index/reader/index.rs
This reverts commit 23a697611af94765fd1f3fce1d179345753fdc1c.
The benchmark suite (and a local bisect) indicated that that commit (from #2742) roughly doubled the time for TopN.
That was because the `TopN` exec method lazily produces segments by checking them out one at a time. The effect of eagerly contructing a set of segments to search with was that all of the segments were very likely to be checked out by one worker.
Revert 23a697611af94765fd1f3fce1d179345753fdc1c
See #2758 for followup around re-fixing this!
> fix: Revert "optimize `SearchIndexReader::collect_segments()`"

- pg_search/src/postgres/storage/utils.rs
Fix compilation warnings for unused code in pg14 & pg15.
> chore: fix compilation warnings on pg14/15

- Cargo.lock
- Cargo.toml
- docs/changelog/0.16.3.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.16.2--0.16.3.sql
> chore: Upgrade to `0.16.3`

- .github/workflows/publish-pg_search-rhel.yml
- Closes #2722
Running a test and then this should be ready. This removes ICU from our RHEL tests and explains why in code.
Broke for users
Remove ICU code
Tested in: https://github.com/paradedb/paradedb/pull/2786/commits/3bba9cf763efe9936c15be4ab0db678b4b83aa06
> ci: Remove hardcoded ICU on RHEL

- benchmarks/src/main.rs
Our benchmark runner uses `psql` and is sensitive to its output.  This teaches the runner to ignore any local `.psqlrc` file.
Basically so @eeeebbbbrrrr can run the benchmarks locally.
I ran it and it works.
> chore: make benchmarks tolerant of rogue .psqlrc files

- .github/workflows/benchmark-backfill.yml
- .github/workflows/test-pg_search-benchmark.yml
- .github/workflows/test-pg_search-stressgres.yml
- .github/workflows/test-pg_search.yml
- Closes #2797 
Ported #2797 over here and have started a new "backfill" workflow.  Merging this without approval so I can start testing that.
> ci: Switch to Depot runners for benchmarks/stressgres

- .github/workflows/benchmark-pg_search-benchmarks.yml
- .github/workflows/benchmark-pg_search-stressgres.yml
I'm in a hurry and shouldn't be.
> ci: fix typeo

- pg_search/sql/pg_search--0.16.4--0.17.0.sql
- Closes #
From #2743 , forgot to add an upgrade script.
> chore: missing UDFs in `0.17.0` upgrade script

- Cargo.lock
- Cargo.toml
- docs/changelog/0.16.4.mdx
- docs/changelog/0.17.0.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: Upgrade to `0.17.0`

- CONTRIBUTING.md
- Closes #N/A
We don't accept those to keep our docs cohesive.
^
^
^
> docs: Explain we won't take docs PRs

- docs/changelog/0.17.0.mdx
- docs/documentation/full-text/scoring.mdx
- docs/documentation/full-text/sorting.mdx
- Closes #
- Add changelog about heap filter pushdown
- Adjust docs around scoring/sorting accordingly
> chore: add docs + changelog about heap pushdown

- .github/workflows/benchmark-backfill-auto.yml
- .github/workflows/benchmark-backfill.yml
- .github/workflows/publish-github-release.yml
- Closes #N/A
Provide an example of the version number when manually triggering a release.
^
^
^
> ci: Clarify release version format

- Cargo.lock
- Cargo.toml
- docs/changelog/0.17.2.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.17.1--0.17.2.sql
> chore: upgrade to `0.17.2`

- docs/documentation/full-text/filtering.mdx
- Closes #
I realized our docs about filtering are very out of date.
> docs: Correct docs about filtering

- Cargo.lock
- Cargo.toml
- docs/changelog/0.16.5.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.16.4--0.16.5.sql
> chore: Upgrade to `0.16.5`

- pg_search/src/postgres/storage/buffer.rs
- pg_search/src/postgres/storage/fsm.rs
- pg_search/src/postgres/storage/utils.rs
Reduce general overhead in the FSM between extending it and popping off one or more blocks.  In doing so, fix a bug where the header's `empty` flag was not being set as eagerly as it could have been.
Additionally, teach our lower-level new block code to use `RBM_ZERO_AND_LOCK` for when opening buffers returned from the FSM. This potentially avoids disk I/O if the buffer isn't in Postgres' buffer cache and also elides a rountrip over FFI to lock the buffer since ReadBufferExtended is doing it for us with this flag set.
Also cleans up lifetime annotations a bit so it's not possible to have multiple mutable borrows from a BufferMut, even when those borrows happen through Page/PageMut.
Pulling up the changes from PR #2989 and #2988.
> perf: improve FSM extend and pop/pop_many performance (cherry pick from 0.18.x)

- pg_search/src/postgres/storage/buffer.rs
- pg_search/src/postgres/storage/fsm.rs
- pg_search/src/postgres/storage/utils.rs
Reduce general overhead in the FSM between extending it and popping off one or more blocks.  In doing so, fix a bug where the header's `empty` flag was not being set as eagerly as it could have been.
Additionally, teach our lower-level new block code to use `RBM_ZERO_AND_LOCK` for when opening buffers returned from the FSM. This potentially avoids disk I/O if the buffer isn't in Postgres' buffer cache and also elides a rountrip over FFI to lock the buffer since ReadBufferExtended is doing it for us with this flag set.
Also cleans up lifetime annotations a bit so it's not possible to have multiple mutable borrows from a BufferMut, even when those borrows happen through Page/PageMut.
For the same reasons as PR #2988
> perf: improve FSM extend and pop/pop_many performance

- pg_search/src/index/writer/segment_component.rs
- pg_search/src/postgres/merge.rs
> chore: cherry pick #2955

- Cargo.lock
- Cargo.toml
- docs/changelog/0.17.6.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.17.5--0.17.6.sql
> chore: Upgrade to `0.17.6`

- Cargo.lock
- Cargo.toml
- docs/changelog/0.17.7.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.17.6--0.17.7.sql
> chore: Upgrade to `0.17.7`

- .github/workflows/cherry-pick.yml
- .gitignore
- Closes #N/A
Failed here: https://github.com/paradedb/paradedb/actions/runs/17160633122/job/48688734790 due to incorrect token usage
> fix: Fix token usage in cherry-pick action

- .github/workflows/test-pg_search-docker.yml
- docker/Dockerfile
- docker/docker-compose.dev.yml
Cherry-pick of: https://github.com/paradedb/paradedb/pull/2954 into `0.17.x.
> fix: Fix the permissions in the ParadeDB Docker image #2954

- pg_search/src/postgres/merge.rs
The `From<&PgSearchRelation> for IndexLayerSizes` `from()` ctor was improperly calculating both the total `index_byte_size` and the `target_segment_byte_size`.
For the former, it needs to only consider SegmentMetaEntries that are actually visible.  In almost every case, at least after a CREATE INDEX of a large index, the index could actually have 2x+ total segments as there are actually visible segments.
Secondly, we need to adjust the `target_segment_byte_size` down by 1/3 to account for how `LayeredMergePolicy` does the same thing.  Failure to do this can cause the background worker to merge segments together that don't actually need to be.
These two miscalculations are what contributed to the recent query benchmark regressions we saw after #3031 was merged.
> fix: make IndexLayerSizes calculations more accurate

- .github/actions/benchmark-stressgres/action.yml
- .github/actions/push-file/action.yml
- .github/workflows/benchmark-pg_search-stressgres.yml
- Closes #N/A
Required as we add our `paradedb[bot]` user.
^
^
^
> ci: Swap to token instead of SSH for pushing to `benchmark-data`

- pg_search/src/postgres/storage/fsm.rs
Fixes a bug where pages weren't properly being marked as empty.
Also optimizes the `pop()/drain()` codepaths so that they're not holding a lock as long.
> fix: cleanup fsm overhead and fix `content.header.empty` bug

- pg_search/src/postgres/storage/buffer.rs
- pg_search/src/postgres/storage/fsm.rs
> perf: reduce FSM locking overhead

- pg_search/src/postgres/storage/fsm.rs
> chore: port fsm fixes from main

- .github/workflows/benchmark-pg_search-stressgres.yml
- .github/workflows/check-pg_search-schema-upgrade.yml
- .github/workflows/cherry-pick.yml
- .github/workflows/publish-github-release.yml
- .github/workflows/publish-paradedb-docker.yml
- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- .github/workflows/test-pg_search-docker.yml
- Closes #N/A
Stop impersonating me. Commit activity boutta drop hard.
These are bot-generated actions and should be labelled as such.
Created a `paradedb[bot]` GitHub user.
We need to test that it works. It's possible it doesn't have all permissions just yet.
> ci: Swap to the ParadeDB Bot for CI automation

- .github/workflows/benchmark-pg_search-benchmarks.yml
- .github/workflows/benchmark-pg_search-stressgres.yml
- Closes #N/A
Very silly. Very annoying. Fixes this: https://github.com/paradedb/paradedb/actions/runs/17322379027/job/49178365258
^
^
^
> ci: Fix Slack notifications on failed jobs

- pg_search/src/postgres/merge.rs
This removes the (sneaky) addition of an "average layer size" based on the configured `target_segment_count` into the list of `background_layer_sizes`.
The reason we're removing this is that when this happens on an existing, large, unbalanced index, it will cause essentially the entire index to be merged in the background, and that's almost never what one would want in a production setting.
Looking to improve operational problems.
> fix: don't include target_segment_count in background_layer_sizes

- pg_search/src/postgres/customscan/pdbscan/solve_expr.rs
- pg_search/tests/pg_regress/expected/custom_scan_with_subquery.out
- pg_search/tests/pg_regress/sql/custom_scan_with_subquery.sql
- Closes #
- Makes warning when a subselect is null less noisy
- Adds a regression test
> chore: clean up + test null subselects

- Cargo.lock
- Cargo.toml
- docs/changelog/0.17.10.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.17.9--0.17.10.sql
> chore: Upgrade to `0.17.10`

- pg_search/src/postgres/mod.rs
> chore: add more metadata to explain output

- .github/workflows/benchmark-pg_search-stressgres.yml
- .github/workflows/publish-github-release.yml
- .github/workflows/publish-paradedb-docker.yml
- .github/workflows/publish-pg_search-debian.yml
- .github/workflows/publish-pg_search-macos.yml
- .github/workflows/publish-pg_search-rhel.yml
- .github/workflows/publish-pg_search-ubuntu.yml
- .github/workflows/test-pg_search-docker.yml
- Closes #N/A
Cherry-pick https://github.com/paradedb/paradedb/pull/3069 to fix failed Stressgres runs.
^
^
^
> chore: Cherry-pick move to paradedb-bot onto 0.17.x

- Cargo.lock
- Cargo.toml
- docs/changelog/0.18.1.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: Upgrade to `0.18.1`

- Cargo.lock
- Cargo.toml
- docs/changelog/0.18.1.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: cherry pick upgrade to `0.18.1` (#3127)

- .github/workflows/benchmark-pg_search-stressgres.yml
- Closes #N/A
This was missing in one of the cherry-picks, leading to: https://github.com/paradedb/paradedb/actions/runs/17627418256/job/50182835310
^
^
^
> ci: Cherry-pick new paradedb[bot] into 0.18.x

- pg_search/src/api/mod.rs
- pg_search/src/api/operator.rs
- pg_search/src/gucs.rs
- pg_search/src/postgres/customscan/aggregatescan/mod.rs
- pg_search/src/postgres/customscan/aggregatescan/privdat.rs
- pg_search/src/postgres/customscan/aggregatescan/scan_state.rs
- pg_search/src/postgres/customscan/pdbscan/mod.rs
- pg_search/src/postgres/customscan/range_table.rs
- pg_search/src/postgres/var.rs
- pg_search/tests/pg_regress/expected/empty_aggregate.out
- pg_search/tests/pg_regress/expected/groupby_aggregate.out
- pg_search/tests/pg_regress/expected/groupby_aggregate_highcard.out
- pg_search/tests/pg_regress/expected/issue_3050.out
- pg_search/tests/pg_regress/expected/json_groupby_aggregate.out
- pg_search/tests/pg_regress/expected/json_groupby_orderby_limit.out
- pg_search/tests/pg_regress/expected/or_exists_join_bug.out
- pg_search/tests/pg_regress/expected/view-support.out
- pg_search/tests/pg_regress/sql/groupby_aggregate.sql
- pg_search/tests/pg_regress/sql/groupby_aggregate_highcard.sql
- pg_search/tests/pg_regress/sql/issue_3050.sql
- pg_search/tests/pg_regress/sql/json_groupby_orderby_limit.sql
- pg_search/tests/pg_regress/sql/or_exists_join_bug.sql
- pg_search/tests/pg_regress/sql/view-support.sql
- tests/tests/index_config.rs
- tests/tests/sqlsmith.rs
> chore: Sync `0.18.x`

- pg_search/src/api/operator.rs
- pg_search/tests/pg_regress/expected/issue_3051.out
- pg_search/tests/pg_regress/sql/issue_3051.sql
- Closes #3151 
The `@@@` return type should be `bool`, not `SearchQueryInput`.
Added regression test.
> fix: sequential scan segfault

- pg_search/src/index/directory/mvcc.rs
Invert our use of `OnceLock` to ensure that we clone an `Arc<OnceLock<T>>` rather than a `OnceLock<Arc<T>>`.
`OnceLock` implements `Clone` by cloning its contents to create a separate disconnected copy. If what is desired is "exactly once behavior", then cloning the `OnceLock` before it has been computed the first time will defeat that.
This change has no impact on benchmarks in this case, but `Arc<OnceLock<T>>` matches the intent of this code, and sets a better example for future us.
> fix: Clone an Arc rather than a OnceLock.

- Cargo.lock
- Cargo.toml
- docs/changelog/0.18.9.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
- pg_search/sql/pg_search--0.18.8--0.18.9.sql
> chore: Upgrade to `0.18.9`

- .github/stressgres/wide-table.toml
#3228 added top-n, but while creating the branch, I failed to include some changes that were necessary in order for it to actually match anything.
> chore: Fix wide-table top-n.

- Cargo.lock
- Cargo.toml
- docs/changelog/0.18.10.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: Upgrade to `0.18.10`

- Cargo.lock
- Cargo.toml
- docs/changelog/0.18.11.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/upgrading.mdx
- docs/docs.json
> chore: Upgrade to `0.18.11`

- README.md
Tests github actions workflow for enterprise. 
- Closes #
> chore: no-op change, test workflow

- docs/deploy/overview.mdx
- docs/deploy/self-hosted/docker.mdx
- docs/deploy/self-hosted/extension.mdx
- docs/deploy/self-hosted/kubernetes.mdx
> docs: Caution that ParadeDB Community should not be run in production

- .github/CODEOWNERS
- Closes #N/A
don't block on Stu for docs reviews.
^
^
^
> chore: Update CODEOWNERS for docs directory ownership

- docs/documentation/advanced/term/regex.mdx
- docs/v2/query-builder/term/regex.mdx
> docs: Add regex flag link and call out some common flags

- docs/v2/aggregates/overview.mdx
- docs/v2/full-text/boost.mdx
- docs/v2/full-text/fuzzy.mdx
- docs/v2/full-text/highlight.mdx
- docs/v2/full-text/match.mdx
- docs/v2/full-text/overview.mdx
- docs/v2/full-text/phrase.mdx
- docs/v2/full-text/proximity.mdx
- docs/v2/full-text/score.mdx
- docs/v2/full-text/term.mdx
- docs/v2/getting-started/install.mdx
- docs/v2/getting-started/load.mdx
- docs/v2/getting-started/quickstart.mdx
- docs/v2/indexing/create_index.mdx
- docs/v2/overview.mdx
- docs/v2/query-builder/json.mdx
- docs/v2/query-builder/match.mdx
- docs/v2/query-builder/overview.mdx
- docs/v2/query-builder/phrase/phrase.mdx
- docs/v2/query-builder/phrase/phrase_prefix.mdx
- docs/v2/query-builder/phrase/regex_phrase.mdx
- docs/v2/query-builder/term/exists.mdx
- docs/v2/query-builder/term/fuzzy_term.mdx
- docs/v2/query-builder/term/range.mdx
- docs/v2/query-builder/term/range_term.mdx
- docs/v2/query-builder/term/regex.mdx
- docs/v2/query-builder/term/term.mdx
- docs/v2/query-builder/term/term_set.mdx
- docs/v2/welcome/architecture.mdx
- Closes #N/A
I've only done a handful of files. If someone else feels so inclined here, feel free to push to my branch. Otherwise I'll get to it this week.
Improve our SEO
Follow best practices
N/A
> docs: [SEO] Properly set noindex to V2

- .github/workflows/test-pg_search-upgrade.yml
- Closes #N/A
Fixes: https://github.com/paradedb/paradedb-enterprise/actions/runs/18278710531/job/52036626860
It failed!
Properly account for running on push events.
See: https://github.com/paradedb/paradedb/actions/runs/18286933486/job/52064330130?pr=3277
> ci: Fix issue with alter extension test not working on push events

- .github/CODEOWNERS
> chore: added stu to scripts and .github codeowners
