paradedb/paradedb

README.md, docs/mint.json
- Closes #
**What**
Update links to new getretake GH org
**Why**
We changed our github org from retake-earth to get-retake
**How**
**Tests**
=> fix: Update links to new getretake GH org

.github/workflows/run-tests.yml
This PR adds CUDA installation to the Linux GHA runners executing our tests, so that the sentence transformers can pass tests without complaining about missing CUDA modules, even though they're not using them
=> feat: Add CUDA to GHA Runners

.github/workflows/publish-to-pypi.yml
Deploy didn't run on `dev` because our CI assumed the branch was called `prod` while it is called `main` -- this fixes it.
=> ci: Match prod branch name properly to trigger deploys

docs/concepts/pipeline.mdx
- Closes #
**What**
- The `verbose` parameter in one of the pages was copy pasted twice
**Why**
**How**
**Tests**
=> fix: Section in docs was copy pasted twice

core/load/opensearch.py
N/A
**What**
The previous implementation of the OpenSearch Connector was indexing documents, but not properly upserting as the function name indicates. This change adds the intended behavior so the document is updated if exists, or created if it doesn't exist.
**Why**
That is the intended behavior of the `bulk_upsert_embeddings` function.
**How**
Using the `doc_as_upsert` option on the request, and setting the operation type to `update`.
**Tests**
=> fix: upsert in opensearch connector

LICENSE
History has had some sad precedents... So here goes. This license remains a permissive OSS license, but prevents third-parties from re-selling our software.
Based on: https://igorkotua.com/strong-oss-licenses/ and https://github.com/elastic/elasticsearch/blob/main/licenses/ELASTIC-LICENSE-2.0.txt
If you are interested in licensing Retake under a different license (for instance, SSPL), please contact me at phil@getretake.com.
=> feat: Update LICENSE to ELv2

.github/workflows/publish-to-pypi.yml, poetry.lock, pyproject.toml
The way `psycopg` was installed in `pyproject.toml` was breaking the PyPi deploy, for some reason. I fixed it by reinstalling it properly.
=> fix: Fix PyPi deploy

.github/workflows/helpers/check-shellcheck.py, pyproject.toml
- Closes #
**What**
- There was a dependency conflict with Supabase
- Bumped Python req down to 3.8 and added transitory `go-true` and `httpx` dependencies
**Why**
**How**
**Tests**
=> fix: Dependency conflict with `supabase-py`

docs/concepts/sink.mdx
- Closes #
**What**
- Fixed small typo in documentation
**Why**
**How**
**Tests**
=> fix: Typo where weaviate_url was used as a dummy url in the Qdrant sink

api/routers/index.py, clients/python/retakesearch/index.py, docs/quickstart.mdx
- Closes #97 
**What**
- Enables users to upsert custom documents to an index
**Why**
- if users have data that lives outside their Postgres table
**How**
Added an `upsert` function to the `Index` class:
```
index.upsert(
documents=[{"key", "value"}]
ids=["id"]
)
```
**Tests**
=> feat: Allow users to upsert custom documents to an index

Dockerfile, docker-compose.yml
Our Dockerfile was missing the `uvicorn` command to run, when pulled from Docker Hub. This adds it while structuring things so that the reloading capability can still be active when developing.
=> feat: Fix the Dockerfile published to Docker Hub while keeping hot-reload working in `dev`

api/routers/index.py, core/extract/postgres.py
- Closes #89 
**What**
- Checks that the relation name, columns, and primary key are valid at the top of `realtime/link`
**Why**
- Before, logic would execute even if the user typed invalid table/column names and the user would get an unexpected error
**How**
**Tests**
=> feat: Check that relation, columns, and primary key are valid

api/routers/index.py, clients/python/retakesearch/index.py, core/search/index.py, core/search/index_mappings.py
- Closes #113 
**What**
- Introduces `Index.create_field` which allows users to set field names and types
**Why**
- Useful for cases where dynamic field mapping leads to incorrect results
**How**
- Introduced a `FieldType` enum
- Created a new API endpoint
**Tests**
- Tested manually with Python client
=> feat: Allow user to define index field types

core/search/index.py
- Closes #
**What**
- There was a bug where searching an empty index would throw an error
**Why**
**How**
**Tests**
=> fix: Don't throw error if an empty index is searched

.github/workflows/publish-to-dockerhub.yml
Seems like the GitHub Action uses absolute paths
=> fix: Fix docker deploy

.github/workflows/publish-opensearch-to-pypi.yml, .github/workflows/publish-retake-to-dockerhub.yml, .github/workflows/publish-retake-to-pypi.yml, .gitmodules
All in the title -- this will only deploy on `main`. By the way, OpenSearch follows a different versioning and deployment scheme to us, and I've kept it unchanged in the interest of making keeping up with upstream easier. This means deploys for `opensearch-py` need to manually increment the `_version.py` file, which should come as part of the last PR touching this code before a promotion.
=> ci: Integrate OpenSearch as submodules + deploy `opensearch-py` to PyPi

.flake8, api/routers/index.py
- Closes #
**What**
- Currently the user gets a pretty confusing error if they try to do a neural/semantic search over a non-vectorized field
**Why**
**How**
**Tests**
=> fix: Show better error in search() if field is not vectorized

clients/python/retakesearch/index.py, clients/typescript/src/lib/index.ts, docs/python/table.mdx, docs/quickstart.mdx, docs/typescript/table.mdx
- Closes #161 
**What**
- Creates a `schema` argument that defaults to `public` for `Table`
**Why**
**How**
**Tests**
=> fix: Allow users to specify `schema` in `Table`

docs/python/table.mdx
- Closes #
**What**
**Why**
**How**
**Tests**
=> fix: Typo in Python client docs

docs/python/table.mdx
- Closes #
**What**
**Why**
**How**
**Tests**
=> fix: Typo in Python client docs (#174)

.github/workflows/publish-retake-to-npm.yml, clients/typescript/package.json, examples/nextjs/package-lock.json
My deploy to NPM uses the new workflow with the `tag` approach which I want to move PyPi to eventually, and I had forgotten to make it increment with the new tag version. This should do it.
=> ci: Upgrade version to new tag version for npm

docs/mint.json, docs/search/boosting.mdx, docs/search/highlighting.mdx, docs/search/object.mdx, docs/search/overview.mdx
- Closes #181 
**What**
Adds more important sections to the How to Search documentation:
- Field Types
- Highlighting
- Object Queries
- Boosting
**Why**
**How**
**Tests**
=> feat: Add more sections to How to Search documentation

.github/workflows/publish-retake-to-dockerhub.yml, .github/workflows/test-retake.yml
We weren't auth-ed when running `pytest` in CI, which is why we were getting rate limits
=> ci: Auth to docker to avoid rate limits

api/config/opensearch.py, api/config/pgsync.py, deploy.sh, docker-compose.dev.yml, docker-compose.yml, sync/sidecar.py
- Possibly Closes #108 
**What**
Modify the current docker compose deploy to use SSL termination using a reverse proxy.
**Why**
The current setup is insecure, it exposes ports to HTTP traffic. This PR proposes closing all traffic to the docker containers and allowing access only through the reverse proxy server, which is secured with SSL. Internal communication will be kept as HTTP since the network is not exposed. This might change at a later time if we decide we want to add additional security.
**How**
The approach consists of:
1. A deploy script which writes the configuration file for Caddy using the provided domain.
2. Caddy server, which automatically redirects all HTTPS requests to the Retake API server.
**Tests**
=> feat: add SSL for docker compose deploy

api/app.py, deploy.sh, docker-compose.yml, poetry.lock, pyproject.toml
Right now, we have no way of knowing whether people are deploying and running Retake on their own environments. This PR adds basic telemetry and improves the deploy script so that we can know whether users are running Retake.
=> feat: Add non-intrusive, opt-out telemetry via PostHog

deploy.sh, docker-compose.dev.yml, docker-compose.yml
This PR adds a write-only PostHog key so that when users deploy our Dockerfile, we get telemetry on usage. This is optional, and can be disabled in the deploy script or by removing the key.
Note that right now, the only telemetry we have is whether a user has ran our docker-compose.yml file. We could add more telemetry for when they run search queries.
=> feat: Add PostHog key

clients/typescript/package.json, clients/typescript/src/index.ts, examples/nextjs/package-lock.json
- Closes #
**What**
- We were importing React components and requiring a react peer dependency in the TS library, which was breaking for clients in non-React environments
**Why**
**How**
**Tests**
=> fix: Don't bundle React into Node library (HOTFIX)

.github/workflows/publish-retake-to-npm.yml
There was a small issue in our CI where we published a non-built version to NPM
=> ci: Build before publish

docker/docker-compose.base.yml, docker/docker-compose.dev.yml, docker/docker-compose.prod.yml, docker/docker-compose.yml, tests/docker-compose.yml
- Closes #110
**What**
Introduces a dedicated ml node for running models and adds recommended settings pulled from the official opensearch docker compose file.
**Why**
Because running models has different requirements and shouldn't be done on a data node.
**How**
- Add the `ml-node` to the main docker compose file
- Add recommended settings to the core service
**Tests**
None, run docker compose directly and confirm cluster starts successfully.
=> feat: add dedicated ml node, use recommended settings for core

.github/workflows/publish-retake-to-dockerhub.yml, api/app.py, docker/search.Dockerfile, tests/test_client.py
Closes #237 
I had a minute. This will add the commit hash to our Telemetry events from PostHog, which helps debug issues that users might face
Tested here:
=> feat: Add commit hash to Dockerfile for telemetry

docs/deployment/cloud.mdx
**What**
Add more prerequisites to the cloud deploy guide.
**Why**
Because OpenSearch and Caddy have some prerequisites that were not mentioned in the guide.
=> docs: add prerequisites to cloud deploy guide

pg_bm25/test/expected/bm25_search.out, pg_bm25/test/fixtures.sql, pg_bm25/test/runtests.sh, pg_bm25/test/sql/bm25_search.sql, pg_search/configure.sh, pg_search/test/expected/search.out, pg_search/test/runtests.sh, pg_search/test/sql/search.sql
- Closes #269 
Enable tests for PG_VERSIONS including 11(.21)
These were previously disabled due to an inconsistency in how Postgres 11 vs 12+ display floating point numbers. 
We updated the testing query to make behavior consistent across Postgres versions, and updated the test file to match.
Self-explanatory.
=> test: Enable tests for PG_VERSIONS including 11

docs/mint.json
- Closes (partial) #283
This makes it so visitors of our documentation can see an "edit" button on our docs, which will lead them to our docs page to suggest contributions and help keep documentation up-to-date. This is a very standard thing in the documentation world.
^
The founder of Mintlify kindly told us the setting to add :)
=> docs: Add "Edit in GitHub" Button to our docs

docs/search/bm25.mdx, pg_bm25/README.md, pg_bm25/src/index_access/scan.rs, pg_bm25/src/index_access/utils.rs, pg_bm25/test/expected/search_config.out, pg_bm25/test/sql/search_config.sql
- Closes #263 
- Implements fuzzy search/typo tolerance
- User can specify which fields are typo tolerant:
```sql
SELECT * 
FROM mock_items 
WHERE mock_items @@@ 'description:keyboardd OR category:electornics:::fuzzy_fields=description,category';
```
- Updated documentation
- Typo tolerance is important
Used the new `:::` syntax to enable users to pass in a comma-separated list of fields that they would like to be typo-tolerant/fuzzy. Inside `amrescan` we set the specified fields to fuzzy using `QueryParser::set_field_fuzzy`. We default the max Levenshtein distance to `2` (maximum allowed by Tantivy).
Wrote additional regression tests for fuzzy search
=> feat: Introduce fuzzy search/typo tolerance

pg_bm25/Cargo.lock, pg_bm25/Cargo.toml, pg_bm25/src/index_access/scan.rs, pg_bm25/src/index_access/utils.rs
I wanted to make a quick improvement to the `SearchConfig` from earlier today, inspired by @rebasedming's syntax for fuzzy search:
```
:::fuzzy_fields=category,description,notes
```
This PR uses Rust's CSV parsing tools to give our `SearchConfig` more of a "first-class" way to parse lists. We have to use an additional attribute for lists fields, but now we can parse them using `serde`, just like the rest of the config:
```rust
#[derive(Debug, Deserialize, Default)]
pub struct SearchQueryConfig {
pub offset: Option<usize>,
pub limit: Option<usize>,
#[serde(default, deserialize_with = "from_csv")]
pub fuzzy_fields: Vec<String>,
}
```
The macro just points `serde` to the custom parser that I've defined at the bottom of the `utils.rs` file. In this function, I delegate all parsing of the …
=> refactor: Add additional parsing for lists in SearchConfig

docs/quickstart.mdx, docs/search/hybrid.mdx, pg_bm25/src/api/mod.rs, pg_bm25/src/index_access/scan.rs, pg_bm25/src/manager/mod.rs, pg_search/README.md, pg_search/src/api.rs, pg_search/test/expected/search.out, pg_search/test/sql/search.sql
- Closes #291 
The existing hybrid search query was broken because BM25 considers higher scores to be better, whereas L2 distance between vectors considers lower scores to be better.
To fix this, I switched our normalization method to minmax normalization, which collapses scores to a range between 0 and 1. This allowed me to invert the L2 distance scores by subtracting them from 1.
In the process I also managed to simplify the hybrid search query and remove the CTE. Here is what it now looks like:
```sql
SELECT
description,
category,
rating,
paradedb.weighted_mean(
paradedb.minmax_bm25(ctid, 'idx_mock_items', 'keyboard'),
1 - paradedb.minmax_norm(
'[1,2,3]' <-> embedding,
MIN('[1,2,3]' <-> embedding) OVER (),
MAX('[1,2,3]' <-> embedding) OVER ()
),
ARRAY[0.8,0.2]
) as score_hybrid
FROM …
```
=> fix: Hybrid search + use minmax normalization

pg_bm25/src/index_access/scan.rs
- Closes #
When calling `rank_bm25` or `highlight_bm25`, users were getting a mysterious `Could not call Option::unwrap on None` error. The cause of this is because sometimes Postgres would decide to do a full bitmap scan, and we hadn't implemented scoring/highlighting inside the bitmap scan. This PR fixes that bug.
Fixes the above bug.
Moved scoring/highlighting to a separate inline function that can be called from both `amgettuple` and `ambitmapscan`.
=> fix: Retrieve scores and highlights in ambitmapscan

pg_bm25/src/index_access/scan.rs, pg_bm25/src/index_access/utils.rs, pg_bm25/test/expected/search_config.out, pg_bm25/test/sql/search_config.sql
Implements autocomplete by using Tanvity's `RegexQuery`. This is a different kind of query, so it's an exclusive codepath. It's compatible with some config options, like `limit` and `offset`, but we'll have to make sure that we make it panic when given contradictory options, like `fuzzy_fields`.
Here's an example of a result:
```sql
select * from products where products @@@ 'com:::prefix_fields=description'
+----+------------------------+--------+-------------+
| id | description            | rating | category    |
|----+------------------------+--------+-------------|
| 6  | Compact digital camera | 5      | Photography |
| 23 | Comfortable slippers   | 3      | Footwear    |
+----+------------------------+--------+-------------+
```
The RegexQuery matches on any word in the document, …
=> feat: Add prefix search options for new autocomplete feature

.github/workflows/lint-rust.yml, .github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, .pre-commit-config.yaml, README.md
- Closes #N/A
This is a very small nit, which will make sure we maximize the cache hits we get from our cache action.
Faster CI
Followed: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
See CI
=> chore: Add restore keys to CI cache action

CONTRIBUTING.md, LICENSE, README.md, pg_bm25/Cargo.toml, pg_search/Cargo.toml
We've thought about it more, and have decided it is more in the spirit of open-source for us to use a standard OSS license that's approved by the OSS foundation. As such, we're switching to AGPL.
=> chore: Convert to APGL

docs/search/autocomplete.mdx, docs/search/fuzzy.mdx, pg_bm25/src/index_access/scan.rs, pg_bm25/src/index_access/utils.rs, pg_bm25/test/expected/search_config.out, pg_bm25/test/sql/search_config.sql
- Closes #329 
- Enables the user to configure the max Levenshtein distance, transpose cost, and prefix for fuzzy queries 
- Also renamed `prefix_fields` to `regex_fields` to avoid confusion
- Example usage:
```sql
SELECT id, description, rating, category 
FROM search_config 
WHERE search_config @@@ 'keybaord:::fuzzy_fields=description&transpose_cost_one=true&distance=1';
```
- We no longer have to hard-code these options
- Via the config string
Wrote an additional regression test
=> feat: Enable configuration of fuzzy query options

.github/workflows/publish-paradedb-to-dockerhub.yml
- Closes #
Adds the missing pgnodemx version to the github release workflow.
Because the latest deploy failed since the extension has an empty version.
Add to `publish-paradedb-to-dockerhub` workflow.
Will have to merge to test.
=> fix: add pgnodemx version to release workflow

.github/workflows/benchmark-paradedb.yml, .prettierignore, README.md, benchmarks/.gitignore, benchmarks/README.md, benchmarks/benchmark-elasticsearch.sh, benchmarks/benchmark-tsquery.sh, benchmarks/benchmark-typesense.sh
* Fix `tsquery` benchmarking
* Add another benchmarking script for Typesense
TODOs (added by Phil): 
- Update all benchmarks in README once we've run them all in CI
- Fix the issue with Typesense failing at 600k+ rows
I am opening up a new issue for these
* `tsquery` benchmarking was originally not actually indexing - we add the gin index here.
* More benches
🤔 
Run the benchmarking scripts!
=> chore: fix tsquery benchmarking and add Typesense benchmark

benchmarks/benchmark-typesense.sh
Addresses #367
See title - allows benchmarking on Typesense with more than 600000 entries
=> chore: split bulk upload into multiple curls for typesense

benchmarks/benchmark-elasticsearch.sh, benchmarks/benchmark-typesense.sh, benchmarks/helpers/get_data.sh
- Closes #
Right now, in CI the benchmarks don't work for Elastic and Typesense because we don't download the dataset. This fixes it.
=> fix: Download dataset for elastic and typesense too

benchmarks/benchmark-typesense.sh
The bulk file search expression was wrong and so nothing was getting indexed for Typesense… this is now fixed
=> fix: typesense benchmark bulk upload

pg_bm25/Cargo.toml
Closes #309
Our paradedb-tantivy fork now contains an initial implementation of fuzzy scoring. This PR pins the version in our `pg_bm25` Cargo.toml file to point to the newest version of the fork.
The work in the current version of paradedb-tantivy takes somewhat of a naive approach, which is just to add together inverted levenshtein distances. It means that we'll "give extra points" to documents that contain multiple relevant terms.
For example, consider these (score, document) pairs, returned for the search term "Rob".
```
1, Str("WHEN GOLD LIKE ROB")
0.8333334, Str("WENN ROT WIE ROBIN")
0.6666667, Str("WHEN RED LIKE ROBIN")
0.5, Str("IF BRONZE LIKE ROBE")
```
Notice that the second item's score is higher than the third, because we match on both "ROBIN" and "ROT".
Next, "RED" is still …
=> feat: implement fuzzy scoring by pinning latest version of paradedb-tantivy

docs/indexing/bm25.mdx
None ticket.
Fix broken anchor links on the `indexing/bm25` page: 
https://docs.paradedb.com/indexing/bm25
Change links on the `/docs` path.
=> docs: fix broken anchor links in indexing/bm25

Cargo.lock, docs/aggregations/bucket.mdx, docs/aggregations/metrics.mdx, docs/indexing/bm25.mdx, pg_bm25/Cargo.toml, pg_bm25/src/api/aggregation.rs, pg_bm25/src/index_access/options.rs, pg_bm25/test/expected/aggregations.out, pg_bm25/test/expected/index_config.out, pg_bm25/test/sql/aggregations.sql, pg_bm25/test/sql/index_config.sql
Use [JSON5](https://json5.org/) for query/options parsing. It's backwards compatible with JSON, so we won't break anybody's existing queries.
We're starting to rely heavily on nested configuration objects, which are cumbersome to write. JSON5 removes a lot of the noise, and lets us write:
```sql
CREATE INDEX idxtokenizerconfig ON tokenizer_config USING bm25 ((tokenizer_config.*)) 
WITH (text_fields='{description: {tokenizer: {type: "ngram", min_gram: 3, max_gram: 5}}}');
```
Notice we don't need quotes on the `text_fields` keys, just like object literals in JavaScript. Trailing commas are also not a problem. If someone wants to put comments in their JSON, for some reason, that's supported too.
Change a couple imports. Serde is awesome. Rust is awesome.
Edited some existing tests to use a …
=> feat: Use json5 crate to parse index/query options

.github/workflows/lint-rust.yml, .github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, Cargo.lock, docker/Dockerfile, pg_bm25/Cargo.toml, pg_bm25/README.md, pg_bm25/src/index_access/build.rs, pg_bm25/src/index_access/cost.rs, pg_bm25/src/index_access/insert.rs, pg_bm25/src/index_access/mod.rs, pg_bm25/src/index_access/options.rs, pg_bm25/src/index_access/scan.rs, pg_bm25/src/operator/mod.rs, pg_search/Cargo.toml, pg_search/README.md
- Closes # 252
Changes the version of pgrx to 0.10.1, which aligns with pgml and allows to use Postgres 16
Version upgrades, add pg16 as required.
Ran the pg_bm25 tests successfully.
=> build: Successful build and test on pg16

docs/blog/introducing_bm25.mdx
- Closes #
A user reported issues w/ ParadeDB's doc/blogs on mobile, and so does Google. It's very minor, but it appears our image is too big in the bm25 blog post, leading to some issues on the page. I make it the same size as the image for the initial blog post, which does not cause issues.
=> fix: Fix mobile usability issue in blog

.github/workflows/publish-paradedb-to-dockerhub.yml, conf/third_party_pg_extensions.json, docker/Dockerfile, docker/docker-compose.dev.yml, scripts/entrypoint.sh
N/A
Make the modifications necessary for the image to be fully compatible with the CloudNativePG operator. This PR removes all the Crunchy Operator comments and dependencies.
Because as of https://github.com/paradedb/helm-charts/pull/36, the operator used in the helm chart will be switched, and the modifications made in this PR make our image work with the new operator.
Change postgres uid to `26` (its the uid used by kubernetes), fix permissions on necessary directories, add some dependencies and create a new tag in the form of: `paradedb:{pg-major}-{version}`. This is necessary because the operator uses the tag to determine the postgres version.
Tested with the new helm chart.
=> feat: CloudNativePG compatible image

.github/workflows/lint-rust.yml, .github/workflows/publish-pg_bm25.yml, .github/workflows/publish-pg_search.yml, .github/workflows/test-paradedb.yml, .github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml
- Closes #
In the recent promotion to `prod`, we faced some issues which stemmed from a small issue in the Dockerfile. Yeah, should've been caught by manual testing. But also, it shouldn't make it's way up to being caught in `prod`. This PR adds a workflow to test the Dockerfile building, to avoid this happening again!
I also removed the caching in CI, it really does not work at all...
=> feat: Add workflow to test building ParadeDB

pg_bm25/src/api/aggregation.rs, pg_bm25/src/api/index.rs, pg_bm25/src/parade_index/index.rs
- Closes #410 
Persist the Tantivy `IndexReader` instance across queries.
Right now, we're re-builder the Tantivy `IndexReader` object on every query. This is inefficient: there is overhead to re-opening the index segments, and we don't get any benefits from the docstore block cache.
In #375, I introduced a system to persist our `ParadeIndex` instance in-memory over the lifetime of a connection. This memory space is per-connection, so each connection to Postgres should have its own singleton instance of `ParadeIndex`.
In several places across the codebase, we've been accessing the `reader()` method of our `ParadeIndex.underlying_index` to get a Tantivy `searcher` object, which actually performs the lookup in our index. This PR makes `underlying_index` private, and instead exposes a …
=> perf: Cache reader along with ParadeIndex

pg_bm25/src/api/search.rs, pg_bm25/src/index_access/scan.rs, pg_bm25/src/manager/mod.rs, pg_bm25/test/expected/search_config.out, pg_bm25/test/sql/search_config.sql
- Closes #409
Compute highlights on the fly when they're actually requested, as opposed to on every iteration of an index scan.
Efficiency! This could potentially be a big speedup for queries that return lots of results.
Generate the highlight snippets inside the `highlight_bm25` `#[pg_extern]` function. This way, we ensure that we're only doing the highlight processing when it's actually part of the query.
To do this, I needed to change the API of `highlight_bm25`. It will require manually specifying the index name, just like `minmax_bm25`.
I also split `get_executor_manager()` into `get_current_executor_manager()` and `get_fresh_exectuor_manager()`. We now call the `fresh()` variant at the top of `amrescan` and `ambitmapscan`, which instantiates a new copy of the manager. Without doing …
=> perf: Move highlighting code out of main query loop

.github/CODEOWNERS, docker/Dockerfile
- Closes #
There was an issue vectorizing with `pgml` because we swapped the userID for `postgres` to match with the new CloudNativePG operator, and had forgotten to set write permissions on the PGDATA folder for the new user. This fixes it.
Bug:
Tested locally, can now run the `ALTER TABLE` command on the Parade Quickstart tutorial properly
=> fix: Set write permission for new userID

.github/workflows/lint-bash.yml, .github/workflows/lint-python.yml, .github/workflows/publish-paradedb-to-dockerhub.yml, .github/workflows/publish-pg_bm25.yml, .github/workflows/publish-pg_search.yml, .github/workflows/publish-third-party-pg_extensions.yml, .github/workflows/test-paradedb.yml, .hadolint.yaml, README.md, docker/Dockerfile, docker/docker-compose.dev.yml
- Closes #
This PR:
- Upgrades `pgml` to be Postgres 16 compatible
- Fix a small typo in the `pg_search` packaging
- Swaps the release action for our CI to be a maintained one, instead of the deprecated one we were using
=> chore: Upgrade `pgml`, small typos, fix CI deprecation warnings

.github/workflows/lint-rust.yml, .github/workflows/publish-pg_bm25.yml, .github/workflows/publish-pg_search.yml, .github/workflows/publish-third-party-pg_extensions.yml, .github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, docker/Dockerfile, pg_bm25/README.md, pg_search/README.md
- Closes #362
One of our users had issued testing ParadeDB on macOS using Postgres.app. It turns out, Postgres.app does not add its `pg_config` binary to path automatically, so we need an extra command. 
I also added `--locked` to our `cargo install` commands, this is good practice and will avoid any issues in the future.
=> fix: Add instructions for self-hosting ParadeDB extensions on macOS with Postgres.app

.github/workflows/publish-pg_bm25.yml, .github/workflows/publish-pg_search.yml
- Closes #
I swapped our release action to a new one, since the old one was deprecated for a few years. Unfortunately, that action doesn't read from ENV. This should fix this.
=> fix: Properly specify github_token for releases

.github/workflows/publish-pg_bm25.yml
- Closes #
Building pg_bm25 keeps failing because the runner runs out of memory on arm64... This makes it one quanta bigger, so that this doesn't happen again.
=> fix: Move to 8vcpu for arm64 runner

pg_bm25/src/index_access/delete.rs, pg_bm25/src/index_access/scan.rs, pg_bm25/src/index_access/vacuum.rs, pg_bm25/src/parade_index/index.rs
- Closes #411
Finished review and rebase of @aragalie's #404. I intended to push to/merge that one, but GitHub closed it and won't let me re-open.
All the notes from #404 still apply. I've spend the last day studying @aragalie's work to better understand VACUUM operations in Postgres. Carefully following the code paths with a debugger helped me verify that everything is being called as expected.
I can't find much information about @aragalie's change to increment `stats_binding.pages_deleted` instead of ` stats_binding.tuples_removed`, as well as the change to increment `stats_binding.num_pages` instead of `stats_binding.num_index_tuples`. @aragalie, it would be great if you could comment on this change!
Otherwise, the PR seems to work well, and I'd be in favor of merging so I can build …
=> perf: MVCC (auto)vacuum and bulk_delete improvements

docker/Dockerfile
N/A
This PR aims to fix the issue seen when trying to use `paradedb.embed` while deploying with the helm chart. It fixes the postgres user group which was incorrectly set to 26 (`tape` group), and finally, installs [barman](https://docs.pgbarman.org/release/2.13/barman-cloud-backup.1.html), which is the final missing piece to get backups fully working.
Because while testing, we ran into the issue:
```
RuntimeError: Failed to import transformers.models.pegasus.modeling_pegasus because of the following
error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error 
(look up to see its traceback):
[Errno 30] Read-only file system: '/var/lib/postgresql/.triton'
```
This happens because the CloudNative operator mounts the root filesystem as …
=> fix: pgml symlinks and postgres permissions

.github/workflows/lint-format.yml, .github/workflows/lint-markdown.yml, .github/workflows/lint-python.yml, .github/workflows/lint-typescript.yml
- Closes #
This PR adds missing linting workflows to our repo. We were not linting for trailing whitespaces and for TypeScript/JSON/etc. files, which led to all CI passing while pre-commit hooks not passing. This should not standardize everything!
=> feat: Add missing lint workflows that are only caught in pre-commit

Cargo.lock, pg_bm25/src/index_access/build.rs, pg_bm25/src/index_access/delete.rs, pg_bm25/src/index_access/insert.rs, pg_bm25/src/index_access/scan.rs, pg_bm25/src/index_access/vacuum.rs, pg_bm25/src/parade_index/index.rs
- Closes #348 
What's happening in #348 is that rows are getting marked "dead" in Postgres due to the `UPDATE` call, but we don't synchronously commit the changes to Tantivy index + reload.
Manually call `.reload` on the tantivy reader after write and before scan.
=> fix: Manually reload index and encapsulate Tantivy writer

scripts/entrypoint.sh
- Closes #
We weren't adding our schema, `paradedb`, to the `search_path` in Postgres. As a result, it was only finding the `public` schema, while our extensions were getting installed on the `paradedb` schema, which led to inconsistencies. This fixes it.
Tested locally on both `public` and `paradedb` schemas
=> fix: Fix `search_path` missing the `paradedb` schema

pg_bm25/pg_bm25.control, pg_bm25/test/runtests.sh, pg_search/pg_search.control, pg_search/test/runtests.sh, pg_sparse/pg_sparse.control, pg_sparse/test/runtests.sh
- Closes #
This PR adds the missing `schema = paradedb` in the `pg_sparse` .control file, and accordingly adds `paradedb` to the `search_path` for all of our extensions in the integration test framework, so that it can be found correctly. This fixes the issue with `pg_sparse` not fully working, and not passing the tests.
CI now passes!
=> chore: Add missing schema to `pg_sparse`

.github/workflows/publish-paradedb.yml, .github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, .github/workflows/test-pg_sparse.yml, pg_bm25/.gitignore, pg_bm25/README.md, pg_bm25/test/expected/bm25_search.out, pg_bm25/test/runtests.sh, pg_bm25/test/sql/bm25_search.sql, pg_search/.gitignore, pg_search/README.md, pg_search/configure.sh, pg_search/test/expected/search.out, pg_search/test/runtests.sh, pg_search/test/sql/search.sql, pg_sparse/.gitignore, pg_sparse/README.md, pg_sparse/test/runtests.sh
- Closes #479 
Postgres 11 is no longer supported by the Postgres development group, and by `pgrx`. This PR removes it. It also removes a hack we had to do in our tests, which is nice!
=> chore: Remove support for Postgres 11

scripts/entrypoint.sh
- Closes #
This PR does 4 things:
- First, we document the use of the POSTGRES_USER and of the role `postgres`, which are both necessary and were previously used by undocumented
- Second, we add `public,paradedb` to the `search_path`. This makes it so the Postgres cluster will default to the `public` schema, but be able to query across both schemas
- Third, we add the same schemas to the `template1` database. This is the database template on which all future databases created by the user in the cluster are mapped. This ensures that the previous point will apply not just to the database the cluster starts with, but to all databases the user creates themselves
- Fourth, We run a vacuum command after installing the `pg_bm25` extension on its dummy data table. This is because we were having …
=> fix: Set `search_path` to across sessions and users

.pre-commit-config.yaml
- Closes #
We were using a poorly supported Python-based Shellcheck pre-commit hook. Turns out Shellcheck itself supports it natively, as per their README: https://github.com/koalaman/shellcheck
The downside is this hook expects Docker. But then again, we all run Docker all the time anyways.
=> fix: Use official Shellcheck repo in pre-commit hooks

pg_bm25/src/index_access/build.rs, pg_bm25/src/index_access/utils.rs, pg_bm25/src/parade_index/index.rs, pg_bm25/test/expected/quoted_table_name.out, pg_bm25/test/sql/quoted_table_name.sql
- Closes #500 
- Fixed a bug where table names with quotes ie `"Activity"` were not getting indexed
- The reason is that we would pull the name of the table inside `build.rs`, and pgrx would strip the quotes out
- Fixed it by directly passing a `PgRelation` reference instead of the table name to our build function
- Added a regression test
=> fix: Table names with quotes not being indexed

pg_bm25/src/index_access/build.rs, pg_bm25/src/index_access/cost.rs, pg_bm25/src/index_access/insert.rs, pg_bm25/src/index_access/options.rs, pg_bm25/src/index_access/scan.rs, pg_bm25/src/operator/mod.rs, pg_sparse/src/index_access/build.rs, pg_sparse/src/index_access/cost.rs, pg_sparse/src/index_access/insert.rs, pg_sparse/src/index_access/options.rs, pg_sparse/src/index_access/scan.rs
- Closes #
This is more of an open question: Postgres' official development group is no longer supporting Postgres 11, and so pgrx dropped it as well. Thus, we dropped it (no longer in our Cargo.toml files). Right now, our code probably works for pg11, because it was recently removed. But since we won't be testing it on Postgres 11 anymore, it probably won't at some point.
I propose we remove all support for Postgres 11 formally so users don't get confused. This also enables us to simplify our code a bit. What do you think?
=> chore: Remove Postgres 10/11

.pre-commit-config.yaml, pg_bm25/src/manager/mod.rs, pg_bm25/src/parade_index/index.rs, pg_bm25/src/parade_index/mod.rs, pg_bm25/src/parade_index/tests/mod.rs, pg_bm25/src/parade_index/tests/tokenizer_chinese_compatible_query.sql, pg_bm25/src/parade_index/tests/tokenizer_chinese_compatible_setup.sql, pg_bm25/src/tokenizers/mod.rs, shared/src/lib.rs, shared/src/logs.rs, shared/src/testing.rs
Fixing a panic caused by tokenizers not being found upon index retrieval from disk.
Also some small fixes around testing/pre-commit. `plog!` needs a conditional attribute above its `Spi` call to work during `cargo test`. We also needed one more exclude in our `.pre-commit-config.yaml`.
The tokenizers for `pg_bm25` are not getting setup correctly when we retrieve an index from disk, which happens on every new connection.
The tokenizers have to be registered before the reader gets created. This is happening correctly when we create a new index, but not when we retrieve from disk.
Move the `ParadeIndex::setup_tokenizers` call to happen _before_ the call to `ParadeIndex::reader()`.
I've opted to add a `tests` sub-module as `src/parade_index/tests`. The test is in `mod.rs`, and some SQL files …
=> fix: Move reader to after tokenizer setup when retrieving index

.cargo/config.toml, .github/workflows/benchmark-paradedb.yml, .github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, .github/workflows/test-pg_sparse.yml, pg_bm25/test/runtests.sh, pg_search/configure.sh, pg_search/test/runtests.sh, pg_sparse/test/runtests.sh
- Closes #
We've realized that we hadn't been building any ways for extensions to upgrade. This involves creating a `.sql` file with custom commands. To make sure we don't forget, and that our upgrade scripts work, I've added some steps in our CI to test whether our extensions can upgrade as part of the promoting to `main`, which is when we release a new versions.
This PR also adds a Slack webhook to notify us if/when our benchmark workflow fails. It had been failing for a few days without us realizing, leading to some error not being caught as quickly as it could've.
^
Simply install an old version + test upgrading
Manual testing done for all 3 extensions
=> feat: Test whether our extensions can upgrade as part of our CI

.github/codecov.yml, .github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, .github/workflows/test-pg_sparse.yml
- Closes #
Now that we've started writing unit tests, I am attempting to re-enable Codecov. I have set it to tolerate 0% code coverage, so that it never fails CI. Once we have higher code coverage, we can make this stricter. I've also set a 5% threshold for modifications, to ensure it never fails CI.
TODO:
=> chore: Reenable Codecov

.github/codecov.yml, .github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, .github/workflows/test-pg_sparse.yml
- Closes #
It turns out our Codecov file was slightly wrong. You can test it with:
```
curl -X POST --data-binary @codecov.yml https://codecov.io/validate
```
I thus fixed the flags issue, and added the flags parameter to the CI uploader. This should enable us to properly get reports broken down per-subfolder, and thus get Markdown badges per-subfolder.
Ref: https://docs.codecov.com/docs/flags && https://community.codecov.com/t/coverage-badge-on-a-per-directory-basis/3158
=> chore: Properly do flags in Codecov

benchmarks/benchmark-paradedb.sh, benchmarks/benchmark-tsquery.sh
- Closes #
All in the title. A user mentioned the benchmarking might be defaulting to not using GIN index. This will help us see that.
=> feat: Add EXPLAIN to the tsvector benchmarking, so we can see the query plan

.github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, .github/workflows/test-pg_sparse.yml, pg_bm25/test/runtests.sh, pg_search/configure.sh, pg_search/test/expected/search.out, pg_search/test/runtests.sh, pg_search/test/sql/search.sql, pg_sparse/README.md, pg_sparse/test/runtests.sh
- Closes #N/A
This PR fixes an issue where our `runtests.sh` and `configure.sh` scripts were not properly interoperating non-pgrx extensions and pgrx extensions. This led to issues testing `pgvector` with `cargo pgrx run`.
This should now be fixed. Our scripts uses the system-wide Postgres installs, which also has the nice side effect of making them faster. It also properly splits paths based on the `arch` on macOS, which was necessary.
TODOs
Fix `pgvector` in `cargo pgrx run`!
See above^
Tested both in CI and manually for Linux Ubuntu and for macOS. I reverted the CI to only do Linux, but did macOS in CI just for testing on a clean environment, in addition to on my local Mac
=> fix: Fix `runtests.sh` and `configure.sh` issues with `pgvector`

pg_bm25/test/runtests.sh, pg_search/configure.sh, pg_search/test/runtests.sh, pg_sparse/test/runtests.sh
- Closes #
I had forgotten to clean up the PG versions for macOS following the recent change, and set `pgrx init` to the current default project at the end to make it work on `cargo pgrx run` by default. This fixes that.
I also re-test locally with `pgvector` and it works great.
=> fix: Make our new test setup also work with `cargo pgrx run`

docs/search/autocomplete.mdx, docs/search/bm25.mdx, docs/search/fuzzy.mdx, pg_bm25/src/index_access/scan.rs, pg_bm25/src/parade_index/fields.rs, pg_bm25/src/parade_index/tests/tokenizer_chinese_compatible_query.sql, pg_bm25/test/expected/bm25_search.out, pg_bm25/test/expected/index_config.out, pg_bm25/test/expected/quoted_table_name.out, pg_bm25/test/expected/search_config.out, pg_bm25/test/expected/tokenizer_config.out, pg_bm25/test/sql/bm25_search.sql, pg_bm25/test/sql/quoted_table_name.sql, pg_bm25/test/sql/search_config.sql, pg_bm25/test/sql/tokenizer_config.sql
As discussed in our community Slack, we've realized that ngrams (and likely other) tokenizers aren't returning the expected results.
We were using Tantivy's `parse_query_lenient`, which was ignoring some configuration issues... Namely, we were using `IndexRecordOption::Basic` when we should have been using `IndexRecordOption::WithFreqsAndPositions`.
`WithFreqsAndPositions` is necessary for proper scoring and tokenization. We should pretty much always be using it. It takes up more index space than `Basic`, but since it's required for most of our `bm25` functionality, we should make it the default. W can save index space optimization as a project for later.
Use `parse_query` so parsing errors aren't silent, and make `WithFreqsAndPositions` the default for our `record` configuration.
I've …
=> fix: Remove lenient parsing and default record to freqs/positions

pg_search/test/runtests.sh
- Closes #
I added it to `configure.sh` but we don't call it in that part of the test. I feel like this has grown a bit overcomplicated... Could probably streamline things, but that's for another PR
=> fix: Add missing `pgrx init` in `pg_search` extension upgrade test

pg_bm25/test/runtests.sh, pg_search/configure.sh, pg_search/test/runtests.sh, pg_sparse/test/runtests.sh
- Closes #N/A
From a recent PR, I set the tests to call their own `cargo pgrx init` to properly associate with system Postgres of the version they're testing against.
In order for the engineer to not need to re-call `cargo pgrx init` themselves after running the tests, we need to re-set it to the default project version after writing the tests. This does that.
=> feat: Reset `pgrx` environment post-tests

.github/codecov.yml, docs/indexing/bm25.mdx, docs/search/bm25.mdx, pg_bm25/src/index_access/utils.rs, pg_bm25/src/json/builder.rs, pg_bm25/src/parade_index/index.rs, pg_bm25/test/expected/text_arrays.out, pg_bm25/test/sql/text_arrays.sql
- Closes #504 
With this PR, Postgres `text[]` and `varchar[]` columns are properly recognized and indexed as Tantivy multivalue fields.
Usage:
``` sql
CREATE TABLE example_table (
id SERIAL PRIMARY KEY,
text_array TEXT[]
);
INSERT INTO example_table (text_array) VALUES 
('{"text1", "text2", "text3"}'),
('{"another", "array", "of", "texts"}'),
('{"single element"}');
CREATE INDEX ON example_table
USING bm25 ((example_table.*))
WITH (text_fields='{text_array: {}}');
SELECT * FROM example_table WHERE example_table @@@ 'text_array:text1';
id |     text_array
----+---------------------
1 | {text1,text2,text3}
(1 row)
```
Added an additional regression test
=> feat: Support text arrays

docs/quickstart.mdx, pg_search/README.md
- Closes #
We were still using the old query syntax on the docs for `minmax_bm25`.
=> fix: `minmax_bm25` docs

.github/workflows/lint-rust.yml, .github/workflows/publish-pg_bm25.yml, .github/workflows/publish-pg_search.yml, .github/workflows/publish-pg_sparse.yml, .github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, .github/workflows/test-pg_sparse.yml, Cargo.lock, docker/Dockerfile, pg_bm25/Cargo.toml, pg_bm25/README.md, pg_search/Cargo.toml, pg_search/README.md, pg_sparse/Cargo.toml, pg_sparse/README.md, shared/Cargo.toml
- resolves https://github.com/paradedb/paradedb/issues/556
- (effectively) resolves https://github.com/paradedb/paradedb/issues/559
- resolves https://github.com/pgcentralfoundation/pgrx/issues/1407
Fixes several weird build edge-cases.
These edge-cases prevent local builds from resolving correctly. These seem to disproportionately afflict CentOS 7, but they can arise in other build environments such as Debian, unless you carefully manage the build environment with e.g. Docker.
Upgrade pgrx to `=0.11.1`.
It does update all the workflows, of course, though I do not believe you wish to run a CentOS 7 test server at this time to test the exact edge-case in question.
=> fix: build edge-cases with pgrx =0.11.1

.github/workflows/publish-pg_bm25.yml, .github/workflows/publish-pg_search.yml, .github/workflows/publish-pg_sparse.yml, .github/workflows/publish-third-party-pg_extensions.yml
- Closes #
Ubicloud is much cheaper, so converting to that. Functionality should be the same.
=> chore: Convert from Buildjet to Ubicloud

.github/workflows/test-pg_bm25.yml, .github/workflows/test-pg_search.yml, docker/Dockerfile
- Closes #
The issue with the tests and the extension re-installing is due to the Rust cache caching previous extension versions. This should be the actual fix for it!
see here: https://doc.rust-lang.org/cargo/commands/cargo-clean.html
=> fix: Clean previous build artifacts to avoid conflicts

benchmarks/benchmark-paradedb.sh
- Closes #
Our benchmarks fail. It seems a regression got introduced and that we didn't catch because we were testing `main` rather than `dev`. This is now fixed, and we need to fix the regression. As such, I'm adding better error logs to help us troubleshoot.
=> chore: Add better error logging to our benchmarks

pg_bm25/test/runtests.sh, pg_search/test/runtests.sh, pg_sparse/test/runtests.sh
- Closes #
This was missing, so the `pg_search` upgrade test was failing.
=> fix: Add pg_sparse to pg_search upgrade test

pg_search/test/runtests.sh
- Closes #
We needed to modify it slightly since `pg_sparse` was introduced in `v0.3.12`
=> fix: Make extension upgrade test work w/ `pg_sparse`

.github/workflows/publish-pg_bm25.yml, .github/workflows/publish-pg_search.yml, .github/workflows/publish-pg_sparse.yml
- Closes #
Unfortunately, the way we were updating the `pg_sparse` version in deployment vs test was different, and the deployment one was wrong. This fixes it. This issue was caught by our extension upgrade test (yay!)
=> fix: Properly update `pg_sparse` version in CI

docker/Dockerfile
- Closes #
Small issue that happened locally if you had previously built `pg_sparse` and had not cleaned.
=> fix: ix error with building dockerfile locally

.github/workflows/benchmark-paradedb.yml, benchmarks/helpers/get_data.sh
- Closes #
Use our own S3-stored dataset for benchmarks, to stop hitting the Dropbox rate limit, and disable on PR until we've gotten the global writer PR in, which will fix it.
=> chore: Fix the benchmarks

docker/Dockerfile
- Closes #
This was causing `pg_sparse` to not work on macOS ARM
=> fix: Disable armnative for `pg_sparse` in Dockerfile

pg_bm25/pg_bm25.control, pg_sparse/svector.control
- Closes #557
This makes it so that using ParadeDB extensions does not require superuser permissions. It was not needed already, but somehow was being enforced.
=> feat: Make ParadeDB extensions not require superuser

Cargo.lock, pg_bm25/README.md
- Closes #
We observed issues with pgrx's Postgres, so we wanted to clarify to our users to use Homebrew's Postgres.
=> fix: Mandate Brew Postgres for development

README.md, docker/docker-compose.dev.yml, docker/docker-compose.yml, pg_bm25/src/lib.rs, pg_bm25/src/parade_index/index.rs, scripts/entrypoint.sh, shared/src/telemetry/posthog.rs
- Closes #590 
- 
We now keep an anonymous UUID per-deployment, so we can tell whether a deployment ping is coming from the same anonymous deployment or not.
Better understanding how many people are using ParadeDB
Write a UUID to a temp file
=> feat: Set fixed anonymous UUID for PostHog

pg_bm25/src/lib.rs, pg_bm25/src/parade_index/index.rs, shared/src/constants.rs, shared/src/lib.rs, shared/src/telemetry/posthog.rs
N/A
This PR adds basic telemetry for tracking user retention. An event is sent when the `ParadeIndex` is created, and since it is cached for subsequent uses, the event is sent once per connection.
To get insight into user retention and extension usage. This event will also allow us to use the Retention insight in PostHog.
- Call telemetry function when `ParadeIndex` is created.
- Try to read the uuid file from the possible extension names.
- Send connection start event to Posthog.
- Abstract extension names into shared constants file.
Manully tested, see PostHog dashboard. However I didn't test with `pg_bm25` deployments yet, only ParadeDB deployments.
We can start using the retention insight:
=> feat: add retention telemetry

pg_bm25/src/api/search.rs, pg_bm25/src/parade_index/mod.rs, pg_bm25/src/parade_index/score.rs, pg_bm25/src/parade_index/state.rs, pg_bm25/test/expected/search_config.out, pg_bm25/test/sql/search_config.sql
- Closes #691
An implementation of a stable sorting for `bm25` results.
After the introduction of the multi-threaded writer in #673, we found that result ordering is not entirely stable, because in the case of ties with the BM25 score, Tantivy falls back to the document address in the index.
The document address is not a stable order across machines (because of the multi-threaded insert), which makes CI testing difficult. It also means that the order of tied results changes as rows are updated, as updated document receives a new document address.
This would cause what might look like "wrong rows" when using `limit_rows` and `offset_rows`, because the result set would be a slice of an incorrect ordering.
Fortunately, I was able to use the `tweak_score` method of the `TopDocs` collector, …
=> fix: Stabilize result order on tied BM25 scores

pg_bm25/sql/_bootstrap.sql, pg_bm25/test/expected/search_config.out, pg_bm25/test/sql/search_config.sql
- Closes #689 
This PR fixes the `create_bm25` definition to use the correct type on the `prefix` search option for fuzzy search.
Because it was incorrectly set as a TEXT field, which caused the following error to show up:
```
<index>.search(unknown, fuzzy_fields => unknown, prefix => boolean) does not exist
```
Fix type to boolean.
Tested the fix works, you can use:
```SQL
--- Test with prefix disabled
SELECT *
FROM search_idx.search(
'key',
fuzzy_fields => 'description,category',
distance => 2,
transpose_cost_one => false,
prefix => false);
id |    description     | rating | category  | in_stock |                       metadata                       
----+--------------------+--------+-----------+----------+------------------------------------------------------
10 | Colorful kids toy  | …
```
=> fix: search prefix option

pg_bm25/test/runtests.sh
- Closes #
In the `runtests.sh`, if we were testing the extension upgrade script, we didn't pass `--features icu`.
=> fix: Add missing icu feature

.github/workflows/publish-pg_bm25.yml
- Closes #
It appears we need quotes to package with multiple features in `cargo pgrx package`. See: https://github.com/paradedb/paradedb/actions/runs/7618513912/job/20749836886
=> fix: Use quotes for multiple features in pgrx package

.github/workflows/lint-rust.yml, .github/workflows/publish-paradedb.yml, .github/workflows/publish-pg_analytics.yml, .github/workflows/publish-pg_bm25.yml, .github/workflows/publish-pg_sparse.yml, .github/workflows/test-paradedb.yml, .github/workflows/test-pg_analytics.yml, .github/workflows/test-pg_bm25.yml, docker/Dockerfile, docs/introduction.mdx, pg_analytics/Cargo.toml, pg_analytics/README.md, pg_analytics/benchmarks/clickbench/benchmark.sh, pg_bm25/Cargo.toml, pg_bm25/README.md, pg_sparse/README.md
- Closes #429 
This PR sets Postgres 16 as the default Postgres version for ParadeDB, pg_bm25, pg_analytics, and pg_sparse.
Because it's what users expect now that it's been out for several months.
Updated it everywhere
See CI :)
=> feat: Upgrade to Postgres 16

.github/workflows/lint-rust.yml, .github/workflows/publish-pg_analytics.yml, .github/workflows/publish-pg_bm25.yml, .github/workflows/test-pg_analytics.yml, .github/workflows/test-pg_bm25.yml, Cargo.lock, docker/Dockerfile, pg_analytics/Cargo.toml, pg_analytics/README.md, pg_analytics/benchmarks/clickbench/benchmark.sh, pg_analytics/src/datafusion/catalog.rs, pg_analytics/src/datafusion/schema.rs, pg_bm25/Cargo.toml, pg_bm25/README.md, shared/Cargo.toml
- Closes #N/A
We've been on an outdated versions of `pgrx` for a while, and this has been their latest version for over a month. I figured it might be worth upgrading while I'm also upgrading Postgres itself.
^
Simply replace everywhere + fix some deprecated functions
See CI
=> chore: Upgrade to `pgrx` `0.11.2`

pg_analytics/README.md, pg_analytics/benchmarks/clickbench/benchmark.sh, pg_analytics/benchmarks/clickbench/benchmark.sql, pg_analytics/benchmarks/clickbench/create.sql, pg_analytics/benchmarks/clickbench/run.sh, pg_analytics/src/api/init.rs, pg_analytics/src/datafusion/context.rs, pg_analytics/src/datafusion/schema.rs, pg_analytics/src/datafusion/table.rs, pg_analytics/src/errors.rs, pg_analytics/src/tableam/insert.rs, pg_analytics/test/fixtures.sql
- Closes #730 
A table created/modified in one connection is now visible to all other connections. The user never has to call `paradedb.init()` themselves anymore.
Having to call `paradedb.init()` was annoying and goes against the behavior users expect from Postgres MVCC.
The `get_delta_table` function now checks to see if a table exists. If it does not, it attempts to open and register a delta table. If it does, it calls `load` on the table, which updates the delta table to the latest state in the delta logs.
Open two connections. In one connection, create/modify a deltalake table. In another connection, SELECT the table - it should be up to date with the first connection.
=> feat: Tables created/modified get shared w all connections

CONTRIBUTING.md, README.md
- Closes #N/A
Conversations with experts in open-source and observing other companies doing open-source has led us to realize that we should have a CLA. This introduces the CLA, clarifies the option of purchasing a commercial license, and modifies the contribution guidelines.
The CLA is already configured via `cla-assistant`
Properly set up contributions for licensing
Via CLA assistant
You can see it display in other existing PRs
=> chore: Introduce CLA

pg_analytics/test/runtests.sh, pg_bm25/test/runtests.sh
- Closes #
We were doing it dynamically, and now that we upgraded PG version it wasn't retrieving the package properly.
=> fix: Hardcode pg15 in extension upgrade test

pg_analytics/src/datafusion/schema.rs, pg_analytics/src/datafusion/table.rs
- Closes #
We can bind `fields` directly to `PgRelation`, so any `PgRelation` can emit Datafusion fields.
```rust
let pg_relation = PgRelation::from_pg(relation);
let fields = pg_relation.fields()?;
```
=> chore: Move `fields` to `table.rs`

.github/workflows/test-pg_analytics.yml, .github/workflows/test-pg_bm25.yml
- Closes #
We upgraded to PG16, and I need to fix a few things about our test setup. Since we want to promote the blog post, I'll disable it for now so CI passes, and open up an issue. I'll fix it over the weekend.
I've manually tested that it updates properly here for the current version.
=> fix: Disable upgrade test until we fix for PG16

.github/workflows/publish-pg_analytics.yml, .github/workflows/publish-pg_bm25.yml, .github/workflows/publish-pg_sparse.yml, docker/Dockerfile
- Closes #
I discovered recently that `checkinstall` is actually not been maintained at all for like... years. Well, it just broke a few days ago. Time to move on to `dpkg-deb`.
I might do another PR to cleanup and centralize the way we build & publish our extensions, since they now all use `dpkg-deb` but this recent one is cleaner than the previous two.
^
^
Tested publishing `pg_sparse` for v0.5.2, which had failed. It is now published properly.
=> fix: Replace `checkinstall` w/ dpkg-deb

pg_bm25/src/writer/client.rs
N/A
Improve the error message when an index is created but the extension is not on the shared preload libraries list.
Because the existing error doesn't really give helpful information.
```
ERROR:  Can't give out share, lock is in an empty state
CONTEXT:  SQL statement "SELECT paradedb.drop_bm25_internal(format('%s_bm25_index', index_name))"
PL/pgSQL function paradedb.drop_bm25(text,text) line 10 at PERFORM
SQL statement "CALL paradedb.drop_bm25(index_name, schema_name => schema_name)"
PL/pgSQL function paradedb.create_bm25(text,text,text,text,text,text,text,text) line 33 at CALL
```
New error message:
```
ERROR:  Could not get lock on writer. Have you added the extension to the shared preload library list?
CONTEXT:  SQL statement "SELECT …
```
=> fix: improve error message when not on preload list

pg_analytics/README.md, pg_bm25/README.md
- Closes #
The previous instructions were misleading following the upgrade to PG16.
=> chore: Clarify README w/ `pg_config`

.github/workflows/publish-pg_analytics.yml, .github/workflows/test-pg_analytics.yml, Cargo.lock, docker/Dockerfile, pg_analytics/Cargo.toml, pg_analytics/README.md, pg_analytics/benchmarks/clickbench/benchmark.sh, pg_analytics/src/datafusion/context.rs, pg_analytics/src/datafusion/datatype.rs, pg_analytics/src/datafusion/schema.rs, pg_analytics/src/datafusion/table.rs, pg_analytics/src/hooks/executor.rs
- Closes #732 
- Closes #755 
This upgrades us to Datafusion 35.
We were previously using Datafusion 32, which had some bugs and was not using SIMD.
We had to fork `delta-rs` to do this. The reason is that we use `delta-rs`' exported Datafusion, but `delta-rs` is on Datafusion 32 and they don't plan on releasing an update anytime soon due to a refactor that the team is working on.
The forked `delta-rs` also has a number of breaking API changes. I made the necessary changes on our end.
Now Datafusion 35 automatically applies SIMD when you run in release mode with Rust nightly, so we can remove that feature flag.
=> chore: Upgrade to Datafusion 35

README.md, benchmarks/README.md, benchmarks/benchmark-elasticsearch.sh, docs/analytics/quickstart.mdx, docs/blog/introducing_analytics.mdx, docs/blog/introducing_bm25.mdx, docs/blog/introducing_paradedb.mdx, docs/blog/introducing_paradedb_cloud.mdx, docs/introduction.mdx, docs/search/indexing/bm25.mdx, pg_analytics/README.md, pg_analytics/src/hooks/executor.rs, pg_analytics/src/tableam/insert.rs, pg_analytics/src/tableam/plan.rs
- Closes #
Chris Riccomini suggested we link to the Quickstart for our blog post, so I did.
I also fixed ElasticSearch to Elasticsearch, which is how Elastic itself calls their product, and Datafusion to DataFusion, which is how DataFusion calls their product.
=> docs: Clarify branding for third-party tools, add link to Quickstart

.github/workflows/test-pg_analytics.yml, .github/workflows/test-pg_bm25.yml, pg_analytics/test/runtests.sh, pg_bm25/test/runtests.sh
- Closes #
I had disabled it since it was broken due to the switch to PG16. The reason is: Our test pulls a previous version of the extension pre-compiled from a past GitHub Release, installs it, then upgrades to the current branch. Since we had just pushed our first PG16 extension, and you can't upgrade from PG15 to PG16 without directly installing a brand new version of the extension compiled for PG16, I had nothing to test installing it against. Now that we've had a few releases, we can do it.
^
^
^
=> fix: Re-enable extension upgrade test, this time for PG16 onwards

docs/search/indexing/overview.mdx, pg_analytics/README.md, pg_bm25/README.md
- Closes #390
We used to be weakly consistent, because we did not want to slow down transactions. This was when we thought customers would primarily run `pg_bm25` in their own database. Now that we expect ParadeDB to be a separate search node to production database(s), we've updated our work thanks to @neilyio to be strongly consistent. This was a lingering issue which I am now closing by fixing the documentation.
We no longer plan to give users the ability to choose the consistency mode, since we don't recommend runnings your search node directly within your primary Postgres.
^
^
^
=> chore: Confirm strong consistency

docs/search/indexing/bm25.mdx, docs/search/indexing/overview.mdx, pg_analytics/src/api/init.rs, pg_analytics/src/datafusion/catalog.rs, pg_analytics/src/datafusion/context.rs, pg_analytics/src/datafusion/datatype.rs, pg_analytics/src/datafusion/schema.rs, pg_analytics/src/datafusion/table.rs, pg_analytics/src/errors.rs, pg_analytics/src/hooks/executor.rs, pg_analytics/src/hooks/handler.rs, pg_analytics/src/hooks/mod.rs, pg_analytics/src/tableam/create.rs, pg_analytics/src/tableam/insert.rs
- Closes #
Better error handling
A few changes:
- Unwraps the error instead of expecting it in the pg_extern funcitons so the actual error messages get printed
- Introduces `ParadeError::NoneError` that prints the type
=> chore: Better error handling

pg_sparse/src/svector.c, pg_sparse/test/expected/cast.out, pg_sparse/test/expected/shnsw_ip.out, pg_sparse/test/sql/cast.sql, pg_sparse/test/sql/shnsw_ip.sql
- Closes #
Converting `float4[]`, `float8[]` and `numeric[]` arrays was broken, due to a typo in the indexing and also to a direct zero comparison leading to indexing many zero values.
Example of failing test:
```sql
SELECT ARRAY[0,1,2,3]::float4[]::svector
array   
-----------
[0,1,2,0]
(1 row)
```
=> fix: Use almost equal comparison to convert arrays into svector

docker/Dockerfile
- Closes #
This PR has introduces changes to the Dockerfile which can reduce the final image size by ~\~70%~ ~60%.
The latest Docker image (v0.5.2) is about 1.73GB due to dev dependencies being included inside the final image. This PR reduces the image to ~725MB.
A brief overview of changes:
- Moved most of the dev dependencies from the `base` image to the `builder` image.
- Compile & package `pg_bm25`, `pg_sparse`, `pg_vector` and `pg_analytics` in their respective build stages.
- Generate `.deb` files for each build stage `checkinstall` and install them in the final image.
=> feat: Reducing docker image size

.github/workflows/test-pg_analytics.yml, .github/workflows/test-pg_bm25.yml
- Closes #
Things like this happen: https://github.com/paradedb/paradedb/actions/runs/7732130732/job/21081359494
And it's because Codecov has network issues. Let's not fail our own CI for that.
=> chore: Don't fail on Codecov error

README.md
- Closes #
Collapses "documentation" and "get started" sections into one and moves them up in the README.
=> docs: Fix get started section

.cargo/config.toml, .github/workflows/test-pg_analytics.yml, .github/workflows/test-pg_bm25.yml
- Closes #809
Only generate code coverage in CI, to avoid it clogging the local folders/builds
^
Moved the `Cinstrument-coverage` to the CI, instead of the `.cargo/config.toml` file
Need to check that it still properly generates the code coverage
=> fix: Only generate profraw in CI

CONTRIBUTING.md
- Part of #794
For legal reasons, it is preferable to get everyone to sign the CLA, and the process is simpler/better.
=> chore: Remove DCO

docs/analytics/quickstart.mdx, pg_analytics/src/hooks/executor.rs, pg_analytics/test/expected/insert.out, pg_analytics/test/sql/insert.sql
- Closes #
Enables `INSERT`s into a deltalake table that reference a heap table.
This gives users a way to copy heap tables into deltalake tables.
Modified the executor hook to call the standard Postgres hook on all `INSERT` statements. Added documentation as well.
See new regression test.
=> fix: Enable copying into deltalake tables

pg_analytics/src/datafusion/datatype.rs, pg_analytics/src/hooks/select.rs, pg_analytics/test/expected/insert.out, pg_analytics/test/sql/insert.sql
- Closes #821 
Fixes an issue where values that were supposed to be NULL were returning as `0`. This was because we were not setting `tts_is_null` in the returned `TupleTableSlot`.
=> fix: Correctly `SELECT` NULL values 

pg_analytics/src/api/init.rs, pg_analytics/src/datafusion/catalog.rs, pg_analytics/src/datafusion/context.rs, pg_analytics/src/datafusion/directory.rs, pg_analytics/src/datafusion/schema.rs, pg_analytics/src/datafusion/table.rs, pg_analytics/src/errors.rs, pg_analytics/src/tableam/create.rs
- Closes #
Fixes a bug where VACUUMs would physically delete delta tables in other databases.
This bug was caused by the fact that all Postgres databases were stored in the same Datafusion catalog. When you're in a new Postgres database, Postgres is unaware of tables in other databases, so VACUUMs would think that these other tables were stale and delete them.
Created a new catalog per Postgres database.
=> fix: New catalog for every database

Cargo.lock, pg_analytics/Cargo.toml
- Closes #
Now that delta-rs 0.17.0 is released, we don't need to rely on our fork anymore.
Added the `indexmap` dependency because `pg_bm25` uses an older version of `indexmap` that isn't compatible with the latest `delta-rs`.
=> chore: Upgrade to delta-rs 0.17.0

pg_analytics/src/datafusion/context.rs, pg_analytics/src/errors.rs, pg_analytics/test/runtests.sh
- Closes #831 
Throws an error if `pg_analytics` is not in `shared_preload_libraries`
```sql
pg_analytics=# select * from t;
ERROR:  Execution error: pg_analytics not found in shared_preload_libraries. Check your postgresql.conf file.
```
Should hopefully reduce user error.
Reads the `shared_preload_libraries` setting inside `init` and checks if `pg_analytics` is in there.
=> feat: Throw error if pg_analytics not in shared_preload_libraries

Cargo.lock, pg_analytics/src/tableam/scan.rs
- Closes #
Uses `PgMemoryContexts` instead of Postgres' memory context API, which provides some nice wrappers and type handling for us.
=> fix: Use `PgMemoryContexts`

pg_analytics/src/hooks/executor.rs, pg_analytics/tests/basic.rs
- Closes #829
Uses information from the `PlannedStmt` to get the relevant subquery for the executor hook on a multiline query.
=> fix: get the relevant substring for a multiline query

pg_bm25/src/api/search.rs, pg_bm25/src/postgres/build.rs, pg_bm25/tests/bm25_search.rs
- Closes #857
We're finding that UUIDs, even when not indexed with `pg_bm25`, are causing an error when present in the bm25 table.
Incorrect handling of non-indexable types like UUID.
Was able to reproduce in a new test, and the test now passes.
=> fix: Correct handling of non-indexable types, including UUID

.github/workflows/publish-paradedb.yml
- Closes #
We use this to deploy our Helm Charts. The code hasn't been updated in 2 years, and it's starting to throw deprecation warnings. So this swaps it to a fork that has kept up.
^
^
Tested here: https://github.com/paradedb/paradedb/actions/runs/7921383816/job/21626562793
=> chore: Upgrade `workflow-dispatch` to a version which isn't deprecated

pg_analytics/src/hooks/executor.rs, pg_analytics/src/hooks/mod.rs, pg_analytics/src/hooks/process.rs, pg_analytics/src/hooks/query.rs, pg_analytics/tests/basic.rs
- Closes #
#829 added support for multi-line queries but only for ones that hit the executor hook. We needed to apply the same fix to the process utility hook.
Introduced a new `current_query_string` function to `pg_sys::PlannedStmt`.
Added more tests involving multi line queries that hit both the executor and process utility hooks.
=> fix: Multi-line utility queries

pg_analytics/src/errors.rs, pg_analytics/src/hooks/alter.rs, pg_analytics/src/hooks/drop.rs, pg_analytics/src/hooks/executor.rs, pg_analytics/src/hooks/handler.rs, pg_analytics/src/hooks/mod.rs, pg_analytics/src/hooks/process.rs, pg_analytics/src/hooks/query.rs, pg_analytics/src/hooks/rename.rs, pg_analytics/src/hooks/truncate.rs, pg_analytics/src/hooks/vacuum.rs, pg_analytics/tests/basic.rs
- Closes #
Introduces a trait that adds the `is_column` method to `RelationData` and `List`, which removes the need to maintain a separate struct for this purpose.
This is just code cleanup and doesn't introduce any new functionality.
=> refactor: Change DeltaHandler struct to traits

pg_bm25/src/index/search.rs
for the reason that `vacuum full` follow the steps: Lock on the relation -> Create an empty storage file  -> Copy live tuples from current storage to new storage  -> Then free up the original storage -> Free up the lock -> for that when the process to `copy` it will re_index and run the but the index in tantivy side will run again, so this commit fix it by use `open_or_create` method instead
- Closes #816
more info 
```cli
#0  tantivy::core::index::IndexBuilder::create_in_dir<std::path::PathBuf> (self=..., 
directory_path=...)
at /home/hyi/.cargo/git/checkouts/tantivy-c35452d6cd96d777/e678820/src/core/index.rs:171
#1  0x0000ffff969496f0 in pg_bm25::index::search::SearchIndex::new (directory=..., fields=...)
at pg_bm25/src/index/search.rs:77
#2  0x0000ffff96990c54 in …
```
=> fix: bm25 index breaks VACUUM FULL

pg_analytics/src/datafusion/context.rs
- Closes #
Uses `c_char` instead of `i8` for `cast_mut_ptr`. `c_char` can be either `i8` or `u8` depending on the target platform: https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/std/os/raw/type.c_char.html
=> fix: `cast_mut_ptr` expects different types on arm/intel

pg_sparse/src/svector.c, pg_sparse/test/expected/serialize.out, pg_sparse/test/sql/serialize.sql
- Closes #838 
Fixes an issue where serializing/deserializing large vectors (len greater than `65536`) would result in dropped values.
User-reported issue.
Converted underlying `n_elem`, `dim`, and `unused` to `int32`.
Added a regression test.
=> fix: Serialize/deserialize large sparse vectors

pg_bm25/src/api/search.rs, pg_bm25/src/env.rs, pg_bm25/src/index/search.rs, pg_bm25/src/postgres/build.rs, pg_bm25/src/postgres/delete.rs, pg_bm25/src/postgres/insert.rs, pg_bm25/src/postgres/utils.rs, pg_bm25/src/writer/client.rs, pg_bm25/src/writer/index.rs, pg_bm25/src/writer/mod.rs, pg_bm25/tests/cleanup.rs
- Closes #870
- Closes #702
#870 describes ballooning memory usage when creating an index on large tables. This is because Postgres seems to want to wait until the end of the transaction to free the memory taken when we lookup `PgTupleDesc` for each row. By manually switching memory contexts and calling `reset()`, we force the memory to be freed. We've gone from a 2.5GB memory increase to no increase at all.
I've also changed the background writer to no longer keep writers in memory. There's an outstanding problem that we see when running the test suite around "too many open files". Dropping writers after commit/abort helps with this, and improves memory usage in the background process.
Previously, we also commit all the cached writers at the end of a transaction. This isn't correct with …
=> fix: Switch memory context during index creation, and delete old folders

.github/workflows/test-pg_bm25.yml, pg_bm25/sql/_bootstrap.sql, pg_bm25/src/api/search.rs, pg_bm25/src/index/score.rs, pg_bm25/src/index/search.rs, pg_bm25/src/index/state.rs, pg_bm25/src/writer/directory.rs, pg_bm25/src/writer/index.rs, pg_bm25/tests/bm25_search.rs
Fixing a few small issues with `rank_hybrid`, as well as handling a unusual deletion case we're seeing in CI.
- `rank_hybrid` was not previously working with schemas not on the `search_path`.
- `rank_hybrid` was returning stale rows when used outside of Postgres index scan, because we couldn't rely on Postgres filtering.
- Deleting Tantivy files occasionally fails, because we try to delete a file that doesn't exist. We now just check for a `NotFound` error, and ignore it if we see it.
New test to confirm `rank_hybrid` results.
=> fix: Dedup search, add schema to hybrid func, fix delete error

.github/workflows/test-pg_analytics.yml, .github/workflows/test-pg_bm25.yml
- Closes #
Fixes this: https://github.com/paradedb/paradedb/actions/runs/8146266846/job/22264945717?pr=938
=> fix: Run cargo clean before packaging, to avoid running out of space on device

pg_bm25/README.md
None.
There is a hyperlink error in the [pg_bm25](https://github.com/paradedb/paradedb/blob/dev/pg_bm25/README.md) `README.md`, it points to the document of `localhost:3000`.
I fixed it to point to the correct page. Let me know if the link still wrong.
=> docs: fix document link typo

pg_analytics/src/hooks/executor.rs, pg_analytics/src/hooks/process.rs, pg_analytics/src/hooks/query.rs, pg_analytics/tests/basic.rs
- Closes #931 
Fixes a bug where `CREATE TABLE heap AS SELECT * FROM parquet` was not working, where `heap` is a heap table and `parquet` is a parquet table.
User-reported bug
We were intercepting this command with our hooks, this PR lets it pass through to the table access method.
Added a test
=> fix: Create heap table from parquet table

Cargo.lock, pg_analytics/Cargo.toml, pg_analytics/src/hooks/executor.rs, pg_analytics/src/types/array.rs, pg_analytics/src/types/datatype.rs, pg_analytics/src/types/date.rs, pg_analytics/src/types/datum.rs, pg_analytics/src/types/mod.rs, pg_analytics/src/types/numeric.rs, pg_analytics/src/types/time.rs, pg_analytics/src/types/timestamp.rs, pg_analytics/tests/primitives.rs, pg_analytics/tests/time.rs
- Closes #905 
Parquet tables now support `time` and `time(6)` types.
More type coverage.
Forked `delta-rs` to support the Time primitive type, and added support for `Time64` on our end. Here's the fork we're using: https://github.com/paradedb/delta-rs/tree/feat/time
See new tests.
=> feat: Support time type

pg_analytics/src/errors.rs, pg_analytics/src/tableam/insert.rs, pg_analytics/tests/insert.rs
- Closes #973 
Shows users an error if they try to `INSERT ... ON CONFLICT`.
`INSERT ... ON CONFLICT` is not implemented. This PR makes it so that users see an error instead of an incorrect INSERT.
=> fix: Disable speculative insert

Cargo.lock, docs/search/full-text/bm25.mdx, pg_bm25/Cargo.toml, pg_bm25/sql/_bootstrap.sql, pg_bm25/src/api/operator.rs, pg_bm25/src/api/search.rs, pg_bm25/src/index/score.rs, pg_bm25/src/index/search.rs, pg_bm25/src/index/state.rs, pg_bm25/src/postgres/scan.rs, pg_bm25/src/schema/config.rs, pg_bm25/tests/bm25_search.rs, pg_bm25/tests/icu.rs, pg_bm25/tests/lindera.rs, pg_bm25/tests/query.rs, pg_bm25/tests/quickstart.rs, pg_bm25/tests/search_config.rs
This is an important PR for `pg_bm25` performance. We now use Tantivy's multi-threaded searcher for 2x faster searches, and we add an option for stable ordering of results. By default, results are unstable for the fastest possible performance.
With testing `pg_search` on over a billion rows, I've been able to identify performance bottlenecks that we start to see at scale. Before this PR, searches over 1.18 billion rows took 30 to 40 seconds. These are now around 200ms for warm searches.
Added a `stable_sort` parameter to search which controls whether we use deterministic ordering (based on key field) for search results.
For multithreading, each connection now stores a static `Executor` which is passed to searches. 
All tests now use `stable_sort`.
=> feat: Optional stable sorting and multithreaded search

docs/deploy/aws.mdx, docs/deploy/gcp.mdx, docs/introduction.mdx, pg_bm25/README.md, pg_sparse/README.md
- Closes # part of #992 
We were missing a variety of updates for `docker run` since Bitnami. This is now fixed.
=> docs: Properly update docker run everywhere

shared/src/github.rs
- Closes #
The shared `paradedb.help` function only creates if it doesn't exist, so `pg_search` and `pg_analytics` don't conflict.
=> fix: `paradedb.help` already installed won't cause extension install to fail

pg_analytics/benchmarks/clickbench/benchmark.sh, pg_search/benchmarks/benchmark-pg_search.sh
- Closes #
Since a recent PR, I suspect the one adding `paradedb.help`, our benchmarks started failing. This PR does two things:
Example of a failed run: https://github.com/paradedb/paradedb/actions/runs/8364062048/job/22898484924
^
^
^
=> ci: Print docker logs when running benchmarks

.github/workflows/benchmark-pg_analytics.yml, .github/workflows/benchmark-pg_search.yml
- Closes #
We were getting a bunch of pings as part of development. This should fix it.
Avoid noise
Check the branch
Check CI
=> fix: Only ping Slack for failed runs on non-PR branches

Cargo.lock, pg_analytics/Cargo.toml, pg_search/Cargo.toml, shared/Cargo.toml, shared/src/telemetry/bgworker.rs, shared/src/telemetry/controller.rs, shared/src/telemetry/event.rs, shared/src/telemetry/mod.rs, shared/src/telemetry/postgres.rs, shared/src/telemetry/posthog.rs
Using the `os_info` crate to gather some information about operating system + processor during the deployment call. The data looks like this:
```json
{
"arch": "arm64",
"extension_name": "pg_search",
"extension_version": "0.5.11",
"os_type": "Mac OS",
"os_version": "13.5.0",
"postgres_version": "16.2",
"timestamp": {
"nanos_since_epoch": 721633000,
"secs_since_epoch": 1711410121
}
}
```
I've derived `Serialize` for `TelemetryEvent` to simplify the implementation. I also removed the associated `Error` type from many of the Telemetry traits, and just baked in the `TelemetryError`. The abstraction was unnecessary.
=> chore: add os + version details to telemetry calls

Cargo.lock, pg_analytics/Cargo.toml, pg_search/Cargo.toml
Benchmarks were failing due to an update to zstd-rs (see: https://github.com/gyscos/zstd-rs/issues/268). Freezing zstd-sys to 2.0.9 for now until a fix is made upstream.
=> fix: freeze zstd-sys version and update cargo dependencies

Cargo.lock, pg_analytics/Cargo.toml, pg_analytics/src/hooks/process.rs, pg_analytics/tests/vacuum.rs
- Closes #793
- Closes #964
Vacuums regressed, and now they’re back.
^^
We were using whether the AST could be parsed to decide whether to use our custom processing hooks, but sqlparser doesn’t support VACUUM. Now, the AST parse-ability only matters for the hooks that depend on the AST, and then we continue on to the `prev_hook` anyway.
=> fix: vacuums work again

pg_analytics/src/tableam/insert.rs, pg_search/benchmarks/README.md
- Closes #1000 
We are seeing very high memory usage when inserting large numbers of rows.
This ended up being similar to the memory issues we had `pg_search`. The culprit is `PgRelation::tuple_desc()`, which allocates memory that is not correctly freed when dropped. To circumvent, we have to do a bit of a hack with memory context switching.
The implementation in this PR is structured carefully. The can be no references to a `PgRelation` instances outside of the `switch_to` call, and you need to make sure to `reset` before and after.
=> fix: reset memory contexts during pg_analytics tuple_insert

.github/workflows/publish-github-release.yml
- Closes #N/A
The way we had our GitHub Release CI set up, it would start by incrementing the value stored in GitHub Actions Variables, and then release. Since values can't be negative, it meant when we did a new minor/major release, it would start with micro version `1` since we couldn't go below 0. This fixes this and enables us to have versions like `v0.6.0`, which is the standard in the industry.
^
We store the next version to release, instead of the past version to release.
Tested by triggering a `workflow_dispatch`
=> feat: Make GitHub Releases be 0-indexed

pg_analytics/tests/vacuum.rs
Vacuum tests were occasionally failing. I think it's because it wasn't checking only the relevant test db. This should hopefully fix it.
=> fix: check only the relevant folder for vacuum tests

.github/workflows/test-pg_analytics.yml, .github/workflows/test-pg_search.yml
- Closes #N/A
We updated our deployment flow so that the version stored in GitHub Actions Variables is the upcoming release version, not the last release version, but I had forgotten to update the way we check for version equality in CI. This should fix it.
N/A
N/A
N/A
=> ci: Update the version checking step

pg_analytics/runtests.sh, pg_search/runtests.sh
- Closes #
Now that we renamed, we need to adjust our extension upgrade test for `pg_search`.
=> ci: Only upgrade pg_search from 0.6.0 onwards

pg_search/benchmarks/benchmark-pg_search.sh
- Closes #
The `pg_search` benchmarks were quite slow. This fixes that. The product is much more stable now, and there's no point in doing really small row counts.
=> ci: Only run benchmarks on 5M rows

pg_analytics/src/storage/metadata.rs
- Closes #
Fixes build issue, see https://doc.rust-lang.org/std/ffi/type.c_char.html#:~:text=Type%20Alias%20std%3A%3Affi%3A%3Ac_char&text=C's%20char%20type%20is%20completely,memory%20with%208%2Dbit%20bytes.
=> fix: Replace `i8` with `c_char`

pg_analytics/src/storage/metadata.rs
- Closes #
There was a slight bug in packaging `pg_analytics`, which this PR fixes. It will over-ride the `v0.6.0` release from last night, and be the proper `v0.6.0` release
=> fix: Prod Promotion v0.6.0

docker/docker-compose.yml, pg_analytics/src/lib.rs, pg_search/src/lib.rs
- Closes #
The retention PR caused a crash in the start of the Dockerfile. Reverting here, and once we bring it back let's add a test to make sure this does not happen again.
=> fix: Comment out retention as it causes crash

Cargo.lock, docs/analytics/limitations.mdx, pg_analytics/Cargo.toml, pg_analytics/src/datafusion/table.rs, pg_analytics/src/datafusion/udf.rs, pg_analytics/src/hooks/select.rs, pg_analytics/src/tableam/index.rs, pg_analytics/src/tableam/scan.rs, pg_analytics/src/types/array.rs, pg_analytics/src/types/datatype.rs, pg_analytics/src/types/datum.rs, pg_analytics/src/types/numeric.rs, pg_analytics/src/types/time.rs, pg_analytics/tests/primitives.rs
- Closes #1055 
Adds support for the `uuid` type
- We store the `uuid` type as a `String` in Datafusion. To convert back to Postgres, we first convert it into bytes and then to the `datum::Uuid` type
- Caught and fixed a bug with lossy data types in `SELECT`s where we were overriding the data types provided by `PgTupleDesc` with our own lossy converted types
Added test for UUID
=> feat: Support UUID

README.md, pg_analytics/src/lib.rs, pg_search/src/lib.rs, shared/src/telemetry/bgworker.rs, shared/src/telemetry/mod.rs
We had to comment out telemetry in #1049, as we weren't picking up the DATA_DIR env variable correctly. 
I also fixed the documentation for how to disable telemetry, and added some extra logging for when it is disabled.
Here, I'm just using `pgrx::pg_sys::DataDir` instead.
I've done a test publish to Docker Hub to confirm this works in a deployed docker image.
=> fix: re-enable telemetry with correct postgres data dir

.github/workflows/test-paradedb.yml, .prettierignore, docker/docker-compose.dev.yml
- Closes #N/A
Two weeks ago, we accidentally pushed a broken Dockerfile to prod. I realized we weren't testing for whether the image starts properly in CI, and took a note to add a test for it. This does that.
Make sure we don't push broken Dockerfiles
Grep the logs for ERROR
See CI
=> ci: Add test for whether the Dockerfile starts properly

shared/src/telemetry/bgworker.rs
Just moving a shutdown check to the beginning of the background worker.
While the GUC setting for telemetry (`paradedb.pg_analytics_telemetry` / `paradedb.pg_search_telemetry`) is a runtime-check, we also have the compile time `TELEMETRY` env var that controls whether telemetry ever happens. If the compile-time `TELEMETRY` is false, then telemetry should never work at runtime, so we might as well just shutdown the worker early.
Confirmed telemetry behavior with both `TELEMETRY=true/false`.
=> fix: shutdown telemetry worker early if TELEMETRY=false at compile time

pg_search/sql/_bootstrap.sql, pg_search/tests/bm25_search.rs, shared/src/fixtures/tables/simple_products.rs
Users reported issues using custom key field names with `rank_hybrid`.
In `minmax`, we return a `TableIterator`, which requires you to statically define the column names and types that you return. We have `"id"` there, and there's not much we can do about that, since we have to have something chosen at compile time.
Fortunately, because of all the funky "SQL-macro" stuff going on in `_bootstrap`, we can just alias the column there to whatever the user passed as `key_field`, so they won't feel any pain from `minmax`'s hard-coded columns.
Added a test for `key_field => 'custom_key_field'`.
=> fix: hardcoded column name in pg_search minmax function

cargo-paradedb/src/tables/mod.rs, pg_analytics/src/types/datatype.rs, pg_analytics/src/types/datum.rs
- Closes #994 
Speeds up any operations that use the table AM scans, including view creation, index creation, and moving data between tables. In my testing scans are 2-3x faster.
I noticed that table AM scans were slow. While reading the documentation, it recommends against using `ArrayIter` for performance reasons.
Use the `is_null` and `value` functions instead of `into_iter`.
All existing tests pass, no new tests needed.
=> fix: Speed up scans by not using `into_iter` when reading batches

Cargo.lock, pg_search/README.md, shared/Cargo.toml, shared/src/telemetry/bgworker.rs, shared/src/telemetry/controller.rs, shared/src/telemetry/event.rs, shared/src/telemetry/postgres.rs, shared/src/telemetry/posthog.rs
We had the wrong `extension_path` for both `pg_analytics` and `pg_search` in telemetry.
While fixing this, I added some extra logging, a `humansize` field for more readable sizes, and started logging the `POSTGRESQL_REPLICATION_MODE` env var.
It's unclear if all env vars propagate to the background worker, so we'll see if any data shows up for that in Posthog.
Confirmed events appear in Posthog.
=> fix: extension_path value in telemetry background worker

pg_analytics/src/types/datum.rs, pg_analytics/tests/primitives.rs, pg_analytics/tests/transaction.rs
- Closes #1087 
Fixes an issue where `uint` DataFusion types were not handled.
Even though Postgres has no `uint` type, some UDFs in datafusion can return a `uint`, which we need to handle and coerce to the correct Postgres integer type.
All `uint` datafusion types are cast to `i64` and then converted to the appropriate Postgres datum.
Added a test
=> fix: `uint` conversion error

.github/workflows/test-pg_search.yml, docker/Dockerfile
- Closes #N/A
We deprecated `pg_sparse`, but I had forgotten to increase `pgvector` to `v0.7.0`, which is the new version containing sparse vectors.
^
^
^
=> chore: Upgrade pgvector version

docs/search/full-text/complex.mdx, pg_search/src/api/index.rs, pg_search/src/query/mod.rs, pg_search/src/schema/mod.rs, pg_search/tests/query.rs
A user on Slack mentioned that we no longer have a way to search across all fields, ever since we switched to the Tantivy "lenient" query parser and introduced advanced queries.
This PR adds a default behavior to `paradedb.term`, emulating the behavior of "lenient" queries that didn't specify a field. If you omit `field` in `paradedb.term`, it'll search across all indexed fields.
Added a test for `term` without a `field` param.
=> feat: Make `paradedb.term` field optional to allow searching all fields

.github/workflows/publish-pg_search.yml
- Closes #1117 
We had forgotten to rename this specific reference. This fixes it.
Reported by user
N/A
N/A
=> fix: Rename missing bm25 reference to search

pg_analytics/src/federation/handler.rs, pg_analytics/src/hooks/executor.rs, pg_analytics/src/hooks/explain.rs, pg_analytics/src/hooks/mod.rs, pg_analytics/src/hooks/process.rs, pg_analytics/src/hooks/select.rs, pg_analytics/src/tableam/update.rs, pg_analytics/tests/explain.rs, shared/src/fixtures/db.rs
- Closes #1034
Implement `EXPLAIN` for Datafusion plans.
Postgres' built-in implementation of `EXPLAIN` doesn't really make sense for queries that are executed in Datafusion, so we show the Datafusion plan instead for these queries.
Intercept the `ExplainStmt` in the utility process handler and check if it is going to be executed by Datafusion, then proceed to explain the statement.
Check the outputs of `EXPLAIN` on parquet, heap, and federated queries.
=> feat: explain

pg_search/sql/_bootstrap.sql, pg_search/tests/index_config.rs
- Closes #912
Throw exception for duplicate index instead of dropping.
Shouldn’t automatically drop indices.
Check if index schema exists and abort if it does.
Check that trying to create a duplicate index errors out.
=> fix: throw exception for duplicate index instead of drop_bm25

docs/analytics/object_stores/local.mdx
- Closes #
There were some copy paste typos for the `pg_lakehouse` docs.
=> docs: Fix typos

docker/Dockerfile
- Closes #N/A
This was missing in our Dockerfile, causing performance issues.
^
^
=> fix: Add `pg_lakehouse` to shared_preload

pg_lakehouse/src/fdw/gcs.rs, pg_lakehouse/src/fdw/options.rs, pg_lakehouse/src/fdw/s3.rs
- Closes #
We don't need to set `root` in the builder. If we do, the `root` will be repeated in the full path.
I tested putting a parquet file in nested folders in S3/Azure and noticed that setting `root` caused queries to fail.
=> fix: Don't double set the root path

cargo-paradedb/src/bench_hits.rs, docker/Dockerfile
- Closes #895 
It's been released for a while, so we should probably upgrade. I also make the benchmarks run on every change to the extension to properly catch issues moving forward.
Stay current
Use `bookworm` and debian-12` for the Postgres and Bitnami Postgres containers respectively
Tested locally that it still builds, runs, and the extensions work properly
=> feat: Upgrade to Debian 12

.github/workflows/benchmark-pg_lakehouse.yml, .github/workflows/publish-pg_lakehouse.yml, .github/workflows/test-pg_lakehouse.yml, pg_lakehouse/src/fdw/base.rs, pg_lakehouse/src/fdw/gcs.rs, pg_lakehouse/src/fdw/local.rs, pg_lakehouse/src/fdw/s3.rs, pg_lakehouse/src/hooks/executor.rs
- Closes #
`begin_scan` was calling `execute_logical_plan`, which was adding 100-200ms latency to queries. This has been moved to `iter_scan`, so it only fires when we call back to the FDW and not on every query.
Performance - now we match DataFusion benchmarks exactly.
=> fix: Remove redundant DataFusion calls

Cargo.lock, pg_lakehouse/Cargo.toml, pg_lakehouse/README.md, pg_lakehouse/src/schema/attribute.rs, pg_lakehouse/src/schema/cell.rs, pg_lakehouse/tests/fixtures/mod.rs, pg_lakehouse/tests/scan.rs, shared/Cargo.toml, shared/src/fixtures/arrow.rs, shared/src/fixtures/db.rs, shared/src/fixtures/mod.rs, shared/src/fixtures/tables/nyc_trips.rs
Adding a test for a "roundtrip" of creating a `RecordBatch` in memory, storing in localstack s3, retrieving the `RecordBatch`, and comparing against original. 
Also made sure that the BYTEA type is supported by DataType::Binary.
Testing as many supported datatypes as possible, and adding tooling to dynamically retrieve record batches in our test environment without having to manually specify the `RecordBatch` schema.
=> feat: roundtrip pg_lakehouse test + fetch_recordbatch helper

docs/analytics/object_stores/azblob.mdx, docs/analytics/object_stores/azdls.mdx, docs/analytics/object_stores/gcs.mdx, docs/analytics/object_stores/s3.mdx
- Closes #
In the docs, the "required" flag was missing from `current_user`.
=> docs: Make `current_user` required

.github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml
- Closes #N/A (partial #1116)
An increasing number of our users have been requesting prebuilt binaries for their operating system. Notably, we weren't sharing prebuilt binaries for Debian 11, which is what most upstream `postgres` Docker images, like the PostGIS ones, are based on. That's a pretty big limitation for adoption. This PR adds support for building in containers on GHA runners, and adds support for Debian 11 and Debian 12 in addition to Ubuntu 22.04. Debian 12 is the base for Ubuntu 22.04, but we've seen some issues with using the Ubuntu version, so I figured we'd just publish everything separately for maximum compatibility.
In a subsequent PR, I'll add support for Red Hat UBI 8 & 9, which should unblock a lot more users, and clean things up a bit further in our CI.
Expand …
=> feat: Also deploy ParadeDB extensions on Debian 11 and 12

.github/workflows/benchmark-pg_lakehouse.yml, .github/workflows/publish-pg_lakehouse.yml, .github/workflows/test-pg_lakehouse.yml, docker/Dockerfile
- Closes #N/A
This enables maximum performance for `pg_lakehouse` inside the Dockerfile. We were already doing this when deploying individual extensions in CI.
^
^
^
=> fix: Make Dockerfile also use Rust nightly

.github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml
- Closes #
This was preventing the `upload_url` from being retrieved
=> fix: Add one more missing dependency to Debian deployments

Cargo.lock, pg_lakehouse/Cargo.toml, pg_lakehouse/src/api/mod.rs, pg_lakehouse/src/datafusion/context.rs, pg_lakehouse/src/datafusion/schema.rs, pg_lakehouse/src/datafusion/session.rs, pg_lakehouse/src/fdw/azblob.rs, pg_lakehouse/src/fdw/azdls.rs, pg_lakehouse/src/fdw/base.rs, pg_lakehouse/src/fdw/gcs.rs, pg_lakehouse/src/fdw/local.rs, pg_lakehouse/src/fdw/s3.rs, pg_lakehouse/src/hooks/executor.rs, pg_lakehouse/src/hooks/mod.rs
- Closes #
We were using `panic!({:?})` instead of `panic!({})`, which means we were showing `Debug` instead of `Display` for error messages.
Show better error messages.
I also made `BaseFdw` functions async to bubble up the `task::block_on` calls.
=> fix: Display error messages correctly

.github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml
- Closes #N/A
We had some issue with building on the wrong architecture for our extensions, and Ubuntu images would get blocked at `tzdata` due to DEBIAN_FRONTEND not being set. For some reason, setting it via `export` does not work, it needs to be directly in the command.
^
^
Tested manually by adding a trigger to this branch
=> fix: Fix issue w/ Ubuntu publishing

.cargo/config.toml, .github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml
- Closes #N/A
Fix an issue where it would crash on `arm64` older CPUs. This happened since we switched to Depot, which uses a newer CPU.
Make sure it's compatible with all versions for our users.
Use `target-cpu=generic`
Needs testing
=> fix: Fix illegal instructions issue on `arm64` extensions

.cargo/config.toml, .github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml
=> fix: Properly set `generic` CPU for `arm` architecture during deployments

cargo-paradedb/README.md
- Closes #
The `cargo-paradedb` docs say that the hits benchmark downloads the full dataset, but that only happens if `-f` is passed in.
=> docs: Add -f option to cargo-paradedb

.github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml, .gitignore
- Closes #
There's been issues when users try to run the `amd64` binary on macOS ARM via Docker on an amd64 image
=> fix: Remove cpu=native on all OSes in CI

pg_lakehouse/README.md, pg_lakehouse/src/datafusion/catalog.rs, pg_lakehouse/src/datafusion/provider.rs, pg_lakehouse/src/datafusion/schema.rs, pg_lakehouse/src/fdw/handler.rs, pg_lakehouse/src/fdw/options.rs, pg_lakehouse/src/hooks/executor.rs, pg_lakehouse/src/hooks/explain.rs, pg_lakehouse/src/hooks/mod.rs, pg_lakehouse/src/hooks/process.rs, pg_lakehouse/src/hooks/query.rs, pg_lakehouse/tests/explain.rs, pg_lakehouse/tests/fixtures/mod.rs
- Closes #
Returns the correct DataFusion plan on `EXPLAIN` and `EXPLAIN ANALYZE`.
I ended up re-using the process utility hook from `pg_analytics`. While the FDW API does have an `explain` hook, this hook is meant to return the query plan if it were executed by the FDW. Since the executor hook intercepts the query before it reaches the FDW, using the process utility hook ensures that the correct plan is shown.
See tests.
=> fix: `EXPLAIN` and `EXPLAIN ANALYZE`

pg_lakehouse/src/datafusion/schema.rs
- Closes #1136
This PR addresses an issue where a panic inside a `Box::pin`-wrapped future would cause the `async_std` global executor to crash permanently.
`Box::pin` is a utility that allows for the creation of a pinned heap allocation. In Rust, pinning is used to prevent data from being moved, which is crucial for certain types of asynchronous programming where references must remain stable across await points.
When you create a future with `Box::pin`, it ensures that the future will stay at a fixed memory location. This is particularly important for self-referential structures or for async tasks that rely on consistent memory addresses.
`async_std` provides a global executor we use to run asynchronous tasks with `block_on`. If this executor crashes, there's no way to restart it, which …
=> fix: don't panic in Box::pin

pg_lakehouse/src/datafusion/format.rs, pg_lakehouse/src/fdw/azblob.rs, pg_lakehouse/src/fdw/azdls.rs, pg_lakehouse/src/fdw/gcs.rs, pg_lakehouse/src/fdw/options.rs, pg_lakehouse/src/fdw/s3.rs
- Closes #
Two fixes for the Azure blob and ADLS Gen2 object stores:
- The `endpoint` server option for Azure should be required.
- We need to pass in `root` for the Azure builder, but only if it's a delta table.
Bug reported by user.
Haven't written a test due to our lack of Azure test fixture, but I uploaded a delta table to our Azure account and tested against it.
=> fix: Connect to tables in Azure

pg_lakehouse/src/datafusion/schema.rs, pg_lakehouse/tests/fixtures/mod.rs, pg_lakehouse/tests/scan.rs, pg_lakehouse/tests/table_names.rs, shared/src/fixtures/arrow.rs
- Closes #1250 
Fixes a bug where tables with names wrapped in quotes could not be queried.
Bug reported by user.
The error was coming from `PgRelation::open_with_name`. We just needed to wrap the table/schema names in quotes.
See tests
=> fix: Query tables with case-sensitive names

.github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml, Cargo.lock, README.md, docker/Dockerfile, docs/deploy/pg_lakehouse.mdx, docs/deploy/pg_search.mdx
- Closes (partial) #1116
We've got a few requests for publishing `.rpm` packages, so this does it for RHEL 9, which is the latest version of Red Hat Enterprise Linux. It's very close to working with RHEL 8, but I decided to stop there and we can bring it later as I've got some other priorities. I've done this at lost hours.
As part of this, I've also improved our test deployment workflow so we can be sure ahead of time that deployments will run properly.
Make it easier for our users to deploy!
Followed the instructions kindly provided by @Vonng from PigSTY!
See here for a test release I've created: https://github.com/paradedb/paradedb/releases/tag/v0.0.0
=> feat: Publish ParadeDB extensions for RHEL 9

Cargo.lock, pg_search/src/api/operator.rs, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/utils.rs, pg_search/tests/bm25_search.rs, pg_search/tests/quickstart.rs
- Closes #1256 
The index access method only inserts/commits when columns that have been indexed are modified. In my testing, this means that UPDATEs of non-indexed columns are over 100X faster!
```sql
\timing
CALL paradedb.create_bm25(
index_name => 'search_idx',
schema_name => 'public',
table_name => 'mock_items',
key_field => 'id',
text_fields => '{description: {tokenizer: {type: "en_stem"}}}'
);
-- BEFORE
pg_search=# update mock_items set category = 'Electronics 2' where description = 'Plastic Keyboard';
UPDATE 1
Time: 165.444 ms
-- AFTER
pg_search=# update mock_items set category = 'Electronics 2' where description = 'Plastic Keyboard';
UPDATE 1
Time: 1.463 ms
```
See Github issue.
1. Instead of passing in the wildcard `table_name.*` to the BM25 index, we pass in the names of the …
=> fix: Only index on fields passed into options

.github/workflows/test-paradedb.yml, .github/workflows/test-pg_lakehouse.yml, Cargo.lock, pg_lakehouse/Cargo.toml
- Closes #N/A
For some reason, locally on macOS it would be `v0.1.1`, and in Docker/Linux it would be `v0.1.2`, which would fail. We can upgrade to a new version later, but this should unblock our other PRs.
^
^
Test locally with both `v0.1.1` (works) and `v0.1.2` (fails) on macOS. CI should pass.
=> fix: Peg `deltalake-aws` to `v0.1.1`

CONTRIBUTING.md, docs/analytics/acceleration.mdx, docs/analytics/object_stores/unsupported.mdx, docs/analytics/quickstart.mdx, docs/analytics_deprecated/quickstart.mdx, docs/deploy/pg_analytics.mdx, docs/deploy/pg_lakehouse.mdx, docs/deploy/pg_search.mdx, docs/import.mdx, docs/search/quickstart.mdx, shared/src/github.rs
- Closes #N/A
The download link for `pg_analytics` was broken, since we stopped shipping post v0.6.1. The download link for `pg_search` and `pg_lakehouse` was also broken, since we changed the URL format. I've also added some clarifications.
No broken links!
N/A
N/A
=> docs: Fix broken download link

docs/deploy/pg_search.mdx, pg_search/README.md
- Closes #1270
Ubuntu 24.04 requires a different version of `libicu`, which our documentation did not specify. This fixes it.
We won't release pre-built binaries for Ubuntu 24.04 yet, so I've just updated the docs.
Avoid users getting confusing errors.
Just updated the docs.
No test needed.
=> docs: Update instructions for `libicu74` for Ubuntu 24.04

.github/workflows/benchmark-pg_lakehouse.yml, .github/workflows/benchmark-pg_search.yml, .github/workflows/lint-bash.yml, .github/workflows/lint-docker.yml, .github/workflows/lint-format.yml, .github/workflows/lint-markdown.yml, .github/workflows/lint-pr-title.yml, .github/workflows/lint-rust.yml, .github/workflows/lint-yaml.yml, .github/workflows/publish-github-release.yml, .github/workflows/publish-paradedb.yml, .github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml, .github/workflows/test-docs.yml, .github/workflows/test-paradedb.yml, .github/workflows/test-pg_lakehouse.yml, .github/workflows/test-pg_search.yml, Cargo.lock
- Closes #N/A
We started having a few CI runs fail due to instances running out of memory. I've realized our listing workflows can probably run on 2 vCPUs instead of 4, to save cost. And our large test workflows should run on 8 vCPUs instead of 4. While this double cost per run, the runs also take half the time, so it all roughly evens out and we don't get any failures/faster results.
^
^
All CI should pass
=> chore: Adjust CI instances size

pg_search/tests/bm25_search.rs
Removing the time dependency on our update test, which is proving flakey.
=> chore: use tantivy document counts to test column update behavior

Cargo.lock, pg_search/Cargo.toml, pg_search/src/api/index.rs, pg_search/src/api/operator.rs, pg_search/src/api/search.rs, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/fixtures/mod.rs, pg_search/src/index/score.rs, pg_search/src/index/search.rs, pg_search/src/index/state.rs, pg_search/src/lib.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/datetime.rs, pg_search/src/postgres/mod.rs, pg_search/src/postgres/scan.rs, pg_search/src/postgres/types.rs, pg_search/src/postgres/utils.rs, pg_search/src/schema/mod.rs, pg_search/src/writer/mod.rs, pg_search/tests/bm25_search.rs, pg_search/tests/key.rs, pg_search/tests/quickstart.rs, pg_search/tests/term.rs
- Closes #1164
Allow users to key on (almost) any type.
It is particularly important for types like UUID, but a user can also key on timestamp, float, etc (or boolean if they want to for some reason).
Introduce a wrapper type to serialize and compare all key types.
See tests/key.rs
=> feat: non-integer keys

.github/workflows/publish-pg_lakehouse.yml
- Closes #
Hotfix to the `v0.7.6` promotion, which fixes Ubuntu deployments for `pg_lakehouse`
=> feat: Prod Promotion - v0.7.6

README.md
- Closes #N/A
We're now at aorund 26K, but we'll just track via Docker pulls instead for simplicity, since it updates automatically.
More accurate info. Docker pulls and self-hosted deploys are independent, but the idea here is not to provide all our user metrics but just give an estimate of usage, which the Docker Pulls does better.
N/A
N/A
=> chore: Remove outdated `pg_search` deployment

README.md, docker/01_bootstrap.sh, docker/Dockerfile
- Closes #890 (as won't fix)
Sister PR: https://github.com/paradedb/helm-charts/pull/97
We added `pg_cron` at a time when we expected people to do a lot of data transformation between row-oriented and column-oriented tables. We no longer plan to support this workload, and we haven't seen any demand for `pg_cron`, so I'm going to remove it in the meantime.
Remove bloat/room for problems.
N/A
N/A
=> chore: Remove pg_cron

.github/workflows/benchmark-pg_lakehouse.yml, .github/workflows/publish-pg_lakehouse.yml, .github/workflows/test-pg_lakehouse.yml, docker/Dockerfile
- Closes #N/A
This is no longer needed now that we've moved from DataFusion to DuckDB
Cleaner
N/A
N/A
=> chore: Remove Rust Nightly

docs/search/full-text/bm25.mdx, pg_lakehouse/tests/fixtures/mod.rs, pg_search/src/postgres/types.rs, pg_search/src/postgres/utils.rs, pg_search/tests/bm25_search.rs
- Closes #1205
When creating a BM25 index on a table with JSON fields containing arrays, the following error was encountered:
```rust
WriterIndexError(SerdeJsonError(Error("invalid type: sequence, expected a map", line: 1, column: 0)))
```
This issue arises during the serialization/deserialization process, preventing proper indexing of JSON arrays.
The fix involves adjusting the serialization/deserialization logic to handle JSON arrays correctly. This change ensures that JSON arrays are flattened and each element is indexed as an individual value.
Added tests to verify the correct behavior of JSON array flattening and indexing:
•	`json_array_flattening`: Tests that individual elements in a JSON array can be searched.
•	`json_array_multiple_documents`: Ensures that documents with JSON …
=> fix: Support JSON top-level arrays in pg_search

Cargo.lock, pg_search/src/index/search.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/utils.rs, pg_search/src/writer/mod.rs, pg_search/tests/index_config.rs
- Closes #1307 
Fixes a crash that occurred when BM25 indexes were created over NULL values.
User reported bug.
In order to handle null values on index build/insert, you need to make use of the `isnull: *mut bool` argument provided by the index access method.
When a null value is encountered, we simply skip it (i.e don't add it to the Tantivy document).
See the `null_values` test.
=> fix: Index on null values

docs/search/full-text/complex.mdx, pg_search/src/api/index.rs, pg_search/src/query/mod.rs, pg_search/tests/bm25_search.rs, pg_search/tests/query.rs
- Closes #
The docs say that the defaults for `fuzzy_term` are `transpose_cost_one = true`, `distance = 2`, and `prefix = true`. But our actual defaults were `transpose_cost_one = false`, `distance = 1`, and `prefix = false`. This was causing confusion.
=> fix: `fuzzy_term` defaults

pg_search/src/bootstrap/create_bm25.rs, pg_search/tests/index_config.rs
- Closes #
Fixes a user-reported issue that indexing on case sensitive columns no longer works.
In the BM25 creation SQL, we need to wrap column names in quotes to preserve casing.
See added test.
=> fix: BM25 indexing on case sensitive columns

pg_lakehouse/src/hooks/executor.rs, pg_lakehouse/tests/scan.rs
- Closes #1332 
Fixes a bug where creating a heap table from a foreign parquet table was broken.
See GH issue.
Make sure that `CREATE` statements are not sent to the executor hook.
See added test
=> fix: `CREATE TABLE` from foreign table

.github/workflows/publish-paradedb.yml
- Closes #
We're starting to build ParadeDB Enterprise, which is hosted in a closed-source repo named `paradedb/paradedb-enterprise`. This CI trigger will start a promotion, which needs to be manually rebased, for every `main` promotion, so that we can keep versions in-sync.
^
Simply trigger a PR creation.
See here for successful test: https://github.com/paradedb/paradedb/actions/runs/9848971656/job/27191894725
=> chore: Create trigger from open-source to closed-source

.github/workflows/benchmark-pg_lakehouse.yml, .github/workflows/benchmark-pg_search.yml, .github/workflows/lint-docker.yml, .github/workflows/lint-yaml.yml, .github/workflows/test-docs.yml, .github/workflows/test-paradedb.yml, .github/workflows/test-pg_lakehouse.yml, .github/workflows/test-pg_search.yml, README.md, pg_lakehouse/README.md, pg_search/README.md
- Closes #N/A
While looking to configure telemetry on `pg_lakehouse`, I noticed a few things were missing to tell users to remove it, and to adjust the README to be similar structure as the `pg_search` one.
N/A
N/A
N/A
=> chore: Add missing details to `pg_lakehouse` README

.github/workflows/benchmark-pg_lakehouse.yml, .github/workflows/benchmark-pg_search.yml, .github/workflows/lint-bash.yml, .github/workflows/lint-docker.yml, .github/workflows/lint-format.yml, .github/workflows/lint-markdown.yml, .github/workflows/lint-pr-title.yml, .github/workflows/lint-rust.yml, .github/workflows/lint-yaml.yml, .github/workflows/publish-github-release.yml, .github/workflows/publish-paradedb.yml, .github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml, .github/workflows/test-docs.yml, .github/workflows/test-paradedb.yml, .github/workflows/test-pg_lakehouse.yml, .github/workflows/test-pg_search.yml
- Closes #1328 
This PR adds support for publishing binaries for Ubuntu 24.04 for our extensions.
Easier setup for our users
Simply add a new container image as part of our build matrix.
=> feat: Add support for publishing Ubuntu 24.04

.cargo/config.toml, .github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml, THANKYOU.md, pg_lakehouse/README.md
- Closes #N/A
This was pointed out by someone on HackerNews -- we had forgotten to update some DataFusion references.
=> chore: Remove outdated references to DataFusion

docker/Dockerfile
- Closes part of #1323
We were missing a permission to write to DuckDB internally.
N/A
N/A
Needs testing
=> fix: Chown duckdb inside the Dockerfile

docker/Dockerfile
- Closes #N/A
There were a few security warnings in our Docker, and I realized they were due to the packages we install in the old way we did telemetry. We no longer need these packages, so we should remove them no matter what. This should also clear up our security warnings.
^
N/A
See CI
=> chore: Remove unneeded dependencies

.github/workflows/publish-paradedb.yml, .github/workflows/publish-pg_lakehouse.yml, .github/workflows/publish-pg_search.yml
- Closes #N/A
This PR uses: https://github.com/actions/attest-build-provenance to sign our builds generated from our CI. This is increasingly required by organizations who follow the SBOM approach to sourcing software.
^
^
See the test run here: https://github.com/paradedb/paradedb/actions/runs/9979512112/job/27578778868?pr=1391
=> ci: Add build provenance attestation

pg_search/src/bootstrap/create_bm25.rs, pg_search/tests/bm25_search.rs
- Closes #1012
support partial index for bm25
just pass where conditions, and finally index_build_range_scan should handle this.
```sql
CALL paradedb.create_bm25_test_table(
schema_name => 'public',
table_name => 'mock_items'
);
CALL paradedb.create_bm25(
index_name => 'search_idx2',
schema_name => 'public',
table_name => 'mock_items',
key_field => 'id',
text_fields => '{description: {tokenizer: {type: "en_stem"}}, category: {}}',
numeric_fields => '{rating: {}}',
predicates => 'category = ''Electronics'''
);
SELECT description, rating, category
FROM search_idx2.search(
'rating:>2',
limit_rows => 20
);
```
=> feat: support partial index for bm25

pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/search.rs, pg_search/tests/index_config.rs
- Closes #1331 
Postgres truncates identifiers to 63 characters. Because `create_bm25` appends `_bm25_index` to the index name, we should truncate the index name to 52 characters to account for the `_bm25_index` suffix.
See user-reported issue.
Added test for truncation.
=> fix: Don't allow index names that are too long

docs/search/full-text/aggregations.mdx, docs/search/full-text/index.mdx
- Closes #
I read through our BM25 index creation docs and realized that many sections are unclear/lack examples. Additionally, some things like fast fields or the fact that normalizers are only useful for fast fields are not documented at all. Finally, we were missing documentation for the new partial indexing feature.
Better docs.
=> docs: Improve BM25 index documentation

cargo-paradedb/src/subcommand.rs, docs/search/full-text/aggregations.mdx, docs/search/full-text/bm25.mdx, docs/search/full-text/complex.mdx, docs/search/full-text/index.mdx, docs/search/quickstart.mdx, pg_search/README.md, pg_search/src/api/config.rs, pg_search/src/api/mod.rs, pg_search/src/bootstrap/create_bm25.rs, pg_search/tests/bm25_search.rs, pg_search/tests/icu.rs, pg_search/tests/index_config.rs, pg_search/tests/key.rs, pg_search/tests/lindera.rs, pg_search/tests/quickstart.rs, pg_search/tests/range.rs, pg_search/tests/replication.rs, pg_search/tests/search_config.rs, pg_search/tests/stemmer.rs, pg_search/tests/term.rs, shared/src/fixtures/tables/simple_products.rs, shared/src/sql/index_setup.sql
- Closes #
Introduces two new functions, `paradedb.field` and `paradedb.tokenizer`, that generate the JSON configuration options passed into `create_bm25`. This makes configuration options easier to document and removes the need for the user to format JSON themselves. Support for the old JSON5 string syntax has been preserved for backward compatibility.
```sql
-- These two queries are equivalent
-- BEFORE
CALL paradedb.create_bm25(
index_name => 'search_idx',
table_name => 'mock_items',
key_field => 'id',
text_fields => '{description: {} category: {}}'
);
-- AFTER
CALL paradedb.create_bm25(
index_name => 'search_idx',
table_name => 'mock_items',
key_field => 'id',
text_fields => paradedb.field('description') || paradedb.field('category')
);
--Nested JSON for tokenizers can be constructed …
```
=> feat: Introduce functions to generate `_field` configurations

.github/workflows/test-pg_lakehouse.yml, .github/workflows/test-pg_search.yml, docs/search/full-text/index.mdx, pg_search/src/postgres/types.rs, pg_search/src/postgres/utils.rs, pg_search/tests/bm25_search.rs, shared/src/fixtures/tables/simple_products.rs
- Closes #1226 
We discovered today that you can add the same key with different values multiple times to the same Tantivy Document, and it'll be treated as an array: https://github.com/quickwit-oss/tantivy/issues/464.
This means that we should be able to index and search arrays of any type in pg_search (aside from JSON arrays, which I realized are still not supported).
As part of this I split json handling out of `try_from_datum_array`. Because both json and array types were being handled by this function, if the user tried to index a JSON array they would receive a cryptic error instead of one telling them that json arrays are not supported.
Support for more types.
See tests
=> feat: Support all types of arrays

pg_search/src/api/index.rs, pg_search/src/api/mod.rs, pg_search/src/api/operator.rs, pg_search/src/api/search.rs, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/env.rs, pg_search/src/fixtures/directory.rs, pg_search/src/fixtures/index.rs, pg_search/src/fixtures/mod.rs, pg_search/src/index/search.rs, pg_search/src/index/state.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/scan.rs, pg_search/src/postgres/vacuum.rs, pg_search/src/schema/config.rs, pg_search/src/writer/directory.rs, pg_search/tests/bm25_search.rs, shared/src/postgres/transaction.rs
`pg_basebackup` currently errors on a bm25 index:
```
pg_basebackup: error: backup failed: ERROR:  file name too long for tar format: "paradedb/pg_search/631368_index_config_bm25_index/tantivy/995cec7539024106b9b6f2f9e8c30776.fieldnorm"
```
We have dynamic-length path names because we create them using the user-defined `index_name`. We also add some characters to the path by putting everything in the `paradedb` folder.
Get rid of the `paradedb` folder, and use the index OID instead of the `index_name`. The max OID value is `4294967295`, so we can expect all created indexes to stay within the path length limit.
This causes a problem with our partial index feature, because the index relation is deleted automatically when you drop the indexed column. That means that we can't lookup the index …
=> fix: use fixed-length + oid-based paths for index storage

CONTRIBUTING.md
Closes: #1445
Adds a link to pre-commit.com in CONTRIBUTING.md
As per #1445 there is the possibility for confusion without such a link.
Trivial addition to markdown documentation.
N/a
=> feat(doc): Add link to pre-commit.com in CONTRIBUTING.md

.pre-commit-config.yaml
Closes #1446
Set `default_language_version`->`python` to `python3` instead of `python-3.11`
Pre-commit hooks break if (only) a newer version than `python-3.11` is installed.
See #1446. As per discussion in issue `python3` is probably the most maintainable value.
Trivial change to config file.
I manually verified that the pre-commit hooks still work by committing this change.
The hooks still work on my system before I uninstalled `python-3.11` and after.
=> fix: Set `default_language_version`->`python` to `python3` instead of `python-3.11`

pg_search/src/index/search.rs, pg_search/tests/replication.rs
`pg_basebackup` hasn't been working. We fixed a major issue with it in #1439, where the file paths generated by `pg_search` were too long for `pg_basebackup` to even run.
Now that its running, we're seeing a segmentation fault when trying to `.search` after completing the replication.
The segfault is caused by infinite recursion that occurs when the replica tries to read the serialized `SearchIndex` config from disk.
The root cause is that the `WriterDirectory` from the _source database_ is serialized and copied over to the _replica_ along with the `SearchIndex`. The `WriterDirectory`, however, contains an absolute file path referencing the _source database's_ file system.
This was repeatedly invalidating our in-memory `SearchIndex` cache, causing the replicate to recursively keep trying …
=> feat: support pg_basebackup

docker/docker-compose.dev.yml
- Closes #1449
Remove duplicate text "for production usage" from a comment.
Grammar.
Trivial text change to comment.
N/a
=> fix(comment): Remove duplicate text "for production usage".

pg_search/README.md
- Closes #1459
Change text "pg_lakehouse" to "pg_search".
This text appears to have been copied from the `pg_lakehouse` README to the `pg_search` one but never updated.
Trivial text change in README file
N/a
=> fix(doc): Change pg_lakehouse to pg_search.

pg_lakehouse/README.md, pg_search/README.md
- Closes #1456
Add instructions for Arch Linux to Development section of pg_search/README.md
I use Arch
Edited README
These steps allow me to successfully run `cargo build` in the `./pg_search` and `./pg_lakehouse` directories.
=> feat(doc): Add instructions for Arch Linux to Development section of pg_search and pg_lakehouse README files

docs/search/full-text/complex.mdx, pg_search/src/api/index.rs, pg_search/src/query/mod.rs, pg_search/tests/query.rs
- Closes #1442 
Adds `paradedb.exists`, which executes the Tantivy `ExistsQuery`.
See Github issue.
See `exists_query` test.
=> feat: Add `ExistsQuery`

.pre-commit-config.yaml
- Closes #
Allow passing pre-commit check when there exists no configuration for AWS credentials.
Programmers may not have set up AWS credentials. This helps them pass the pre-commit check.
=> chore: Allow missing keys in detect-aws-credentials

docs/analytics/import/delta.mdx, pg_lakehouse/tests/scan.rs
- Closes #1323 
NOTE: This is branched off #1436, which needs to be merged first!
The error was found to be associated with a typo in the Dockerfile for the `.duckdb` folder permission. This is fixed in my `cnpg-docker` branch, so it should be ready to go. This PR uncomments the test that was failing.
We want to support the extension, and have a user waiting for it.
^
See CI once we PR it against `dev`
=> fix: DuckDB Delta Lake Extension Autoloading

pg_lakehouse/src/fdw/trigger.rs, pg_lakehouse/tests/table_config.rs
- Closes #1476
hardcore the wrong alter statement
introduce `schema_name` to `construct_alter_table_statement`
Added tests in `pg_lakehouse/tests/table_config.rs`
=> fix: Update ALTER TABLE statement to include schema name in construct_alter_table_statement function

docs/search/full-text/complex.mdx, pg_search/README.md, pg_search/src/api/index.rs, pg_search/src/index/state.rs, pg_search/src/query/mod.rs, pg_search/tests/query.rs
- Closes #1172 
`MoreLikeThis` is a useful, missing query from Tantviy's library. It's a little more involved to implement, because a version of it requires looking up document by id to match against.
This PR implements and exposes `more_like_this` along with the other advanced queries.
Added test variants for each kind of `key_field`, as they all can be accepted on the `with_document_id` parameter.
=> feat: Expose more like this function

docs/search/full-text/complex.mdx
- Closes #1385
As described in #1385, there's a Tantivy-level limitation that prevents proper scoring with `TermSet` queries. This PR adds a documentation note about that.
=> chore: document scoring limitation for TermSet query

docs/search/full-text/index.mdx, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/writer/directory.rs, pg_search/tests/bm25_search.rs
- Closes #[633](https://github.com/paradedb/paradedb/issues/633)
Users have requested being able to see the size of their BM25 indexes.
This PR adds a method on the dynamic index schema to check the size.
Added a new test.
=> feat: add `index_size` method to get index directory size in bytes

docker/Dockerfile
- Closes #N/A
This fixes an issue where the user would not be able to install DuckDB extensions if not connected as superuser.
^
^
N/A
=> fix: Fix DuckDB permission in Dockerfile

docker/Dockerfile
- Closes #N/A
This fixes a bug, which was reported in Slack, that our Helm Chart is failing to launch due to UID configuration issue. We *need* to add a test for this to our CI, which will come in a separate PR. This is a hotfix PR to get the user unblocked.
^
Switch the postgres user uid to map what CNPG expects.
=> fix: Fix CNPG uid issue

.github/workflows/publish-github-release.yml, .github/workflows/test-pg_analytics.yml, .pre-commit-config.yaml
- Closes #
This removes the useless staging RC, which we were never using. We also comment out the version upgrade test, since this is an artifact of when the extension was in the same repository. I'm going to move the publishing over to the other repository.
=> chore: Remove staging RC

docs/search/full-text/index.mdx, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/postgres/build.rs, pg_search/tests/index_config.rs
- Closes #
Right now if a `key_field` is passed into `_fields`, the server throws an error and the user gets an opaque crash error. Now, we catch this in `create_bm25` and display a better error. I've also updated the docs and removed some accidentally committed debug statements.
See added test to `invalid_create_bm25`
=> fix: throw error if `key_field` is indexed

docker/Dockerfile
- Closes #N/A
I've been productionizing our K8s environment. There was an issue where we weren't bringing in correctly the `.sql` upgrade scripts from `pg_cron`. Somehow this caused no issue to our Dockerfile, but trips up the Helm chart. This PR fixes that.
It also upgrades our other Dockerfile dependencies.
The `pg_cron` issue was breaking our Helm chart.
Proper folder
Manually tested.
=> fix: Fix pg_cron scripts and upgrade extension dependencies

.github/workflows/test-paradedb.yml, docker/bootstrap.sh
- Closes #
This PR properly installs `pg_cron` and adds a CI check for failing runs when ERRORs are detected in the logs.
=> fix: Properly install `pg_cron` and add CI check

docs/replication/pg_search.mdx
- Closes #
Clarify what parts of the replication docs should not be run if `pg_search` is not used on the primary.
Reduce user error in replication setup.
=> docs: update replication docs

pg_search/README.md
- Closes #1495
Documents `DATABASE_URL` in `pg_search/README.md`
`DATABASE_URL` is necessary. I also wasn't immediately intuitive what I should set it to. 
Add text to `pg_search/README.md`
Work much better after setting this :P
=> feat(doc): Document `DATABASE_URL` in `pg_search/README.md`

pg_search/README.md
- Closes #
Add `pgvector` installation instructions to `pg_search/README.md`
`pgvector` needed for hybrid search unit tests
Add text to `pg_search/README.md`
=> docs: add `pgvector` installation instructions to `pg_search/README.md`

pg_search/src/api/search.rs, pg_search/src/index/state.rs
- Closes #
Replace `search_dedup` with `search`.
With #1535 , `search_dedup` is no longer necessary and adds extra query latency.
=> chore: remove `search_dedup`

.github/DISCUSSION_TEMPLATE/announcements.yml, .github/DISCUSSION_TEMPLATE/general.yml, .github/DISCUSSION_TEMPLATE/ideas.yml, .github/DISCUSSION_TEMPLATE/q-a.yml, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
- Closes #N/A
We've got much better issues since introducing templates, and today we got a very unclear discussion opened again. So I'm introducing templates for discussions too!
^
Followed the GitHub documentation
Not sure how to test this until it's merged, tbh.
=> chore: Add templates to GitHub Discussions

.github/workflows/lint-cargo-toml.yml, .pre-commit-config.yaml, Cargo.toml
- Closes #
When working on #1550 , I found the CI lacks the `Cargo.toml` formatting check.	
It is better to enforces a consistent formatting style across TOML files, making them easier to read and understand
- use `taplo-cli` to check and format `Cargo.toml` files
- add `taplo-cli` format to pre-commit
=> chore: Add toml formatting check

pg_search/src/api/search.rs, pg_search/src/index/score.rs, pg_search/src/index/state.rs, pg_search/src/schema/mod.rs
Through profiling, we've discovered performance bottlenecks stemming from fetching document fields from the documents returned by Tantivy queries.
This PR introduces an improved approach with fewer lookups, representing up to a 4x speedup in query times with large result sets.
We index the `key_field` and `ctid` for a row as `FAST` fields in Tantivy, and its cheaper to look these up in the fast field columnar store as the index segment is being read, as opposed to looking up the actual document from the resulting `DocAddress` set.
The easiest way to do this was in the Tantivy collector's `tweak_score` modifier, which builds a custom `Score` object that we currently use for stable sorting. The `Score` object now contains a `ctid` as well as a `key` and a `bm25` score.
The implementation in …
=> chore: rely on tweak_score fast_field lookups for key + ctid

docker/Dockerfile
- Closes #N/A
We needed to recursively set the permissions for installing DuckDB extensions as part of `pg_analytics`. This does it.
Create DuckDB extensions
Recursively set permissions
=> fix: Fix permissions for creating DuckDB extensions

cargo-paradedb/src/benchmark.rs, cargo-paradedb/src/cli.rs, cargo-paradedb/src/main.rs, cargo-paradedb/src/subcommand.rs
- Closes #279 
Adds the GIN index over tsvector to `cargo-paradedb`.
Commands:
```bash
cargo paradedb bench eslogs build-gin-index --limit 10
cargo paradedb bench eslogs query-gin-index --limit 10
```
In an upcoming blog post I'd like to bake tsvector against pg_search on various types of queries over 1 billion rows.
=> chore: add `GIN`/`tsvector` to benchmarks

Cargo.lock, cargo-paradedb/Cargo.toml, docs/changelog/0.9.2.mdx, docs/deploy/pg_analytics.mdx, docs/deploy/pg_search.mdx, docs/deploy/upgrading.mdx, docs/mint.json, pg_search/Cargo.toml, pg_search/sql/pg_search--0.9.1--0.9.2.sql, shared/Cargo.toml, tokenizers/Cargo.toml
- Closes #N/A
Update the changelog for `v0.9.2` of `pg_search` and `v0.1.1` of `pg_analytics`.
^
^
^
=> chore: Prepare v0.9.2

pg_search/src/postgres/utils.rs, pg_search/tests/documentation.rs
Our `ctid_satisfies_snapshot()` function was doing too much work, which would lead to a crash on `--enable-cassert` Postgres builds, and undefined behavior in production builds.
The long and short of it is that we were trying to construct a valid `pg_sys::HeapTupleData` on the stack, by calling into `pg_sys::PageGetItemId()` and then passing that to `pg_sys::PageGetItem()`.
In reality, the call to `pg_sys::heap_hot_search_buffer()` wants a pointer to an uninitialized (or zero'd) `pg_sys::HeapTupleData` so that it can fill in the fields properly.
Us trying to inspect the page item without knowing if we have a valid ctid is what was causing Postgres to crash in the case where the ctid being validated represents a HOT update.  There's probably plenty of other cases where it might have also …
=> fix: crashing bug in the `VisibilityChecker`. 

docs/ingest/import/spatial.mdx, docs/mint.json
- Closes #
Since `pg_analytics` supports the DuckDB-spatial extension, it should include documentation for its usage.
=> docs: Support DuckDB-spatial extension

docker/Dockerfile
This is an alternative implementation of #1554. It uses NPM to install `barman-cloud`. I tried to optimize this as much as possible with a thorough cleans up to reduce the size of the new layer to only `72MB`.
This can be further improved, but I don't think the cost/benefit curve is justified.
Closes #1554
Adds support for orchestration with CloudNative PG.
Installs `barman-cloud` via NPM on a clean `postgres` image that is then used as the base for the final layer. From a lot of trial and error this is one of the easiest ways producing the least size overhead.
Manual tests performed for the presence of Barman Cloud binaries and normal Postgres operation. I'll write a more elaborate test suite for Barman Cloud as part of the Helm Chart testing.
=> feat: Dockerfile with Barman Cloud for CloudNativePG support

Cargo.lock, docs/api-reference/full-text/bm25.mdx, pg_search/Cargo.toml, pg_search/src/api/operator.rs, pg_search/src/api/search.rs, pg_search/src/index/score.rs, pg_search/src/index/state.rs, pg_search/src/postgres/scan.rs, pg_search/tests/stable_sort.rs
n/a 
This adds a "fast path" for the `.search()` function for when there's no limit, no order by, and `stable_sort = false` (default is true!).  Cuts execution time nearly in half or even more for queries returning very large sets.
To speed things up
By detecting if we can do the fast path mode and using a custom tantivy `Collector` that streams results through a crossbeam **un**bounded channel.
The only case we can do this is with: 
```sql
SELECT * FROM idxname.search(query=>'...', stable_sort=>false)
```
But if the user doesn't care about scores or ordering and needs *all* the matching rows back, this is now ***much*** faster.
Current `dev` branch, using a 15G tantivy index with about 51M docs:
```sql
[v16.2][1802739] reddit=# select count(*) from idxreddit.search(query => 'body:(the)', …
```
=> feat:  add a "fast path" for the `.search(query=>'...', stable_sort=>false)` case

pg_search/src/bootstrap/create_bm25.rs, pg_search/tests/bm25_search.rs, pg_search/tests/index_config.rs
- Closes #1577
Add a `pg_catalog.pg_depend` entry for the created schema + index in a `create_bm25` call.
Although we encourage users to use `drop_bm25` to remove their `pg_search` indexes, its not too difficult to provide more broad support for cascading drops when using `DROP SCHEMA` and `DROP INDEX`.
We can just do this inside the implementation of `create_bm25`, where other dynamically-formatted SQL is run.
Two new tests added for dropping schema + index in each direction.
=> fix: and pg_depend entry for drop schema + index

pg_search/src/api/config.rs, pg_search/tests/search_config.rs, pg_search/tests/tokenize.rs, tokenizers/src/manager.rs
- Closes #
We expose `stem` as a tokenizer, but it's actually a token filter in Tantivy. This means that `stem` can be applied to any tokenizer and doesn't need to be a separate tokenizer. This PR introduces the `stemmer` option to `paradedb.tokenizer`. Now, like lowercasing, you can stem any tokenizer:
```sql
paradedb.tokenizer('default', stemmer => 'English');
paradedb.tokenizer('ngrams', stemmer => 'English', min_gram => 2, max_gram => 2, prefix_only => false);
```
More tokenizer configurability.
See added `language_stem_filter` test. The old `stem` tokenizer has been preserved for backward compatibility. Since I'm working on a docs PR, I'll just update the documentation there.
=> feat: make `stemmer` a filter

pg_search/src/postgres/build.rs, pg_search/src/postgres/scan.rs, pg_search/tests/documentation.rs, pg_search/tests/one_index.rs
n/a
Currently, pg_search allows for creating multiple `USING bm25` indexes per table.  This is problematic as Postgres isn't guaranteed to choose the index the user has specified with their `SELECT idxname.search()` query.  It may, in fact, choose any one of the other indexes.  When all costs are equal, it's not clear which index Postgres decides to choose, but the last one created seems to be the favorite.
Knowing this, the thought process then becomes "how do we allow multiple `USING bm25` indexes per table"?.  As things stand right now, I don't believe we can.
There's not enough context in the CREATE INDEX statement and the corresponding SELECT for postgres to choose a specific index, and even if we lie and open/query a different one (as we do now), we're past the point of being able …
=> feat: only allow one USING bm25 index per relation

shared/src/fixtures/db.rs
- Closes # n/a
The test framework should also report the underlying `sqlx` error when a query fails.
Makes debugging tests a lot easier
=> chore: teach test framework to report the underlying sqlx error

.github/workflows/test-pg_search.yml
- Closes #N/A
Eric's PR added new log printing to our CI, but on `dev` we skip some of the runs to avoid running the CI unnecessarily. You can see that here: https://github.com/paradedb/paradedb/actions/runs/10814680271/job/30001714090
This PR just adds the proper check.
No failed CI
^
Tested manually
=> fix: Fix CI with log printing

docs/api-reference/full-text/complex.mdx, pg_search/src/query/mod.rs, pg_search/tests/bm25_search.rs, pg_search/tests/query.rs
- Closes #
Now, the fuzzy term query defaults to using `FuzzyTermQuery::new` instead of `FuzzyTermQuery::new_prefix`.
`new_prefix` causes some strange matches. For instance, `zz` matches against the document `Chris`. I couldn't figure out why Tantivy considers this a match, and `FuzzyTermQuery::new` seems like a more appropriate default.
=> chore: change fuzzy term default to `prefix = false`

pg_search/tests/search_config.rs, tokenizers/src/manager.rs
- Closes #
- The lowercase filter can now be configured for the `raw` tokenizer
- The stemmer filter can be configured for language tokenizers (CJK, Lindera, and ICU)
This is a **breaking change** for the `raw` tokenizer. Since the lowercase filter defaults to `true`, by default the `raw` tokenizer now lowercases. This is consistent with the behavior of all other tokenizers.
This can be disabled with `paradedb.tokenizer('raw', lowercase => false)`. 
Make all tokenizers equally configurable.
=> fix: Add missing `stemmer` and `lowercase` filters to `raw` and language tokenizers

.github/workflows/publish-paradedb.yml, .github/workflows/test-paradedb.yml
- Closes #N/A
This workflow will trigger the Helm Chart Test workflow from `paradedb/helm-charts`. This will ensure that modifications to the Dockerfile here are also tested against our Helm Chart, to avoid regressions.
We need to:
^
^
See CI
=> ci: Add a test for the Helm chart

docs/mint.json
- Closes #N/A
Koala is used to traffic deanonymization, to help uncover leads that look at our documentation.
It was recommended by Mintlify, Mongo and a few others.
^
^
^
=> chore: Add Koala API Key

.github/workflows/test-paradedb.yml
- Closes #N/A
The token is not necessary since the repo is public. External contributors don't have access to GitHub Secrets, so this was blocking them. Should be fixed now. I've also updated to a more maintained version of the workflow.
=> chore: Remove the need on token for workflow dispatch

README.md, docker/Dockerfile, docker/bootstrap.sh, docs/deploy/extensions.mdx
- Closes https://github.com/paradedb/paradedb/issues/1461
Enable ParadeDB users to use PostGIS
See issue
I opted to use apt-get to install Postgis straight in the final docker image rather than build it in a builder image and copy the files like with other extensions. Main reason for this is that Postgis depends on a bunch of other packages which we would have to install manually if we wanted to compile it ourselves, see: https://packages.ubuntu.com/noble/postgresql-16-postgis-3
Added the SQL from https://github.com/postgis/docker-postgis/blob/master/initdb-postgis.sh to our `bootstrap.sh` to enable the extensions.
I ran the SQL from https://github.com/postgis/docker-postgis/blob/master/test/tests/postgis-basics/run.sh on the container to test basic functionality.
=> feat: Postgis support in ParadeDB

pg_search/src/postgres/types.rs, pg_search/tests/json.rs
- Closes # n/a
Fixes a segfault when trying to set a field of postgres type `::json` as a pg_search `json_fields` member.
When converting the Datums into owned values, we were treating a Datum of type `JSONOID` as if it were `JSONBOID` (notice the B).  These are not compatible.
Added a test to catch this.  Locally, my test doesn't crash but raises an internal Postgres ERROR, but the segfault is likely dependent on whatever the Datum points to in memory.
=> fix: segfault with fields of type '::json'

pg_search/src/api/index.rs, pg_search/src/query/mod.rs, pg_search/tests/query.rs
- Closes #
`fuzzy_phrase` is the first ParadeDB-specific query builder function. `fuzzy_phrase` matches documents according to the following criteria:
"Given a field and value, tokenize value and match documents if ANY ONE of the tokens are a `fuzzy_term` match against the document." 
This query demonstrates the usage of `fuzzy_phrase`:
```sql
SELECT description, rating, category 
FROM search_idx.search(query => paradedb.fuzzy_phrase(field => 'description', value => 'ruining shoez'));
description     | rating | category
---------------------+--------+----------
Sleek running shoes |      5 | Footwear
White jogging shoes |      3 | Footwear
Generic shoes       |      4 | Footwear
(3 rows)
```
`fuzzy_phrase` can also be configured to match documents if **ALL TOKENS** are a `fuzzy_term` …
=> feat: Introduce `fuzzy_phrase` query

.github/workflows/test-pg_search.yml
- Follow up https://github.com/paradedb/paradedb/pull/1655
=> fix: Dynamically determine pgrx version failure when pushing to dev

docs/api-reference/full-text/conjunction.mdx, docs/api-reference/full-text/lenient_parsing.mdx, docs/api-reference/full-text/overview.mdx, pg_search/src/bootstrap/format.rs, pg_search/src/index/search.rs, pg_search/src/index/state.rs, pg_search/src/query/mod.rs, pg_search/src/schema/config.rs, pg_search/tests/query.rs
- Closes #1112 
introduce `lenient_parsing: Option<bool>` and `conjunction_mode: Option<bool>` in `SearchConfig`
see `lenient_config_search` and `conjunction_config_search` in `tests/query.rs`
=> feat: adding lenient and conjuction configs

pg_search/src/bootstrap/create_bm25.rs, pg_search/src/lib.rs
- Closes #
This ensures these blocks will be emitted in the generated extension schema after the object(s) they themselves depend on.
It's a little unclear to me if these blocks could be emitted prior to the objects they depend on during pgrx's schema generation.  Now we define their dependency relationships explicitly.
This hasn't been a problem, and maybe never would be one, but pgrx's schema generator isn't deterministic along the edges (that's another issue!), so making sure these blocks are linked up correctly is *probably* important.
=> chore: assign `requires = []` arrays to `extension_sql!()` usages

docs/api-reference/faceting/metric.mdx
closes #1547
Short doc entry for cardinality, based on Tantivy's docs added here:
https://github.com/quickwit-oss/tantivy/pull/2446/files
This new feature is limited to enterprise ParadeDB, along with the rest of aggregation queries.
=> chore: add docs entry for cardinality aggregation

pg_search/src/lib.rs
- Closes #
Introduces a check for whether the extension has been added in `pg_init`. Now when the extension is missing an error is thrown at `CREATE EXTENSION` time.
```sql
CREATE EXTENSION pg_search;
ERROR:  pg_search must be loaded via shared_preload_libraries. Add 'pg_search' to the shared_preload_libraries configuration in the postgresql.conf file.
```
Reduces user error.
See similar implementation by Citus: https://github.com/citusdata/citus/blob/f6959715dc49404510f2f3340b9719b33ddd152b/src/backend/distributed/shared_library_init.c#L392
=> chore: check `shared_preload_libraries` in `pg_init`

.github/workflows/assign-github-issue.yml, .github/workflows/take.yml, CONTRIBUTING.md
- Closes #1657 
This is a small commit on top of @Weijun-H's work for a workflow for external contributors to self-assign issues.
See #1679 
^
^
=> ci: [Phil + Weijun] Create GitHub Actions workflow to allow users to self-assign issues

pg_search/tests/replication.rs, shared/src/fixtures/db.rs
We're seeing intermittent CI failures in the replication tests, likely due to the use of `Thread::sleep` to wait for replication between Postgres instances.
Introduced a `fetch_retry` method on the `Query` trait, which accepts wait time and retry number. We'll retry a few times if we get an invalid result.
Modified existing tests.
=> chore: introduce retries in replication tests

cargo-paradedb/src/tables/mod.rs, pg_search/src/api/index.rs, pg_search/src/bootstrap/format.rs, pg_search/src/fixtures/client.rs, pg_search/src/index/search.rs, pg_search/src/index/state.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/datetime.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/scan.rs, pg_search/src/postgres/types.rs, pg_search/src/schema/mod.rs, pg_search/src/writer/client.rs, shared/src/fixtures/arrow.rs, shared/src/fixtures/db.rs, tokenizers/src/icu.rs, tokenizers/src/manager.rs
- Closes #
I noticed several instances of the `unwrap()` function throughout the project. To improve debugging and provide better context when handling errors, we should make a concerted effort to avoid using `unwrap()` whenever possible.
=> chore: Avoid `unwrap()` and replace it by `expect()`

docs/ingest/postgres.mdx
- Closes #
Our "Ingest" docs use `-Fc` when dumping the database but fail to use it on the corresponding `pg_restore` command.
Also add a link to the Postgres `pg_dump` docs.
=> docs: use -Fc on pg_restore too

pg_search/src/api/operator.rs, pg_search/src/api/operator/searchconfig.rs, pg_search/src/api/operator/searchqueryinput.rs, pg_search/src/api/operator/text.rs, pg_search/tests/find_var_relation.rs
- Closes #1693
This addresses issue #1693 by implementing a more robust function for finding a `Var`'s original relation (if it has one).
To support more query plans, because we should not limit the SQL a user can execute.
By better looking through the [`pg_sys::PlannerInfo`] structure's Query, differently, depending on if the referenced field (`Var`) comes from a relation, a subquery, or a CTE.
It's likely this isn't complete, but it directly addresses the edge cases I've uncovered thus far.  If we have to revisit this in the future we now have a single function that can be improved.
A few new tests were added in the new `find_var_relation.rs` file
=> fix: issue #1693:  `Var` relation lookup is more correct

.github/workflows/test-pg_search.yml, README.md, pg_search/Cargo.toml, pg_search/README.md, pg_search/src/postgres/build.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/utils.rs
- Closes #N/A
Imagine supporting Postgres 12. Yuck.
It's getting deprecated by the PGDG now that 17 is just about out. Time to move on.
Remove code!
CI passes on all other versions
=> chore: Remove Postgres 12 Support

docs/api-reference/optimization/joins.mdx
- Closes #
Document creating a btree index on the foreign key column to speed up joins.
=> docs: document usage of btree index in join

pg_search/src/api/operator/searchconfig.rs, shared/src/gucs.rs
- Closes #
This introduces a new GUC (`paradedb.per_tuple_cost`) that describes how much it costs for us to retrieve a single tuple from a tantivy index in situations that are **NOT** Index Scans.
In our case, it costs **A LOT** and we'd prefer Postgres only consider not using an Index Scan if there's literally no other option.  As such, the default for this new GUC is one hundred million!
Prior to this, our per-tuple costing calculations were way off.  I think I misread the default value for `pg_sys::cpu_index_tuple_cost`, so our little formula of multiplying that by 10k really didn't do enough to encourage Postgres to not directly use our `@@@` operator.
Having this as a GUC will let us experiment a bit with "what if..." scenarios, if necessary.
Rather than fumble around with some kind …
=> feat: a GUC for `per_tuple_cost`

.prettierignore, docs/api-reference/getting-started/install.mdx, docs/api-reference/getting-started/quickstart.mdx, docs/api-reference/guides/hybrid.mdx, docs/api-reference/introduction.mdx, docs/deploy/pg_search.mdx, docs/mint.json, docs/welcome/introduction.mdx
- Closes #
Moves the quickstart guide to the same page as the API reference/tutorials. We had a user report that they weren't able to find the reference page after completing the quickstart, this makes it easier to find.
I also modified the quickstart guide to use the same exact table and BM25 index as the reference tutorial so there would be no confusion.
=> docs: Colocate quickstart guide with API reference

docker/Dockerfile, docker/bootstrap.sh
- Closes #N/A
This was causing issues with needing to update often, as in #1707. This should be more maintainable.
No one is using `pgvectorscale` and it's bloating the Dockerfile, so I'm removing it.
We also need to remove it on our Helm Chart
^
Only use the major version.
See CI
=> chore: Don't hardcode such a specific PostGIS version & remove pgvectorscale

docs/api-reference/indexing/tokenizers.mdx
- Closes #575
Introduce the ability to add a Postgres field to the Tantivy index more than once, using an `alias` to disambiguate. The alias can be used in the query to specify the field with particular tokenization, etc: `name:Mouse OR description_stem:mouses`.
Multiple tokenizers are available as an enterprise-only feature. This PR contains only documentation for the feature.
=> feat: introduce aliases for paradedb.field, allowing for multiple tokenizer configurations

.github/workflows/test-pg_search.yml
- Closes #N/A
We had removed it since `0.10.0` was backwards-incompatible.
^
^
^
=> chore: Reactivate extension upgrade test

Cargo.lock, docker/Dockerfile, pg_search/Cargo.toml, pg_search/README.md, shared/Cargo.toml
- Closes #1719
Upgrade `pgrx` to `0.12.5`.
This is required for PG17 support.
Update Cargo files and corresponding README guides.
See CI.
=> chore: Upgrade `pgrx` to `0.12.5`

.github/workflows/benchmark-pg_search.yml, .github/workflows/lint-rust.yml, .github/workflows/publish-paradedb.yml, .github/workflows/publish-pg_search.yml, .github/workflows/test-paradedb.yml, .github/workflows/test-pg_search.yml, README.md, docker/Dockerfile, docs/deploy/pg_analytics.mdx, docs/deploy/pg_search.mdx, pg_search/Cargo.toml, pg_search/README.md, pg_search/src/postgres/build.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/utils.rs
- Closes #1686
This adds Postgres 17 support.
Postgres 17 released today.
- Add `pg17` Rust features.
- Add `17` to workflow files.
Some edits in workflow files might not be final and should be discussed further.
See CI.
=> chore: Add Postgres 17 Support

pg_search/src/api/search.rs, pg_search/src/index/state.rs, pg_search/src/postgres/mod.rs, pg_search/src/postgres/scan.rs, pg_search/src/postgres/types.rs, pg_search/tests/index_only_scan.rs
- Closes # n/a
This teaches our IAM impl how to do "Index Only Scans', but only for the index's "key_field".
Speed.
We now implement the `amcanreturn` function and return true for the first index attribute if it's a number/float/bool.  This enables Postgres to plan an Index Only Scan for queries that only return that field, which can be quite many.
In one particular case, a query planned as a regular Index Scan took about 6s to return 21M rows and now it takes about 2.4s to return those same 21M rows right out of the underlying tantivy index.
In other cases, with a smaller number of rows, I've seen queries go from about 300ms to 25ms.
Existing tests pass and added a new one to verify we get an Index Only Scan when we think we should.
=> feat: support Index Only Scans

docker/Dockerfile
- Closes #N/A
We decided to wait until shipping PG17, so we should keep the Dockerfile on PG16 for now. We can upgrade in a few weeks.
^
^
^
=> chore: Keep the Dockerfile on PG16

pg_search/src/index/state.rs, pg_search/src/query/mod.rs, pg_search/tests/mlt.rs
- Closes #1747
First, make some changes to be able to bubble up `Result::Err`s from inside the tantivy search executor to the main thread.
Secondly, fix the actual issue reported by #1747, which is that when a query uses "more like this", we need to transparently turn on scoring.
My CTO reported this bug and I don't want to disappoint him.
When we convert our `SearchQueryInput` into a tantivy `dyn Query`, we now set a `requires_scoring: &mut bool` flag to true while recursing through the query tree.  That is then used when constructing the new `SearchState`.
Yeppers
=> fix: transparently turn on scoring when a query uses "more like this"

docker/bootstrap.sh, docker/update_pg_analytics.sh, docker/update_pg_search.sh
- Closes #N/A
We were installing our extensions in a custom template database. This meant that tools like pgAdmin wouldn't automatically use this template when creating new databases. By installing in `template1` instead all new databases will have our extensions pre-installed, which is what users expect.
^
^
^
=> feat: Install extensions in template1

pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/projections/mod.rs, pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, pg_search/tests/custom_scan.rs
- Closes #1753
Fixes issue #1753.
Bugs are bad
Actually walk the expression tree attached to each TargetEntry to see if there's any reference to our score/snippet functions that use a Var from the current range table index level.  Pull out the direct function expression that uses the var and add to our target list, if we have one.
Of course.
=> fix: build more precise TargetEntries to detect usages of `paradedb.score()` and `paradedb.snippet()`

pg_search/src/index/search.rs
lifetime parameter of SearchIndex::from_disk should be static
the lifetime of return type should be related to an argument type, a dangling lifetime on return position means the borrowing can lives for arbitrarily long (which means `'static`), `&mut Self` could simply be `'static`.
=> fix: lifetime parameter of `SearchIndex::from_disk` should be static

pg_search/src/api/operator.rs, pg_search/src/api/operator/searchconfig.rs, pg_search/src/api/search.rs, pg_search/src/index/mod.rs, pg_search/src/index/reader.rs, pg_search/src/index/search.rs, pg_search/src/index/state.rs, pg_search/src/index/writer.rs, pg_search/src/postgres/cost.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/projections/snippet.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/scan.rs, pg_search/src/postgres/transaction.rs, pg_search/src/query/mod.rs, pg_search/tests/mlt.rs
This PR is an effort to decouple some important components that interact with the Tantivy index. Up until now, we've had the `SearchIndex` hold references to the tantivy reader, searcher, and writer, and maintain a separate `SearchState` that is configured at query time. 
This work separates these out as separate components, passed to each other as method parameters.
Besides code organization, the big reason to do this is that we're finding that we more carefully need to mange the lifecycle of Tantivy objects. Now that we're relying on Tantivy's internal locking system, for example, we're finding that even the `Reader` needs to correctly lock the index directory when it is initialized (internally in `open_segment_readers`).
Co-ordinating the lifecycle of Tantivy objects across Postgres …
=> chore: extract SearchIndexReader from SearchIndex

pg_search/src/api/index.rs, pg_search/src/query/mod.rs, pg_search/tests/bm25_search.rs
- Closes #
JSON support for the following query builder functions: `term`, `fuzzy_term`, `phrase`, `phrase_prefix`, `fuzzy_phrase`, and `range`.
You can now do
```sql
SELECT * FROM mock_items
WHERE id @@@ paradedb.fuzzy_term('metadata.color', 'whiet');
```
I'm working on documentation in another PR so I'll add docs for this separately. Important details to document:
1. For `range` to work over JSON fields, it must be indexed as `fast`.
2. Datetime fields in JSON MUST be RFC 3339 compliant, otherwise Tantivy is not able to tell whether it's a datetime value or a string and will incorrectly cast it to a string. For instance, `{"date": "2024-01-01"}` will not work with range queries.
JSON can now be searched with query builder functions in addition to the query string syntax.
Tantivy …
=> feat: JSON support for query builder term/phrase functions

pg_search/src/api/operator.rs, pg_search/src/api/operator/searchconfig.rs, pg_search/src/api/search.rs, pg_search/src/fixtures/index.rs, pg_search/src/index/search.rs, pg_search/src/index/writer.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/cost.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/scan.rs, pg_search/src/postgres/transaction.rs, pg_search/src/postgres/vacuum.rs
Following up on #1762, I've proceeded with removing the global `SEARCH_INDEX_MEMORY` cache. This means we no longer keep any Tantivy-related state in memory between queries, which we expect to eliminate our window for race conditions as different connections compete for Tantivy resources.
Since #1707, we've seen some rare instances of concurrent Tantivy readers and writers competing for the Tantivy directory lock and throwing errors. We believe we can eliminate this issue by no longer caching either the Tantivy `Reader` instance or the `Index` instance in memory, and reloading them on every query.
I've moved the remaining global state to the `SearchIndexWriter` file, where we just track the index/db oids so that we can properly commit + abort indexes on creation + drop.
No new tests, but …
=> chore: remove caching and load index instance from disk on each query.

pg_search/src/query/mod.rs, pg_search/tests/bm25_search.rs
- Closes #
Fixes an issue where doing a term query over a JSONB value in the form of `'["abc", "def", "ghi"]'::JSONB` would not find any matches.
Bug fix.
This is because we were incorrectly using a text `Term` instead of a JSON `Term` for these types of queries.
See `json_array_term`
=> fix: `paradedb.term` over flat JSONB arrays

.github/workflows/test-pg_search.yml
Turn on RUST_BACKTRACE=1 in CI for hopefully better stacktraces.
- Closes #
=> chore: RUST_BACKTRACE=1 in CI

pg_search/sql/pg_search--0.10.3--0.10.4.sql, pg_search/src/bootstrap/create_bm25.rs
- Closes # n/a
This adds a SRF that returns a resultset of all of an index's segments, their document count, byte size, and number of deleted docs.
Having some visibility into the structure of a tantivy index is useful
None.  Just call it yourself with `SELECT * FROM paradedb.index_info('idxname');`
=> feat: function to inspect index segments

docker/bootstrap.sh
- Closes #N/A
See here: https://trac.osgeo.org/postgis/ticket/5125
We no longer need to reconnect, so removing. I found this out while adding support for our Helm chart.
Faster boot, less logs
^
Install properly without it, tested in Kubernetes
=> chore: Reboot no longer necessary in Postgis install

.github/workflows/check-pg_search-schema-upgrade.yml
- Closes #N/A
Our PRs are now getting an avalanche of schema diff comments. This small change will make it so the comment is updated with new commits rather than creating a brand new one.
Avoid too many comments, but keep the correctness so the developer can know what to add to the upgrade script.
Retrieve comment by type + content and update the body.
See CI!
=> chore: Update comment from schema upgrade if already exists

pg_search/sql/pg_search--0.10.3--0.10.4.sql, pg_search/src/api/index.rs, pg_search/src/api/operator/text.rs, pg_search/src/index/search.rs, pg_search/src/query/mod.rs, pg_search/src/schema/config.rs, pg_search/tests/query.rs
- Closes #1748 
Lets the user specify `lenient` and `conjunction_mode` in `parse` and `parse_with_field`. These are the only two functions that actually take raw Tantivy query strings from the user, so it makes so much sense to put these options here.
For example:
```sql
SELECT * FROM mock_items WHERE id @@@ paradedb.parse('shoes running', lenient => true);
```
Migrate these options to the new syntax.
See added tests: `parse_lenient`, `parse_conjunction`, and `parse_with_field_conjunction`
=> feat: Move `lenient` and `conjunction_mode` to `paradedb.parse`/`paradedb.parse_with_field`

pg_search/src/index/reader.rs, pg_search/src/schema/config.rs, pg_search/tests/mlt.rs
- Closes #1747
Re-implement a scoring check for `MoreLikeThis`.
I removed it in #1762 because it was complication my reading refactor by mutating the SearchConfig.
We just recurse through the SearchConfig query to check if MoreLikeThis is present.
I've added a few tests against nesting MoreLikeThis inside some higher-order queries.
=> fix: re-implement scoring check for more like this queries

pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/builders/custom_scan.rs, pg_search/src/postgres/customscan/builders/custom_state.rs, pg_search/src/postgres/customscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/projections/snippet.rs, pg_search/tests/bm25_search.rs, pg_search/tests/key.rs, pg_search/tests/query.rs, pg_search/tests/replication.rs, pg_search/tests/snapshot.rs
- Closes #
This fixes the segfaults that a number of the @@@ tests uncovered.  This was a problem with allocating the "method" structs in a memory context that didn't live long enough.  These structs are supposed to be static consts, but b/c of rust monomorphization we have to allocate, but we do that just one, per generic, in TopMemoryContext so they never go away.
One way this would exhibit is with prepared statements, on the second execute:
```sql
PREPARE crash_on_two AS SELECT * FROM t WHERE field @@@ 'value';
EXECUTE crash_on_two; -- ok
EXECUTE crash_on_two; -- crash!
```
Our test suite uses prepared statements and there's a number of tests that execute the same query multiple times, so I did not add a new test for this specific case.
PR also fixes a bug about how the "rti" (range …
=> fix: @@@ crashes, rti/varno confusion, and minor test query cleanup

pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, pg_search/tests/custom_scan.rs
- Closes #1776
The custom scan now does a better job of handling joins and figuring out which predicates from the restrict info list are necessary at any given level, and which need to be changed to "give me everything, sorry".
Added an edited version of the test from #1776 and updated an existing test that's now behaving more correctly.
=> fix: custom scan is better at joins

pg_search/sql/pg_search--0.10.3--0.10.4.sql
- Closes #
In the upgrade script, it quoted (and transformed to lowercase) the default value for the `paradedb.create_bm25()` procedures's `schema_name =>` argument to be `'current_schema'` when in fact it should be `CURRENT_SCHEMA`.
=> fix: in upgrade.sql, CURRENT_SCHEMA should not be quoted

.github/workflows/publish-paradedb.yml
- Closes #
Add tags like `v0.11.0` and `0.11.0` only for the default version (PG16).
Tags without PG version number like `v0.11.0` shouldn't be added to every PG version.
=> fix: docker image tags

Cargo.lock, pg_search/Cargo.toml, pg_search/src/index/search.rs, pg_search/src/index/writer.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/vacuum.rs, pg_search/src/schema/document.rs, pg_search/src/schema/mod.rs
The "ambuild callback" was creating a new `SearchIndex` instance on every row being indexed, drastically slowing down indexing times.
On a local test dataset of 50M rows (~16G) indexing dropped from 53 minutes to about 21 minutes
Improve CREATE INDEX times, remove some dead code, and general code cleanup.
This also cleans up the mutability requirements of various methods -- tantivy is mostly atomic, so things like insert and delete don't need mutable references.
=> fix: don't re-create a `SearchIndex` on every indexed row

.github/workflows/benchmark-pg_search.yml, .github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/lint-rust.yml, .github/workflows/publish-pg_search.yml, .github/workflows/test-pg_search.yml
- Closes #
Use `--debug` when installing `cargo-pgrx` in CI so it'll build a little faster.
CI is pretty slow right now.  Every little bit might help.
=> chore: use `--debug` when installing `cargo-pgrx` in CI

.github/workflows/publish-paradedb.yml, .github/workflows/test-paradedb.yml
- Closes #N/A
This PR:
- Moves our container build for test and publish from Depot, which costs 200$/mo, to Docker Build Cloud, which costs 6$/mo
- Combines the two Docker test jobs we had for arm/amd onto a single job, to reduce CI minutes by half
- Only runs the Docker test on changes to the `docker/` folder, to significantly reduce Docker build minutes (by 90%+ here)
- Rename the Docker workflow to say Docker in the name, so it's easier to understand what it tests
Depot is starting to charge us A LOT, and our CI was super wasteful.
^
Manually tested. You can see it here: https://app.docker.com/build/accounts/paradedb/builds
=> chore: Switch to Docker Build Cloud

.github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/lint-rust.yml, .github/workflows/test-pg_search.yml
- Closes #N/A
We switched our runners to Ubicloud, and need to switch the cache as well.
=> chore: Update Rust cache location

docs/documentation/configuration.mdx, docs/documentation/indexing/create_index.mdx, pg_search/src/api/operator/searchconfig.rs, pg_search/src/gucs.rs, pg_search/src/index/search.rs, pg_search/src/lib.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/customscan/hook.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/vacuum.rs
Introduce a set of GUCs, and documentation, to allow configuration of system resources dedicated to tantivy during its indexing processes.
As a followup to #1803, which reduced indexing time from ~53 minutes to ~21 minutes on a local database, this PR allows resource configuration such that that same data now indexes locally in 9m 42s.
- Closes #
Add a series of GUCs to let the superuser decide how many threads and how much memory per thread to dedicate to tantivy during indexing.
Also, this rejiggers how we manage our GUC state.  The trait and impl was just too much boilerplate to be easily extensible.
On a big computer, fully utilizing its hardware resources can **drastically** improve indexing performance.
=> feat: GUCs to control resource usage during CREATE INDEX and INSERT/UPDATE/COPY

.github/workflows/benchmark-pg_search.yml, .github/workflows/lint-docker.yml, .github/workflows/lint-format.yml, .github/workflows/lint-rust.yml, .github/workflows/publish-github-release.yml, .github/workflows/publish-paradedb.yml, .github/workflows/publish-pg_search.yml, .github/workflows/test-docs.yml, .github/workflows/test-pg_search.yml
- Closes #N/A
I was fixing something, and realized two things:
1) We run our `dev` CI to fill the Rust cache, yet we were running it even when no Rust files had changed. Oops? Now we'll only update the Rust cache if it needs to be updating, i.e. if Rust/Toml files changed.
2) The way we were passing PGRX version is deprecated, using `env.` instead of `outputs.`. I fixed this.
3) The Criteron manual save added by @eeeebbbbrrrr was unfortunately not saving. The cache is 16KB and cannot be overridden. I simply removed it, it should save automatically post-run.
4) The `lint-rust.yml` CI had a different key cache, so it wasn't properly taking advantage of the cache.
5) There was a missing run check on a `Extract pgrx Version` step, which meant this step ran unnecessarily when everything else …
=> ci: Only run `dev` CI on Rust files and small other fixes

.github/CODEOWNERS, .github/workflows/benchmark-pg_search.yml, .github/workflows/lint-docker.yml
- Closes #N/A
More CI anthills... Requested by @eeeebbbbrrrr. This stores the results of benchmark runs as GitHub artifact, which gets compared and printed on PRs.
^
^
CI
=> ci: Cache benchmark performance, and compare across runs

.github/workflows/benchmark-pg_search.yml
- Closes #N/A
We were previously defaulting to retrieving the artifact for the PR branch, which none existed, rather than from the `dev` branch. This should fix that, and finally make our benchmark comparison code work (famous last words).
Code that works is better than one that doesn't.
Retrieve the latest `dev` run ID and pass that to the artifact download step.
See CI
=> ci: Retrieve the correct GitHub artifact to compare benchmark runs

Cargo.lock, pg_search/Cargo.toml, pg_search/src/index/writer.rs, pg_search/src/postgres/vacuum.rs, tests/Cargo.toml, tests/tests/vacuum.rs, tokenizers/Cargo.toml
- Closes #1835 
Fixes an issue where the number of segments was becoming unbounded.
User-reported bug.
In the current implementation, every Tantivy `Index` holds onto a `ManagedDirectory`, which stores a snapshot of all segment files present in `managed.json` when initialized. When an `IndexWriter` flushes to disk, the `IndexWriter` appends its new segment paths to that snapshot of segment files and flushes it to `managed.json`.
This does not account for the scenario where the contents of `managed.json` are modified by another processes' `IndexWriter` (now that we allow for concurrent writers) after the snapshot is taken. This causes segments to become lost, which causes them to stay on disk forever (garbage collection doesn't know about them).
In my fork of Tantivy, I fixed this by …
=> fix: Unbounded number of segments

.github/workflows/test-pg_search.yml, pg_search/src/postgres/customscan/builders/custom_state.rs, pg_search/src/postgres/visibility_checker.rs, tests/tests/custom_scan.rs
Fix a bug where we could leak open tantivy file handles if an error occurred in the middle of executing our custom scan.
(for testing purposes, adds an operating system dependency on the `lsof` tool.)
- Closes #1835 (maybe?)
It was possible for us to leak open tantivy file handles if an ERROR was raised in the middle of executing our Custom Scan.  This is because the state objects we create weren't being properly dropped in that case.
There's a new test called `leaky_file_handles` that uses the system command `lsof` to see if there's leaky things.
=> fix: bug where we could leak open tantivy file handles

pg_search/src/api/operator.rs, pg_search/src/api/operator/searchqueryinput.rs, pg_search/src/api/operator/text.rs, tests/tests/query.rs
- Closes #1841
Postgres might decide to re-plan a PREPAREd statement, and when the rhs of our `@@@` operator is TEXT, it may replace it with a `Param` node instead of the `Const` node we've been assuming up to this point.
In that case, we transform the operator expression from `field @@@ $1::text` into `key_field @@@ paradedb.parse_with_field('field', $1::text)`, which then gets properly paramterized through the normal IndexScan machinery.
There's a few new tests here to make sure that when Postgres replans a prepared statement that it still executes, even if the plan is a little different.
=> fix: better support prepared statements in the form of `field @@@ $1::text`

docs/documentation/full-text/sorting.mdx
- Closes #
The fast sorting example had `paradedb.score` in the query, which is incorrect.
=> docs: fix fast sorting example

.github/workflows/benchmark-pg_search.yml
- Closes #N/A
There was an issue where we weren't accounting for the fact that a PR will be run on `dev` when PRing into `main`, for storing our benchmark artifacts. This led to `dev` runs without an artifact stored, which would fail the benchmark. This fixes that.
So it works!
Only push artifacts on `push` event.
See CI
=> ci: Make benchmark artifact storing work with the `main` branch PRs as well

pg_search/src/index/directory.rs
- Closes #
Makes our `SearchFs::total_size()` impl resilient to filesystem changes while we're calculating the directory size.  This came up as a failure in CI once.
The directory _could_ be being modified concurrently... especially by a background merge process.
=> fix: guard against concurrent file deletions

pg_search/src/postgres/scan.rs, tests/tests/parallel.rs
=> fix: bug where parallel workers that don't have anything to do would instead just query the whole index

.github/workflows/benchmark-pg_search.yml, .github/workflows/test-pg_search.yml
- Closes #N/A
There was a small issue in the branch naming logic.
We were also not pushing on `main`, which is an oversight. I also removed the nightly run, since it's not necessary now that we run on every PR.
This should properly compare it now!
On PRs, we want `base_ref`. On push, we want `ref`.
See CI
=> ci: Fix benchmark artifact storage logic

.github/workflows/benchmark-pg_search.yml, .github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/lint-rust.yml, .github/workflows/test-pg_search-upgrade.yml, .github/workflows/test-pg_search.yml
- Closes #N/A
We were saving the Rust cache on every branch, which was busting our maximum 10GB Rust cache, which meant nothing was hit. We only save on `dev`, so feature branches (PRs) see it.
Make the Rust cache work.
^
^
=> ci: Only save Rust cache on dev

.github/workflows/test-pg_search-upgrade.yml, pg_search/sql/pg_search--0.10.2--0.10.3.sql
- Closes #1850
This fixes the extension upgrade script from v0.10.2 to v0.10.3.
Is the cause of upgrade failures from "v0.10" to "v0.11".
=> fix: upgrade path from 0.10.2 to 0.10.3

.github/workflows/check-pg_search-schema-upgrade.yml
- Closes #N/A
As per: https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-issues
PRs are considered a type of issue, and we needed to enable `issue` write permissions for creating comments. This does that!
Enable external contributors to post schema upgrade comments to the PR.
^
^
=> ci: Fix issue with external contributors unable to create PR comments

docs/documentation/configuration/index.mdx, pg_search/src/gucs.rs, pg_search/src/index/merge_policy.rs, pg_search/src/index/mod.rs, pg_search/src/index/search.rs, pg_search/src/index/writer.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/vacuum.rs
- Closes #
Introduce a new merge policy that will merge the smallest segments in order to keep at least "N" segments, and there could be a "plus one" segment for leftovers.  The idea is that we can roughly keep a minimum number of segments while merging together the smallest segments.
We also add two new index `WITH` options, `target_segment_count = integer` which provides the "N" for the above and a `merge_on_insert = boolean` which dictates if we perform a merge after INSERT/UPDATE/COPY statements.
CREATE INDEX and (auto)VACUUM will always do a merge, using our new policy.
To give users a bit more flexibility and provide a default that allows for better parallelism during search.
Existing tests pass along with a run of our internal stressgres tool.
=> feat: new `NPlusOneMergePolicy` that targets that many segments

docs/documentation/configuration/index.mdx, pg_search/src/gucs.rs
- Closes #1872
When calculating how much memory to allocate to tantivy for index writing, make sure we don't exceed its hard-coded limits, which now become our hard-coded limits.
Our (`pg_search`'s) GUC `paradedb.create_index_memory_budget` is considered to be **per thread**, whereas if it's unset and we fallback to Postgres' `maintenance_work_mem`, we treat that as an overall value, dividing that total by the parallelism value.
From there, we make sure the newly-calculated per-thread memory budget does not exceed tantivy's hardcoded limits, which we adopt in code as our own.
As pointed out in #1872, it's easy to generally configure Postgres in a way that then becomes incompatible with tantivy.
=> fix: clamp per-thread memory budget allocation to tantivy limits

docs/documentation/full-text/sorting.mdx, docs/documentation/indexing/delete_index.mdx, docs/documentation/indexing/inspect_index.mdx, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/postgres/options.rs, tests/tests/bm25_search.rs, tests/tests/custom_scan.rs, tests/tests/documentation.rs, tests/tests/find_var_relation.rs, tests/tests/fixtures/tables/deliveries.rs, tests/tests/fixtures/tables/simple_products.rs, tests/tests/index_config.rs, tests/tests/json.rs, tests/tests/lindera.rs, tests/tests/query.rs, tests/tests/query_json.rs, tests/tests/replication.rs, tests/tests/search_config.rs, tests/tests/sorting.rs
- Closes #
Now that the dynamic schemas are gone, we can stop appending `bm25_index` to the Postgres index names, which was a footgun to users trying to run ALTER/DROP/etc. on the index.
This should have no effect to existing indexes.
- Also removed the unused `uuid` option
- Removed the "max 53 character index name" check. This was necessary because we were manipulating the index name, but now we can let Postgres handle the index name (by default, Postgres truncates at 63 characters).
=> chore: Remove `bm25_index` suffix

pg_search/src/index/merge_policy.rs, pg_search/src/index/search.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/insert.rs, tests/tests/cleanup.rs, tests/tests/replication.rs
- Closes #
This moves the tantivy index commit to the end of `do_heap_scan()` and then immediately asks tantivy to wait for the merge threads, there in the foreground.
At least during CREATE INDEX or REINDEX, if we don't wait in the foreground for the merge to finish, an index over a large table could have an untenable amount of segments.
There's a new test to make sure we get the proper segment count in all cases.
=> fix: move merging to foreground on CREATE INDEX

docs/documentation/aggregates/overview.mdx, docs/documentation/configuration/parallel.mdx
- Closes #
The docs failed to mention that users also need to set `max_parallel_workers` to increase query parallelism.
=> docs: fix parallel scan docs

pg_search/sql/pg_search--0.12.0--0.12.1.sql, pg_search/src/bootstrap/test_table.rs, tests/tests/bm25_search.rs
Some mock data for our test tables featuring some nested json objects.
Useful for nested json tests about to go into enterprise repo.
=> chore: create mock customer data table

docs/documentation/advanced/compound/parse.mdx, docs/documentation/advanced/term/term.mdx, docs/documentation/indexing/create_index.mdx, pg_search/sql/pg_search--0.12.0--0.12.1.sql, pg_search/src/api/index.rs, pg_search/src/postgres/types.rs, pg_search/src/schema/anyenum.rs, pg_search/src/schema/mod.rs, tests/tests/documentation.rs, tests/tests/index_config.rs
- Closes #
Supports indexing enums as `numeric_fields`.
Enums can be used as filter conditions.
We extract and index the enum ordinal value.
See `custom_enum` test.
=> feat: Support indexing enums

pg_search/src/api/operator/text.rs, pg_search/src/index/reader.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/visibility_checker.rs
- Closes #
Seeing a nearly 2x performance improvement in selecting large number of rows from queries such as:
```sql
SELECT * FROM t WHERE ... @@@ ...; -- selects millions of rows
```
Getting rid of some low-hanging per-tuple evaluation overhead.
We cleanup the VisibilityChecker to do it the same way Postgres' `nodeIndexscan.c` does it, which saves a little bit of overhead.
We cleanup our `BufferedChannelCollector` to immediately send blocks of matched documents (as a `Vec<T>`) over the channel.  We also switch to using a bounded channel (bound to the # of CPUs) -- this is where the big performance improvement came from.
And as a drive-by, fix a possible segfault in our `SupportRequestSimplify` processing.
=> feat: improve general CustomScan performance

tests/tests/cleanup.rs
- Closes #
The segment count test is flakey, sometimes an extra segment is created after vacuum and that's okay.
=> chore: make segment count test less flakey

docs/documentation/advanced/compound/boost.mdx, docs/documentation/advanced/compound/overview.mdx, pg_search/sql/pg_search--0.12.0--0.12.1.sql, pg_search/sql/pg_search--0.12.2--0.12.3.sql, pg_search/src/api/index.rs, pg_search/src/query/mod.rs, tests/tests/documentation.rs, tests/tests/mlt.rs, tests/tests/query.rs, tests/tests/query_json.rs
Changes the `boost` parameter to `factor` everywhere.
This is more consistent with naming for other interfaces (like `boost_factor` in MoreLikeThis), and is a decision we made based on feedback from ORM integrators.
=> feat: rename `boost` parameter to BoostQuery as `factor`

.github/CODEOWNERS, .github/workflows/lint-rust.yml, .github/workflows/publish-paradedb.yml, docker/Dockerfile, docs/deploy/extensions.mdx, docs/deploy/replication/self-hosted.mdx, docs/deploy/self-hosted/docker.mdx, docs/deploy/self-hosted/extensions.mdx, docs/documentation/getting-started/install.mdx, docs/welcome/introduction.mdx, pg_search/Cargo.toml, pg_search/README.md, tests/README.md
- Closes #1718
PG17 is the new latest Postgres.
Keep up.
Updated all the references to PG16. We already added support before.
CI!
=> feat: Set PG17 as the default

docs/documentation/indexing/partitioned.mdx
We made partitioned indexes available to the community in #1915, this PR updates the docs to reflect that.
=> chore: update documentation to reflect partitioned index availability 

pg_search/sql/pg_search--0.12.2--0.13.0.sql, pg_search/src/api/operator.rs, pg_search/src/postgres/customscan/pdbscan/projections/mod.rs, pg_search/src/postgres/customscan/pdbscan/projections/score.rs, pg_search/src/postgres/customscan/pdbscan/projections/snippet.rs, tests/tests/custom_scan.rs
- Closes #1895
We now tell Postgres, in the case of a query with JOINs, that calls to `paradedb.score()` and `paradedb.snippet()` need to be wrapped in a proper `PlaceHolderVar` so that their values are not lost during query planning/execution -- specifically through nodes like HashJoin and MergeJoin.
Our intent is to support generating (and properly tracking) scores/snippets from either/both sides of a join.
Using the Postgres `PlaceHolderVar` node when the query is a join.
Yes.
=> fix: issue #1895: joins+scores now work correctly

pg_search/src/postgres/customscan/pdbscan/mod.rs, tests/tests/custom_scan.rs
- Closes #1951
Fixes a bug where we tried to open a relation with a `pg_sys::Oid::INVALID`.  In this case, it's fine if we don't have a heap relation oid and we can just return None.
Yes.
=> fix: issue #1951: fail gracefully when the relation oid is unknown

pg_search/src/api/operator.rs, pg_search/src/postgres/customscan/pdbscan/projections/mod.rs
- Closes #
There's a few places where we construct `pg_sys::Const` and `pg_sys::FuncExpr` nodes with a `paradedb.searchqueryinput` Datum.  Our `paradedb.searchqueryinput` type is a binary type and as such doesn't have a collation, so using `DEFAULT_COLLATION_ID` is incorrect -- it should just be InvalidOid.
It's strictly wrong this way and it's likely the cause of a report indicating that pg_search didn't quite work with Citus.
=> chore: fix incorrect collation designations for SearchQueryInput

Cargo.lock, Cargo.toml, tests/tests/query.rs
- Closes #1910
Our [tantivy fork](https://github.com/paradedb/tantivy/pull/12) now uses our own fork of [fst](https://github.com/paradedb/fst), where I've added support for `^` and `$` in our regex query.
New test added for `^` and `$` in regex query.
=> fix: point tantivy-fst fork to paradedb to fix regex

docs/documentation/advanced/compound/disjunction_max.mdx, docs/documentation/advanced/phrase/phrase_prefix.mdx, tests/tests/documentation.rs
- Closes #1953 
- Closes #1954
A couple mistakes in our docs from when we introduced JSON syntax. Thank you @Traverso!
Tests added for each query.
=> fix: correct docs for disjunction_max and phrase_prefex

docs/documentation/indexing/create_index.mdx, docs/documentation/indexing/tokenizers.mdx, pg_search/sql/pg_search--0.12.2--0.13.0.sql, pg_search/src/bootstrap/create_bm25.rs, tests/tests/helpers.rs
Introduces `paradedb.index_fields` as well as `paradedb.format_create_bm25` functions as helpers for creating and inspecting indexes.
Also some final doc changes around `CREATE INDEX`, removing outstanding references to `paradedb.field`.
Typing out the JSON that is now required for `CREATE INDEX` is cumbersome, so `format_create_bm25` will return a SQL string that can be evaluated.
`paradedb.index_fields` lets us inspect the field configuration that was used to create an index.
New tests for each function.
=> feat: add index_fields() and format_create_bm25 functions to support CREATE INDEX

.github/workflows/publish-paradedb-docker.yml, .github/workflows/publish-pg_search-debian.yml, .github/workflows/publish-pg_search-macos.yml, .github/workflows/publish-pg_search-rhel.yml, .github/workflows/publish-pg_search-ubuntu.yml
- Closes #1834 
We've had requests for macOS prebuilt binaries. I decided to build for macOS 15 and macOS 14 only, which should be plenty for now. If we need more, we can add later. The benefit of this is that these versions are arm-only, so we save on half of the binaries.
I've also added support for Ubuntu 20.04, which is still requested by some customers.
I've also split up the jobs between 4 files, one per OS. This has the benefit of:
- Not having containers on Ubuntu, which was unnecessary. This speeds up deploys and reduces costs.
- Failures only affect an individual OS, which avoids re-running 40+ jobs.
- Workflow files are shorter and cleaner, since we don't need as many if-statements.
Easier to use!
^
All tested manually up to the publishing step.
=> ci: Split publishing per-OS and add support for macOS and Ubuntu 20.04

pg_search/src/postgres/build.rs, pg_search/src/postgres/utils.rs, tests/tests/reindex.rs
This PR adjusts some of the verification logic in our `ambuild` method to support `REINDEX` and `CREATE INDEX CONCURRENTLY`.
Now that we've entirely adopted `CREATE INDEX` syntax for creating BM25 indexes, its much easier for users to take advantage of `CONCURRENTLY` so they can build new indexes in the background.
I've added a new set of tests to `reindex.rs` that covers some basic scenarios for both `REINDEX` and `CREATE INDEX`.
=> feat: enable concurrent index creation + reindex on BM25

pg_search/src/bootstrap/create_bm25.rs
- Closes #
If `schema_name` is not specified, `format_create_bm25` currently generates an invalid `CREATE INDEX` statement.
=> fix: allow empty schema name in `format_create_bm25`

docs/documentation/indexing/create_index.mdx, tests/tests/documentation.rs
Added a section to `create_index.mdx` for concurrent indexing.
New test in `documentation.rs`.
=> docs: CONCURRENT index creation

pg_search/src/api/config.rs, pg_search/src/bootstrap/create_bm25.rs, tests/tests/helpers.rs
The new `format_create_bm25` function needs to de-deuplicate they key_field in the CSV column.
Added an execution step to each test to ensure validity.
=> fix: dedup key_field in format_create_bm25 

docs/documentation/indexing/tokenizers.mdx, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/utils.rs, pg_search/src/schema/mod.rs, tests/tests/bm25_search.rs, tests/tests/documentation.rs, tests/tests/index_config.rs
Adds support for multiple tokenizers on a single field in BM25 indexes by allowing aliased fields to reference source columns.
Enables more flexible text search by allowing different tokenization strategies (e.g. exact match, stemming, n-grams) to be applied to the same text content without duplicating data.
- Added optional column field to SearchFieldConfig to specify source column
- Modified field validation to handle aliased fields referencing source columns
- Updated schema and index building logic to support field aliasing
- Prevented key fields from being used as aliases to maintain index integrity
Added comprehensive test cases covering:
- Basic multi-tokenizer functionality with stemming and n-grams
- More-like-this queries with aliased fields
- Multiple aliases pointing to same …
=> feat: enable multiple tokenizers through aliased fields configs

pg_search/src/api/operator/searchqueryinput.rs
- Closes #
Fix typo found via `typos --hidden --format brief`
=> chore: Fix typo, SeachQueryInput -> SearchQueryInput

.github/workflows/publish-pg_search-debian.yml, .github/workflows/publish-pg_search-macos.yml
- Closes #N/A
An extra `/opt/homebrew/opt/` was being prepended to the install path by accident, resulting in Postgres not being able to find the binaries.
We like when things work.
Fix the installation path to avoid duplicate append.
Manual
=> fix: Fix macOS binaries install path

.github/workflows/check-pg_search-schema-upgrade.yml
- Closes #N/A
This way external contributors can now what schema diff to add, even if it's not commented on the PR.
=> ci: Display schema diff in GHA logs

.github/workflows/publish-pg_search-macos.yml
- Closes #N/A
We had a report of missing symlinks in our macOS binary installation. This PR fixes it! Instead of installing our extension within a symlink directory, we install it in a standalone directly, `opt/paradedb`, similar to what `pgvector` does, and add symlinks to both Postgres directories.
References:
- https://www.unix.com/man-page/osx/1/pkgbuild/
```
--scripts scripts-path
Archive the entire contents of scripts-path as the package scripts. If this directory contains scripts named preinstall and/or
postinstall, these will be run as the top-level scripts of the package. If you want to run scripts for specific bundles, you must
specify those in a component property list; see more at COMPONENT PROPERTY LIST.  Any other files under scripts-path will be used
only if the top-level …
```
=> fix: Fix macOS install

pg_search/src/lib.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/storage/utils.rs
- Closes #
Freezes items in our linked list that are below the vacuum age threshold set in `postgresql.conf`.
`u32` `TransactionIds` can wrap around. Tuples need to be marked as frozen so that new wrapped transaction values don't conflict with existing ones.
Wrote unit tests
=> fix: Freeze old XIDs in the linked list

docs/documentation/indexing/tokenizers.mdx, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/reader/index.rs, pg_search/src/index/search.rs, pg_search/src/index/writer/index.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/index.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/utils.rs, pg_search/src/schema/mod.rs, tests/tests/bm25_search.rs, tests/tests/documentation.rs, tests/tests/index_config.rs
Adds support for multiple tokenizers on a single field in BM25 indexes by allowing aliased fields to reference source columns.
Enables more flexible text search by allowing different tokenization strategies (e.g. exact match, stemming, n-grams) to be applied to the same text content without duplicating data.
- Added optional column field to SearchFieldConfig to specify source column
- Modified field validation to handle aliased fields referencing source columns
- Updated schema and index building logic to support field aliasing
- Prevented key fields from being used as aliases to maintain index integrity
**Note from Ming**
To make this work with block storage, I had to fold the changes from https://github.com/paradedb/paradedb/pull/2027 into this PR.
Added comprehensive test cases …
=> feat: enable multiple tokenizers through aliased field configs

docs/documentation/advanced/phrase/phrase.mdx, tests/tests/documentation.rs
- Closes #2036
Fixed the docs for the `Phrase` query, which incorrectly uses the named parameter `values` in the example (even though the parameter list is correct). Our test was using the positional call style, so it didn't reflect this inconsistency.
Added a couple new test cases.
=> fix: doc example for "phrase" query

tests/tests/replication.rs
- Closes #2044 
Fixing the newly added physical streaming replication test to use the environment's appropriate `pg_ctl` binary and not relying on one being available in the system PATH.
Portable tests, and it's clear that the intention was to do this when the tests were written.
Use the primary ephemeral postgres instance's `pg_ctl` path instead of one in the system PATH.
This is fixing a broken test.
=> fix: Use the primary postgres pg_ctl path rather than the system pg_ctl path in replication test

cargo-paradedb/src/main.rs
- Closes #
```rust
pub async fn bench_eslogs_build_elastic_table(
elastic_url: String,
postgres_url: String,
table: String,
) -> Result<()> {
```
However, the caller is:
```rust
EsLogsCommand::BuildElasticIndex {
table,
url,
elastic_url,
} => block_on(subcommand::bench_eslogs_build_elastic_table(
url,
table,
elastic_url,
)),
```
=> fix: mis-aligned params for building ES index in cargo-paradedb

pg_search/src/index/directory/utils.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/linked_items.rs
Derive `Copy` for `SegmentMetaEntry` and tighten up the necessary derives for `FileEntry` and `DeleteEntry` while we're here.
Also, the `impl Default for SegmentMetaEntry` is only necessary for tests.
- Closes #
=> chore: `SegmentMetaEntry` can be `#[derive(Copy)]`

pg_search/sql/pg_search--0.13.2--0.13.3.sql, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/directory/utils.rs, pg_search/src/index/writer/index.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/storage/utils.rs, pg_search/src/postgres/vacuum.rs
- Closes #
Some optimizations around `garbage_collect` in high insert/update scenarios:
1. **Compaction**: If `garbage_collect` renders entire pages in the linked list empty, they should be removed from the linked list (provided it's not the first page in the list). The pointer of the previous node then needs to be rewritten to point to the next non-empty page.
2. **Merge on insert**: Garbage collection now attempts to run during `merge_on_insert` (if a lock can be acquired).
Also introduces `paradedb.storage_info` and `paradedb.page_info`. `storage_info` returns all the blocks in the segment meta linked list and the max offset of each page. `page_info` returns information about every item for a particular block number.
In Stressgres, I'm seeing the linked list never growing beyond one …
=> feat: Garbage collection TPS optimizations

pg_search/src/gucs.rs
- Closes #
The old default for indexing threads was `8`. If we set it to `0`, then default indexing threads autodetects parallelism, which feels like a better default.
=> chore: default indexing threads to autodetect available CPUs

pg_search/src/index/directory/utils.rs, pg_search/src/index/writer/channel.rs, pg_search/src/index/writer/segment_component.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/storage/linked_bytes.rs, pg_search/src/postgres/utils.rs, pg_search/src/schema/mod.rs
Writing to block storage would prefer we do it 1 full block at a time, rather than partially filling a block.  Rust's `std::io::BufWriter` is incompatabile with this desire, as it will write everything through if the new set of bytes doesn't fit in the buffer.
We implement our own `ExactBuffer` that keeps a buffer of exactly `bm25_max_free_space()` bytes and will write through only in chunks of that size, if necessary.
Unrelated, during `ambuild()` and `aminsert()`'s initialization, we go walk the `TupleDescriptor` and `SearchIndexSchema` **once** to categorize the fields to be indexed, rather than doing that on every row being inserted.
Combined, these two changes nearly double the indexing records-per-second rate of a large dataset.
- Closes #
=> feat: Optimize writing to be exactly `bm25_max_free_space()` bytes

pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/normal.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, pg_search/src/postgres/storage/buffer.rs
- Closes #
This fixes parallel index/custom scans to work correctly on block storage.
The primary fix here is that `SearchIndexReader::open()` now only holds onto a *pinned* `CLEANUP_LOCK` buffer, instead of a pinned&locked version.
This is necessary to ensure that buffer LWLocks aren't held longer than they should be.  Doing so can cause Postgres to fail to empty the parallel worker message queues because ProcessInterrupts doesn't do anything if there's an outstanding LWLock.
All existing tests, plus stressgres, pass.
=> fix: parallel scans now work correctly on block storage

docs/documentation/advanced/specialized/more_like_this.mdx, docs/documentation/indexing/field_options.mdx
Removing the deprecated `stored` field from index configuration in our docs, code, and tests.
=> chore: remove stored field from index configuration

cargo-paradedb/src/subcommand.rs, pg_search/src/bin/pgrx_embed.rs, pg_search/src/lib.rs
- Closes #
Rust v1.84 introduced some new clippy lint warnings, which this PR addresses.
As a result, our MSRV is now v1.84.0
=> chore: fix v1.84.0 clippy complaints

Cargo.lock, Cargo.toml, pg_search/src/index/fast_fields_helper.rs, pg_search/src/index/reader/index.rs, pg_search/src/index/writer/index.rs, pg_search/src/lib.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/utils.rs, pg_search/src/postgres/vacuum.rs, pg_search/src/query/mod.rs, pg_search/src/query/range.rs, pg_search/src/schema/mod.rs
- Closes #
For short while we modified our tantivy fork to allow for pushing Postgres "ctid" values directly into the tantivy postings file, inline with its `DocId`s so that we could get the ctid values as quickly as possible, avoiding fast fields.
Well, as of a commit to https://github.com/paradedb/paradedb/pull/2065, our "fast fields is quite slow" drama is gone, so we're able to undo this "ctids in postings" business.
I've updated our tantivy fork in https://github.com/paradedb/tantivy/commit/83efdfa3879921a478afe098dcc1fd9835d2b52d to revert that particular (huge!) changeset and this PR against pg_search undoes our side of that change.
Now that we're using fast fields correctly, the performance numbers are essentially identical, which isn't necessarily surprising as we're still …
=> chore: undo "ctids in postings"

Cargo.lock, Cargo.toml, pg_search/src/index/directory/channel.rs, pg_search/src/index/directory/mvcc.rs, pg_search/src/index/directory/utils.rs, pg_search/src/index/merge_policy.rs, pg_search/src/index/reader/index.rs, pg_search/src/index/search.rs, pg_search/src/index/writer/index.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/buffer.rs, tests/tests/cleanup.rs
- Closes #
Fixes a problem where `CREATE INDEX` and large bulk inserts could be significantly slowed down by merge if the `target_segment_count` does not match the number of segments that exist. This problem manifests itself in two places:
1. In `CREATE INDEX`: Over very large tables, the number of segments can exceed the target segment count if the segment doesn't fit in memory. Merging the index down to the target segment count at the end is a bad idea because you're essentially rewriting the entire index.
2. In bulk inserts: If, say, a million rows are inserted at once, several new segments will appear. The n plus one merge policy will try to merge those new segments down into one segment, which is again very expensive and probably not optimal.
Significant improvements to write …
=> perf: do not do expensive merges

.github/workflows/publish-pg_search-debian.yml, .github/workflows/publish-pg_search-rhel.yml
- Closes #N/a
We removed Debian 11 since it was EOL-ed. However, one of our upcoming integration partners require it. This re-adds publishing binaries for Debian 11.
^
^
Tested in CI
=> ci: Add Debian 11

pg_search/src/gucs.rs
- Closes #
Like indexing parallelism, statement parallelism should default to number of CPUs.
=> chore: default statement_parallelism to `0`

Cargo.lock, pg_search/src/lib.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/normal.rs
- Closes #
If we have two (or more) consecutive search result tuples that happen to be on the same Postgres page, as indicated by their "ctid" value, we can re-use the visibility map status from the first tuple we found on that block.  
Eliminating some per-tuple overhead, even only in the cases where consecutive results are on the same page, can improve the performance of queries returning lots of rows.  In fact, the larger the resultset being returned the more likely this scenario will become.
In a test using a query of `... WHERE pkey @@@ paradedb.all()` that counts 50M rows, it decreased the time from about 216ms to 168ms -- about 30%.
By keeping a rolling cache of the last block's visibility.
All existing tests pass.
=> feat: minor optimization around VisibilityMap access

pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/normal.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, tests/tests/custom_scan.rs, tests/tests/sorting.rs
- Closes #
Transform our existing "Top N" custom scan support into being parallel query capable.
Essentially if the "N" is, say, 10, we kick off parallel workers for each segment (up to num_segments/2) and each segment will return 10 tuples.  Then postgres sorts those and picks the final top 10.
Significantly faster to find the "top N" docs per segment in parallel than serially.
For example, if the index has 10 segments and the limit is 10, we'll have 5 parallel workers that each return 20 tuples (10 from two different segments, most likely), totaling 100 tuples. Postgres will then sort those and return only the top 10 back to the user.
This works for "Top N" by `paradedb.score()` and also for ordering by a fast field.  In both cases, ascending and descending ordering is supported.
When …
=> feat: parallel top-n queries

docs/documentation/aggregates/overview.mdx
=> docs: Typo in `VACUUM` command

pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, tests/tests/custom_scan.rs
- Closes #
If a query has a LIMIT but no ORDER BY, we can run this through our custom scan's "top n" machinery, but essentially picking a random document.
We endeavor to *avoid* parallel custom scans here, but we will generate one if the LIMIT happens to be greater than num_segments cubed -- needed some kind of heuristic and this seems to roughly be the breaking point on my computer.  We can always tweak this logic in the future
Our prior implementation was a pretty big regression relative to non-block-storage tantivy.
We distinguish between queries with only a LIMIT and queries with both a LIMIT and ORDER BY, and pass through the proper information to make different decisions at the point we query tantivy.
Existing, plus new tests, all pass.
=> feat: optimize queries with a `LIMIT` but no `ORDER BY`

.github/workflows/test-pg_search-upgrade.yml
- Closes #N/A
We are releasing breaking changes, so can't upgrade. We'll restart upgrading from 0.14.0 onwards, but that requires 0.14.0 to be out first!
It would fail otherwise
^
^
=> ci: Disable upgrade test CI until 0.14.1

pg_search/Cargo.toml
- Closes #2092
We now expose pgrx' `unsafe-postgres` feature flag as one of our own, allowing those building pg_search against a Postgres fork that claims to not be compatible to easily build pg_search.
Building pg_search against a Postgres fork is cumbersome b/c it requires hand-editing our `Cargo.toml` to add the `unsafe-postgres` feature to our pgrx dependency line.
This will let thse folks build pg_search with:
```shell
$ cargo pgrx package pgXX --features icu,unsafe-postgres
```
=> feat: add a top-level feature for pgrx' `unsafe-postgres` feature

pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs
In the general cases of querying a segment (or even all segments) we no longer go through tantivy's `Collector` APIs and instead map the underlying `Scorer` as an `Iterator`.
This allows us to completely eliminate the need to first collect all the `(Score, DocAddress)` matches into `Vec`s.
Additionally, it allows for `SearchIndexReader::estimate_docs()` to avoid a lot of overhead and just use the `::size_hint()`, which is good enough for our query planning purposes.
- Closes #
=> perf: don't `.collect()` search results anymore

pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, tests/tests/custom_scan.rs
- Closes #
This adds a line to EXPLAIN output to show the number of segments in the index being queried.
This is useful for understanding the size of the index and evaluating what is happening behind the scenes.
One new test to ensure the new "Segment Count" line exists.
=> feat: EXPLAIN now shows index segement count

Cargo.lock, Cargo.toml
Now that we've stabilized the changes to our Tantivy fork, we can point at main branch again.
=> chore: point to paradedb/tantivy main branch

pg_search/src/lib.rs, pg_search/src/postgres/fake_aminsertcleanup.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/mod.rs, tests/tests/copy.rs
- Closes #
Using `COPY` to copy data into a table with an existing `USING bm25` index would crash on Postgres versions less than 17 due to COPY being considered a utility statement whose memory context cleanup process doesn't exactly match regular DML like INSERT/UPDATE.
COPY works fine on pg17 due to the `aminsertcleanup()` function that was introduced.
For Postgres v13-16 this PR fakes a similar process by hooking the Executor's "end" callback, the process utility hook, and also adding a transient "on abort" transaction callback.
Crashing is bad and we were missing a test around COPY, so we never caught this.
Existing tests pass and also a new test has been added for COPY.
=> fix: COPY into a table with bm25 index no longer crashes on Postgres <=16

Cargo.lock, Cargo.toml, pg_search/src/postgres/storage/linked_bytes.rs
- Closes #
We defer loading a `LinkedBytesList`'s `BlockList` until needed.  This eliminates quite some overhead during query planning.
Additionally, we update our tantivy dependency rev to pick up the recent lazy loading changes from https://github.com/paradedb/tantivy/pull/20
In a test here, these two changes combined drop query planning time, for a simple query, from about 1.4ms to about 0.436ms.
Existing tests pass
=> perf: improve query planning times by loading `BlockList`s on demand and update tantivy rev

.github/workflows/test-pg_search-upgrade.yml, .github/workflows/test-pg_search.yml
- Closes #N/A
v0.14 brought unit tests and we didn't update the extension upgrade workflow to follow the same framework.
^
^
^
=> ci: Fix extension upgrade test workflow

pg_search/src/index/fast_fields_helper.rs, pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/delete.rs
- Closes #
We know that the `ctid` field is a `FFType::U64` so we can directly construct it as such, rather than surfing the various types until we find the one that works.
This cleans up a tiny bit of overhead when first iterating a segment's search results.
Just some general code cleanup with a _minor_ performance improvement.
=> chore: overload `FFType::new()` for the `ctid` field

pg_search/src/index/merge_policy.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/normal.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/utils.rs, pg_search/src/postgres/utils.rs, pg_search/src/postgres/visibility_checker.rs
- Closes #
This changes our use of `pg_sys::IsTransactionState()` to directly link to the function so that we can bypass the sigsetjmp overhead pgrx introduces.
This function, as written in Postgres, does not call `ereport()` so we don't have to worry about the FFI boundary.
Calling `pg_sys::IsTransactionState()` showed up as about 3% of the 66% of the time pg_search spends reading Buffers during a simple query.
With this, it's no longer in the profile at all.
=> perf: bypass `pg_sys::IsTransactionState()`, directly linking to the function

.github/workflows/test-paradedb.yml
- Closes #N/A
We only run Docker Scout on PRs to `main`, to avoid permission issues with community contributors.
^
^
^
=> ci: Only run Docker Scout on PRs to `main`

.github/workflows/test-pg_search-upgrade.yml, docker/Dockerfile
- Closes (partially) #2020
- Closes #2030 
Issue created by setting user postgres in docker file
When trying to run paradedb docker image with --tmpfs parameter it fails with folder permission issue.
By removing user postgres, the container starts with root container and switches to postgres user after creating in $PGDATA dir in postgres([entrypoint.sh](https://github.com/docker-library/postgres/blob/0b87a9bbd23f56b1e9e863ecda5cc9e66416c4e0/17/bookworm/docker-entrypoint.sh#L310))
Test instructions are mentioned in the attached issue
=> fix: rm user postgres in dockerfile

Cargo.lock, Cargo.toml, pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/normal.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, pg_search/src/postgres/customscan/pdbscan/parallel.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, pg_search/src/postgres/mod.rs, pg_search/src/postgres/parallel.rs, pg_search/src/postgres/scan.rs
- Closes #
Ever since we first added support for Parallel Index Scans, we've had a bug where a parallel scan worker could see a different representation of the index than the main backend connection first did.  
The way a worker "checked out" a segment was based simply on decrementing a counter, and assuming that number was the `SegmentOrdinal`.  This is incorrect when a parallel scan worker opens the index for itself and possibly sees a different list of segments, in a different order.
This approach was then inherited by our Parallel Custom Scan support, spreading this bug like a virus.
This was found in researching why we'd occasionally see a stressgres failure.  Turns it it was because parallel scan workers were querying the wrong, or even too many, segments.
We fix this problem by …
=> fix: send the list of segment ids to the parallel scan workers

docs/documentation/advanced/json/arrays.mdx, tests/tests/documentation.rs
Closes #2129 
`paradedb.term` should take two separate arguments.
=> fix: incorrect json arrays test

pg_search/src/index/reader/index.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/vacuum.rs
Related to #2067.  I don't believe this fixes that issue, but gets us a few steps closer.  Specific investigation into that issue will be in a future PR.
We had a few deadlocks related to block storage.
The first was that `LinkedItemList::garbage_collect()` would travel to the next page and exclusively lock it while it still held an exclusive lock on the current page.  This could cause a lock inversion between concurrent backends that were traversing the linked list at the same time.
The second is that `ambulkdelete()` was simply holding the MERGE_LOCK too long.  Specifically, holding it while we (now temporarily) lock the CLEANUP_LOCK page could cause deadlocks in concurrent backends.
And while not exactly a deadlock issue, via discussions with @rebasedming, we've decided we were holding …
=> fix: deadlocks be gone!

pg_search/src/index/merge_policy.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/vacuum.rs
- Closes #2067
This gets a (non-parallel) VACUUM able to respond to cancel query requests.
It's quite bad to not be able to interrupt things when asked, especially for production systems.
We look to see if there's a pending interrupt, and if there is then we branch to drop our `merge_lock` and then call `vacuum_delay_point()` one last time, which should catch the pending interrupt.  This doesn't happen if the vacuum process `IsInParallelMode()`.
We also now call `vacuum_delay_point()` every 100 docs in `ambulkdelete()` and every 100 blocks in `amvacuumcleanup()`.  We want to be a good citizen here, but we also need our index vacuum to hurry up and finish already.
Existing tests pass, along with stressgres, that has now been augmented to allow cancelling jobs during the run.
=> fix: issue #2067:  vacuum can be cancelled

Cargo.lock, Cargo.toml, pg_search/src/postgres/utils.rs, pg_search/src/schema/mod.rs, tests/tests/datetime.rs
- Closes #2139 
Allows term and range queries with subsecond precision.
See GH issue.
By default, Tantivy truncates datetime terms in the index and in fast fields to second precision. Postgres defaults to microsecond precision - this PR stores everything with microsecond precision. Also fixed a conversion issue on our end where we were truncating to seconds.
Needs https://github.com/paradedb/tantivy/pull/27 to be merged.
=> fix: allow subsecond precision for datetime queries

pg_search/sql/pg_search--0.14.1--0.14.2.sql, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/directory/mvcc.rs, pg_search/src/index/directory/utils.rs, pg_search/src/index/reader/index.rs, pg_search/src/index/writer/index.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/index.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/schema/mod.rs
- Closes #
Primarily, this PR fixes a concurrency bug with VACCUM where it could delete segments it shouldn't.  The reason this could happen is that, eventually, tantivy reloads the IndexMeta from the Directory and we use that information to compare with the previous version to see if any segments had been deleted.
The nature of MVCC is such that the reloading phase could see different entries b/c of concurrent transactions, causing us to mark a segment as deleted when it was not. 
Spurious instances of records temporarily disappearing from the index are bad!  They also take literal days to track down and fix.  Big ups to @rebasedming for his help with this.
The solution is for our [`MVCCDirectory`] to locally cache the results of `load_metas()` and always return that, ensuring tantivy …
=> fix: concurrency bug related to VACUUM deleting segments it shouldn't

pg_search/src/index/directory/channel.rs, pg_search/src/postgres/delete.rs
- Closes #
We increment `pg_sys::InterruptHoldoffCount` in our `ChannelRequstHandler` before we send a closure to a background thread to wait for it to finish.  We then decrement it when that closure has returned from the background thread.
This ensures that Postgres will ignore interrupts while we're essentially blocked on a background tantivy thread doing indexing/commit work.
Also, `ambulkdelete()` no longer inspects the `pg_sys::InterruptPending` state.  We rely on `pg_sys::vacuum_delay_point()` to process interrupts, if it even can.
Because of our open MergeLock, it probably can't.  But that's okay as far as things go.
Existing tests, plus stressgres pass.
I did some testing by sending various `kill (1)` signals to random postgres backends as well, and none of them caused any kind of …
=> fix: interrupt holdoff around threads

Cargo.lock, Cargo.toml, pg_search/src/index/directory/channel.rs, pg_search/src/index/directory/mvcc.rs, pg_search/src/index/directory/utils.rs, pg_search/src/postgres/storage/block.rs
- Closes #
This overrides the default implementation of
`Directory::supports_garbage_collection()` to return false, and then removes all the code that might have been called if it were to return true.
It also moves our tantivy dependency rev forward to the commit from https://github.com/paradedb/tantivy/pull/28. 
Explictly opting out of garbage collection, which
https://github.com/paradedb/tantivy/pull/28 now allows us to do, a) removes all calls to `Directory::list_managed_files()` through normal operations and b) gives us some peace of mind that tantivy won't do something we don't expect.
This idea came about when researching the concurrency issue fixed by PR #2142.
Existing tests pass, and so does stressgres
=> feat: implement new `tantivy::Directory::supports_garbage_collection()` function

docker/Dockerfile, docs/deploy/self-hosted/extensions.mdx, docs/deploy/upgrading.mdx
- Closes #N/A
This removes a no-longer-necessary fix now that we bundle it properly in code in `pg_analytics`, and upgrades to the `v0.3.1` version. We first need to do a `pg_analytics` release before the Docker test passes.
^
^
CI
=> chore: Upgrade to `pg_analytics` 0.3.1

.github/workflows/benchmark-pg_search.yml, .github/workflows/test-pg_search-stressgres.yml, .github/workflows/test-pg_search-upgrade.yml, .github/workflows/test-pg_search.yml, docker/Dockerfile, docs/deploy/self-hosted/extensions.mdx, docs/deploy/self-hosted/logical-replication/getting-started.mdx, pg_search/README.md, pg_search/src/lib.rs, tests/tests/replication.rs
There doesn't seem to be any reason why pg_search has to be in shared_preload_libraries on PG 17.
=> feat: allow pg_search to not be in shared_preload_libraries on PG 17

Cargo.lock, Cargo.toml, pg_search/src/index/directory/channel.rs, pg_search/src/index/directory/mvcc.rs
- Closes #
We added support for tantivy's `Directory` to have a panic handler, to be used when a thread pool worker (from committing and merging) panics.
This implements one on MVCCDirectory (and delegats down to it for ChannelDirectory) that makes a best effort to report the panic back to Postgres, rolling back the current transaction, rather than causing rust to abort the whole process, taking down the entire Postgres cluster with it.
Also moves our tantivy dependency rev to 81c6d2bf74307682830a598bb5d99d237c946deb.
Having rust, from a background thread, abort() the process, which crashes Postgres, is bad.
=> feat: Support the new tantivy Directory panic handler

tests/tests/aborted_xact.rs
- Closes #
Just a little test to validate that we're not returning rows from aborted transactions.
Because we didn't have one.
Yes, this PR is a test.
=> chore: a test for aborted transactions

pg_search/src/postgres/customscan/pdbscan/scan_state.rs, tests/tests/bm25_search.rs
- Closes #
`paradedb.snippet` now works over text arrays instead of throwing an incompatible type error.
User reported bug.
=> fix: `paradedb.snippet` works over `varchar[]` and `text[]`

docs/deploy/self-hosted/logical-replication/getting-started.mdx
- Closes #
Document that the logical replica with ParadeDB installed needs to be PG17+.
=> docs: logical replication only supported for ParadeDB pg17

pg_search/Cargo.toml, pg_search/src/gucs.rs, pg_search/src/lib.rs
This allows not running a background worker that would just be idle
anyway if a hosting provider were to globally disable
paradedb.pg_search_telemetry.
=> feat: allow disabling telemetry at compile time

docs/documentation/configuration/index.mdx, docs/documentation/configuration/write.mdx, pg_search/src/gucs.rs
- Closes #
The previous default create index and statement memory of `maintenance_work_mem/parallelism` was way too small, since the default `maintenance_work_mem` is `15MB`. This makes the default 1GB.
=> fix: default indexing mem to 1gb

pg_search/src/index/directory/mvcc.rs, pg_search/src/postgres/storage/block.rs, tests/tests/cleanup.rs
- Closes #
The function was lacking a test and so it failed to work.
This gets is working again by implementing `MVCCDirectory::list_managed_files()` and the necessary surrounding code.
Adds a test for `paradedb.validate_checksum()`.  Returning zero rows means the checksum passed.
=> fix: `paradedb.validate_checksum()` works again

pg_search/src/postgres/customscan/pdbscan/projections/mod.rs, tests/tests/joins.rs
- Closes #
We had a bug where `paradedb.snippet()` when used with a JOIN could cause us to generate its corresponding `pg_sys::Const` node placeholder multiple times, and then when injecting the actual snippet, we'd send it to the wrong `pg_sys::Const` pointer.
Because of this bug, it was possible for the user to think we were returning NULL for the snippet.  Technically we were, but that was incorrect!
Added a new test file to test for this.  It notes another problem we have (and encodes the current behavior), but that problem is out of scope for this simple fix.
=> fix: properly return `paradedb.snippet()`s from JOINs

pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, tests/tests/query_edge_cases.rs
- Closes #2141
This fixes another bug with handling Postgres' `NOT` operator.
The existing test was insufficient, so it's been updated.
=> fix:  another edge case in NOT handling

pg_search/src/api/operator/searchqueryinput.rs, pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/hook.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/projections/mod.rs, pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, pg_search/src/query/mod.rs, tests/tests/custom_scan.rs, tests/tests/joins.rs
- Closes #
This adds improved Join support, allowing our (Parallel) Custom Scans to be used for the left and right sides of the JOIN.
It also ensures that snippets and scores are pulled up from each side of the join and go to their proper Const pointer slot in the projection list.
This PR also adds some basic integration points for parameterized plans, however they are not supported.  Our custom scan implementation will raise an ERROR if it's asked to execute a parameterized plan. 
For better compatibility with PREPAREd statements, users should `SET plan_cache_mode = force_custom_plan;` in their session or directly in `postgresql.conf`.
Our JOIN support wasn't exactly complete, especially as it related to being able to use our Custom Scans and pulling up scores/snippets from them.  The …
=> feat: improved JOIN support

.pre-commit-config.yaml, pg_search/sql/pg_search--0.15.2--0.15.3.sql, pg_search/src/api/operator/searchqueryinput.rs, pg_search/src/api/operator/text.rs, pg_search/src/lib.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/builders/custom_scan.rs, pg_search/src/postgres/customscan/builders/custom_state.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/normal.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/parallel.rs, pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, pg_search/src/postgres/customscan/pdbscan/solve_expr.rs, pg_search/src/postgres/mod.rs, pg_search/src/postgres/parallel.rs, pg_search/src/query/iter_mut.rs, pg_search/src/query/mod.rs, pg_search/src/query/solve_expr.rs, tests/tests/fixtures/mod.rs, tests/tests/parallel_index_scan.rs, tests/tests/parameterized_queries.rs, tests/tests/query_edge_cases.rs
- Closes #2061
This adds improved support for parameterized queries/plans to our (Parallel) Custom Scan implementation.
In order for our Custom Scan to solve more query types directly, parameterized plan support is essential.  Parameterized plans can come from, at least, the PREPARE statement along with queries that use subselects.
Lots of tracing through the Postgres sources to understand how query parameters work!
Existing tests all pass, including the ones around joins,  Additionally, a new `tests/parameterized_queries.rs` has been added that exercises the general cases this PR was meant to solve.
=> feat: improved parameterized plan support

pg_search/src/postgres/fake_aminsertcleanup.rs, pg_search/src/postgres/insert.rs, tests/tests/executor_hooks.rs
- Closes #2187
For Postgres versions before v17 we have to fake a system similar to the `aminsertcleanup()` function by hooking the executor.
Our efforts to do that were not nearly complete enough and didn't account for the fact the postgres executor is reentrant.
Now we hook the ExecutorRun_hook along with the ExecutorFinish_hook and push/pop a stack a of our own state tracking information so we know what indexes have been modified by `aminsert()` at that level of the executor.  This allows us to do the cleanup work necessary for that level.
Existing tests pass, and a few new ones were added, including the entire re-create from #2187.
=> fix: issue #2187 - properly support recursive executor calls

pg_search/src/bootstrap/create_bm25.rs, pg_search/src/postgres/index.rs, pg_search/src/postgres/options.rs, tests/tests/index_config.rs, tokenizers/src/manager.rs
- Closes #2198
Prior to this PR, we would trucate TEXT `key_field` values to 255 characters.  This undoes that, effectively allowing a TEXT key_field value to be as long as necessary.
This will potentially require users that use TEXT primary keys to REINDEX their `USING bm25` indexes as now our understanding of the index's schema does not match what's on disk.  This will lead to incorrect search results due to tokenization differences.
Truncating `key_field` values can make it impossible to later search for them by their whole value using (at least) the `paradedb.term()` function.
A new test has been added to validate this change.
=> fix: issue #2198 -- don't truncate TEXT `key_field`s

pg_search/src/bootstrap/create_bm25.rs, pg_search/src/postgres/index.rs, pg_search/src/postgres/options.rs, pg_search/src/schema/mod.rs, tests/tests/index_config.rs
- Closes #2199
We index fields of type UUID as text and until now their values were being tokenized using Tantivy's default tokenizer.  Which in the case of well-formed UUIDs would split the value into 5 tokens, splitting on the dash (`-`).
This PR will necessitate that users that store UUIDs perform a REINDEX of all their `USING bm25` indexes so that the index schema matches what we believe to be true.
This is problematic because it is then impossible for the (at least) `paradedb.term()` function to find docs matching a full UUID value.
Absent a user-specific `text_fields:{}` configuration for a UUID column, we hardcode our own default, which uses the `raw` tokenizer and normalizer
A new test has been added to assert this behavior.
=> fix: issue #2199 - UUID fields need to use the `raw` tokenizer/normalizer

docs/documentation/configuration/index.mdx, docs/documentation/configuration/write.mdx, pg_search/src/gucs.rs
- Closes #2194
This changes the `paradedb.create_index_memory_budget/parallelism` and `paradedb.statement_memory_budget/parallelism` GUCS to be USERSET so that they can be changed by regular users.
Perhaps in production environments it's unrealistic to require superuser privileges to change the variables.
No additional tests necessary.
=> feat: make memory/parallelism GUCs USERSET instead of SUSET

pg_search/src/index/merge_policy.rs, pg_search/src/postgres/storage/utils.rs, tests/tests/cleanup.rs
- Closes #
We can check the "vacuum horizon" (my words) to decide if the last merge transaction's effects are visible to the backend trying to obtain a MergeLock, instead of looking at active Snapshot.
In fact, looking at the active Snapshot is not even possible when operating inside a Logical Replication Worker -- doing so leads to an assert failure in Postgres.
Better compatibility with logical replication.
Existing tests pass and stressgres has run solid for about 25 minutes w/o a problem.
=> fix: no longer use a Snapshot to acquire the MergeLock

pg_search/src/postgres/customscan/pdbscan/parallel.rs, pg_search/src/postgres/mod.rs, pg_search/src/postgres/parallel.rs
- Closes #
This struct was inadvertently tagged as `, packed`, which was causing some compilation problems.
While here, tighten up access to the struct's member fields.
It's unsafe to access, via reference, members of a packed struct due to alignment.  What's curious is that only @rebasedming saw rustc give compilation errors about this.
=> chore: remove `packed` from the ParallelScanState struct

pg_search/src/lib.rs
If the telemetry feature is disabled, then we don't need to the import. Import the function at time of use.
=> fix: clean up unused import if telemetry features is disabled

Cargo.lock, cargo-paradedb/Cargo.toml, pg_search/Cargo.toml, tests/Cargo.toml, tests/tests/parallel.rs, tokenizers/Cargo.toml, tokenizers/src/lindera.rs
- Closes #
This upgrades our dependencies to their latest versions.
A few minor code changes in the tests related to the `rng` crate, and the `tokenizers/src/lindera.rs` stuff needed to be brought up to speed with their new APIs -- we were over a year behind on that.
It was time to upgrade things, and the `lindera` dependency updates might possibly fix was was just reported in #2211.  That remains to be seen, however.
Existing tests work
=> chore: upgrade all our dependencies

.github/workflows/test-paradedb.yml, Cargo.lock, Cargo.toml
- Closes #
Look, I can't actually explain this, but using the HEAD (rev 53e98c8 as of today) of the `rust_icu` crate's git repo gets our Dockerfile building again.
=> fix: our `Dockerfile` now builds

docker/Dockerfile
- Closes #
This changes our `Dockerfile` to install the ICU v76 library to `/usr/local/`.  This is necessary as `/usr/local/lib/` is on the default `ld.so.conf` search path, at the top.
The library needs to be installed in a place that a) the `rust_icu`'s crate can find the `bin/icu-config` binary, and b) Postgres can ultimately find the ICU libraries when it's started.
=> fix: install icu76 to /usr/local

.github/workflows/test-paradedb.yml, docker/docker-compose.dev.yml, docs/deploy/ci/github-actions.mdx, docs/deploy/ci/gitlab-ci.mdx, docs/deploy/ci/overview.mdx, docs/docs.json, docs/welcome/support.mdx
- Closes #2020
This PR adds documentation for running ParadeDB in CI and a test for `tmpfs` for upstream `postgres` compatibility.
Customers are asking
- For GitLab, followed their official Postgres template: https://gitlab.com/gitlab-examples/postgres/-/blob/master/.gitlab-ci.yml?ref_type=heads
CI
=> docs: ParadeDB in CI

.github/stressgres/single-server.toml, .github/workflows/test-pg_search-stressgres.yml
Working through using stressgres' new "auto" mode and an updated CI job that's consistent with what we're now doing on enterprise, but without logical replication
=> chore: refreshing stressgres CI job

pg_search/README.md
I'm just reproducing the setup instructions here.
I came across this while installing it on a 20.04 box.
It looks like Ubuntu 20.04 has icu66 available.
https://launchpad.net/ubuntu/focal/+source/icu
=> docs: ubuntu-20.04 has libicu-66 available

Cargo.lock, Cargo.toml, pg_search/src/index/directory/channel.rs, pg_search/src/index/directory/mvcc.rs
- Closes #
This allows Tantivy to be aware of any pending Postgres interrupts (mainly concered about "^C" user, or administrator, query cancel commands).
The important bit here is that this, when combined with https://github.com/paradedb/tantivy/pull/31/commits/cbaff7f180dfa0e5c5c962bc734ef0e47e99290f, makes tantivy index merges cancellable.
This is incredibly important not only from a UX perspective (users need the ability to cancel INSERT/UPDATE statements, even if they're "stuck" in the segment merge phase), but it's also important for being able to quickly/cleanly stop a running Postgres instance that is maybe merging segments via a logical replication apply worker, or similar.
Cancelling a merge may not happen immediately, but will happen on the next big "chunk" of data that tantivy …
=> feat: make tantivy aware of pending Postgres interrupts

pg_search/src/index/directory/channel.rs, pg_search/src/index/reader/channel.rs
- Closes #
Just some code cleanup as a fallout from PR #2237.
Blindly unwrapping in the cases where we can cleanly return a `Result::Error` is uncool.
=> fix: error handling cleanup

.github/stressgres/single-server.toml, .github/workflows/test-pg_search-stressgres.yml
- Closes #
Move the "SET" statements out of the query that gets run and into the `on_connect=` property so that they're only run once, and not included in the measurement of the SELECT statement itself.
I think this is why the stressgres graphs show our custom scan being slower.  We'll find out.  Regardless, there's no need for these SET statements to run more often than when the connection is first created.
=> fix: remove non-pg_search overhead from CI stressgres job

pg_search/sql/pg_search--0.15.2--0.15.3.sql, pg_search/sql/pg_search--0.15.5--0.15.6.sql
- Closes #
The predicate pushdown work added two new UDFs and were originally added to the 0.15.2--0.15.3 upgrade path, but weren't actually merged until after 0.15.5, so their schema definitions need to be moved.
=> fix: schema upgrade scripts

pg_search/src/index/directory/channel.rs, pg_search/src/index/reader/channel.rs, pg_search/src/index/writer/channel.rs
- Closes #
Not all of our ChannelRequest variants were defined with a response channel (a `oneshot::Sender<T>`), but they all need to be, so that the reply and return value (some kind of `Result<T>` in nearly every case) can be properly returned to tantivy.
Without this, many of the channel requests, including SaveMetas, were not waiting for the operation to actually finish on the main thread before returning control back to tantivy.  And in those cases, we also weren't passing the `Result<T>` result from the actual request back to tantivy either, we'd just lie and say that it worked.
This could cause tantivy to get ahead, in terms of its execution, from the processing we need to do on the main thread, leading to various kinds of undefined, and at least incredibly confusing, behavior.
=> fix: `ChannelRequest`s must wait on reply

Cargo.lock, Cargo.toml, pg_search/Cargo.toml, pg_search/src/lib.rs
- Closes #
Using our new `lindera` fork
(https://github.com/paradedb/lindera/commit/df56adc01b50ca125449ae19fb5d95a3ee86bb9a) we are now able to get `reqwest` out of our normal builds, which also removes `tokio` and a litany of other dependencies.
The impetus for this was a customer reporting that they got an error excuting a query:  `cannot spawn executor threads... Resource temporarily unavailable`.
Turns out that phrase was coming from `tokio`'s `init()` function, which was being pulled in by `reqwuest`, which is actually only necessary for us when a) telemetry is turned on, and b) when `lindera` is running its `build.rs` -- *not* from its regular library.
=> chore: excise `reqwest` from our binary's dependency tree

benchmarks/src/main.rs
- Closes #
Adds a `--vacuum` option to benchmarks that will run `VACUUM ANALYZE` before benchmarks begin. Useful for eliminating heap fetches.
=> chore: run vacuum before benchmarks

pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, tests/tests/pushdown.rs
- Closes #2232 
This PR implements pushdown of `IS NOT NULL` into Tantivy and avoids query builder to query null values.
User requested to query for null values without query builder. Plus, tiny bit of query performance improvement.
Detect NullTest in query and pushdown to Tantivy.
test included in `pushdown.rs` to check if ParadeDB Custom Scan is generated when the query includes `IS NOT NULL`
=> feat: Pushdown `IS NOT NULL` to Tantivy

.github/workflows/check-pg_search-schema-upgrade.yml
- Closes #2285.
There's an issue with the bot posting comments for a pull request comming from a forked repo.
That's due to where GitHub Actions takes secrets.
From the [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target):
> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does. This prevents execution of unsafe code from the head of the pull request that could alter your repository or steal any secrets you use in your workflow. **This event allows your workflow to do things like label or comment on pull requests from forks.** Avoid using this event if you need to build or run code from the pull …
=> ci: Fixes bot comments for PRs from forked repos

pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/directory/channel.rs, pg_search/src/index/directory/utils.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/linked_bytes.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/storage/merge.rs, pg_search/src/postgres/storage/utils.rs, pg_search/src/postgres/vacuum.rs
- Closes #
Until now, page recycling only happened during the `amvacuumcleanup` process.  With this PR it happens immediately after a segment merge is complete (at the end of our `aminsertcleanup`), which is the point in which pages have otherwise been freed and can be recycled.
The page reclimation itself happens outside of a lock as the segments its operating on are known to not be in use by any other backend but that one.
Additionally, `amvacuumcleanup` becomes a no-op.
There's a few minor internal API function name changes to make things a little easier to understand.  There's also a handful of new asserts to validate the invariants this requires -- namely that we never try to recycle pages we're not allowed (our "fixed block numbers list") and also that we don't mark as deleted pages …
=> feat: move page recycling to the foreground

.github/workflows/check-pg_search-schema-upgrade.yml
- Closes #2285.
I broke the diff generation while allowed making comments, but the last thing never happens as there's no diff produced.
I missed an important thing about `pull_request_target`. It's not only using the target's context, but also sets the git reference to it. Therefore, making a diff between the target branch and the target branch surely produces nothing.
The fix explicitly specifies what commit the `checkout` action should use via the `ref` argument. The value is set to be `head_ref` of the `github` context ([docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context))
> The head_ref or source branch of the pull request in a workflow run. This property is only available …
=> ci: Fixed schema diff generation

.github/workflows/check-pg_search-schema-upgrade.yml
- Closes #2285.
`ref` is just a branch name in most of cases (though it's different if it points to the main repository branch). Therefore, the `checkout` action cannot use an external `ref` to the current repository.
I'm your free CI/CD engineer that nerd-sniped himself with the issue he found, and there's no GitHub Actions sandbox to verify changes locally.
As I said above, without `repository` parameter `checkout` cannot execute without pointing to an external `ref`. Alternatively, it's possible to use `pull/ID/head` fake refs or just a HEAD's SHA:
* `${{ github.event.pull_request.head.sha }}`
* `refs/pull/${{ github.event.number }}/head`
Using an explicit `ref` or by adding the `repository` parameter.
In production.
=> ci: Fixed head ref resolution for diff generation

docs/documentation/configuration/write.mdx, pg_search/src/gucs.rs, pg_search/src/index/merge_policy.rs, pg_search/src/postgres/insert.rs, tests/tests/cleanup.rs
- Closes #
This new GUC, `paradedb.segment_merge_scale_factor` is an integer that's multiplied by the host's available parallelism at the time we decide if we're going to attempt a merge.  The default is `1` (one).
If the index segment count is less than this calculated value, then we will skip merging.
Also fixes a bug with `NPlusOneMergePolicy` where it would merge all the segments down to one if they all happened to be the same size.  Test included.
The ability to defer merging small segments created via atomic INSERT/UPDATE statements, essentially into batches, at some future INSERT/UPDATE can help to improve overall update performance.
=> feat: new GUC: `paradedb.segment_merge_scale_factor`

pg_search/src/index/directory/mvcc.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/linked_items.rs
- Closes #
Tantivy looks up `FileEntry` instances quite often, and it's to our benefit to just cache all of them when we lookup the first one.
If for some reason the requested entry isn't in the cache we'll re-populate the cache.  This can happen from a tantivy instance that has internally added a new segment during commit.
This improves the SELECT TPS rate of one particular stressgres test by around 50%, which is pretty great.
=> perf: cache `FileEntry`s in `MvccDirectory`

tests/tests/cleanup.rs, tests/tests/segment_merge_scale_factor.rs
- Closes #
Moved this new test to a standalone module.  It needs to be the only one connected to the database when it runs so that its "vacuum horizon" isn't impacted by other concurrent backends running tests.
It is a test.
=> fix: move test to standalone module

pg_search/src/index/directory/utils.rs, pg_search/src/index/merge_policy.rs, pg_search/src/postgres/insert.rs, tests/tests/cleanup.rs, tests/tests/segment_merge_scale_factor.rs
- Closes #
This changes our `NPlusOneMergePolicy` so that it will only do 1 full `compute_merge_candidates()` reduction during any given tantivy merge process.  All subsequent attempts by tantivy to compute merge candidates will return none.
This also, and probably more importantly, removes all the logic it contained around also trying to merge by document count -- it's strictly byte-sized based now and will create new candidates at the `max_mergeable_segment_size` value.
Finally, fixes a bug in `do_merge()` where we included the `segment_merge_scale_factor` as part of the actual target_segments -- that's not what we want.  We only want to use that GUC value to determine if we should merge and we account for non-mergable segments when figuring out if we're beyond the scale factor.
Trying …
=> perf: adjust merge policy to only merge once per merge operation

pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, tests/tests/custom_scan.rs
- Closes #
If the set of fast fields we detect are necessary are all "Junk", then we're not actually returning fast fields, and so the decision of if the custom scan is capable of returning numeric or string fast fields should be false.
There's a new test for this case.
=> fix: don't use FastFields optimization when not returning anything

pg_search/src/postgres/customscan/pdbscan/exec_methods.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, tests/tests/custom_scan.rs
- Closes #
Our "Top N" queries got broken as part of the new block storage when Postgres planned a normal custom scan instead of a parallel custom scan.
New test included.
=> fix: "Top N" queries now work without parallel custom scans

pg_search/src/gucs.rs, tests/tests/cleanup.rs
- Closes #
In our internal benchmarks, we've found that a default scale factor of `5` is a significant (10X+) improvement to write speeds. There can be a 2X reduction to search speeds, depending on the query.
=> chore: default scale factor to 5

pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, tests/tests/matview.rs, tests/tests/pushdown.rs
- Closes #2308
- Closes #2301
This fixes an issue with the recent `IS [NOT] NULL` pushdown feature where if the attribute isn't found in the root we'd panic, rather than returning `None`, indicating that it's not a predicate we can use.
Two new tests added.
=> fix: issue #2308 and issue #2301

Cargo.lock, Cargo.toml
- Closes #
We can't handle quietly being upgraded to a pgrx point release due to all sorts of competing dependencies across various extensions we install in CI and Docker
=> chore: our pgrx version needs to be locked

.github/workflows/check-pg_search-schema-upgrade.yml
- Closes #
There's a redundant mention of `pg_search`.
It's already mentioned in the same sentence before.
Using a text editor.
No.
=> ci: Deduped workflow description

pg_search/src/postgres/customscan/pdbscan/projections/snippet.rs, tests/tests/bm25_search.rs
- Closes #1952 
Fixes max_num_chars not being respected while querying for highlights using the snippets function.
The function was not following tantivy behaviour and also wasn't consistent with paradedb docs.
max_num_chars wasn't being respected because we were casting a pointer to the snippetinfo config instead of the actual value that was provided in the arg due to which max_num_chars was being set to a very high value. 
Yes, added a few extra asserts to test for max_num_chars changes.
=> fix: fixed snippets not respecting max_num_chars and added tests for the same

pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, tests/tests/pushdown.rs, tests/tests/str_ff_exec.rs
- Closes #2282 
fixes an issue where rows with `NULL` values in a string fast field were missing from query results when using the `StringFastFieldExecState` execution method.
queries involving string fast fields should return all matching rows, including those with `NULL` values in the fast field.
updated `collect()` function in the `TermOrdSegmentCollector` (implementing the `SegmentCollector` trait) to properly handle `NULL` values in string fast fields.
manual testing in `psql` confirms the correct results. Unit tests added to test suite are not returning expected values.
=> fix: missing rows when using `StringFastFieldExec` method

pg_search/src/bootstrap/create_bm25.rs
- Closes #
Bring back `paradedb.is_merging` so the extension can upgrade.
=> chore: bring back `is_merging`

.github/workflows/publish-pg_search-macos.yml
- Closes #N/A
macOS deploys got broken by some upstream changes as of `0.15.9`. This fixes it.
^
^
^
=> fix: Fix macOS deploys

docs/documentation/indexing/fast_fields.mdx
Small documentation change to:
- reflect that UUIDs are treated as fast fields by default as per [comment on this issue](https://github.com/paradedb/paradedb/issues/2324#issuecomment-2742966481)
- fix links to the other data types
=> docs: Update fast_fields documentation to reflect UUID fast field default

pg_search/src/postgres/utils.rs
- Closes #
`isnull` checked after comparing the attribute names.
The operands are executed from left to right, so the `dev` version tries to compare strings first and only then check `isnull`. That's totally inefficient.
Using my favorite text editor.
Nope.
=> perf: Made cheaper expression first

pg_search/src/index/directory/channel.rs, pg_search/src/index/writer/index.rs
- Closes #
`ChannelRequestHandler::wait_for_internal()` should try to process still-queued messages before running the caller's `action_func`.
It should also, when the caller has indicated it's the last action and the handler is going to be dropped, process in a blocking manner all other incoming messages after the action completed and until the remote sender is dropped
It was possible for a ChannelRequest message to get lost.
=> fix: `ChannelRequestHandler::wait_for()` should process all messages 

Cargo.lock, tokenizers/Cargo.toml
- Closes #N/A
Updated lindera to 0.32.3.
I have changed the download URL for the dictionary and would like you to change it to the new version.
The old download URL will be closed in the future.
=> chore: Upgrade lindera to 0.40.0

Cargo.lock, Cargo.toml
- Closes #
We just moved to lindera v0.40.0, which includes the PR I put up awhile back, so we don't need to patch that into our dependency tree anymore
=> chore: no need to use our linda PR directly

pg_search/sql/pg_search--0.15.10--0.15.11.sql, pg_search/src/bootstrap/create_bm25.rs
- Closes #
This is a view that makes figuring out how a segment is organized by its layers really simple.
```sq;
[v16.2][20023] test=# select * from paradedb.index_layer_info;
relname        |   layer_size    | count |                                                                                                                 >
-----------------------+-----------------+-------+----------------------------------------------------------------------------------------------------------------->
idxa                  | 1024 MB..       |     0 | 
idxa                  | 10 kB..1024 MB  |    10 | {6c62932f,2ba1d9e6,1e74b134,b3578065,8d350491,56d2b06d,a766c091,805a5b84,2f3df680,b3b934a3}
idxa                  | ..10 kB         |    26 | …
```
=> feat: a view to inspect index layers

.github/stressgres/single-server.toml, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/directory/mvcc.rs, pg_search/src/index/directory/utils.rs, pg_search/src/index/merge_policy.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/storage/merge.rs, pg_search/src/postgres/storage/utils.rs
- Closes #
When insert/updating tuples, specifically for the "merge" portion of the insert, we no longer require a Postgres `Snapshot`.
Essentially, we don't need to use the snapshot to determine if a segment meta entry (or block!) is recyclable, and we don't need a snapshot to determine if a segment is mergable.
This allows us to simplify the code quite a bit and eliminates a complexity around `aminsert()` that behaves differently between community and enterprise (with logical replication).
Existing tests pass
=> feat: Snapshots are no longer necessary during insert

pg_search/src/index/directory/utils.rs
- Closes #
`load_metas()` might need to know the current transaction id to determine if an entry is mergeable, but if we don't have a transaction id we also don't need to assign one.
This would only happen during a postgres WAL recovery situation, so isn't even applicable here on community pg_search, but it's best to be as correct as we can.
=> fix: no need to assign a `TransactionId` if we don't have one

.github/workflows/publish-paradedb-docker.yml
- Closes #N/A
This PR enables publishing Docker images with a specific tag and for a specific PG version. We can then use this to push tags for arbitrary branches and do individual testing on live deployments.
Easily troubleshoot issues/add logs.
Added a new input for PG major version and made sure we don't trigger the `latest` tags if a manual version is provided.
Need to test manually
=> ci: Enable manually publishing individual Docker images

pg_search/src/postgres/options.rs, tests/tests/layer_sizes.rs
- Closes #
Unifies the layer size parsing logic for `layer_sizes` and `validate_layer_sizes` functions.
Deduplication decreases the probability of the functions to desync and makes it easier to maintain the code.
Making a new function.
Covered by the existing tests.
=> refactor: Unifies layer size parsing logic

.gitattributes, .github/workflows/publish-pg_search-pgxn.yml, META.json.in, Makefile
- Touches #1019.
Adds a `pgxn` publication workflow.
Allows users to use `pgxn` to consume `pg_search`, and automates publication in `pgxn`.
A new workflow according to the FAQ and paradedb/pg_analytics#203.
Nope.
=> ci: Added pgxn publication workflow

pg_search/sql/pg_search--0.15.11--0.15.12.sql, pg_search/src/bootstrap/create_bm25.rs
- Closes #
Adds 3 more columns to the `paradedb.index_layer_info` view:  `low`, `high`, `byte_size`, which are the low end of the layer size range, the high end of the layer size range, and the total byte size of the segments in that layer.
Practical usage of this view showed it needs a few more columns.
=> feat: enhance the paradedb.index_layer_info view

pg_search/sql/pg_search--0.15.11--0.15.12.sql, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/directory/mvcc.rs, pg_search/src/index/directory/utils.rs, pg_search/src/index/merge_policy.rs, pg_search/src/index/reader/index.rs, pg_search/src/index/writer/index.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/scan.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/linked_bytes.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/storage/merge.rs, pg_search/src/postgres/vacuum.rs, tests/tests/layerd_merge.rs, tests/tests/merge.rs
- Closes #
This adds a new UDF named `paradedb.force_merge()` that when given an index name and a byte size (either as exact byte number or a pretty string, ie, '10G') will essentially force a merge of segments up to the specified size -- effectively creating a new layer.
The intent is that the user would specify a byte size that's (significantly) larger than the largest layer_size configured on the index, but this is not required.
We also adjust our decision making around what segments a concurrent merge-after-insert might do such that we calculate the merge candidates ahead of time, enabling other concurrent merges to have access to more segments for merging, which includes the new `force_merge()` function.
---
Along with the above...
We used to use the "vacuum horizon" to be the …
=> feat: add new `paradedb.force_merge()` function

pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/merge.rs
- Closes #
The `MergeEntry`, rather than panicking, should return `pg_sys::InvalidBlockNumber` from its `pintest_blockno`, and we should not try to get a conditional lock on it during recyclable-checking.
`MergeEntry` goes through the same general "is recyclable" process as `SegmentMetaEntry`, but doesn't also have the requirement of pinning a page
=> fix: `MergeEntry` should indicate it doesn't have a "pintest_blockno"

.github/workflows/benchmark-pg_search.yml, .github/workflows/test-pg_search-stressgres.yml
- Closes #N/A
I noticed these jobs were running on draft PRs, which they're not supposed to.
^
^
^
=> ci: Don't run Stressgres on drafts

docs/deploy/upgrading.mdx
- Closes #
Updated our upgrade docs to include:
1. `paradedb.version_info`
2. Helm chart instructions
Removed `pg_analytics` from it as well.
=> docs: Update upgrade docs

.gitignore, pg_search/sql/pg_search--0.15.12--0.15.13.sql, pg_search/src/api/index.rs, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/postgres/index.rs, tests/tests/fixtures/mod.rs, tests/tests/fixtures/tables/mod.rs, tests/tests/fixtures/tables/partitioned.rs, tests/tests/index_config.rs
-
We already supported partitioned tables to a large degree, but our tests were not validating that.
Additionally, metadata functions which did not check the relation kind that they were operating on [would fail with a TRAP](https://gist.github.com/stuhood/6d43e6b9caee5379722e4457d13b5b8c) due to assuming that the heap relation for the index was itself not partitioned.
See #2191.
Extracted a partitioned table fixture, and then expanded test coverage on metadata functions and query planning.
Adjusted metadata functions to either:
* Render the schema of the first child partition (`paradedb.schema`)
* Expose information for all partitions (`paradedb.{merge,vacuum,index}_info`)
More work remains for #2191: see https://github.com/paradedb/paradedb/issues/2191#issuecomment-2763111092.
See …
=> fix: Fix metadata functions, and increase test coverage for partitioned tables

docs/README.md, docs/deploy/enterprise.mdx, docs/documentation/indexing/create_index.mdx, tests/tests/fixtures/tables/partitioned.rs, tests/tests/index_config.rs
None.
Add a test that our custom scan still has filters pushed down after some partitions are pruned.
#2370 did not test this case, and it is a particularly important one for time-partitioned tables.
Adjust `sale_date` in the partitioned fixture to be indexed as fast.
See above.
=> test: Fast fields should be used in custom scan on partitioned index

pg_search/sql/pg_search--0.15.12--0.15.13.sql, pg_search/src/bootstrap/create_bm25.rs
- Closes #
We should give "PUBLIC" the ability to SELECT from our `paradedb.index_layer_info` view.  There's no PII in the view and not requiring superuser to select from it enables external monitoring tools to more easily use it.
=> fix: grant select permissions to public on the paradedb.index_layer_info view

pg_search/src/bootstrap/create_bm25.rs, pg_search/src/postgres/insert.rs
- Closes #
This teaches `merge_index_with_policy()` how to garbage collect immediately after doing a merge, which gets the space freed by the merge returned to the FSM so that the next merge candidate can potentially use it.
While doing this, it exposed that in the non-force_merge case, we only need to garbage collect if a merge happened.  This frees up a bit of CPU and disk I/O in the normal happy path of inserting rows that don't need to be merged.
To ensure that a force merge has the opportunity to reuse existing space rather than potentially being required to allocate more.
=> feat: `paradedb.force_merge()` now garbage collects after each merge

pg_search/src/index/reader/index.rs
- Closes #
If we are a WAL receiver, the SearchIndexReader must hold a share lock on the `SEGMENT_METAS_START` buffer to prevent WAL records from a concurrent save_new_metas from being applied while a parallel custom/index scan is running (since applying a WAL record requires an exclusive lock).
WAL streaming is enterprise-only but putting this in community keeps things consistent.
=> fix: `SearchIndexReader` takes share lock on `SEGMENT_META_ENTRY`

pg_search/src/index/directory/utils.rs, pg_search/src/index/reader/index.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/storage/merge.rs
Adds `LinkedItemList::atomically`, and uses it in `save_new_metas` and `garbage_collect`
Although the primary holds exclusive locks to prevent other local processes from being able to observe a `LinkedItemList` in an inconsistent state, physical replicas cannot obey these locks, and can therefore observe the buffers of the list at any point in time.
That makes it necessary to publish bulk changes to `SegmentMetaEntry`s atomically, so that a physical replica can never observe it halfway through an operation like `save_new_metas` or `garbage_collect`. 
We acquire an exclusive lock on the header of the `LinkedItemList`, clone it, and then operate on the clone until we're ready to commit all changes by swapping in the clone.
Added a test of the `LinkedItemList::atomically` method, and had …
=> fix: Add `LinkedItemList::atomically`, and use it for bulk operations on `SegmentMetaEntry`s

pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, tests/tests/custom_scan.rs
- Closes #2397
Fixes possible endless loops in our "Top N".
The code would get confused about when it was done querying/expanding the results.
Existing tests pass and the `top_n_matches` test has been updated a bit to catch some cases that it didn't previously.
=> fix: issue #2397 -- endless loop during certain TopN queries

pg_search/src/index/reader/index.rs
- Closes #
In Enterprise we have found a new way to prevent WAL replication conflicts without a share lock
=> fix: remove share lock from `SegmentIndexReader`

docs/documentation/guides/hybrid.mdx, tests/tests/documentation.rs
- Closes #
The hybrid search query from our guide was doing some suboptimal things like calling the custom scan twice and not letting get the top N query get pushed down.
=> docs: Update hybrid search query to be more optimized

pg_search/src/index/merge_policy.rs
- Closes #
`adjust_byte_size` can be smarter about a segment's size and say it's `0` if it has all deleted docs. Without this condition, `adjust_byte_size` can estimate that a segment's size is much larger than `0`.
=> fix: if segment has no docs, adjust byte size to `0`

pg_search/src/index/directory/utils.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/linked_bytes.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/storage/merge.rs, pg_search/src/postgres/storage/utils.rs
- Closes #
This PR is four changes to cleanup our internal APIs around page recycling along with fixing two bugs where pages could be leaked.
First, internal APIs have been changed such that there's no longer a distinction between "mark_deleted" and "return_to_fsm".  Now, we simply `return_to_fsm` individual `BufferMut` instances or larger collections of them, such as with `LinkedBytesList`.  Internally, the underlying page is automatically marked as deleted.
The impetus for this internal API change is that the new `AtomicGuard::commit()` and `AtomicGuard::drop()` functions were leaking old (or new) pages because they failed to `.mark_deleted()`.  Now, that's just not possible.
Secondly, we rename `BM25Page::recyclable()` to `BM25Page::is_reusable()` and change its implementation to …
=> fix: stop leaking pages and make pages recyclable earlier

pg_search/src/schema/mod.rs, tests/tests/search_config.rs
- Closes #
We don't use tantivy's document store and we **want** all fields to **NOT** be stored.
This PR fixes an issue where indexed fields that use our default configurations would actually default to `stored = true`.  This wastes space and time -- two precious resources.
A new test was added and existing tests pass.
=> fix: don't default to `stored = true`

pg_search/src/schema/mod.rs, tests/tests/search_config.rs, tests/tests/term.rs
- Closes #2442
In order to set a normalizer, the field must be a fast field.  
Otherwise, while the setting would have no effect, it's very confusing to know you've set a `normalizer` but then never see it in the `paradedb.schema()` output.
Raise an error if `normalizer` is set but the field isn't `fast: true`
There's a new test to validate we now raise an error and an existing test needed to be adjusted because it set a normalizer but didn't also set the field to fast.
=> fix: issue #2442 -- using the `normalizer` setting requires `fast:true`

pg_search/src/postgres/customscan/pdbscan/mod.rs, tests/tests/index_config.rs
- Closes #2405
Enable ORDER BY LIMIT push down optimization for BM25 indexes on partitioned tables.
Previously, when running queries with ORDER BY LIMIT on partitioned tables with BM25 indexes, the TopN optimization was not applied. This resulted in less efficient execution, as each partition was scanned separately using NormalScanExecState, and sorting/limiting was done after combining results.
- Modified the limit detection logic to recognize when we're dealing with a partitioned table structure
- Created a helper function `is_partitioned_table_setup` that:
- Examines all partitioned tables in baserels
- Checks if our current relation is a partition of any of these tables using bitmap operations
- Uses direct bitmap overlap check (bms_overlap) for efficient relationship detection
- When …
=> fix: ORDER BY ... LIMIT ... is pushed down on partitioned table

docker/Dockerfile
- Closes #2431 
Upgrades and pins Barman to `v3.13.2`
=> feat: Upgraded Barman Cloud to version 3.13

pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/parallel.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, tests/tests/sorting.rs
- Closes #2405
The last piece of #2405 was ensuring that we declare sorted outputs sorted, by marking the resulting plan with the relevant `pathkey`.
But additionally:
* we were occasionally marking parallel-workers results sorted, which is not correct because each worker might consume multiple segments.
* we were not marking some other cases where we push down sorting to Tantivy as resulting in sorted outputs, meaning that Postgres would re-sort them. 
The early-cutoff feature described in #2405 requires that outputs are declared sorted.
Added tests for partitioned early cutoff, and tests that we do not declare any output sorted when parallel workers are used.
=> fix: Remove unnecessary sorts, and add necessary sorts

pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/directory/utils.rs, pg_search/src/index/writer/segment_component.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/linked_bytes.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/storage/merge.rs, pg_search/src/postgres/storage/mod.rs
Fix issues with consistency of the `SEGMENT_METAS` list in the presence of physical replication.
Physical replicas replay the WAL without regard for locks held on the primary. Consequently, there is no lock that we can hold that will prevent a physical replica from consuming a snapshot of the `SegmentMetaEntry`s immediately before one of the segment's files is deleted.
Additionally, two other bugs were causing the `SegmentMetaEntry`s to appear non-atomically on physical replicas: a bug in the `atomically` method, and the lack of hand-over-hand-locking in `LinkedList` implementations.
* Split `LinkedItemList::retain` out of `LinkedItemList::garbage_collect` to provide different selection logic when we're deciding whether something can actually be freed.
* Add a `segment_metas_garbage` …
=> fix: Improve atomicity of `LinkedItemList`s

pg_search/src/gucs.rs
- Closes #
We seemed to have missed this setting in #2194
=> fix: make `create_index_parallelism` userset

pg_search/src/schema/mod.rs, tests/tests/search_config.rs, tests/tests/term.rs
PR #2443 introduced an incompatible change with existing indexes created prior to it being merged/released.
The most expedient thing is to revert it.
- Closes #
=> fix: revert PR #2443 - don't require fast=true when setting a normalizer

.github/workflows/publish-github-release.yml, .github/workflows/publish-paradedb-docker.yml
- Closes #N/A
- Default the `-rc` version to 1 rather than 0 to match what is done elsewhere.
- Remove the Helm release. We don't need this, it stemmed from a misunderstanding I had of how to publish Helm charts.
^
^
^
=> ci: Fix some nitpicks for `staging` releases

pg_search/src/postgres/build.rs, pg_search/src/schema/mod.rs
- Closes #
Rather than warning that the `raw` tokenizer is deprecated whenever we deserialize a schema configuraiton, only do it during CREATE INDEX.
The previous location generated too much WARNING spam!
=> fix: move the `raw` tokenizer deprecation warning to CREATE INDEX

pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, tests/tests/pushdown.rs
- Closes #
We had a bug where a `bool_field = TRUE | FALSE` in a query would cause our custom scan code to think the query needed scores when it did not.
Looks like a cut-n-paste error from the original predicate pushdown PR #2197 
A new test has been added to tickle the exact condition reported by the user.
=> fix: bool pushdown is no longer confused with scoring

Cargo.lock, Cargo.toml, docs/documentation/advanced/specialized/more_like_this.mdx, docs/documentation/indexing/field_options.mdx, pg_search/src/api/config.rs, pg_search/src/api/index.rs, pg_search/src/index/reader/index.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/types.rs, pg_search/src/query/mod.rs, pg_search/src/query/more_like_this.rs, pg_search/src/schema/mod.rs, tests/tests/documentation.rs, tests/tests/fixtures/tables/simple_products.rs, tests/tests/helpers.rs, tests/tests/query.rs, tests/tests/query_json.rs
- Closes #
The only holdout to us removing the Tantivy store for all fields is the "more like this" query, which looks up a document in the store.
This PR reroutes the "more like this" query to construct the document from the Postgres heap instead of the Tantivy store.
Now that store is no longer required anywhere, we also remove `store` from the code base, tests, and docs.
This PR paves the way for a follow-on PR to make Tantivy not write to the store file at all (right now it writes some fixed data to the store file even if no fields are stored).
Implemented our own `MoreLikeThis` query that reads from the Postgres heap instead of the Tantivy store.
Depends on https://github.com/paradedb/tantivy/pull/39
All existing tests pass with `store` removed.
=> chore: Remove dependence on Tantivy store everywhere

Cargo.lock
- Closes #
Update  `openssl`, `tokio`, and `crossbeam-channel` cargo packages
There are known vulnerabilities in the listed packages:
- https://github.com/advisories/GHSA-4fcv-w3qc-ppgg / https://rustsec.org/advisories/RUSTSEC-2025-0022.html
- https://github.com/advisories/GHSA-rr8g-9fpq-6wmg / https://rustsec.org/advisories/RUSTSEC-2025-0023.html
- https://github.com/advisories/GHSA-pg9f-39pc-qf8g / https://rustsec.org/advisories/RUSTSEC-2025-0024.html
```
cargo update -p openssl --precise 0.10.72
cargo update -p tokio --precise 1.44.2
cargo update -p crossbeam-channel --precise 0.5.15
```
=> chore: Update `openssl`,  `tokio`, and `crossbeam-channel`  packages

Cargo.lock, Cargo.toml, tests/tests/helpers.rs, tests/tests/jieba.rs, tokenizers/Cargo.toml, tokenizers/src/manager.rs
Integrates the tantivy-jieba crate, allowing users to select 'jieba' as a tokenizer type for BM25 indices. Includes basic tokenization and indexing tests.
NOTE: I am very much in "no one knows you're a dog on the internet" mode here, since 2.5 pro has done the heavy lifting here. I can only say that: 
* I built it locally against pg native and the docker versions; 
* I got it working, created tests, checked them, they passed;
* pgrx dependencies were giving me exceptional grief and I skipped the pre-commit hooks after spending even more time trying to sort that than hacking on the actual extension itself. It appears to be a Mac + C interaction, and I simply exhausted all available methods short of jumping to linux and doing everything again. 
- Closes #2490
This PR adds support for the …
=> feat: add tantivy-jieba tokenizer support

Cargo.lock, benchmarks/Cargo.toml, pg_search/Cargo.toml, pg_search/src/lib.rs, pg_search/src/postgres/datetime.rs, pg_search/src/postgres/storage/block.rs, pg_search/src/postgres/storage/merge.rs, tests/Cargo.toml, tests/tests/fixtures/db.rs, tokenizers/Cargo.toml
- Closes #
This upgrades all our dependencies -- work inspired by #2493.
Needed to follow `bincode`'s migration guide from https://docs.rs/bincode/2.0.1/bincode/migration_guide/index.html to ensure backwards compatibility with existing serialized SegmentMetaEntry and MergeEntry instances.
Everything still passes, tho it was necessary to make test database names more unique in our "Db" fixture, which was surprising.
=> chore: upgrade all dependencies

pg_search/src/index/fast_fields_helper.rs, pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs
- Closes #2453
Moves the choice of execution method to the planning phase, so that we can directly consume the chosen method to make assertions about the properties of the output.
As described on #2453: the current split can cause the type of confusion exemplified by #2452, where although a property like `sort_direction` is set on the builder, whether it is actually _used_ is not known until an execution method is chosen. For example: the `TopN` execution mode will consume the `sort_direction` and `limit`, but other execution modes will not apply a sort.
Introduce `enum ExecMethodType`, which is chosen during planning and then consumed verbatim during execution to construct the `ExecMethod`. 
Existing tests.
=> chore: Move the selection of the custom scan execution method to planning

docker/Dockerfile, docs/deploy/self-hosted/high-availability/configuration.mdx
Explain new (highly) recommended replication settings for `enterprise` users.
As the docs explain: failing to set these settings will result in frequent query cancels.
New section of the `High Availability > Configuration` page.
n/a
=> feat: Physical replication recommended settings docs

.github/workflows/test-pg_search-benchmark.yml, .github/workflows/test-pg_search-stressgres.yml
- Closes #N/A
When a partially completed job gets cancelled because a new run of the same commit was triggered, it shows as a red X in GitHub UI. Even though the job hasn't "failed", it was just skipped. This is because Microsoft hates us and loves money.
This PR cannot fully solves this, but it will at least make jobs that haven't launched yet and get cancelled do so with a green check. Because green is good.
^
^
^
=> ci: Avoid some red Xs in CI

.cursor/rules/03-development-workflow.mdc, scripts/pg_search_test.sh
Fixes path references and script issues
Fixed two issues:
1. Corrected command-line argument handling in pg_search_test.sh
2. Fixed incorrect path references in development workflow documentation
1. The test script had incorrect syntax for passing arguments (`$"@"` instead of `"$@"`)
2. Documentation examples incorrectly referenced scripts with `../scripts/` path instead of `./scripts/`
1. Fixed the argument handling in pg_search_test.sh
2. Updated path references in development documentation
3. Removed redundant `psql` command in documentation example
These changes fix script execution and documentation; no functional test changes needed.
=> chore: fixed two minor issues in cursor rules and test runner script.

pg_search/src/postgres/customscan/pdbscan/exec_methods.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/normal.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/parallel.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, pg_search/src/postgres/mod.rs, tests/tests/custom_scan.rs
- Closes #2472
Fix for missing results in nested loop joins when ParadeDB custom scans are rescanned.
When PostgreSQL executes a nested loop join, it calls `rescan_custom_scan` for the inner relation (potentially multiple times). Our custom scan implementation wasn't properly resetting its state between rescans, causing either missing results.
1. Added a `reset()` method to `PdbScanState` that properly resets all relevant state variables
2. Added reset implementations for all exec methods (TopN, Normal, FastFields)
3. Called `reset()` when `rescan_custom_scan` is invoked
4. Refactored the scan initialization logic to separate it from rescan logic
Added comprehensive test case that reproduces the issue in both parallel and non-parallel modes:
- Created a minimal reproducible test case with …
=> fix: proper scan state reset on `rescan_custom_scan`

pg_search/sql/pg_search--0.15.18--0.15.19.sql
- Closes #
The drop on `index_info` needs to cascade to the `index_layer_info` view.
=> chore: fix `0.15.19` upgrade script

pg_search/src/index/fast_fields_helper.rs, pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs
- Closes #2505.
Revert #2492.
The target lists used during planning and execution were different, and so #2492 resulted in #2505.
Revert #2492 for now, and then we can re-land it later with a test for #2505, and an appropriate target list.
=> fix: Revert "Move the selection of the custom scan execution method to planning (#2492)"

pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, tests/tests/custom_scan.rs
- Closes #2511
As described in #2511, it's currently possible for a TopN scan to get stuck in an endless loop if the index/data is structured in just the right way.
This fixes it by continuing to expand the "top n" results from tantivy until we've accepted "N" visible docs or we've read every possible matching doc from the segment.
By essentially not having a limit to the "MAX_CHUNK_SIZE".  It's now capped at u32::MAX, which is the max number of docs a segment could possibly contain.
A full re-create has been added.
=> fix: Issue #2511 -- TopN scans no longer endless loop

pg_search/src/postgres/customscan/pdbscan/parallel.rs, tests/tests/custom_scan.rs
- Closes #2515 
`compute_nworkers` uses `max_parallel_workers_per_gather` instead of `max_parallel_workers`.
This is the correct setting to use.
Added test for parallel custom and index only scans.
=> fix: parallel scans respect `max_parallel_workers_per_gather`

pg_search/src/api/operator.rs, tests/tests/sqlsmith.rs
- Closes #
`sqlsmith` discovered a crash due to dereferencing a null pointer.  This "fixes" it by checking the pointer before dereferencing it.
Crashing is bad
```shell
$ sqlsmith --verbose --target="host=localhost port=5416 dbname=sqlsmith user=smith" --exclude-catalog --log-to="host=localhost port=5416 dbname=sqlsmith_log user=smith"
```
After a few minutes `sqlsmith` would generate a query akin to this that caused the crash.
The exact query sqlsmith generated has been added as a rstest.
=> fix: prevent crash from malformed subquery

pg_search/src/index/fast_fields_helper.rs, pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, scripts/pg_search_run.sh, tests/tests/custom_scan.rs, tests/tests/index_config.rs
This reverts commit 31665d1bad2456de6ba273c71bd3d3c190b9090f.
- Closes #2505
- Closes #2453
- 
This PR fixes an issue with incorrect query plans for JOIN operations with string fast fields. The bug caused an assertion failure with the error `natts == self.inner.which_fast_fields.len()` when executing JOINs that reference TEXT fields in JOIN conditions.
When handling JOIN queries, the system needs to be aware of all columns referenced throughout the query, not just those in the target list. The issue occurred because:
1. The execution method selection only considered columns in the target list
2. For JOIN queries, additional columns used in JOIN conditions weren't properly accounted for
3. This led to choosing specialized execution methods (like StringFastFieldExecState) when they couldn't …
=> fix: move the selection of the custom scan execution method to planning

pg_search/src/index/fast_fields_helper.rs, pg_search/src/lib.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/mod.rs, pg_search/src/postgres/utils.rs, tests/tests/query.rs, tests/tests/str_ff_exec.rs
- Closes #
Some of these allow annotations have bothered me for awhile and so now they're gone.
In particular, we now lookup the `USING bm25`'s index access method handler `pg_sys::Oid` in a new way -- by asking the SysCache.
These `#[allow(...)]` could hide bugs, and in fact, the `#![allow(unpredictable_function_pointer_comparisons)]` likely was, which was the impetus for rejiggering how we determine if an index is a `USING bm25` index.
All existing tests pass
=> chore: remove some `#[allow(...)]` annotations

tests/tests/layered_merge.rs
- Closes #
I think the issue is that sometimes a merge isn't happening, so perform more inserts so that a merge has to be triggered.
=> fix: make `dont_merge_create_index_segments` test less flakey

Cargo.lock, pg_search/Cargo.toml, pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, tests/tests/custom_scan.rs
- Closes #2526 
The previous logical scan implementation had a logical bug when converting `And`s with nested `Or`s into a `SearchQueryInput`
Fix wrong results being returned
- Introduced proptests to check for logical equivalence in the conversion.
- Wrote an integration test to make sure there's no regression
=> fix: Incorrect `SearchQueryInput` generated by custom scan

Cargo.lock, Cargo.toml
- Closes #
Upgrades to pgrx v0.14.3 so we can use the fixes to `cargo pgrx regress`
=> chore: upgrade to pgrx v0.14.3

pg_search/src/postgres/customscan/pdbscan/pushdown.rs, pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, pg_search/tests/pg_regress/expected/issue_2528.out, pg_search/tests/pg_regress/expected/setup.out, pg_search/tests/pg_regress/sql/issue_2528.sql, pg_search/tests/pg_regress/sql/setup.sql, tests/tests/pushdown.rs
- Closes #2528 
Introduces a new struct that wraps around a `pg_sys::Var` that checks if the corresponding field is actually indexed.
Right now, certain queries error unless the custom scan is explicitly disabled.
Added pg_regress test
=> fix: custom scan tries to push down quals that aren't indexed

.github/workflows/test-pg_search-upgrade.yml
- Closes #
Bumps the version from `0.15.0` to `0.15.6`, since `0.15.0` was using a forked version of pgrx that no longer exists.
=> fix: Bump upgrade CI test version to `0.15.6`

.github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/lint-rust.yml, .github/workflows/publish-pg_search-debian.yml, .github/workflows/publish-pg_search-rhel.yml, .github/workflows/publish-pg_search-ubuntu.yml, .github/workflows/test-pg_search-benchmark.yml, .github/workflows/test-pg_search-stressgres.yml, .github/workflows/test-pg_search-upgrade.yml, .github/workflows/test-pg_search.yml, pg_search/src/api/operator/searchqueryinput.rs, pg_search/src/index/fast_fields_helper.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/builders/custom_state.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mixed.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, pg_search/src/postgres/scan.rs, pg_search/tests/pg_regress/expected/mixedff_advanced_01_aggregation.out, pg_search/tests/pg_regress/expected/mixedff_advanced_05_union_window_functions.out, pg_search/tests/pg_regress/expected/mixedff_advanced_06_score_function.out, pg_search/tests/pg_regress/expected/mixedff_advanced_09_multi_index_search.out, pg_search/tests/pg_regress/expected/mixedff_queries_01_complex_join.out, pg_search/tests/pg_regress/expected/mixedff_queries_03_cte_test.out, pg_search/tests/pg_regress/expected/mixedff_queries_04_subquery.out, rust-toolchain.toml, tests/tests/custom_scan.rs
- Closes #2556.
Moves to extracting fast fields from `RelOptInfo.reltarget.exprs` at planning time, which resolves the issue identified in #2554 and #2556 by ensuring that we always extract more fast fields at planning time than at execution time (which is now logged as a fallback in `compute_exec_which_fast_fields`, but which we haven't encountered any cases of in our tests). 
Ensuring that all fast fields are located at planning time allows us to revert the portion of #2554 which made `WhichFastFields` optional. Optional fast fields caused #2556, because NULLs would be emitted for any fast fields which we failed to detect. That caused a recurrence of #2505.
The failure was seemingly masked by missing `VACUUM`/`ANALYZE` statements, meaning that some tests which would otherwise have …
=> fix: Extract fast fields in more locations at planning time

Cargo.lock, tests/Cargo.toml, tests/tests/fixtures/querygen/joingen.rs, tests/tests/fixtures/querygen/mod.rs, tests/tests/fixtures/querygen/wheregen.rs, tests/tests/qgen.proptest-regressions, tests/tests/qgen.rs
#2540 added `qgen` tests, which generate and compare many valid queries between btree and bm25 indexes: that infrastructure uncovered real bugs (see #2534).
This change migrates the existing `qgen` tests to tests atop the Rust `proptest` crate, and adds an additional test which reproduces #2544 and #2556.
`proptest` allows for randomly exploring a very large set of possible inputs. When it finds a failing input, it reduces the input as much as possible, and then records the failing seed in a file. Reproducing a failure that it has produced just requires re-running the test (which will start by trying all seeds it has ever seen fail based on the `regressions` file).
When reproducing the failure from #2533 for example, `proptest` automatically minimizes the failure to a much smaller query …
=> test: Convert `gqen` to `proptests`

pg_search/src/postgres/customscan/explainer.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/tests/pg_regress/expected/mixedff_advanced_01_aggregation.out, pg_search/tests/pg_regress/expected/mixedff_advanced_02_mixed_fast_non_fast.out, pg_search/tests/pg_regress/expected/mixedff_advanced_03_limit_topn.out, pg_search/tests/pg_regress/expected/mixedff_advanced_04_execution_method_selection.out, pg_search/tests/pg_regress/expected/mixedff_advanced_05_union_window_functions.out, pg_search/tests/pg_regress/expected/mixedff_advanced_06_score_function.out, pg_search/tests/pg_regress/expected/mixedff_advanced_07_recursive_cte.out, pg_search/tests/pg_regress/expected/mixedff_advanced_08_type_conversion.out, pg_search/tests/pg_regress/expected/mixedff_advanced_09_multi_index_search.out, pg_search/tests/pg_regress/expected/mixedff_basic_01_basic_mixed_fields.out, pg_search/tests/pg_regress/expected/mixedff_basic_02_multiple_string_fields.out, pg_search/tests/pg_regress/expected/mixedff_basic_03_multiple_numeric_fields.out, pg_search/tests/pg_regress/expected/mixedff_basic_04_mixed_field_types.out, pg_search/tests/pg_regress/expected/mixedff_edgecases_01_corner_cases.out, pg_search/tests/pg_regress/expected/mixedff_edgecases_02_null_handling.out, pg_search/tests/pg_regress/expected/mixedff_edgecases_03_string_edge_cases.out, pg_search/tests/pg_regress/expected/mixedff_edgecases_04_complex_string_patterns.out, pg_search/tests/pg_regress/expected/mixedff_queries_01_complex_join.out, pg_search/tests/pg_regress/expected/mixedff_queries_02_order_by.out, pg_search/tests/pg_regress/expected/mixedff_queries_03_cte_test.out, pg_search/tests/pg_regress/expected/mixedff_queries_04_subquery.out
- N/A
This PR removes the "Segment Count" field from the ParadeDB scan's explainer output when the `COSTS` option is turned off, making the output more stable when used in our pgregress tests.
The "Segment Count" information is not stable and can differ from one execution to another.
1. Added an `is_costs()` method to the `Explainer` struct to check if costs should be displayed
2. Modified the `explain_custom_scan` function to conditionally display "Segment Count" only when `explainer.is_costs()` returns true
3. Updated the regression test outputs to reflect the change
All existing tests have been updated to reflect the new explainer output formatting. The tests verify that "Segment Count" is no longer shown when costs are turned off.
=> chore: removed "Segment Count" from the explainer if `COSTS` are turned off.

.github/workflows/lint-rust.yml
Explicitly request the `clippy` and `rustfmt` components for the `lint` CI job.
In some cases, the `lint` CI job does not already have the `rustfmt` component installed.
=> chore: Use explicit components in the lint job.

tests/tests/fixtures/mod.rs, tests/tests/qgen.rs
Enable `log_min_duration_statement` for our integration tests.
Our CI job reports the Postgres logs at the end of the run, and we occasionally have long running queries produced by the proptests -- reporting long running statements will help us track down and reduce the cost of those tests.
=> test: Enable long-running-statement logging in tests

pg_search/src/postgres/customscan/pdbscan/exec_methods.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mixed.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/normal.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/parallel.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, pg_search/src/postgres/customscan/pdbscan/solve_expr.rs, pg_search/tests/pg_regress/expected/issue_2564-parallel.out, pg_search/tests/pg_regress/expected/issue_2564.out, pg_search/tests/pg_regress/expected/mixedff_queries_04_subquery.out, pg_search/tests/pg_regress/sql/issue_2564-parallel.sql, pg_search/tests/pg_regress/sql/issue_2564.sql
- Closes #2564
`NormalScanExecState` was failing to reset enough of its internal state to realize that during a rescan it should actually execute the query again.
It's worth noting that the bug itself, despite the report in #2564, is not dependent on `ANALYZE` so much as post-ANALYZE, postgres would choose an entirely different query plan which didn't involve rescans, so this bug wasn't tickled.
Fixed the bug and also removed the default implementation for `ExecMethod::reset()` so that implementors are kinda required to consider what they need to do.
New regression test added based on the repro from #2564 (which shares common DDL with other regression tests).
It also introduced a change in expected output in an existing regression test/query and after some analysis, the change is correct. …
=> fix: issue #2564 -- `NormalScanExecState` now properly resets on rescans

scripts/pg_search_run.sh
- N/A
Fixed the `pg_search_run.sh` script to properly handle command-line arguments by separating arguments meant for the script from those intended for `psql`.
The previous implementation incorrectly passed all arguments to `psql` using `$@`, which could cause issues when trying to pass arguments specifically to the script itself.
- Added a new `OTHER_ARGS` array to store arguments intended for `psql`
Manually verified that the script correctly handles arguments, passing only the relevant ones to `psql`.
=> chore: fixed the run script not to pass all args to psql.

pg_search/src/lib.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, tests/tests/qgen.rs
- Closes #
This is improves (and in some cases corrects) our custom scan's cost and selectivity estimation.
Providing more accurate costs can allow Postgres to choose better plans for any given query.
A few things:
- when a query contains a `Qual::ExternalVar`, then our scan will output all rows, so the selectivity in that case now gets set to `1.0`
- when parallel workers are to be used, we need to divide the selectivity by the number of workers so that we can better indicate the number of tuples any given worker will emit
- fix a bug where we'd use an existing `norm_selc` of -1.0 on accident!
- we also had situations where the "total cost" would be calculated as `0.0`, which is, of course, incorrect too
This is all (mostly) isolated to the custom scan's `callback` function and …
=> fix: estimate improvements

Cargo.lock, Cargo.toml, pg_search/src/index/fast_fields_helper.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mixed.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/numeric.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/string.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, tests/tests/pushdown.rs
- Closes #2619.
Builds atop #2610 to make fast field execution lazier. `StringFF` and `MixedFF` were both merging _across_ segments, but that will almost never show a benefit, because a `DocAddress` can only come from one segment, and if we _were_ going to merge across segments, we'd want to do so via lazy, sorted order iterators (as introduced here).
Make fast fields faster, and prepare to enable sorting of fast fields (#2623).
* Replace `sorted_ords_to_terms` with a `ords_to_sorted_terms` function which produces an iterator of sorted terms.
* Remove the cross-segment batching/grouping that `StringFF` and `MixedFF` were doing.
* `StringFF` now lazily emits results from each segment in sorted order, meaning that it never has the full set of strings for a segment in memory (only the …
=> perf: Make fast field execution lazier

pg_search/src/api/aggregate.rs, pg_search/src/parallel_worker/mqueue.rs, pg_search/tests/pg_regress/expected/aggregate-udf.out, pg_search/tests/pg_regress/sql/aggregate-udf.sql
- Closes #
`paradedb.aggregate()` had the potential to crash if no parallel workers were available.
This fixes that bug (in `mqueue.rs`) and then addresses the situation of not being able to spawn workers in `aggregate()` by just running the aggregate right there in the calling backend.
customer report and crashing is bad!
Existing tests pass.  It's a little difficult to write a test to expose this as it requires concurrent backends where one has consumed all available parallel worker slots.
I can at least confirm my manual test to recreate this now works as expected.
=> fix: `paradedb.aggregate()` won't crash if it couldn't launch workers

docs/documentation/configuration/write.mdx, pg_search/src/gucs.rs, pg_search/src/index/writer/index.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, tests/tests/aborted_xact.rs
- Closes #
We now use the `SerialIndexWriter` to insert rows during `aminsert()`, which seems to essentially double INSERT/UPDATE performance of small, single-row statements.
This then led to `SearchIndexWriter` being renamed to `SearchIndexDeleter` because now it's only used by `ambulkdelete()`.
We're basically one step away from being able to completely delete the `ChannelDirectory` and all the complexity it contains!
As a result of all this, the `paradedb.statement_parallelism` GUC is now gone.  Internally we keep the concept, but it's hardcoded to 1 -- Postgres doesn't support parallel worker-based INSERT/UPDATE/COPY statements.
It's a clear performance win mostly by removing the `ChannelDirectory` from this code path.
All existing tests pass.  Stressgres locally looked good with a …
=> perf: improve INSERT/UPDATE perf with `SerialIndexWriter`

pg_search/src/schema/mod.rs, pg_search/tests/pg_regress/expected/find_ctid.out, pg_search/tests/pg_regress/sql/find_ctid.sql
Like the title says, we also need to be able to construct a `SearchField` instance for the postgres "ctid" system column.  This was a minor regression from #2660, because now we only rely on the index's TupleDescriptor to lookup attributes.
Specifically, the `paradedb.find_ctid()` was broken due to this, which is something used in some stressgres test suites.
Yes, yes there's a new one to assert that `paradedb.find_ctid()` works.
=> fix: should be able to construct a `SearchField` for `ctid`

pg_search/src/api/builder_fns.rs, pg_search/src/api/mod.rs, pg_search/src/api/operator.rs, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/reader/index.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/build_parallel.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, pg_search/src/postgres/customscan/pdbscan/projections/mod.rs, pg_search/src/postgres/customscan/pdbscan/projections/snippet.rs, pg_search/src/postgres/customscan/pdbscan/pushdown.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/utils.rs, pg_search/src/postgres/var.rs, pg_search/src/query/mod.rs, pg_search/src/schema/mod.rs
This renames `src/api/index.rs` to `src/api/builder_fns.rs` and then moves the `struct FieldName` type and its associated trait impls and functions to `src/api/mod.rs`.
Having multiple `index.rs` files in the repo has annoyed me for a very long time.
There's no functional changes here.  Everything was shifted around using RustRover's refactoring tools.
n/a
=> chore: rename module and move type

pg_search/src/schema/mod.rs, pg_search/tests/pg_regress/expected/fast_fields_options.out, pg_search/tests/pg_regress/expected/issue_2688.out, pg_search/tests/pg_regress/expected/top_n_scan.out, pg_search/tests/pg_regress/sql/issue_2688.sql
- Closes (partially) #2688 
`is_sortable` was erroneously emitting `true` when the field was a range field -- we have not implemented support for this so it should return `false`.
=> fix: Fall back to Postgres when sorting by range field

pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/options.rs, pg_search/tests/pg_regress/expected/mixedff_basic_05_uuid.out, pg_search/tests/pg_regress/sql/mixedff_basic_05_uuid.sql
- Closes #2703
As described in #2703, UUID columns which are indexed as `fast` are incorrectly interpreted as numeric fast fields during `collect_fast_fields`. This fails at execution time for `Mixed` and `String` fast field execution modes.
Relatedly: a `UUID` `key_field` was not correctly being configured as `fast` at index creation time, meaning that scans using it would not use the fast field execution methods.
To fix the crash described on #2703, and to allow fast-field execution to be used in more cases.
In two commits:
1. fix the `FastFieldType` which is extracted for a UUID
2. fix the `key_field` configuration that is used for a UUID
The latter change is backwards compatible, but gaining the advantage of the fast UUID field will require a reindex.
Added a repro test which now …
=> fix: Allow UUID columns to be used in fast field execution

docs/documentation/full-text/sorting.mdx, docs/documentation/indexing/create_index.mdx, pg_search/src/api/operator.rs, pg_search/src/api/operator/searchqueryinput.rs, pg_search/src/api/operator/text.rs, pg_search/src/index/search.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/build_parallel.rs, pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, pg_search/src/postgres/expression.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/mod.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/utils.rs, pg_search/src/query/more_like_this.rs, pg_search/src/schema/mod.rs, tests/tests/expression.rs, tests/tests/index_config.rs
- Closes #1936 
This PR add support for expressions in pg_search's BM25 indexes.
Users can now directly use expressions instead of using generated columns to have the same result.
This PR supports both query syntaxes, here are some examples extracted from the tests:
```sql
=> CALL paradedb.create_bm25_test_table(table_name => 'index_config', schema_name => 'paradedb');
CALL
=> CREATE INDEX index_config_index ON paradedb.index_config
USING bm25 (id, lower(description)) WITH (key_field='id');
CREATE INDEX
=> INSERT INTO paradedb.index_config (description) VALUES ('Test description');
INSERT 0 1
=> SELECT count(*) FROM paradedb.index_config WHERE index_config @@@ paradedb.term('_pg_search_1', 'test');
count
-------
1
(1 row)
=> SELECT count(*) FROM paradedb.index_config WHERE …
```
=> feat: support expressions in indexes

pg_search/src/schema/config.rs, pg_search/tests/pg_regress/expected/misconfigured_configs.out, pg_search/tests/pg_regress/sql/misconfigured_configs.sql
- Closes #
In #2660 I made serde throw an error for invalid index configs. While this was an improvement for new indexes it unintenionally broke existing indexes. This PR reverts that change until we're ready for a breaking release.
Added a regression test
=> fix: make incorrect configs not error

pg_search/src/api/aggregate.rs, pg_search/src/index/fast_fields_helper.rs
Use batch lookups for the `ctid` in aggregates, and re-use buffers.
Although fast fields do not have optimized decoding for batch lookups, they do have a small amount of loop unrolling for batch lookups via the [`first_vals` and `get_vals_opt` methods](https://github.com/paradedb/tantivy/blob/3ffaeb8e0c44e07e03a5d27423eee843bf87a0bc/columnar/src/column_values/mod.rs#L84-L109).
Adjustments to the benchmark suite to use `paradedb.aggregate` show a 5% to 20% performance improvement for MVCC-aware aggregates.
=> perf: Batch field lookups in MVCC-aware aggregates

pg_search/tests/pg_regress/expected/parallel_build_large.out, pg_search/tests/pg_regress/sql/parallel_build_large.sql
- Closes #
In CI, the parallel build regression test can sometimes create one or two segments fewer than the target. So loosen our constraints around that.
=> chore: stabilize regression output

pg_search/src/index/directory/mvcc.rs, pg_search/src/index/reader/index.rs, pg_search/src/index/search.rs, pg_search/src/index/writer/index.rs, pg_search/src/postgres/build_parallel.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/insert.rs, pg_search/src/schema/mod.rs
In nearly every case we have enough information to construct a `SearchIndexSchema` without also needing to instantiate a `MVCCDirectory` and a tantivy `Index`.
Invent a new function, `SearchIndexSchema::from_index()` to require the caller to pass the necessary information and update all the old compatible `SearchIndexSchema::open()` call points.
General code cleanup and also removes overhead of opening an Index and MVCCDirectory when we already have them.
=> chore: cleanup around `SearchIndexSchema::open()`

docs/docs.json, docs/documentation/configuration/index.mdx, docs/documentation/configuration/segment_count.mdx, pg_search/src/gucs.rs, pg_search/src/postgres/build_parallel.rs, pg_search/src/postgres/options.rs, pg_search/tests/pg_regress/expected/parallel_build_empty.out, pg_search/tests/pg_regress/expected/parallel_build_large.out, pg_search/tests/pg_regress/expected/parallel_build_small.out, pg_search/tests/pg_regress/sql/parallel_build_empty.sql, pg_search/tests/pg_regress/sql/parallel_build_large.sql, pg_search/tests/pg_regress/sql/parallel_build_small.sql
Adds a new index `WITH` option to let users set the `target_segment_count`.
It probably makes sense to have this value as a property of the index itself so that the same value can be reused during REINDEX.  If unspecified it defaults to the  number of CPUs on the host system.
After discussions with @rebasedming, we have decided to remove the `paradedb.target_segment_count` GUC.
Existing tests that used the old GUC have been updated to use this new index option.  Docs updated too.
=> feat: add `target_segment_count` as an index `WITH` option

pg_search/src/gucs.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/qual_inspect.rs, pg_search/tests/pg_regress/expected/issue_2753.out, pg_search/tests/pg_regress/sql/issue_2753.sql, tests/tests/custom_scan.rs
- Closes #2753
When extracting quals from a join `RestrictInfo`, we will convert vars into external vars. But one of the cases of that conversion was not covered by a check that we were extracting quals for a join.
Additionally, add an enabled-by-default `paradedb.enable_custom_scan_without_operator` GUC to control whether the custom scan can be used when we've successfully found expressions to push down, but have _not_ found use of our operator.
See #2753.
Added the repro from #2753, and added a test of the new GUC.
=> fix: Do not convert vars to external on a base relation

docs/documentation/indexing/create_index.mdx
Adds documentation for creating indexes on expressions, as implemented in #2389
=> feat: documentation for indexes on expressions

pg_search/src/gucs.rs, pg_search/tests/pg_regress/expected/issue_2745.out, pg_search/tests/pg_regress/expected/mixedff_advanced_03_limit_topn.out, pg_search/tests/pg_regress/expected/mixedff_advanced_07_recursive_cte.out, pg_search/tests/pg_regress/expected/mixedff_advanced_09_multi_index_search.out, pg_search/tests/pg_regress/expected/mixedff_queries_04_subquery.out, pg_search/tests/pg_regress/expected/pushdown_scalar_array_opexr.out, pg_search/tests/pg_regress/expected/score_join_predicates.out, pg_search/tests/pg_regress/expected/score_non_indexed_predicates.out, pg_search/tests/pg_regress/expected/unified_expression_comprehensive.out, pg_search/tests/pg_regress/sql/pushdown_scalar_array_opexr.sql, tests/tests/fixtures/querygen/mod.rs, tests/tests/pushdown.rs
- N/A
PR #2639 was causing write throughput regression.
We will disable the `paradedb.enable_custom_scan_without_operator` GUC by default.
=> fix: reverted "feat: always do pushdowns when we can"

.github/stressgres/bulk-updates.toml, pg_search/src/api/operator/searchqueryinput.rs, pg_search/src/bootstrap/create_bm25.rs, pg_search/src/index/directory/mvcc.rs, pg_search/src/index/directory/utils.rs, pg_search/src/index/reader/index.rs, pg_search/src/index/search.rs, pg_search/src/index/writer/index.rs, pg_search/src/postgres/build.rs, pg_search/src/postgres/build_parallel.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/rel.rs, pg_search/src/postgres/scan.rs, pg_search/src/postgres/storage/utils.rs, pg_search/src/postgres/utils.rs, pg_search/src/query/mod.rs, pg_search/src/query/more_like_this.rs, pg_search/src/schema/mod.rs, pg_search/tests/pg_regress/expected/index_config_errors.out, pg_search/tests/pg_regress/expected/top_n_scan.out, pg_search/tests/pg_regress/sql/index_config_errors.sql, tests/tests/index_config.rs
#2660 brought a much needed round of cleanups to how we manage index schemas.  Unfortunately, it introduced quite some overhead in reading/decoding/validating the schema.  This process was happening quite a bit throughout the execution paths of `aminsert` and other hot-spots.
#2176 brought the ability to essentially keep one heavy-weight `PgSearchRelation` instantiated and cheaply clone it when necessary.  This PR cleans up things further such that the `SearchIndexSchema` is now a lazily-evaluated property of `PgSearchRelation`.  This means `SearchIndexSchema` is only evaluated when needed, and then only once (at least per statement).
Furthermore, its internal properties are lazily-evaluated, ensuring any given code path doesn't do more work than it needs.
This also renames …
=> chore: more improvements to index/schema configuration and management

Cargo.lock, benchmarks/Cargo.toml, benchmarks/src/main.rs
Dedupe index creation and query running across `md`/`csv` output formats, and add support for emitting `json` from the query benchmark job.
In order to graph them in https://github.com/benchmark-action/github-action-benchmark
Manually validated that all `--output` modes produce expected results.
=> chore: Add support to the benchmark tool for emitting JSON

pg_search/src/api/aggregate.rs, pg_search/src/parallel_worker/mod.rs, pg_search/tests/pg_regress/expected/aggregate-udf.out, pg_search/tests/pg_regress/sql/aggregate-udf.sql
- Closes #
We were passing `-1` to `chunk_range`, which takes `usize`, leading to an underflow -> wrapping around. Additionally, the existing `aggregate_udf` test thinks it's testing over multiple segments but actually isn't -- if it had, it would have triggered this error.
Updated existing test
=> fix: "attempt to multiply with overflow" error in `paradedb.aggregate`

.github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/test-pg_search-docker.yml
- Closes #N/A
- Don't make Docker Scout post on PRs that don't modify the Dockerfile, not necessary.
- Make sure the SchemaBot workflow errors when community contributors make a PR, so we can catch needed changes to the SQL upgrade script.
- Rename it to SchemaBot
QoL
^
CI
=> ci: Post "One-branch Release Model" Improvements

.github/workflows/test-pg_search-benchmark.yml
Increase the run count in for the readonly queries.
To reduce noise in https://paradedb.github.io/paradedb/benchmarks/
=> chore: Increase benchmark run count to reduce noise.

.github/workflows/test-pg_search-benchmark.yml, .github/workflows/test-pg_search-stressgres.yml
let benchmark jobs run concurrently
=> ci: remove the cancel-in-progress

.github/workflows/test-pg_search-benchmark.yml, .github/workflows/test-pg_search-stressgres.yml
Adjusts the new benchmark jobs to run and comment on `perf:` PRs (without pushing to the graphs).
To more easily evaluate that `perf:` PRs do what they say on the tin.
* Run for PRs with `perf` in their title.
* Calculate the sha once, potentially from the PR head.
* Give permission to comment on PRs.
* Always comment on perf PRs.
Manual testing via the PR: see comments made by the gitub-actions bot here.
=> perf: Adjust benchmark job to post for `perf` PRs.

.github/workflows/test-pg_search-benchmark.yml, .github/workflows/test-pg_search-stressgres.yml
Adjust benchmarks jobs to automatically run when the `benchmark` label is applied.
#2820 failed to actually filter to `perf:`-titled PRs, but additionally, in practice that would have been too noisy, since they would have re-run on every push to the PR.
Manually tested adding/removing the label.
=> chore: Run benchmarks on `benchmark`-labeled PRs.

.github/actions/benchmark-benchmarks/action.yaml, .github/actions/benchmark-stressgres/action.yaml
ConcurrentCI runners can all end up trying to publish at the exact same time and to avoid locking confusion with git, we introduce a random sleep between 1 and 61 seconds before each publish step.
=> ci: we (likely) need to sleep before publishing benchmarks

.github/workflows/benchmark-pg_search-benchmarks.yml, .github/workflows/benchmark-pg_search-stressgres.yml
The new benchmark `action.yaml` files don't exist in historical commits, which is what the benchmarks also test during a backfill.
So always use whatever is at `main`.
=> ci: use the custom/composite actions from @main

.github/workflows/benchmark-pg_search-benchmarks.yml, .github/workflows/benchmark-pg_search-stressgres.yml
we need to fetch the latest action definitions from `main`
=> ci: fix where the custom actions are to be found

Cargo.lock, Cargo.toml
Lazily load fast field dictionaries from buffers: see https://github.com/paradedb/tantivy/pull/55
A customer reported slower-than-expected paging on a string/uuid column. 85% of the time for that query was being spent in _opening_ a fast fields string/bytes column, with a large fraction of that time spent fully consuming the column's `Dictionary`. 
See the attached benchmark results:
* [`docs` dataset](https://github.com/paradedb/paradedb/pull/2842#pullrequestreview-3014379545)
* No regressions.
* 2x faster for `top_n-score`
* 1.4x faster for `highlighting` 
* [`logs` dataset](https://github.com/paradedb/paradedb/pull/2842#pullrequestreview-3014350211)
* No regressions.
* 4.5x faster for `paging-string-max`
* 1.7x faster for `paging-string-median`
* 1.6x faster for `paging-string-min`
The …
=> perf: Lazily load fast fields dictionaries.

.github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/test-docs.yml, .github/workflows/test-pg_search-docker.yml, .github/workflows/test-pg_search-upgrade.yml, .github/workflows/test-pg_search.yml, RELEASE.md
Run most `main` CI jobs on PRs to stable branches (named `0.*.x`), and formalize them a bit in `RELEASE.md`.
=> chore: Formalize stable branches

.github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/test-docs.yml, .github/workflows/test-pg_search-docker.yml, .github/workflows/test-pg_search-upgrade.yml, .github/workflows/test-pg_search.yml
Run most `main` CI jobs on PRs to stable branches (named `0.*.x`), and formalize them a bit in `RELEASE.md`.
=> chore: Formalize stable branches (cherry-pick of #2848)

pg_search/sql/pg_search--0.16.3--0.16.4.sql, pg_search/sql/pg_search--0.16.4--0.17.0.sql
This fixes the upgrade script paths in light of today's 0.16.4 patch release.
There were no schema changes from 0.16.3 to 0.16.4, but there are going to be some from 0.16.4 to whenever we release 0.17.0
=> chore: fix schema upgrade scripts

.github/actions/benchmark-benchmarks/action.yml, .github/actions/benchmark-stressgres/action.yml
This uses variables to form the important bits of the Slack message link to the github pages repo.  Will fix links for enterprise benchmark reports.
=> ci: fix gh-pages link in slack messages

.github/actions/benchmark-benchmarks/action.yml
- Closes #N/A
This will replace:
by the same `PR #2870: chore: Upgrade to 0.17.0` but with the commit as a hyperlink to it, which I thought was cleaner and less noise.
^
^
^
=> ci: Make benchmark Slack notifs be a link

pg_search/src/api/operator.rs, pg_search/tests/pg_regress/expected/issue_2844-rls.out, pg_search/tests/pg_regress/sql/issue_2844-rls.sql
- Closes #2844
When the right-hand-side of the `@@@` operator is a complex expression that can't be evaluated to a `T_Const` during planning, we need to rewrite it to be a call to our `paradedb.with_index(<indexrelid>, <rhs>)` so that it can be properly used in Filter contexts during execution.
This seems to come up, at least, during RLS rule evaluation if those rules use our `@@@` operator.
So long as the right-hand-side of `@@@` is a `SearchQueryInput`, we need to be able to execute it when Postgres wants us to, whether that's during a scan or, as in this case, a filter being run as part of RLS evaluation.
Wrapping Postgres expression nodes!
I used the re-create the OP from #2844 put together as a regression test.  I seem to be lacking the creative energy today to reduce the test down …
=> fix: issue #2844 - Use `paradedb.with_index()` when necessary

.github/actions/benchmark-stressgres/action.yml
- Closes #N/A
We did this for benchmarks, but had forgotten for stressgres. Just easier to read.
^
^
^
=> chore: Make commit be hyperlink on its name for stressgres Slack notifs

.github/workflows/test-pg_search-upgrade.yml
Bump the upgrade job to a source version of `v0.15.19`.
It's the oldest version which currently works, due to Lindera URL changes.
=> chore: Bump upgrade job to a floor of `v0.15.19`

pg_search/src/index/reader/index.rs
`SearchIndexReader::{top_by_field_in_segments, top_by_string_field_in_segments}` were not using `SearchIndexReader::need_scores`, and were instead universally enabling scores.
Use the `enable_scoring` helper and `self.need_scores` to skip computing scores where possible.
Computing scores requires field norms, which ([if they have not been disabled](https://docs.paradedb.com/documentation/indexing/record)) can take time to load and use.
=> perf: Skip computing scores if not requested for top-n field queries

pg_search/src/postgres/customscan/pushdown.rs, pg_search/src/postgres/customscan/qual_inspect.rs
All `extern "C-unwind"` functions require the `#[pg_guard]` attribute.  We had a few that were missing it, which _could_ lead to a crash.
=> fix: add #[pg_guard] to extern C-unwind functions

pg_search/src/index/fast_fields_helper.rs, pg_search/src/index/reader/index.rs, pg_search/src/index/reader/scorer.rs, pg_search/src/postgres/customscan/builders/custom_path.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mixed.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/fast_fields/mod.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/tests/pg_regress/expected/mixedff_advanced_06_score_function.out
- Closes #2715
- Closes #2623
Adjust the `MixedFastField` executor to stream results, and only buffer up to a hard coded batch size in memory.
Additionally, avoid creating the intermediate tuple-like `FieldValues` structure, and directly consume the column values to produce a tuple in a postgres `Slot`.
Currently, the `MixedFastField` and `StringFastField` executors buffer entire columns in memory: that implementation will not scale to larger datasets. Moving to streaming allows them to be used with arbitrarily large datasets.
Removing the intermediate `FieldValues` creation also makes `MixedFastField` ~equivalent to `StringFastField` in terms of overhead: a followup change will remove `StringFastField`.
#2623 discussed potentially continuing to buffer entire columns and then declaring …
=> perf: Reduce buffering during mixed fast field scans

.github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/check-typo.yml, .github/workflows/lint-bash.yml, .github/workflows/lint-docker.yml, .github/workflows/lint-format.yml, .github/workflows/lint-markdown.yml, .github/workflows/lint-pr-title.yml, .github/workflows/lint-rust.yml, .github/workflows/lint-yaml.yml, .github/workflows/test-docs.yml, .github/workflows/test-pg_search-docker.yml, .github/workflows/test-pg_search-upgrade.yml, .github/workflows/test-pg_search.yml
Enable CI on PR drafts.
It is good to be able to run CI _before_ notifying your teammates that something is reviewable. Because we additionally use required-reviewers/owners, it is currently impossible to run CI without beginning to email all reviewers.
Moving forward: we should usually only post something as a Draft if we would like CI to run: for simply sharing a branch with someone, or for self-review without CI, we can use the [compare](https://github.com/paradedb/paradedb/compare) view. And we should only actually mark something reviewable when we would like the mentioned users to review it.
=> chore: Enable running CI for drafts.

pg_search/README.md
Because 0.13 is outdated.
https://github.com/paradedb/paradedb/blob/main/Cargo.toml#L31
- Closes #
=> chore: upgrade to pgrx v0.15.0

pg_search/src/api/operator.rs, pg_search/tests/pg_regress/expected/operators.out, pg_search/tests/pg_regress/sql/operators.sql
- Closes #
The new &&&,|||,###,=== operators are all defined to take a value of type TEXT on the left-hand-side.
If the lhs Var happens to be coercible to text, but not actually TEXT, such as VARCHAR, Postgres will wrap that Var node in a RelabelType, which we need to be able to see through in order to find the actual field being referenced on the left-hand-side of the operator.
The existing `operators.sql` regression test has been updated to also test using a VARCHAR field.  I can't think of any other types that Postgres will relabel to TEXT, especially among the set of data types we support.
=> fix: Node relabeling no longer defeats new operators

docs/docs.json
- Closes #N/A
A user reported that the link in our docs was outdated. Somehow all other links for Slack were this one, but the one in the docs was different. This fixes that.
People can join our Slack!
Just used the same invite link as we do everywhere else.
I verified it's correct in incognito.
=> docs: Fix broken Slack link

pg_search/Cargo.toml, pg_search/src/index/writer/segment_component.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/linked_bytes.rs, pg_search/src/postgres/storage/metadata.rs, pg_search/src/postgres/storage/utils.rs
When extending a relation the backend needs to clear the relation's `SMgrRelation`'s "SIZE_CACHE" so that it doesn't become confused about the size of a relation relative to other concurrent relation extensions that may have occurred.
Failure to do this can cause errors like the below under high read/write concurrency:
```
ERROR:  XX001: could not read blocks 10..10 in file "base/16384/16552": read only 0 of 8192 bytes
```
PR #2716 introduced this bug as it changed our approach of always calling `pg_sys::relation_open()` to the new `PgSearchRelation` which wraps an already-opened `pg_sys::Relation` pointer and is cheaply clone-able.  
Essentially, prior to #2716 we'd always get a new `SMgrRelation` and it would ask the kernel about the size of the relation on disk, whereas #2716 made us …
=> fix: relation extension cache invalidation

.github/workflows/test-pg_search-upgrade.yml
This is the first version of pg_search where we introduced `rust-toolchain.toml` which is pretty important in allowing today's CI job runner to compile the pg_search of yesterday.
Starting to see CI failures from our `test-pg_search-upgrade.yml` due to the world moving forward while old code doesn't.
=> ci: test pg_search upgrades starting from v0.16.1 (#2910)

pg_search/sql/pg_search--0.17.2--0.18.0.sql, pg_search/src/api/builder_fns/pdb.rs, pg_search/src/api/operator.rs, pg_search/src/api/operator/andandand.rs, pg_search/src/api/operator/atatat.rs, pg_search/src/api/operator/boost.rs, pg_search/src/api/operator/eqeqeq.rs, pg_search/src/api/operator/fuzzy.rs, pg_search/src/api/operator/hashhashhash.rs, pg_search/src/api/operator/ororor.rs, pg_search/src/index/reader/index.rs, pg_search/src/query/mod.rs, pg_search/src/query/pdb_query.rs, pg_search/tests/pg_regress/expected/fuzzy.out, pg_search/tests/pg_regress/sql/fuzzy.sql
Introduces a new SQL type named `fuzzy(N, b, b)` that can be used in various query contexts to indicate that the term(s) being searched for should be "fuzzy terms".
Some examples:
```sql
SELECT * FROM t WHERE f === 'beer'::fuzzy(2);   -- FuzzyTerm query
SELECT * FROM t WHERE f @@@ 'beer wine cheese'::fuzzy(2); -- QueryParser query with fuzzy set for the field "f"
SELECT * FROM t WHERE f &&& 'beer wine cheese'::fuzzy(2); -- Match conjunction query with fuzzy
SELECT * FROM t WHERE f ||| 'beer wine cheese'::fuzzy(2); -- Match disjunction query with fuzzy
```
The type modifier can take 3 arguments: a distance calculation in the range `0..=2` and two booleans written as either `t`/`f` or (literally) `"true"`/`"false"` (this is a Postgres restriction -- `true` or `false` on their own don't …
=> feat: ability to specify term "fuzzy"-ness via a cast to `::fuzzy(N)`

.github/workflows/test-pg_search-docker.yml, docker/Dockerfile, docker/docker-compose.dev.yml
- Closes #N/A
One of our customers reported that specifying the PostgreSQL data directory with `tmpfs` fails, exposing a permission issue. Meanwhile, doing the same with the upstreasm `postgres:latest` Docker image works. I reproduced and that's true.
- [8b938fe](https://github.com/paradedb/paradedb/pull/2954/commits/8b938fe6a9ccdadb6bad71a70d2eb205f0d7add4) makes our CI test properly catch this issue. Previously, our CI test did use a `--tmpfs` but it used the `tmp/` folder. That commit shows the error being reproduced.
- [07245cc](https://github.com/paradedb/paradedb/pull/2954/commits/07245cc2148862bd5a9c8d3557f68272d72c4522) removes the manually specified `USER postgres`, and provides an explanation. In short, the official Postgres container starts as root, runs chmod/chown to properly …
=> fix: Fix the permissions in the ParadeDB Docker image

pg_search/src/index/writer/segment_component.rs, pg_search/src/postgres/merge.rs
- Closes #
There were two places we were panicking if there was an interrupt: one at the end of `merge_index`, and another in the `Drop` impl of `ExactBuffer`.
=> fix: shouldn't panic if there was an interrupt

.github/workflows/publish-paradedb-docker.yml
When a version was specified directly via a workflow run, the `TAG` was not being set, causing the publish to fail.
To allow direct publishes of images.
=> fix: Properly set a tag during a manual docker publish (#2960)

.github/workflows/publish-paradedb-docker.yml
- Closes #N/A
We tried to make pre-releases recently that were not correctly marked as pre-releases. In semVer, anything with a `-` is a pre-release, so mark it as such.
Don't push official releases when we do mean to!
Instead of filtering out official releases via `-rc`, we do it via `-` only.
CI
=> ci: Don't tag Docker images as `latest` if there's a `-` in the tag

.github/workflows/benchmark-pg_search-benchmarks.yml, .github/workflows/benchmark-pg_search-stressgres.yml, .github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/test-docs.yml, .github/workflows/test-pg_search-docker.yml, .github/workflows/test-pg_search-upgrade.yml, .github/workflows/test-pg_search.yml
- Closes #N/A
Some workflows, like benchmarking, were not triggered for 0.*.x branches.
We run releases out of these branches.
Add a new branch trigger in GHA.
N/A
- Closes #
=> chore: cherry pick #2975 into `0.17.x`

.github/workflows/benchmark-pg_search-benchmarks.yml, .github/workflows/benchmark-pg_search-stressgres.yml, .github/workflows/check-pg_search-schema-upgrade.yml, .github/workflows/test-docs.yml, .github/workflows/test-pg_search-docker.yml, .github/workflows/test-pg_search-upgrade.yml, .github/workflows/test-pg_search.yml
- Closes #N/A
Some workflows, like benchmarking, were not triggered for 0.*.x branches.
We run releases out of these branches.
Add a new branch trigger in GHA.
N/A
- Closes #
=> chore: cherry pick #2975 into `0.18.x`

.github/workflows/lint-rust.yml
Install `cargo machete` with `--locked`.
Otherwise its deps could shift in ways which break CI when we're trying to get other things done.
=> fix: Install `cargo machete` as locked.

.github/workflows/lint-rust.yml
Install `cargo machete` with `--locked`.
Otherwise its deps could shift in ways which break CI when we're trying to get other things done.
=> fix: Install `cargo machete` as locked. (cherry-pick of #2993)

.github/workflows/cherry-pick.yml
Add Github workflows which use https://github.com/marketplace/actions/github-cherry-pick-action to automatically open cherry-picks to stable branches for appropriately labeled PRs.
This eliminates some annoying manual/local steps when a fix is landing on `main` which needs to be propagated to stable branches.
To automatically open cherry-pick PRs to `0.17.x` and/or `0.18.x`, use the `cherry-pick/0.17.x` and `cherry-pick/0.18.x` labels, respectively.
=> chore: Add workflows to automatically cherry-pick from `main` to stable branches

pg_search/src/postgres/merge.rs, pg_search/src/postgres/rel.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/fsm.rs, pg_search/tests/pg_regress/expected/parallel_vacuum.out, pg_search/tests/pg_regress/sql/parallel_vacuum.sql
- Closes #2986
This fixes issue #2986.  The primary problem here is that parallel vacuum processes can't create a transaction id via `pg_sys::GetCurrentTransactionId()` so we instead teach the FSM to use `pg_sys::GetCurrentTransactionIdIfAny()` and in the case of a parallel vacuum process we'll fall back to the `pg_sys::FirstNormalTransactionId`.
A subtle difference is here that parallel vacuum processes won't be able to reuse blocks from the FSM in the case where `ambulkdelete()` adds a ".deletes" file to a segment.  This is better than not being able to vacuum at all.
Thanks to @rebasedming for getting a test case together.
Additionally, that test case uncovered a race condition with the background merge process because it turns out it didn't hold a relation lock on the index at all. …
=> fix: parallel vacuum process now runs correctly

pg_search/src/postgres/catalog.rs, pg_search/src/postgres/customscan/pushdown.rs, pg_search/src/postgres/mod.rs, pg_search/tests/pg_regress/expected/missing_terms_with_operator_fn.out, pg_search/tests/pg_regress/sql/missing_terms_with_operator_fn.sql
- Closes #
It's possible that when upgrading pg_search from `v0.15.26` to `v0.17.x` we could generate an ERROR complaining that
`paradedb.terms_with_operator(...)` doesn't exist if the user upgraded the extension binary but has not yet run `ALTER EXTENSION pg_search UPDATE;`.
This fixes that by inspecting the catalogs directly when it's necessary to lookup that function and plumbing through an `Option<pg_sys::Oid>` return value.
To help users/customers/partners better deal with upgrading from really old pg_search versions.
Existing tests pass, especially the ones added in #2730, and a new regress test has been added that explicitly removes the function from the schema and ensures the query still works (tho with a different plan, of course).
=> fix: don't ERROR if `paradedb.terms_with_operator` is missing

pg_search/src/index/directory/utils.rs, pg_search/src/postgres/storage/metadata.rs
This brings back our segment meta entry garbage list.  It's necessary to help avoid potential query cancel situations in parallel workers.
=> fix: restore the garbage list

.github/workflows/publish-paradedb-docker.yml, .github/workflows/test-pg_search-docker.yml
- Closes #N/A
This PR fixes two issues:
- We were unconditionally marking any non-beta release Docker images as being `latest`. This means despite having released `0.18.0` before, now releasing `0.17.7` marked it as latest. This PR fixes this by comparing the semver versions and creating a flag based on the output, which is used in the Docker Tag step. This is mostly the same code as in the `publish-github-release.yml`, where we had a similar issue before.
- I also added some more logs to our `Test ParadeDB Docker` job to help verify why some users reported permission errors. It seems that the PR #2954 simply wasn't porteed over to the `0.17.x` release branch.
Properly tag Docker releases.
^
All tested manually.
=> fix: Only mark Docker images as `latest` if they actually are the latest ones

pg_search/src/postgres/merge.rs, pg_search/src/postgres/storage/merge.rs, tests/tests/layered_merge.rs
We change the decisions around when/how/what to merge such that we prefer to merge in the background if we can.  That is defined as all of these being true:
- the user has either a default or non-zero configuration for `background_layer_sizes`
- no other merge (foreground or background) is currently happening
- the layer policy simulation indicates there is merging work to do 
or
- the request to merge came from a VACUUM
Otherwise we'll merge in the foreground if:
- the request to merge came from `aminsert`
- the user has either a default or non-zero configuration for `layer_sizes`
Additionally, when merging in the background we now consider the combined/unique set of layer sizes from both `layer_sizes` and `background_layer_sizes`, and ensure the maximum layer size is clamped to our …
=> perf: optimize merging heuristics to prefer background merging

.github/workflows/publish-github-release.yml, .github/workflows/publish-paradedb-docker.yml
- Closes #N/A
For some reason, it still published as `latest`. I don't know why, because I tested it and ran another branch with these logs, and it didn't tag as `latest`... Maybe the CI just needed to be updated in `main`? Anyways, dropping these logs in case this happens again.
^
^
^
=> ci: Add better logs for the `is_latest` in Publish Docker job

pg_search/src/postgres/customscan/qual_inspect.rs, pg_search/tests/pg_regress/expected/unified_expression_comprehensive.out, pg_search/tests/pg_regress/sql/unified_expression_comprehensive.sql
- Closes #3043 
Prevents system crashes when `paradedb.enable_filter_pushdown` is enabled and heap filter expressions contain subqueries.
When `enable_filter_pushdown` is enabled, expressions that cannot be pushed down to the index are converted to `Qual::HeapExpr` for heap-based evaluation. However, `HeapFieldFilter` uses `CreateStandaloneExprContext()` which lacks the infrastructure needed for subquery evaluation (subplans, proper executor state), causing system crashes when subqueries are present.
Added subquery detection in `try_pushdown()` using the existing `contains_exec_param()` function to identify expressions containing EXEC parameters (subqueries). When subqueries are detected, the function returns `None` instead of creating a `Qual::HeapExpr`, causing PostgreSQL's regular …
=> fix: excluded sub-queries from filter-pushdown (on non-indexed fields).

.github/actions/push-file/action.yml
This teaches our `push-file.yml` action how to retry. 
At least in large benchmark backfills, concurrent jobs can end up trying to push to the same repo at the same time, and that means their local git state isn't up-to-date, so a retry is required.
=> fix: teach `push-file.yaml` how to retry

Cargo.lock, Cargo.toml
This is the 0.17.x-specific version of PR #3081.
Our tantivy timeline has forked and so has our dependency points.
=> perf: update tantivy dependency

pg_search/src/index/directory/utils.rs, pg_search/src/index/merge_policy.rs, pg_search/src/index/writer/index.rs, pg_search/src/lib.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/fsm.rs, pg_search/src/postgres/storage/utils.rs
Teach the FSM how to conditionally upgrade its buffer lock to an exclusive lock, skipping the page if it can't be acquired (unless it's the last page, then we wait).
While here, centralize `std::thread::available_parallelism()` (it actually showed up on profiles!) and gate some `pgrx::debug!()` statements
Trying to remove some overhead that showed up during profiling.
=> perf: FSM conditional locking & other minor drive-bys

pg_search/src/index/writer/index.rs
Our recent changes to tantivy have adjusted the default MemoryArena page size from 1MB to 512k, and this actually has a downstream effect of allowing indexers to fit more docs in the arena before tantivy calcuates that the indexer has exceeded its memory budget.
We have a test that exposed this, so this adjustes the number of documents to insert to generate 5 segments.
=> fix: fix failing test

docs/docs.json, docs/v2/aggregates/overview.mdx, docs/v2/full-text/phrase.mdx, docs/v2/indexing/create_index.mdx, docs/v2/overview.mdx
Small fixes to make sure people don't get lost or stuck in the v2 docs.
- Add link back to v1 from v2 overview
- Add links back to correct page in v1 when v2 isn't implemented
- Change the sidebar anchor for v2 to be "Documentation (v2)"
=> fix: Clarify v2 API docs

pg_search/src/postgres/catalog.rs, pg_search/src/postgres/customscan/pushdown.rs, pg_search/src/postgres/mod.rs, pg_search/tests/pg_regress/expected/missing_terms_with_operator_fn.out, pg_search/tests/pg_regress/sql/missing_terms_with_operator_fn.sql
Cherry picks PR #3013, which only landed in 0.17.x, to `main` and `0.18.x` via the label.
=> chore: cherry-pick PR3013 to main

.github/workflows/cherry-pick.yml
In #3095 I removed the `[cherry-pick/x.y.z]` labels from our automated cherry pick PRs, but after seeing that in action I think some kind of label will be helpful.  So this adds `[automated-cherry-pick]`, which is not a bright, burning red but a cool, neutral gray.
To make looking at the PR list a little easier
=> chore: add a label to automated cherry picks

Cargo.lock, Cargo.toml, pg_search/src/index/reader/index.rs, pg_search/tests/pg_regress/expected/top_n_scan.out, pg_search/tests/pg_regress/sql/top_n_scan.sql, tests/tests/fixtures/querygen/mod.rs, tests/tests/fixtures/querygen/wheregen.rs, tests/tests/qgen.rs
TopN was not handling nulls properly: instead, they were filled in with a default, which would cause an error when the limit was high enough to include them.
See https://github.com/paradedb/tantivy/pull/61.
Added a regression test and property tests (which exposed a related issue in pushdown: https://github.com/paradedb/paradedb/pull/3110).
=> fix: Fix handling of nulls in TopN

pg_search/src/postgres/merge.rs
- Closes #
There was a bug where vacuum would ignore background merging being disabled and do one anyway
=> fix: Do not background merge during vacuum if background merge is disabled

Cargo.lock, Cargo.toml, docs/changelog/0.17.12.mdx, docs/deploy/self-hosted/extension.mdx, docs/deploy/upgrading.mdx, docs/docs.json, pg_search/sql/pg_search--0.17.10--0.17.12.sql
- Closes #
Note that `0.17.11` was skipped because it was a hotfix in enterprise.
=> chore: Upgrade to `0.17.12`

pg_search/src/gucs.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, pg_search/src/postgres/options.rs
- Closes #
Adds a GUC that allows the user to control how many results we fetch per segment for a Top N query.
```
f = number of results fetched
n = limit specified by the query
d = number of dead tuples in the heap, estimated by Postgres
a = number of alive tuples in the heap, estimated by Postgres
m = GUC limit_fetch_multiplier setting
f = n * (1 + (1 + d) / (1 + a)) * m
```
Accelerate Top N queries that are bottlenecked by retries
=> feat: add `limit_fetch_multiplier` index setting to reduce Top N retries

pg_search/src/postgres/utils.rs
Add a proptest for our port of `pg_sys::TransactionIdPrecedesOrEquals()`.
There was a moment of internal confusion around if it was actually correct or not.
This is a test.
=> chore: proptest for our pg_sys::TransactionIdPrecedesOrEquals function

pg_search/src/api/mod.rs, pg_search/src/gucs.rs, pg_search/src/postgres/customscan/aggregatescan/mod.rs, pg_search/src/postgres/customscan/aggregatescan/privdat.rs, pg_search/src/postgres/customscan/aggregatescan/scan_state.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/var.rs, pg_search/tests/pg_regress/expected/empty_aggregate.out, pg_search/tests/pg_regress/expected/groupby_aggregate.out, pg_search/tests/pg_regress/expected/groupby_aggregate_highcard.out, pg_search/tests/pg_regress/expected/issue_3050.out, pg_search/tests/pg_regress/expected/json_groupby_aggregate.out, pg_search/tests/pg_regress/expected/json_groupby_orderby_limit.out, pg_search/tests/pg_regress/sql/groupby_aggregate.sql, pg_search/tests/pg_regress/sql/groupby_aggregate_highcard.sql, pg_search/tests/pg_regress/sql/json_groupby_orderby_limit.sql
- Closes #3131 
- Opens #3156 #3155 
Pushes down `group by ... order by ... limit` to Tantivy
By pushing down the sort/limit to Tantivy, we can significantly speed up `group by` queries over high cardinality columns.
- Before we were hard-coding a bucket size and sorting the results ourselves, now the bucket size is set to the limit and we push the sort down to the Tantivy term agg
=> feat: push down `group by ... order by ... limit`

pg_search/src/postgres/build.rs, pg_search/tests/pg_regress/expected/key-field-uuid-raw-warning.out, pg_search/tests/pg_regress/expected/keys_snippet_score.out, pg_search/tests/pg_regress/expected/mixedff_basic_05_uuid.out, pg_search/tests/pg_regress/sql/key-field-uuid-raw-warning.sql
Remove the warning about using the `raw` tokenizer when the `key_field` is a UUID field.
The drama here is that we (pg_search) assign the `raw` tokenizer to UUID fields used as the key_field so there's nothing a user can do about it.  Warning about our own bad decisions is not cool.
Many user and customer complaints.
Existing tests pass but a couple of the regression test expected output is now different.
=> chore: don't warn about `raw` tokenizer on UUID key fields

pg_search/src/postgres/customscan/aggregatescan/mod.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/qual_inspect.rs
This does two things.  
One, the first commit (62d752572b2d7bc5a02b7203ac2c83949e38e27e) simply reorders some code in the custom scan callback so it can decide to exit early if we're not going to submit a path.  Specifically, this is intended to avoid opening a Directory and Index and related structures.
Two, the second commit (5ac1dde23ef0809bea4b942d04fd14acc9d1c152) makes a new decision to not evaluate possible pushdown predicates when the statement type is not a SELECT statement.  This cuts out the overhead of needing to read/deserialize the index's schema at all on (at least) UPDATE statements.
This does mean that we won't consider doing pushdowns for UPDATE statements, even if doing one would make the UPDATE scan faster.
Trying to reduce per-query overhead, targeting our stressgres …
=> perf: teach custom scan callback to exit early if it can

pg_search/tests/pg_regress/expected/groupby_aggregate_highcard.out, pg_search/tests/pg_regress/expected/issue_3050.out
Fix the expected output of two regression tests in `0.18.x`.
Two regression test expected outputs are wrong relative to the code in the `0.18.x`.
=> chore: fix regression tests

pg_search/src/aggregate/mod.rs, pg_search/src/postgres/customscan/pdbscan/solve_expr.rs, pg_search/src/query/heap_field_filter.rs, pg_search/src/query/mod.rs
Evaluating heap filters was leaking a `CreateStandaloneExprContext` per execution, which could eventually lead to OOMs.
`PgBox::from_pg` does not free the resulting memory: it's expected to be freed by a memory context, since PG created it.
Always use a global expression context created by `ExecAssignExprContext` in `begin_custom_scan`.
A repro uses significantly less memory, and [a benchmark query added for this purpose](https://github.com/paradedb/paradedb/pull/3175) is faster.
=> fix: Always use a shared expression context to execute HeapFilters.

pg_search/src/postgres/customscan/aggregatescan/mod.rs, pg_search/tests/pg_regress/expected/aggregate-groupby-conflict.out, pg_search/tests/pg_regress/expected/groupby_aggregate.out, pg_search/tests/pg_regress/sql/aggregate-groupby-conflict.sql, pg_search/tests/pg_regress/sql/test-fruit-types-issue.sql
- Closes #2963
Removes aggregate limitations that prevented queries where the same field is used in both `GROUP BY` and aggregate functions (e.g., `SELECT rating, AVG(rating) FROM table GROUP BY rating`).
Previous safety checks blocked these queries due to Tantivy's "incompatible fruit types" errors, but testing shows the underlying issue is resolved. The limitations were overly restrictive and caused unnecessary fallbacks to slower PostgreSQL aggregation.
- Removed `has_search_field_conflicts` function and field conflict validation
- Eliminated ~35 lines of restrictive code in `extract_and_validate_aggregates`
- Previously blocked queries now use faster `AggregateScan` instead of `GroupAggregate`
- **`aggregate-groupby-conflict.sql`** - Tests `GROUP BY field` with aggregates on same …
=> feat: removed aggregation limitations re mix of aggregate functions and aggregation on group-by column.

pg_search/src/aggregate/mod.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/src/postgres/customscan/pdbscan/privdat.rs, pg_search/src/postgres/customscan/pdbscan/scan_state.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/mod.rs, pg_search/src/postgres/scan.rs, pg_search/src/postgres/storage/metadata.rs
- Closes #
Add `ambulkdelete_epoch` to the index metadata and make sure it's passed down to all scans. In enterprise, this value is used to detect query conflicts with concurrent vacuums on the primary.
=> feat: Port `ambulkdelete_epoch` to community

pg_search/src/postgres/delete.rs
- Closes #
In `ambulkdelete`, write all delete files to the meta list atomically, instead of one at a time.
Reduces the number of writes to the metas list.
- Closes #
=> fix: write all delete files atomically (#3178)

docs/docs.json
- Closes #N/A
We've consolidated GA4 reporting to be issued via Google Tag Manager, so we're now double-counting docs visits. This fixes that.
Double counting is no bueno.
Configured in GTM.
I am pretty sure it works.
=> docs: Remove GA4 integration since it's now a duplicate

pg_search/src/postgres/build.rs, pg_search/src/postgres/options.rs, pg_search/tests/pg_regress/expected/key-field-text-as-keyword.out, pg_search/tests/pg_regress/sql/key-field-text-as-keyword.sql
Closes: #2502
This allows the user to change the key_field's tokenizer to `keyword` since until now we complain that `raw` is deprecated.
It's not right for us to complain that the `raw` tokenizer is deprecated and then not allow the user to change it.
In the case of key_field TEXT columns we long long ago made the wrong decision to use the `raw` tokenizer as the default tokenizer.  Then we decided to deprecate the `raw` tokenizer in favor of the `keyword` tokenizer, but we never actually let users change the key_field's tokenizer.  So now we do... for TEXT fields only.
A new regression test has been added.  All other tests pass.
=> fix: allow user to set TEXT `key_field`'s tokenizer to `keyword`

pg_search/src/postgres/build.rs, pg_search/tests/pg_regress/expected/index_config_errors.out
The error used to say the column didn't exist in the table, but what it's actually trying to say is that the column isn't covered in the bm25 USING clause.
- If the column isn't in the table but is in the USING then Postgres will throw it's own error before this code is reached.
- If the column is in the table and is isn't in the USING we will get this error
- If the column isn't in **either** then I suppose we could throw a more accurate warning, but this way at least it will throw the new erro, fixing which will result in the PG error
```
pg_search=# create table tester(id int, words text);
CREATE TABLE
pg_search=# CREATE INDEX   
ON tester USING bm25(id, words) WITH (
key_field = 'id', 
numeric_fields = '{
"missing": {"fast": true}
}'
) ;
ERROR:  the column `missing` does not exist in …
```
=> fix: Fix error for invalid col in FF JSON

.github/workflows/cherry-pick.yml
- Closes #N/A
0.17.x is dead, long live 0.18.x
^
^
^
=> chore: Remove 0.17.x cherry-pick

.github/stressgres/wide-table.toml
Adjust the `wide-table` stressgres config to:
* Include a top-n query
* Start with a larger base table
* Execute single inserts at about 1/3 the rate of updates
* Update random data, rather than always the same rows
To better match production usecases.
Note: this will require a stressgres backfill!
=> chore: Increase accuracy of wide-table benchmark

docs/documentation/full-text/sorting.mdx, pg_search/src/api/mod.rs, pg_search/src/index/reader/index.rs, pg_search/src/postgres/customscan/pdbscan/exec_methods/top_n.rs, pg_search/src/postgres/customscan/pdbscan/mod.rs, pg_search/tests/pg_regress/expected/mixedff_advanced_06_score_function.out, pg_search/tests/pg_regress/expected/topn_scores.out, pg_search/tests/pg_regress/sql/topn_scores.sql, tests/tests/sorting.rs
- Closes #3227 
Allows the `TopNScanState` to return scores.
Avoid falling back to the normal exec state, which can be very slow.
Added regression test.
=> feat: TopN scan can emit scores for any `ORDER BY`

pg_search/src/postgres/customscan/pdbscan/projections/mod.rs, pg_search/src/postgres/customscan/pdbscan/projections/snippet.rs, pg_search/tests/pg_regress/expected/issue_3256.out, pg_search/tests/pg_regress/sql/issue_3256.sql
- Closes #3256 
See GH issue
When mapping a const node to our list of snippet generators, we were matching only on the field name and function OID, which is not unique enough -- it doesn't account for the function arguments.
Added regression test
=> fix: `paradedb.snippet` projects correctly when called multiple times over the same field

pg_search/tests/pg_regress/expected/partial_index_score_fix.out, pg_search/tests/pg_regress/sql/partial_index_score_fix.sql, tests/tests/bm25_search.rs, tests/tests/helpers.rs, tests/tests/index_config.rs, tests/tests/reindex.rs, tests/tests/search_config.rs, tokenizers/src/manager.rs
- Closes #
For better maintainability:
1. Removes three extremely deprecated tokenizers: `en_stem`, `stem`, and `lowercase`
2. Wraps the filter builders in a macro, guaranteeing that all the filters are applied to all tokenizers
=> chore: Remove deprecated tokenizers: `en_stem`, `stem` and `lowercase`

macros/src/lib.rs
Fix an issue where functions tagged with our `#[builder_fn]` macro could end up with the same name.
It's come up in CI once or twice and I've seen it locally as well
=> fix: possible naming collisions with builder functions

.github/stressgres/wide-table.toml, pg_search/proptest-regressions/postgres/storage/avl.txt, pg_search/sql/pg_search--0.18.11--0.18.12.sql, pg_search/src/api/admin.rs, pg_search/src/gucs.rs, pg_search/src/postgres/build_parallel.rs, pg_search/src/postgres/delete.rs, pg_search/src/postgres/insert.rs, pg_search/src/postgres/merge.rs, pg_search/src/postgres/options.rs, pg_search/src/postgres/storage/avl.rs, pg_search/src/postgres/storage/buffer.rs, pg_search/src/postgres/storage/fsm.rs, pg_search/src/postgres/storage/linked_bytes.rs, pg_search/src/postgres/storage/linked_items.rs, pg_search/src/postgres/storage/merge.rs, pg_search/src/postgres/storage/metadata.rs, pg_search/src/postgres/storage/mod.rs
This implements a new `v2` FSM that's fronted by an AVL tree which allows for minimal locking during extension and draining.  It also provides efficient continuation during drain as xid blocklists are exhausted or found to be unavailable to the current transaction.  And it implements a (simple) transparent conversion of the current `v1` FSM to the new format.
Additionally, this fixes a problem with background merging where more than one background merger process could be spawned at once -- I've seen up to 8 concurrently.  It does this by introducing some a new page on disk to track the process and coordinate locking.
Our current FSM is very heavyweight in terms of lock contention.  This should get us to something that isn't.
A number of new tests for the array-backed AVL tree and the FSM …
=> feat: A Free Space Manager fronted by an AVL tree
